T1000	Speculation 8599 8602	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 8599 8704	may be of relevance for the design of vaccines and for strategies in immunotherapy in infectious diseases
T1002	Negation 5842 5845	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 5842 5880	not a Th cell-subset-specific cytokine
T1004	Negation 6378 6381	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 6378 6410	not Th1cells (Chang etal., 2007)
T1006	Speculation 6229 6238	suggested
E1003	Speculation:T1006 Scope:T1007
T1007	Span 6150 6238	Differential transcriptional regulation of IL-10 in Th1 and Th2 cells has been suggested
T1008	Speculation 7111 7121	suggesting
E1004	Speculation:T1008 Scope:T1009
T1009	Span 7111 7218	suggesting that additional factors are in place to induce IL-10 expression in Th1 cells, albeit transiently
T1010	Speculation 487 494	whether
E1005	Speculation:T1010 Scope:T1011
T1011	Span 487 529	whether Th1 cells develop to produce IL-10
T1012	Negation 362 365	not
E1006	Negation:T1012 Scope:T1013
T1013	Span 362 424	not produced by Th1 cells in response to antigenic stimulation
T1014	Negation 1673 1676	not
E1007	Negation:T1014 Scope:T1015
T1015	Span 1673 1718	not blood of TB patients (Gerosa etal., 1999)
T1016	Speculation 1204 1207	may
E1008	Speculation:T1016 Scope:T1017
T1017	Span 1204 1279	may lead to the chronic nonhealing infection shown to be regulated by IL-10
T1018	Speculation 2094 2100	likely
E1009	Speculation:T1018 Scope:T1019
T1019	Span 2094 2460	likely that IL-10 production by Th1 cells is evoked under conditions of high inflammation and antigenic stimulation, whereas regulatory CD4+ Tcells producing IL-10 may operate to regulate the immune response under conditions in which the pathogen is clinically controlled, such as in infection with L. major (Friedlin strain) (Belkaid etal., 2002; Suffia etal., 2006
T1020	Speculation 1495 1504	speculate
E1010	Speculation:T1020 Scope:T1021
T1021	Span 1495 1718	speculate that Th1 cells will be induced to express high amounts of IL-10, in keeping with reports that IL-10-producing Th1 cells were found in CD4+ clones isolated from BAL but not blood of TB patients (Gerosa etal., 1999)
T1022	Speculation 2852 2861	potential
E1011	Speculation:T1022 Scope:T1023
T1023	Span 2852 2955	potential additional mechanisms whereby effector Tcell responses may be dampened during chronic disease
T1024	Speculation 2258 2261	may
E1012	Speculation:T1024 Scope:T1025
T1025	Span 2258 2461	may operate to regulate the immune response under conditions in which the pathogen is clinically controlled, such as in infection with L. major (Friedlin strain) (Belkaid etal., 2002; Suffia etal., 2006)
T1026	Negation 3239 3242	not
E1013	Negation:T1026 Scope:T1027
T1027	Span 3239 3250	not totally
T1028	Speculation 2917 2920	may
E1014	Speculation:T1028 Scope:T1029
T1029	Span 2892 2955	effector Tcell responses may be dampened during chronic disease
T1030	Speculation 4024 4033	suggested
E1015	Speculation:T1030 Scope:T1031
T1031	Span 4024 4052	suggested (Shaw etal., 2006)
T1032	Speculation 3483 3486	may
E1016	Speculation:T1032 Scope:T1033
T1033	Span 3483 3574	may compensate for an absolute requirement for IL-12 in the induction of IL-10 by Th1 cells
T1034	Negation 4266 4273	absence
E1017	Negation:T1034 Scope:T1035
T1035	Span 4266 4288	absence of added IL-12
T1036	Negation 4122 4125	not
E1018	Negation:T1036 Scope:T1037
T1037	Span 4122 4158	not express IL-10 upon restimulation
T1038	Speculation 4771 4777	likely
E1019	Speculation:T1038 Scope:T1039
T1039	Span 4771 4971	likely that in T. gondii infection invivo (Shaw etal., 2006), the requirement for IFN-gamma to induce IL-10, was for feedback upregulation of IL-12 by DCs, which in turn induced IL-10 in the Th1 cells
T1040	Speculation 4662 4670	suggests
E1020	Speculation:T1040 Scope:T1041
T1041	Span 4662 4758	suggests that repeated high-level TCR activation feeds back to upregulate IL-12 production by DC
T1042	Speculation 5115 5122	suggest
E1021	Speculation:T1042 Scope:T1043
T1043	Span 5115 5155	suggest the existence of common pathways
T1044	Speculation 4989 4992	may
E1022	Speculation:T1044 Scope:T1045
T1045	Span 4989 5062	may be differentially regulated in Th1 and Th2 cells as has been reported
T1046	Speculation 5371 5380	suggested
E1023	Speculation:T1046 Scope:T1047
T1047	Span 5347 5460	ICOS signaling has been suggested to induce IL-10 (Ito etal., 2007; Witsch etal., 2002) in both Th1 and Th2 cells
T1048	Speculation 5201 5208	unclear
E1024	Speculation:T1048 Scope:T1049
T1049	Span 5161 5208	the molecular basis for these is as yet unclear
