T1000	Speculation 1028 1036	indicate
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1028 1062	indicate the MFI for WT GFP+ cells
T1002	Negation 387 390	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 270 400	The frequency of transduced cells in the cultures was equivalent for all constructs (approximately75-90% GFP+ cells; not depicted)
T1004	Speculation 1433 1436	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1433 1488	may participate in sustaining late IFN-gamma expression
T1006	Negation 1519 1522	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1519 1529	not T-bet)
T1008	Negation 1659 1662	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1659 1692	not granzyme B protein expression
T1010	Speculation 1530 1533	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1530 1575	may cooperate to activate perforin expression
T1012	Speculation 1593 1602	indicates
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1593 1692	indicates the partial effect of T-bet deficiency on Gzmb mRNA but not granzyme B protein expression
