T1000	Speculation 1255 1261	and/or
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1255 1377	and/or function of Foxp3, which have been found to be deficient in several autoimmune diseases and virus-induced disorders
T1002	Speculation 1170 1173	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1170 1279	may aid in the discovery of therapeutic approaches designed to rescue the expression and/or function of Foxp3
