T1000	Speculation 4208 4216	unlikely
E1000	Speculation:T1000 Scope:T1001
T1001	Span 4208 4251	unlikely cause for the observed methylation
T1002	Speculation 4385 4390	might
E1001	Speculation:T1002 Scope:T1003
T1003	Span 4385 4486	might represent a mechanism that accounts for the previously observed loss of IRF-4 expression in CML
T1004	Negation 4874 4883	could not
E1002	Negation:T1004 Scope:T1005
T1005	Span 4853 5017	the loss of this IRF could not be reverted in ICSBP-negative cell lines (EM-2, CML-T1, K-562 and LAMA-84) by treatment with AzadC (Figure 6) and AzadC has no effect
T1006	Negation 5008 5010	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 5008 5074	no effect on ICSBP levels in ICSBP-positive U-937 cells (Figure 6)
T1008	Speculation 2801 2804	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2801 2855	may also play a role in regulation of IRF-4 expression
T1010	Speculation 3430 3433	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 3430 3485	may thus be the mechanism of IRF-4 deregulation in vivo
T1012	Speculation 3491 3499	possible
E1006	Speculation:T1012 Scope:T1013
T1013	Span 3491 3614	possible cause for the aberrant methylation in tumorigenesis is an increased level of DNMTs during the pathogenetic process
T1014	Negation 4119 4122	not
E1007	Negation:T1014 Scope:T1015
T1015	Span 4119 4193	not detect significant mRNA expression differences of selected DNMT or MBP
T1016	Speculation 5087 5094	suggest
E1008	Speculation:T1016 Scope:T1017
T1017	Span 5087 5145	suggest a distinct regulatory mechanism for these two IRFs
T1018	Speculation 5237 5240	may
E1009	Speculation:T1018 Scope:T1019
T1019	Span 5237 5409	may thus be a subject of alterations in the promoter methylation status leading to expression changes, which might contribute to the initiation and/or progression of cancer
T1020	Speculation 294 302	putative
E1010	Speculation:T1020 Scope:T1021
T1021	Span 294 354	putative cause for absent IRF-4 expression in leukemia cells
T1022	Negation 313 319	absent
E1011	Negation:T1022 Scope:T1023
T1023	Span 313 354	absent IRF-4 expression in leukemia cells
T1024	Negation 497 501	lack
E1012	Negation:T1024 Scope:T1025
T1025	Span 497 592	lack of IRF-4 expression: The detected base pair changes at position -1081 (T-->C substitution)
T1026	Negation 425 427	no
E1013	Negation:T1026 Scope:T1027
T1027	Span 425 521	no genetic alterations in the IRF-4 promoter, which can account for the lack of IRF-4 expression
T1028	Speculation 679 687	unlikely
E1014	Speculation:T1028 Scope:T1029
T1029	Span 679 908	unlikely responsible for absent IRF-4-expression since the first two mutations were found both in IRF-4-positive and -negative cells whereas the latter change was not detected consistently in all IRF-4-negative or -positive cells
T1030	Negation 842 845	not
E1015	Negation:T1030 Scope:T1031
T1031	Span 820 939	the latter change was not detected consistently in all IRF-4-negative or -positive cells and may thus be a polymorphism
T1032	Negation 969 972	not
E1016	Negation:T1032 Scope:T1033
T1033	Span 969 1040	not change any known putative transcription factor binding sites (30,31
T1034	Speculation 913 916	may
E1017	Speculation:T1034 Scope:T1035
T1035	Span 913 939	may thus be a polymorphism
T1036	Speculation 990 998	putative
E1018	Speculation:T1036 Scope:T1037
T1037	Span 990 1129	putative transcription factor binding sites (30,31) and also do not affect any restriction sites or primer binding sites of the used assays
T1038	Negation 1054 1057	not
E1019	Negation:T1038 Scope:T1039
T1039	Span 1054 1129	not affect any restriction sites or primer binding sites of the used assays
T1040	Speculation 1345 1348	can
E1020	Speculation:T1040 Scope:T1041
T1041	Span 1345 1485	can be induced by demethylation and successful IFN-alpha therapy (3), respectively, the existence of such genetic aberrations seems unlikely
T1042	Negation 1260 1263	not
E1021	Negation:T1042 Scope:T1043
T1043	Span 1140 1298	permanent genetic variations in the IRF-4 coding sequence, such as deletions or mutations resulting in stop-codons have not been excluded by sequence analysis
T1044	Speculation 1477 1485	unlikely
E1022	Speculation:T1044 Scope:T1045
T1045	Span 1363 1485	demethylation and successful IFN-alpha therapy (3), respectively, the existence of such genetic aberrations seems unlikely
T1046	Speculation 1471 1476	seems
E1023	Speculation:T1046 Scope:T1047
T1047	Span 1471 1485	seems unlikely
T1048	Speculation 1722 1727	might
E1024	Speculation:T1048 Scope:T1049
T1049	Span 1722 1806	might also be a result of activation of positive transcriptional regulators of IRF-4
T1050	Speculation 1509 1516	whether
E1025	Speculation:T1050 Scope:T1051
T1051	Span 1509 1663	whether the previously described down-regulation of IRF-4 expression in human myeloid leukemias was due to a differential hypermethylation of the promoter
T1052	Speculation 2400 2403	may
E1026	Speculation:T1052 Scope:T1053
T1053	Span 2400 2471	may account for the absence of IRF-4 expression in the respective cells
T1054	Speculation 2224 2229	could
E1027	Speculation:T1054 Scope:T1055
T1055	Span 2207 2320	IRF-4 expression could indeed be connected to the methylation status of distinct CpG motifs in the IRF-4 promoter
T1056	Speculation 2569 2577	possible
E1028	Speculation:T1056 Scope:T1057
T1057	Span 2569 2602	possible involvement of this site
T1058	Speculation 2556 2566	indicating
E1029	Speculation:T1058 Scope:T1059
T1059	Span 2556 2602	indicating a possible involvement of this site
T1060	Speculation 6134 6137	may
E1030	Speculation:T1060 Scope:T1061
T1061	Span 6134 6347	may promote leukemogenesis in myeloid cell context (3), which was recently confirmed in IRF-4-/- ICSBP-/- double knock-out mice (53), while IRF-4 up-regulation may induce a growth advantage in lymphomas or MM (48)
T1062	Speculation 5346 5351	might
E1031	Speculation:T1062 Scope:T1063
T1063	Span 5346 5409	might contribute to the initiation and/or progression of cancer
T1064	Speculation 6510 6513	may
E1032	Speculation:T1064 Scope:T1065
T1065	Span 6510 6565	may be a consequence of IRF-4 promoter hypermethylation
T1066	Speculation 6375 6382	suggest
E1033	Speculation:T1066 Scope:T1067
T1067	Span 6375 6565	suggest that IRF-4 promoter methylation regulates IRF-4 expression, and that aberrant expression of IRF-4 in certain types of leukemia may be a consequence of IRF-4 promoter hypermethylation
T1068	Speculation 6294 6297	may
E1034	Speculation:T1068 Scope:T1069
T1069	Span 6294 6347	may induce a growth advantage in lymphomas or MM (48)
