T1000	Speculation 1292 1301	not known
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1292 1406	not known whether these transcription factors function redundantly to control effector CD8+ T cell differentiation
T1002	Negation 1248 1251	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1161 1269	the specific roles of T-bet and Eomes in clonal expansion and CTL differentiation have not yet been resolved
T1004	Speculation 1412 1419	whether
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1412 1499	whether they do so directly by targeting specific effector cytokine and cytolytic genes
T1006	Speculation 1302 1309	whether
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1302 1499	whether these transcription factors function redundantly to control effector CD8+ T cell differentiation, and whether they do so directly by targeting specific effector cytokine and cytolytic genes
T1008	Negation 1809 1812	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1809 2038	not expressed in naive CD4+ T cells, its expression is up-regulated during Th1 cell differentiation, and Runx3 influences Th1 cell differentiation and function through direct regulation of the Il4 and Ifng cytokine genes (15, 16)
T1010	Negation 1764 1767	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1764 1789	not in CD4+ SP cells (14)
T1012	Negation 2776 2783	lacking
E1006	Negation:T1012 Scope:T1013
T1013	Span 2776 2789	lacking Runx3
T1014	Speculation 2219 2226	whether
E1007	Speculation:T1014 Scope:T1015
T1015	Span 2219 2276	whether Runx3 influenced cytolytic T cell differentiation
