T1000	Speculation 892 895	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 892 974	may serve as effective targets in the treatment of EBV-associated B cell lymphomas
T1002	Speculation 845 852	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 845 974	suggest that Akt, NFkappaB, and Stat3 pathways may serve as effective targets in the treatment of EBV-associated B cell lymphomas
T1004	Speculation 1621 1627	likely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1621 1693	likely underlies the ability of LMP1 to promote malignant transformation
