T1000	Speculation 3328 3331	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 3328 3459	may function as a transcriptional repressor, potentially through the formation of both DNA-protein and protein-protein interactions
T1002	Speculation 3307 3316	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 3307 3459	suggested that Foxp3 may function as a transcriptional repressor, potentially through the formation of both DNA-protein and protein-protein interactions
T1004	Speculation 3627 3634	whether
E1002	Speculation:T1004 Scope:T1005
T1005	Span 3627 3793	whether Foxp3 could target additional signaling pathways by examining transcriptional activation of NF-kappaB-dependent and NF-kappaB-independent retroviral pathogens
T1006	Speculation 3373 3384	potentially
E1003	Speculation:T1006 Scope:T1007
T1007	Span 3373 3459	potentially through the formation of both DNA-protein and protein-protein interactions
T1008	Speculation 3641 3646	could
E1004	Speculation:T1008 Scope:T1009
T1009	Span 3641 3793	could target additional signaling pathways by examining transcriptional activation of NF-kappaB-dependent and NF-kappaB-independent retroviral pathogens
T1010	Speculation 679 685	and/or
E1005	Speculation:T1010 Scope:T1011
T1011	Span 679 1003	and/or function may be a significant factor in the pathogenesis of several autoimmune disorders (e.g., multiple sclerosis [5], myasthenia gravis [6], and type 1 diabetes [7]) and virus-induced immunologic disorders (e.g., human T lymphotropic virus type I [HTLV-I]-associated myelopathy/tropical spastic paraparesis [HAM/TSP
T1012	Speculation 186 197	potentially
E1006	Speculation:T1012 Scope:T1013
T1013	Span 186 211	potentially self-reactive
T1014	Speculation 2166 2174	indicate
E1007	Speculation:T1014 Scope:T1015
T1015	Span 2166 2293	indicate how Foxp3 promotes the development and function of regulatory T cells came from a report by Ziegler and colleagues [16
T1016	Speculation 695 698	may
E1008	Speculation:T1016 Scope:T1017
T1017	Span 695 1034	may be a significant factor in the pathogenesis of several autoimmune disorders (e.g., multiple sclerosis [5], myasthenia gravis [6], and type 1 diabetes [7]) and virus-induced immunologic disorders (e.g., human T lymphotropic virus type I [HTLV-I]-associated myelopathy/tropical spastic paraparesis [HAM/TSP], and HIV-induced AIDS [8-10])
T1018	Speculation 2323 2328	could
E1009	Speculation:T1018 Scope:T1019
T1019	Span 2323 2547	could inhibit transcriptional activation by physically interacting with forkhead binding sites located immediately adjacent to critical cis-acting NF-AT binding sites found in various cytokine promoters (e.g., IL-2 promoter)
T1020	Speculation 2302 2311	suggested
E1010	Speculation:T1020 Scope:T1021
T1021	Span 2302 2547	suggested that Foxp3 could inhibit transcriptional activation by physically interacting with forkhead binding sites located immediately adjacent to critical cis-acting NF-AT binding sites found in various cytokine promoters (e.g., IL-2 promoter)
T1022	Speculation 2768 2778	suggesting
E1011	Speculation:T1022 Scope:T1023
T1023	Span 2768 2917	suggesting that Foxp3 transcriptional repression was mediated by binding in a sequence-specific manner to promoters containing forkhead binding sites
T1024	Speculation 2589 2594	could
E1012	Speculation:T1024 Scope:T1025
T1025	Span 2589 2723	could repress activation of a synthetic reporter vector containing an SV40 promoter and three tandem copies of a forkhead binding site
T1026	Speculation 2998 3003	could
E1013	Speculation:T1026 Scope:T1027
T1027	Span 2998 3049	could inhibit NF-AT as well as NF-kappaB activation
T1028	Negation 3183 3194	rather than
E1014	Negation:T1028 Scope:T1029
T1029	Span 3183 3280	rather than binding of Foxp3 to promoter elements adjacent to cis-acting NF-AT or NF-kappaB sites
