T1000	Speculation 1840 1843	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1840 2039	may influence the balance between clearance and persistent infection with certain pathogens (Moore etal., 2001; Trinchieri, 2007), thus determining whether chronic infection or immunopathology ensues
T1002	Speculation 348 351	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 348 399	may result in chronic infection (Brooks etal., 2006
T1004	Speculation 3532 3539	Because
E1002	Speculation:T1004 Scope:T1005
T1005	Span 3532 3647	Because Th1 and Th2 cells cross regulate each other's development and function and can suppress Th17 cell responses
T1006	Speculation 1988 1995	whether
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1988 2039	whether chronic infection or immunopathology ensues
T1008	Speculation 4055 4062	unknown
E1004	Speculation:T1008 Scope:T1009
T1009	Span 4055 4062	unknown
T1010	Speculation 3802 3805	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 3802 3939	may thus act as a feedback regulator to control the pathology associated with an overexuberant, albeit efficacious, inflammatory response
