T1000	Speculation 7962 7965	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 7962 8225	may persist in CD4+ T cells (in particular regulatory T cells, which are known reservoirs of HIV-1 and HTLV-I) and result in the accumulation of viral proteins that either stimulate NF-kappaB and/or CREB activation or directly inhibit Foxp3 expression or function
T1002	Speculation 8310 8313	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 8310 8417	may be a crucial step in the pathogenesis of virus-induced immunological disorders such as AIDS and HAM/TSP
T1004	Negation 6613 6620	lacking
E1002	Negation:T1004 Scope:T1005
T1005	Span 6613 6635	lacking the FKH domain
T1006	Speculation 6745 6752	appears
E1003	Speculation:T1006 Scope:T1007
T1007	Span 6745 6891	appears that in CD4+ T cells, the FKH domain is dispensable for the proper functioning of Foxp3 with respect to both NF-kappaB and CREB activation
T1008	Speculation 7757 7760	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 7757 7859	may limit HIV-1 and HTLV-I transcription by interfering with activation of NF-kappaB and CREB pathways
T1010	Negation 7911 7914	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 7911 7923	not absolute
T1012	Speculation 295 298	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 295 469	may become important in light of recent reports suggesting that Foxp3 expression in thymic epithelial cells was crucial for directing development of T cells in the thymus [42
T1014	Speculation 191 198	appears
E1007	Speculation:T1014 Scope:T1015
T1015	Span 158 276	the carboxyl-terminal FKH domain appears to be dispensable for mediating these effects, at least in T cell populations
T1016	Speculation 844 852	possible
E1008	Speculation:T1016 Scope:T1017
T1017	Span 844 1234	possible that the FKH domain has a complex tertiary structure that is particularly sensitive to misfolding caused by genetic mutations and that an intact FKH domain is absolutely critical for promoting Foxp3 function in the nucleus, whereas the structure of the amino-terminal proline-rich region may tolerate certain mutations as long as the NF-kappaB/NF-AT binding motif remains unaltered
T1018	Speculation 343 353	suggesting
E1009	Speculation:T1018 Scope:T1019
T1019	Span 343 470	suggesting that Foxp3 expression in thymic epithelial cells was crucial for directing development of T cells in the thymus [42]
T1020	Speculation 1247 1250	may
E1010	Speculation:T1020 Scope:T1021
T1021	Span 1247 1286	may also include the zinc finger domain
T1022	Speculation 1141 1144	may
E1011	Speculation:T1022 Scope:T1023
T1023	Span 1141 1234	may tolerate certain mutations as long as the NF-kappaB/NF-AT binding motif remains unaltered
T1024	Speculation 1469 1472	may
E1012	Speculation:T1024 Scope:T1025
T1025	Span 1469 1550	may also be important with respect to Foxp3 function is the leucine zipper domain
T1026	Speculation 1310 1313	may
E1013	Speculation:T1026 Scope:T1027
T1027	Span 1305 1376	that may be targeted by the amino-terminal proline-rich region of Foxp3
T1028	Negation 2293 2300	absence
E1014	Negation:T1028 Scope:T1029
T1029	Span 2293 2349	absence of the HTLV-I-encoded transactivator protein Tax
T1030	Speculation 1734 1737	may
E1015	Speculation:T1030 Scope:T1031
T1031	Span 1734 1768	may play a role in dimer formation
T1032	Speculation 2938 2953	indicating that
E1016	Speculation:T1032 Scope:T1033
T1033	Span 2938 3096	indicating that higher regulatory activity of CD4+CD25+ T cells from HIV-1-infected patients was associated with lower HIV-1 viral loads in these patients [46
T1034	Negation 2729 2732	not
E1017	Negation:T1034 Scope:T1035
T1035	Span 2729 2750	not in Jurkat T cells
T1036	Negation 4129 4132	not
E1018	Negation:T1036 Scope:T1037
T1037	Span 4129 4171	not directly affect the functioning of Tax
T1038	Negation 3808 3811	not
E1019	Negation:T1038 Scope:T1039
T1039	Span 3808 3820	not DeltaFKH
T1040	Speculation 5466 5473	whether
E1020	Speculation:T1040 Scope:T1041
T1041	Span 5466 5511	whether in the presence or the absence of Tax
T1042	Negation 5497 5504	absence
E1021	Negation:T1042 Scope:T1043
T1043	Span 5497 5512	absence of Tax)
T1044	Speculation 5544 5549	could
E1022	Speculation:T1044 Scope:T1045
T1045	Span 5544 5606	could interact with this additional cellular signaling pathway
T1046	Speculation 5530 5537	whether
E1023	Speculation:T1046 Scope:T1047
T1047	Span 5530 5606	whether Foxp3 could interact with this additional cellular signaling pathway
T1048	Speculation 6489 6499	suggesting
E1024	Speculation:T1048 Scope:T1049
T1049	Span 6489 6555	suggesting that the FKH domain of Foxp3 is important at some level
T1050	Speculation 6004 6007	may
E1025	Speculation:T1050 Scope:T1051
T1051	Span 6004 6049	may be the result of the physical interaction
