T1000	Negation 1331 1334	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1331 1424	not observe any major differences between these two populations throughout the culture period
T1002	Negation 70 74	fail
E1001	Negation:T1002 Scope:T1003
T1003	Span 70 114	fail to silence CD4 expression normally (Fig
T1004	Speculation 1426 1441	indicating that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1426 1607	indicating that in terms of effector CTL differentiation and under our culture conditions, Runx3-/- CD8+ T cells that also coexpress CD4 are indistinguishable from those that do not
T1006	Negation 1604 1607	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1604 1607	not
