T1000	Negation 1588 1594	failed
E1000	Negation:T1000 Scope:T1001
T1001	Span 1588 1661	failed to develop mature and functionally active B- and T-lymphocytes (12
T1002	Speculation 840 847	unclear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 789 847	The cause of the silencing of IRF-4 level remained unclear
T1004	Speculation 2296 2303	thought
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2181 2343	De novo DNA methylation of genes such as cell cycle, DNA repair, apoptosis and tumor suppressor genes is therefore thought to be involved in tumorigenesis (15-17)
T1006	Speculation 1759 1766	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1759 1823	suggest a crucial role for IRF-4 in the function of immune cells
T1008	Speculation 2941 2948	thought
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2902 3014	Methyl-CpG-binding proteins (MBPs) are thought to inhibit the binding of transcriptional factors to the promoter
T1010	Speculation 2752 2760	possible
E1005	Speculation:T1010 Scope:T1011
T1011	Span 2752 2813	possible explanation for de novo methylation in tumorigenesis
