T1000	Speculation 1804 1817	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1804 1987	indicate that LMP1 also activates phosphatidylinositol 3 kinase (PI3K)/Akt signaling and that this activation is required for LMP1-mediated transformation of rodent fibroblasts [5,19]
T1002	Speculation 614 620	likely
E1001	Speculation:T1002 Scope:T1003
T1003	Span 614 661	likely contributes to the development of cancer
T1004	Speculation 2654 2660	likely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2654 2803	likely because LMP1 recruits similar TRAF molecules, TRAFs 1/2/3/5 and TRAF6, through the C-terminal activation regions 1 and 2 domains, respectively
T1006	Negation 2205 2211	unable
E1003	Negation:T1006 Scope:T1007
T1007	Span 2168 2264	mice deficient for CD40 or CD40L are unable to form GCs in response to T cell-dependent antigens
T1008	Speculation 3285 3295	suggesting
E1004	Speculation:T1008 Scope:T1009
T1009	Span 3285 3343	suggesting that LMP1 contributes to tumor development [26]
T1010	Negation 2822 2828	unable
E1005	Negation:T1010 Scope:T1011
T1011	Span 2822 2876	unable to restore affinity maturation and GC formation
T1012	Speculation 4551 4561	suggesting
E1006	Speculation:T1012 Scope:T1013
T1013	Span 4551 4624	suggesting that these pathways are required for their growth and survival
T1014	Negation 4240 4247	absence
E1007	Negation:T1014 Scope:T1015
T1015	Span 4240 4282	absence of activated Stat6, the IL4 target
T1016	Speculation 4632 4638	appear
E1008	Speculation:T1016 Scope:T1017
T1017	Span 4626 4762	These appear to be the same targets that are deregulated in wild-type B-1a lymphomas that arise spontaneously through age predisposition
