T1000	Speculation 698 701	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 698 769	may be involved in the regulation of IRF-4 expression in leukemia cells
T1002	Speculation 651 658	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 651 769	whether IRF-4 promoter methylation or mutation may be involved in the regulation of IRF-4 expression in leukemia cells
T1004	Negation 1513 1516	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1513 1639	not detect an association of methylational status and mRNA expression of DNA methyltransferases or methyl-CpG-binding proteins
T1006	Negation 1359 1362	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1359 1386	not in IRF-4-positive cells
T1008	Speculation 1720 1728	putative
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1720 1785	putative mechanism of down-regulated IRF-4 expression in leukemia
T1010	Speculation 1662 1669	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1662 1785	suggest CpG site-specific IRF-4 promoter methylation as a putative mechanism of down-regulated IRF-4 expression in leukemia
