T1000	Negation 779 782	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 779 822	not in Jurkat or primary human CD4+ T cells
T1002	Speculation 346 349	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 346 391	may negatively impact retroviral pathogenesis
T1004	Speculation 1371 1380	suggested
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1371 1467	suggested that high Foxp3 expression is associated with low proviral load and absence of disease
T1006	Negation 1449 1456	absence
E1003	Negation:T1006 Scope:T1007
T1007	Span 1449 1467	absence of disease
T1008	Speculation 1483 1490	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1483 1596	suggest an expanded role for Foxp3 in regulating NF-kappaB- and CREB-dependent cellular and viral gene expression
