T1000	Speculation 7103 7110	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 7103 7171	suggest that LMP1 affects bcl6 and GC formation through this pathway
T1002	Speculation 7272 7278	likely
E1001	Speculation:T1002 Scope:T1003
T1003	Span 7272 7317	likely contribute to malignant transformation
T1004	Speculation 8340 8347	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 8340 8432	suggest that in vivo these properties of LMP1 are major factors in the development of cancer
T1006	Speculation 6275 6281	likely
E1003	Speculation:T1006 Scope:T1007
T1007	Span 6275 6331	likely the inhibition of the Fox01 transcription factors
T1008	Speculation 6766 6772	likely
E1004	Speculation:T1008 Scope:T1009
T1009	Span 6766 6823	likely blocks GC formation through downregulation of bcl6
T1010	Speculation 6857 6870	indicate that
E1005	Speculation:T1010 Scope:T1011
T1011	Span 6857 6956	indicate that expression of LMP1 and bcl6 are mutually exclusive in non-HD and classical HD [72,73]
T1012	Negation 7067 7071	lack
E1006	Negation:T1012 Scope:T1013
T1013	Span 7067 7102	lack of Fox01 in the lymphoma cells
T1014	Speculation 891 894	may
E1007	Speculation:T1014 Scope:T1015
T1015	Span 891 944	may explain the enhanced promotion to lymphomagenesis
T1016	Speculation 263 273	suggesting
E1008	Speculation:T1016 Scope:T1017
T1017	Span 263 325	suggesting that LMP1 is directly involved in tumor development
T1018	Speculation 1402 1405	may
E1009	Speculation:T1018 Scope:T1019
T1019	Span 1402 1479	may contribute to the bias of LMP1 transgenic mice towards B-1 cell lymphomas
T1020	Speculation 1131 1139	possibly
E1010	Speculation:T1020 Scope:T1021
T1021	Span 1131 1184	possibly contribute to the expansion of B-1 cells [20
T1022	Negation 1713 1716	not
E1011	Negation:T1022 Scope:T1023
T1023	Span 1713 1742	not transformation [24,50,51]
T1024	Negation 1572 1579	absence
E1012	Negation:T1024 Scope:T1025
T1025	Span 1572 1597	absence of transformation
T1026	Speculation 1782 1785	may
E1013	Speculation:T1026 Scope:T1027
T1027	Span 1782 1880	may account for the ability of LMP2 to exacerbate autoimmunity and bypass anergy induction [52,53]
T1028	Speculation 1613 1620	suggest
E1014	Speculation:T1028 Scope:T1029
T1029	Span 1613 1742	suggest that the mimicry of B cell receptor signaling by LMP2 promotes B-1 cell differentiation but not transformation [24,50,51]
T1030	Speculation 2207 2214	thought
E1015	Speculation:T1030 Scope:T1031
T1031	Span 2160 2254	the differentiation of B-1 versus B-2 cells is thought to be independent of CD40 signaling [54
T1032	Negation 1943 1946	not
E1016	Negation:T1032 Scope:T1033
T1033	Span 1943 2006	not reflect effects of LMP1 signaling on B cell differentiation
T1034	Speculation 2930 2943	indicate that
E1017	Speculation:T1034 Scope:T1035
T1035	Span 2930 3070	indicate that although LMP1 is expressed in all B lymphocytes in the transgenic mice, malignancy develops in this specific subset of B cells
T1036	Speculation 2816 2823	thought
E1018	Speculation:T1036 Scope:T1037
T1037	Span 2802 2895	B-1 cells are thought to be the murine progenitor of B cell chronic lymphocytic leukemia [30]
T1038	Speculation 4272 4275	may
E1019	Speculation:T1038 Scope:T1039
T1039	Span 4272 4370	may further enhance Stat3 activation or may contribute to other IL10-responsive signaling pathways
T1040	Speculation 4170 4178	suggests
E1020	Speculation:T1040 Scope:T1041
T1041	Span 4170 4308	suggests that although Stat3 is constitutively activated in the lymphoma cells, the induction of IL10 may further enhance Stat3 activation
T1042	Speculation 4915 4925	suggesting
E1021	Speculation:T1042 Scope:T1043
T1043	Span 4915 4995	suggesting that activation of cRel is associated with B cell transformation [27]
T1044	Speculation 4312 4315	may
E1022	Speculation:T1044 Scope:T1045
T1045	Span 4312 4370	may contribute to other IL10-responsive signaling pathways
T1046	Negation 5741 5744	not
E1023	Negation:T1046 Scope:T1047
T1047	Span 5741 5827	not lead to phosphorylation and inactivation of the downstream target GSK3 (Figure 6A)
T1048	Speculation 5014 5021	suggest
E1024	Speculation:T1048 Scope:T1049
T1049	Span 5014 5183	suggest that similar to CD40-induced proliferation, LMP1 induces proliferation through PI3K-mediated activation of Akt and activation of NFkappaB components such as cRel
T1050	Speculation 6189 6196	suggest
E1025	Speculation:T1050 Scope:T1051
T1051	Span 6189 6255	suggest that other Akt targets contribute to malignant progression
T1052	Negation 5947 5950	not
E1026	Negation:T1052 Scope:T1053
T1053	Span 5947 6077	not affect the survival of LMP1 transgenic lymphocytes or the wild-type and LMP1 transgenic lymphoma cells (Figure 7A, 7C, and 7E)
