T1000	Negation 530 532	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 530 597	no other structural homologies between these two genes can be found
T1002	Speculation 147 154	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 51 233	GATA3, a member of the GATA family that is abundantly expressed in the T-lymphocyte lineage, is thought to participate in T-cell receptor gene activation through binding to enhancers
