T1000	Speculation 635 647	hypothesized
E1000	Speculation:T1000 Scope:T1001
T1001	Span 635 746	hypothesized that this increased viral transcription was mediated, in part, through the phosphorylation of CREB
T1002	Negation 600 603	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 600 630	not CD3 receptor cross-linking
T1004	Negation 1165 1167	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1165 1218	no change in total level of CREB protein was observed
T1006	Negation 885 888	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 885 892	not CD3
T1008	Speculation 1588 1598	suggesting
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1588 1697	suggesting that lymphocyte activation enhances binding independently of phosphorylation of CREB at serine 133
T1010	Speculation 1308 1318	suggesting
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1308 1431	suggesting phosphorylation required antecedent activation of both protein tyrosine kinases (PTK) and protein kinase A (PKA)
T1012	Speculation 1823 1830	suggest
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1823 1940	suggest CD2 receptor modulation of CRE-mediated transcription following ligand engagement (e.g. cell-to-cell contact)
T1014	Speculation 1710 1718	indicate
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1710 1818	indicate specific modulation of the CREB/ATF-1 family of transcription factors by the CD2 signalling pathway
