T1000	Speculation 1323 1336	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1323 1465	indicate that defective recruitment of NF-kappa B may underlie Nef's negative transcriptional effects on the HIV-1 and interleukin 2 promoters
T1002	Negation 994 997	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 994 1128	not affect the DNA-binding activity of other transcription factors implicated in HIV-1 regulation, including SP-1, USF, URS, and NF-AT
T1004	Speculation 1484 1492	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1484 1601	suggests that Nef inhibits NF-kappa B induction by interfering with a signal derived from the T-cell receptor complex
T1006	Speculation 1373 1376	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1373 1465	may underlie Nef's negative transcriptional effects on the HIV-1 and interleukin 2 promoters
