T1000	Negation 1127 1134	lacking
E1000	Negation:T1000 Scope:T1001
T1001	Span 1127 1236	lacking the transcriptional activator functions AF-1 and AF-2, or AF-2 only, or the entire DNA-binding domain
T1002	Speculation 856 863	appears
E1001	Speculation:T1002 Scope:T1003
T1003	Span 846 919	c-erbA/TR appears to act as a binary switch affecting erythroid cell fate
T1004	Speculation 1706 1716	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1706 1769	suggesting a pivotal role of RXR for erythroid cell development
