T1000	Negation 957 960	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 957 978	not as p50 homodimers
T1002	Speculation 422 434	examined for
E1001	Speculation:T1002 Scope:T1003
T1003	Span 422 514	examined for their capacity to interact with the PRDII regulatory element of interferon beta
T1004	Speculation 1096 1099	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1096 1176	may permit functional diversification of a limited number of regulatory proteins
