T1000	Speculation 1743 1746	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1743 1816	may improve the survival of transduced cells and prolong clinical benefit
T1002	Speculation 1617 1624	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1617 1816	suggest that in future clinical gene therapy trials, a combined pharmacologic and genetic strategy like the one reported here may improve the survival of transduced cells and prolong clinical benefit
