T1000	Negation 943 946	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 943 982	not inhibit NF-kappaB activation by LPS
T1002	Speculation 195 202	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 154 316	The nuclear factor kappaB (NF-kappaB) is thought to be crucially involved in the gene activation of several cytokines, including tumor necrosis factor alpha (TNF)
T1004	Speculation 1099 1102	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1099 1210	may be modulated at the molecular level by signals originating from tissue structural cells such as fibroblasts
T1006	Speculation 1024 1034	hypothesis
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1024 1210	hypothesis that inflammatory and immune responses of monocytes/macrophages may be modulated at the molecular level by signals originating from tissue structural cells such as fibroblasts
