T1000	Negation 947 958	rather than
E1000	Negation:T1000 Scope:T1001
T1001	Span 947 986	rather than by antigen receptor signals
T1002	Negation 757 760	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 757 784	not with calcium ionophores
T1004	Speculation 1428 1435	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1428 1595	suggest that IL-1 induces both NF-kappa B nuclear translocation and the synthesis of a protein(s) responsible for terminating NF-kappa B-DNA interaction in the nucleus
T1006	Negation 1191 1194	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1188 1242	is not associated with I kappa B nuclear translocation
T1008	Speculation 1658 1666	probably
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1658 1795	probably by functionally antagonizing the IL-1-induced synthesis of a protein(s) responsible for the transient NF-kappa B-DNA interaction
