T1000	Speculation 1223 1230	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1223 1356	whether NF(P), a nuclear factor specific for the P sequence, is related to NF-kappa B and nuclear factor for activated T cell (NF-AT)
T1002	Speculation 745 758	indicate that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 745 851	indicate that the IL-5 gene is positively regulated by cAMP in a manner opposite to that for the IL-2 gene
T1004	Speculation 1612 1625	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1612 1778	indicate that a component or components of NF-AT have the potential to reconstitute NF(P), whereas NF-kappa B alone does not account for NF(P) in Jurkat crude extract
T1006	Negation 1733 1736	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1733 1778	not account for NF(P) in Jurkat crude extract
T1008	Speculation 1810 1817	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1810 1895	suggest that NF-AT-like factors are involved in the regulation of IL-4 and IL-5 genes
