T1000	Negation 755 758	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 755 803	not interfere with the synthesis of Rel proteins
T1002	Negation 86 89	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 86 140	not with the processing of p105/NF-kappa B1 in T cells
T1004	Negation 1016 1019	nor
E1002	Negation:T1004 Scope:T1005
T1005	Span 1016 1143	nor does it "stabilize" the C-terminal portion of p105, I kappa B gamma, which is degraded during p105 processing to mature p50
T1006	Negation 942 949	neither
E1003	Negation:T1006 Scope:T1007
T1007	Span 942 1143	neither inhibits the processing of the NF-kappa B1 precursor p105 to p50, nor does it "stabilize" the C-terminal portion of p105, I kappa B gamma, which is degraded during p105 processing to mature p50
T1008	Speculation 1159 1172	indicate that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1159 1344	indicate that CsA interferes with a specific event in the signal-induced degradation of I kappa B alpha and I kappa B beta, but does not affect the processing of NF-kappa B1/p105 to p50
T1010	Negation 1292 1295	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1292 1344	not affect the processing of NF-kappa B1/p105 to p50
