T1000	Speculation 633 640	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 633 743	whether the HSF2 isoforms play functionally distinct roles during the hemin-mediated erythroid differentiation
T1002	Speculation 530 537	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 530 628	whether the molar ratio of HSF2-alpha and HSF2-beta isoforms is crucial for the activation of HSF2
T1004	Speculation 1377 1384	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1377 1507	suggest that HSF2-beta acts as a negative regulator of HSF2 activity during hemin-mediated erythroid differentiation of K562 cells
