T1000	Negation 1081 1084	nor
E1000	Negation:T1000 Scope:T1001
T1001	Span 1081 1212	nor EA/S motifs contributed pronouncedly to Akv MLV transcription in NIH 3T3 cells lacking DNA-binding ALF1 or HEB and E2A proteins
T1002	Negation 1066 1073	neither
E1001	Negation:T1002 Scope:T1003
T1003	Span 1066 1212	neither E(gre) nor EA/S motifs contributed pronouncedly to Akv MLV transcription in NIH 3T3 cells lacking DNA-binding ALF1 or HEB and E2A proteins
T1004	Negation 1339 1342	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1339 1374	not EA/S-directed MLV transcription
T1006	Negation 1164 1171	lacking
E1003	Negation:T1006 Scope:T1007
T1007	Span 1164 1212	lacking DNA-binding ALF1 or HEB and E2A proteins
