T1000	Speculation 640 645	might
E1000	Speculation:T1000 Scope:T1001
T1001	Span 640 676	might be identical or related to USF
T1002	Speculation 617 626	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 617 676	suggested that HIV-TF1 might be identical or related to USF
T1004	Speculation 780 790	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 780 852	suggesting that phosphorylation of HIV-TF1 was essential for DNA binding
T1006	Speculation 659 661	or
E1003	Speculation:T1006 Scope:T1007
T1007	Span 649 676	identical or related to USF
T1008	Speculation 991 998	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 991 1062	suggest that HIV-TF1 is involved in transcriptional regulation of HIV-1
