T1000	Speculation 1555 1562	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1555 1652	suggest a general role for Tax induction of IL-1alpha gene transcription by the NF-kappaB pathway
T1002	Negation 915 921	unable
E1001	Negation:T1002 Scope:T1003
T1003	Span 915 993	unable to induce transcriptional activity of IL-1alpha promoter-CAT constructs
T1004	Speculation 1716 1719	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1716 1915	may be important in the hypercalcemia, osteolytic bone lesions, neutrophilia, elevation of C-reactive protein, and fever frequently seen in patients with HTLV-I-induced adult T-cell leukemia/lymphoma
