T1000	Speculation 1375 1378	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1375 1476	may be involved in T cell activation as important negative regulators of the transcription factor AP1
T1002	Speculation 1316 1324	suggests
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1316 1476	suggests that protein phosphatases 1 and 2A (PP1 and PP2A) may be involved in T cell activation as important negative regulators of the transcription factor AP1
