T1000	Speculation 1732 1735	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1732 1925	may be of value as a reporter gene for analyzing the mechanism of action of CsA and its influence on the positive and negative selection of lymphocytes in response to self and not-self antigens
T1002	Speculation 1678 1681	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1678 1725	may be important in achieving immunosuppression
T1004	Negation 557 560	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 557 583	not reverse CsA inhibition
T1006	Speculation 139 142	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 139 394	may achieve its immunosuppressive effects by inhibiting the calcium- and calmodulin-dependent phosphatase calcineurin which is required for activation of target genes by members of the NFAT (nuclear factor of activated T cells) transcription factor family
T1008	Speculation 640 643	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 601 655	at least one other NFAT-sensitive gene may be involved
T1010	Speculation 585 595	suggesting
E1005	Speculation:T1010 Scope:T1011
T1011	Span 585 655	suggesting that at least one other NFAT-sensitive gene may be involved
T1012	Speculation 767 776	potential
E1006	Speculation:T1012 Scope:T1013
T1013	Span 767 811	potential phosphoprotein of unknown function
T1014	Speculation 696 705	potential
E1007	Speculation:T1014 Scope:T1015
T1015	Span 696 724	potential NFAT-binding sites
T1016	Negation 1597 1600	not
E1008	Negation:T1016 Scope:T1017
T1017	Span 1597 1633	not excluding other possible targets
T1018	Speculation 795 802	unknown
E1009	Speculation:T1018 Scope:T1019
T1019	Span 795 811	unknown function
T1020	Speculation 1617 1625	possible
E1010	Speculation:T1020 Scope:T1021
T1021	Span 1617 1725	possible targets, early inhibition of G0S2 expression by CsA may be important in achieving immunosuppression
T1022	Speculation 1483 1490	suggest
E1011	Speculation:T1022 Scope:T1023
T1023	Span 1483 1633	suggest that G0S2 expression is required to commit cells to enter the G1 phase of the cell cycle, and that, while not excluding other possible targets
