T1000	Speculation 905 912	unknown
E1000	Speculation:T1000 Scope:T1001
T1001	Span 774 912	the molecular mechanisms by which Ets and NF-kappaB/NFAT proteins cooperatively regulate inducible T-cell gene expression remained unknown
T1002	Speculation 548 558	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 548 748	suggesting that this pattern of nuclear protein binding sites reflects an evolutionarily conserved mechanism for regulating inducible T-cell gene expression that has been co-opted during HIV evolution
T1004	Speculation 1760 1770	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1760 1909	suggesting that physical interaction between Ets and NF-kappaB proteins is required for the transcriptional activity of the HIV-1 and HIV-2 enhancers
T1006	Negation 1619 1624	fails
E1003	Negation:T1006 Scope:T1007
T1007	Span 1619 1654	fails to interact with Ets proteins
T1008	Speculation 2155 2164	potential
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2155 2242	potential target for the development of novel immunosuppressive and antiviral therapies
T1010	Speculation 1942 1949	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1942 2122	suggest that evolutionarily conserved physical interactions between Ets and NF-kappaB/NFAT proteins are important in regulating the inducible expression of T-cell genes and viruses
