T1000	Negation 1236 1239	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1236 1282	not augment cytokine-induced VCAM-1 expression
T1002	Speculation 186 196	hypothesis
E1001	Speculation:T1002 Scope:T1003
T1003	Span 186 249	hypothesis that nitric oxide (NO) limits endothelial activation
T1004	Speculation 1519 1526	propose
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1519 1707	propose that NO's ability to limit endothelial activation and inhibit monocyte adhesion may contribute to some of its antiatherogenic and antiinflammatory properties within the vessel wall
T1006	Speculation 1426 1440	indicated that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1426 1707	indicated that NO represses VCAM-1 gene transcription, in part, by inhibiting NF-kappa B. We propose that NO's ability to limit endothelial activation and inhibit monocyte adhesion may contribute to some of its antiatherogenic and antiinflammatory properties within the vessel wall
T1008	Speculation 1607 1610	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1607 1707	may contribute to some of its antiatherogenic and antiinflammatory properties within the vessel wall
