T1000	Negation 890 897	neither
E1000	Negation:T1000 Scope:T1001
T1001	Span 890 957	neither of these agents reduced LPS-stimulated TF mRNA accumulation
T1002	Speculation 295 303	suggests
E1001	Speculation:T1002 Scope:T1003
T1003	Span 295 500	suggests a role for oxidant stress in the signalling pathway of various cell types by virtue of its ability to induce DNA binding of various transcription factors, including nuclear factor kappa B and AP-1
T1004	Negation 1486 1489	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1486 1546	not result in an accumulation of the less mature forms of TF
T1006	Speculation 967 977	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 967 1024	suggesting a posttranscriptional mechanism for the effect
T1008	Negation 1805 1807	no
E1004	Negation:T1008 Scope:T1009
T1009	Span 1805 1907	no effect on LPS-induced tumor necrosis factor in murine cells, but with inhibition in human monocytes
T1010	Speculation 1585 1592	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1585 1713	suggest that antioxidants exert their effects by impairing translation and/or by causing degradation of newly translated protein
T1012	Speculation 1978 1986	suggests
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1978 2071	suggests a novel mechanism whereby these agents might modulate monocyte/macrophage activation
T1014	Speculation 1767 1775	appeared
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1715 1867	The effect of antioxidants on tumor necrosis factor appeared to be species specific, with no effect on LPS-induced tumor necrosis factor in murine cells
T1016	Speculation 2026 2031	might
E1008	Speculation:T1016 Scope:T1017
T1017	Span 2026 2071	might modulate monocyte/macrophage activation
