T1000	Speculation 835 841	appear
E1000	Speculation:T1000 Scope:T1001
T1001	Span 817 918	the two molecules appear to function in different signaling pathways upstream of IL-2 gene expression
T1002	Negation 741 744	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 699 812	the interaction between SLP-76 and Vav is not required for their cooperation in augmenting IL-2 promoter activity
T1004	Negation 1237 1240	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1237 1247	not SLP-76
T1006	Negation 1172 1179	without
E1003	Negation:T1006 Scope:T1007
T1007	Span 1172 1194	without affecting AP-1
T1008	Speculation 1310 1317	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1310 1454	suggest that the synergy between SLP-76 and Vav in regulating IL-2 gene expression reflects the cooperation between different signaling pathways
