T1000	Speculation 1089 1098	potential
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1089 1232	potential NF-kappaB binding sequence which is located around 120 bp upstream of the transcription initiation site in murine and human p40 genes
T1002	Speculation 948 957	potential
E1001	Speculation:T1002 Scope:T1003
T1003	Span 948 1032	potential nuclear factor (NF)-kappaB binding sites conserved between mouse and human
T1004	Speculation 1627 1634	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1627 1861	suggest that the NF-kappaB binding site located around 120 bp upstream of the transcription initiation site in murine and human p40 promoter regions could be important for the p40 induction by CD40 ligation via activation of NF-kappaB
T1006	Negation 1608 1611	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1608 1611	not
T1008	Speculation 1776 1781	could
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1776 1861	could be important for the p40 induction by CD40 ligation via activation of NF-kappaB
