T1000	Speculation 349 351	if
E1000	Speculation:T1000 Scope:T1001
T1001	Span 349 510	if the benefit is attributable to simple binding and clearance of TNF-alpha or to binding on the cell surface and subsequent deletion of the activated macrophage
T1002	Speculation 339 348	not clear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 339 510	not clear if the benefit is attributable to simple binding and clearance of TNF-alpha or to binding on the cell surface and subsequent deletion of the activated macrophage
T1004	Speculation 524 531	appears
E1002	Speculation:T1004 Scope:T1005
T1005	Span 517 584	a drug appears to be less effective than preclinical models suggest
T1006	Speculation 425 427	or
E1003	Speculation:T1006 Scope:T1007
T1007	Span 425 510	or to binding on the cell surface and subsequent deletion of the activated macrophage
T1008	Speculation 1182 1185	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1182 1258	may soon be possible to predict response on the basis of genetic composition
T1010	Speculation 993 1001	suggests
E1005	Speculation:T1010 Scope:T1011
T1011	Span 993 1092	suggests that these diseases are far more heterogeneous in humans than in their murine counterparts
T1012	Speculation 1582 1585	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1582 1708	may clinicians determine which therapies should remain novelties and which should become an accepted part of the armamentarium
T1014	Speculation 1194 1202	possible
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1194 1258	possible to predict response on the basis of genetic composition
T1016	Speculation 1657 1663	should
E1008	Speculation:T1016 Scope:T1017
T1017	Span 1657 1708	should become an accepted part of the armamentarium
T1018	Speculation 1623 1629	should
E1009	Speculation:T1018 Scope:T1019
T1019	Span 1623 1708	should remain novelties and which should become an accepted part of the armamentarium
