T1000	Speculation 224 234	whether or
E1000	Speculation:T1000 Scope:T1001
T1001	Span 224 406	whether or not human monocytes/macrophages can produce nitric oxide (NO) when stimulated with lipopolysaccharide (LPS), with or without co-stimulation by interferon-gamma (IFN-gamma)
T1002	Negation 352 359	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 352 406	without co-stimulation by interferon-gamma (IFN-gamma)
T1004	Speculation 1257 1263	should
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1171 1377	The importance of resolution of this controversy is that future research in this area should be directed toward the understanding of alternative mechanisms that can result in the successful production of NO
T1006	Negation 991 998	absence
E1003	Negation:T1006 Scope:T1007
T1007	Span 991 1110	absence of one or more nuclear factors in human macrophages (e.g., an LPS-inducible nuclear factor-kappa B/Rel complex)
T1008	Speculation 1332 1335	can
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1332 1377	can result in the successful production of NO
