T1000	Speculation 1081 1095	indicates that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1081 1149	indicates that phospholipase A2 and 5-lipoxygenase are also involved
T1002	Negation 590 592	No
E1001	Negation:T1002 Scope:T1003
T1003	Span 590 668	No degradation of p105 and p100 inhibitors was observed under these conditions
T1004	Speculation 1270 1274	seem
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1160 1343	the NF-kappaB activation pathway involving the acidic sphingomyelinase of the endolysosomial membrane did not seem to participate in the LPS-induced NF-kappaB activation in U937 cells
T1006	Negation 1266 1269	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1160 1343	the NF-kappaB activation pathway involving the acidic sphingomyelinase of the endolysosomial membrane did not seem to participate in the LPS-induced NF-kappaB activation in U937 cells
