T1000	Negation 1265 1268	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1265 1333	not in mature B cells (JY, Namalwa) or nonlymphoid (HeLa) cell lines
T1002	Speculation 972 980	possibly
E1001	Speculation:T1002 Scope:T1003
T1003	Span 972 989	possibly TCR beta
T1004	Negation 2072 2075	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 2072 2086	not HeLa cells
T1006	Speculation 1485 1487	or
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1477 1503	the CRE or T alpha 1 motif
T1008	Speculation 2416 2423	appears
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2372 2561	the transcriptional activity of TCF-1 alpha appears to depend on the TCF-2 alpha and T alpha 1 (CREB) transcription factors and the context of its binding site within the TCR alpha enhancer
