T1000	Negation 643 646	MBP
E1000	Negation:T1000 Scope:T1001
T1001	Span 643 696	MBP stimulated 2-fold increases in IL-8 messenger RNA
T1002	Negation 590 593	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 590 641	not stimulate significant levels of IL-8 production
T1004	Negation 926 928	No
E1002	Negation:T1004 Scope:T1005
T1005	Span 926 995	No NF-IL-6 binding activity was detected in the same nuclear extracts
T1006	Negation 824 827	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 824 924	not produce an increase in the binding activity of nuclear factor (NF)-kappaB or activator protein-1
T1008	Speculation 1248 1261	indicate that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1248 1488	indicate that MBP is selective among the eosinophil granule proteins as a stimulus for neutrophil IL-8 release and, further, that stimulation of neutrophil IL-8 release by MBP involves both transcriptional and posttranscriptional regulation
T1010	Negation 1186 1189	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1186 1231	not stimulate the release of either chemokine
T1012	Speculation 1551 1554	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1551 1641	may contribute to the pathophysiology of acute asthma and other inflammatory lung diseases
