T1000	Negation 885 887	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 885 905	no Sp1 binding sites
T1002	Speculation 503 516	evaluated for
E1001	Speculation:T1002 Scope:T1003
T1003	Span 503 593	evaluated for their capacity to produce virus progeny following transfection-cocultivation
T1004	Speculation 1197 1204	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1197 1445	suggest that the human immunodeficiency virus type 1 LTR possesses functional redundancy which ensures virus replication in different T-cell types and is capable of changing depending on the particular combination of transcriptional factors present
