T1000	Negation 981 984	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 981 1252	not contribute at a detectable level to the mature erythrocyte compartment of the chimeric animals, based on analysis of glucose phosphate isomerase-1 (GPI-1) isozymes and hemoglobins that distinguish ES cell-derived erythrocytes from host blastocyst-derived erythrocytes
T1002	Negation 714 722	with the
E1001	Negation:T1002 Scope:T1003
T1003	Span 714 803	with the exception of beta h1-globin, which continued to be expressed at a very low level
T1004	Speculation 1446 1460	indicated that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1446 1591	indicated that the EKLF-/- erythrocytes in adult animals must be short-lived, apparently due to the imbalance of beta- versus alpha-globin chains
T1006	Speculation 1355 1364	suggested
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1355 1439	suggested that the ES cell-derived reticulocytes were present at a level of 6% to 8%
T1008	Speculation 1524 1534	apparently
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1524 1672	apparently due to the imbalance of beta- versus alpha-globin chains, leading to the precipitation of excess alpha-globin chains to form Heinz bodies
T1010	Speculation 1503 1507	must
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1503 1591	must be short-lived, apparently due to the imbalance of beta- versus alpha-globin chains
