T1000	Speculation 853 859	should
E1000	Speculation:T1000 Scope:T1001
T1001	Span 853 979	should be useful for therapeutic strategies and the development of immunosuppressants targeting the CD28 costimulatory pathway
T1002	Speculation 716 723	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 716 836	suggest that lipoxygenase metabolites activate ROI formation which then induce IL-2 expression via NF-kappa B activation
