T1000	Negation 730 737	absence
E1000	Negation:T1000 Scope:T1001
T1001	Span 730 784	absence of exogenously supplemented 1 alpha,25-(OH)2D3
T1002	Negation 644 647	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 644 664	not express VDR mRNA
T1004	Negation 1188 1194	failed
E1002	Negation:T1004 Scope:T1005
T1005	Span 1188 1261	failed to induce 24-hydroxylase mRNA or its metabolic activity in B cells
T1006	Negation 994 1000	failed
E1003	Negation:T1006 Scope:T1007
T1007	Span 994 1039	failed to modulate CD23 expression in B cells
T1008	Speculation 1278 1285	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1278 1425	suggest that although human B lymphocytes can express VDR mRNA and protein, they exhibit a functional block for vitamin D-dependent gene regulation
