T1000	Negation 333 336	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 333 388	not undergone T cell receptor (TCR) gene rearrangements
T1002	Negation 29 32	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 29 66	not of gamma delta T cell development
T1004	Speculation 835 842	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 835 984	suggest possible mechanisms by which Id3 overexpression can differentially affect development of pre-T cells into TCRalpha beta and gamma delta cells
T1006	Negation 678 681	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 678 709	not into TCRgamma delta T cells
T1008	Negation 1106 1109	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1106 1133	not from control-transduced
T1010	Speculation 843 851	possible
E1005	Speculation:T1010 Scope:T1011
T1011	Span 843 984	possible mechanisms by which Id3 overexpression can differentially affect development of pre-T cells into TCRalpha beta and gamma delta cells
T1012	Speculation 1245 1252	suggest
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1245 1353	suggest that bHLH factors are required to control T cell development after the T/NK developmental checkpoint
