T1000	Negation 1026 1033	neither
E1000	Negation:T1000 Scope:T1001
T1001	Span 1026 1083	neither TNF or LPS stimulated VCAM-1 expression in HUAECs
T1002	Negation 471 474	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 471 484	not to HUAECs
T1004	Speculation 1525 1533	indicate
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1525 1625	indicate a dissociation between the ability of HUAECs to upregulate nuclear factor-kappaB and VCAM-1
T1006	Negation 1299 1301	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1299 1404	no difference in the pattern of TNF-stimulated nuclear factor-kappaB activation between HUVECs and HUAECs
