T1000	Speculation 525 534	plausible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 525 708	plausible that LMP-1 modifies signal transduction pathways that result in the activation of one or more transcription factors that ultimately regulate transcription of oncogenic genes
T1002	Speculation 506 513	unknown
E1001	Speculation:T1002 Scope:T1003
T1003	Span 446 513	The mechanisms by which LMP-1 upregulates these proteins is unknown
T1004	Speculation 1438 1451	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1438 1523	indicate that LMP-1 activates NF-kappa B in B-cell lines by targeting I kappa B alpha
T1006	Speculation 940 953	indicate that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 940 1081	indicate that increased NF-kappa B DNA binding and functional activity are present in B-lymphoid cells stably or transiently expressing LMP-1
