T1000	Negation 1057 1060	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1057 1144	not migrate with translated p50/p65 dimers but instead comigrated with c-Rel/p65 dimers
T1002	Negation 820 823	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 820 862	not p50/p65 heterodimers or p50 homodimers
T1004	Negation 1273 1280	absence
E1002	Negation:T1004 Scope:T1005
T1005	Span 1273 1305	absence of p50 in the TF complex
T1006	Speculation 903 917	indicated that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 903 1099	indicated that the presence of a cytosine at position 1 precluded binding of NF-kappa B. In fact, under low-ionic-strength conditions, the TF complex did not migrate with translated p50/p65 dimers
T1008	Speculation 1419 1433	indicated that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1419 1538	indicated that the TF site conferred LPS inducibility on a heterologous promoter and was transactivated by c-Rel or p65
