T1000	Negation 902 908	failed
E1000	Negation:T1000 Scope:T1001
T1001	Span 902 975	failed to restore the proliferative response in the presence of tepoxalin
T1002	Negation 775 778	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 758 815	Cytotoxicity was not demonstrated at these concentrations
T1004	Speculation 1422 1425	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1422 1600	may be at least in part due to its ability to reduce the amount of available iron resulting in decreased activation of NF kappa B and subsequent inhibition of cytokine production
T1006	Speculation 1352 1359	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1352 1600	suggest that the action of tepoxalin to inhibit proliferation in PBMC may be at least in part due to its ability to reduce the amount of available iron resulting in decreased activation of NF kappa B and subsequent inhibition of cytokine production
