T1000	Negation 1562 1571	no longer
E1000	Negation:T1000 Scope:T1001
T1001	Span 1495 1607	Promoter constructs with mutations in these sequence elements were no longer expressed specifically in monocytes
T1002	Speculation 1251 1264	indicate that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1251 1493	indicate that Mono B contains a member of the polyomavirus enhancer-binding protein 2/core-binding factor (PEBP2/CBF) family, which includes the AML1 gene product, while Mono A is a distinct complex preferentially expressed in monocytic cells
T1004	Speculation 1795 1808	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1795 1988	indicate that the monocyte/B-cell-specific transcription factor PU.1 and the Mono A and Mono B protein complexes act in concert to regulate monocyte-specific transcription of the CSF-1 receptor
T1006	Negation 1752 1755	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1752 1779	not other cell types tested
