T1000	Negation 964 967	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 876 986	LPS binding to plasma membrane receptors and internalization of LPS into monocytes were not affected by lysoPC
T1002	Negation 519 522	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 519 572	not affect LPS-induced TF activity of human monocytes
T1004	Speculation 1614 1617	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1614 1698	may thus attenuate activation of coagulation during inflammation and atherosclerosis
T1006	Speculation 1523 1531	probably
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1523 1605	probably being mediated by both transcriptional and posttranscriptional mechanisms
