T1000	Negation 523 526	Nor
E1000	Negation:T1000 Scope:T1001
T1001	Span 523 582	Nor was fragmentation observed after treatment with RU38486
T1002	Negation 361 364	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 361 521	not observed in ICR27TK.3 cells containing mutant glucocorticoid receptors (L753F) that are activation-deficient but retain the ability to repress AP-1 activity
T1004	Speculation 584 599	indicating that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 584 643	indicating that repression of AP-1 activity is not involved
T1006	Negation 631 634	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 600 643	repression of AP-1 activity is not involved
T1008	Negation 1245 1248	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1245 1277	not in resistant ICR27TK.3 cells
T1010	Speculation 927 937	suggesting
E1005	Speculation:T1010 Scope:T1011
T1011	Span 927 1006	suggesting that synthesis of a component with a rapid turnover rate is required
T1012	Speculation 1427 1429	or
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1413 1458	IkappaB alpha or some other inhibitory factor
T1014	Speculation 1334 1348	indicated that
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1334 1458	indicated that a substantial amount of cytoplasmic NF-kappaB is complexed with IkappaB alpha or some other inhibitory factor
T1016	Speculation 1549 1552	may
E1008	Speculation:T1016 Scope:T1017
T1017	Span 1549 1599	may contribute to glucocorticoid-induced apoptosis
T1018	Speculation 1474 1481	suggest
E1009	Speculation:T1018 Scope:T1019
T1019	Span 1474 1599	suggest that induction of a labile inhibitory factor such as IkappaB alpha may contribute to glucocorticoid-induced apoptosis
