T1000	Speculation 520 530	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 520 596	suggesting a cooperative effect of B7 and LFA-3 at the transcriptional level
T1002	Negation 357 360	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 357 366	not LFA-3
T1004	Speculation 1561 1569	indicate
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1561 1759	indicate distinct effects of B7 and LFA-3 costimulation on the activity of AP-1 and NF-kappa B. These may partly account for the differential effects of B7 and LFA-3 costimulation on IL-2 expression
T1006	Negation 899 902	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 899 937	not influence the levels of NF-kappa B
T1008	Speculation 1663 1666	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1663 1759	may partly account for the differential effects of B7 and LFA-3 costimulation on IL-2 expression
