T1000	Speculation 1244 1254	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1244 1303	suggesting an additional structural role for the AP-1 sites
T1002	Speculation 739 753	indicated that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 739 813	indicated that five Sp1 sites mediated basal expression in uninduced cells
T1004	Speculation 1522 1536	indicated that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1522 1621	indicated that c-Fos/c-Jun, c-Rel/p65, and Sp1 regulate TF gene expression in human monocytic cells
