T1000	Speculation 791 798	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 791 902	suggest that a decline in proteasome activity results in a failure to fully degrade IkappaBalpha in the elderly
T1002	Negation 557 560	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 468 612	Examination of activation-induced phosphorylation and ubiquitination of IkappaBalpha did not demonstrate any significant age-related alterations
T1004	Speculation 1121 1124	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1121 1180	may be central to immune dysfunction that accompanies aging
T1006	Speculation 941 944	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 941 1071	may underlie both the observed decrease in NFkappaB induction and the IL-2 receptor expression in TNF-treated T cells during aging
