T1000	Negation 605 607	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 605 638	no intrinsic DNA-binding activity
T1002	Speculation 183 196	indicate that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 183 379	indicate that in addition to the octamer-binding proteins Oct-1 and Oct-2, other B cell components are required for lymphoid-restricted, octamer site-mediated immunoglobulin gene promoter activity
T1004	Negation 833 839	absent
E1002	Negation:T1004 Scope:T1005
T1005	Span 833 884	absent in most of the other cells or tissues tested
T1006	Negation 694 697	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 694 722	not those of Oct-4 and Oct-6
