T1000	Speculation 978 988	indicating
E1000	Speculation:T1000 Scope:T1001
T1001	Span 978 1060	indicating ERK2 is the preferred substrate for upstream kinase of the MAPK pathway
T1002	Negation 940 947	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 940 976	without significantly affecting ERK1
T1004	Speculation 1873 1881	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1873 2103	suggests that CoCl2-induced cellular signals directing increased expression of VCAM-1 in HUVEC involve downstream activation of MAP kinase and NF-kappaB, while the phosphorylation of PECAM-1 occurs as a result of activation of PKC
