T1000	Speculation 1003 1010	propose
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1003 1192	propose that KBF1 is a competitive inhibitor of NF-kappa B and discuss how these factors may be involved in the transient expression of IL-2 and IL-2R alpha genes during the immune response
T1002	Negation 984 987	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 984 998	not sufficient
T1004	Speculation 1092 1095	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1078 1192	these factors may be involved in the transient expression of IL-2 and IL-2R alpha genes during the immune response
