T1000	Speculation 360 362	or
E1000	Speculation:T1000 Scope:T1001
T1001	Span 325 422	endothelial cell glutathione (GSH) or oxidized glutathione (GSSG) can alter neutrophil adhesivity
T1002	Speculation 306 313	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 306 390	whether changes in endothelial cell glutathione (GSH) or oxidized glutathione (GSSG)
T1004	Negation 1238 1241	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1238 1265	not with the GSSG/GSH ratio
T1006	Negation 725 732	without
E1003	Negation:T1006 Scope:T1007
T1007	Span 725 746	without cell toxicity
T1008	Negation 1353 1356	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1353 1372	not with GSH levels
