T1000	Speculation 1260 1270	indicating
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1260 1339	indicating a dominant role of this adhesion molecule in the late phase response
T1002	Speculation 777 787	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 777 824	suggesting a role for xanthine oxidase and H2O2
T1004	Speculation 1772 1785	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1772 1991	indicate that A/R elicits a two-phase neutrophil-endothelial cell adhesion response that involves transcription-independent and transcription-dependent surface expression of different endothelial cell adhesion molecules
T1006	Speculation 1555 1565	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1555 1608	suggesting a role for de novo macromolecule synthesis
