T1000	Speculation 401 408	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 401 521	suggest an involvement of reactive oxygen species (ROS) in signal transduction pathways leading to NF-kappa B activation
T1002	Speculation 349 356	appears
E1001	Speculation:T1002 Scope:T1003
T1003	Span 318 383	this transcriptional activator appears to regulate HIV activation
T1004	Speculation 700 703	can
E1002	Speculation:T1004 Scope:T1005
T1005	Span 687 742	antioxidants can be used as therapeutic agents for AIDS
T1006	Speculation 600 606	should
E1003	Speculation:T1006 Scope:T1007
T1007	Span 600 676	should block the activation of NF-kappa B and subsequently HIV transcription
T1008	Speculation 1241 1244	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1241 1278	may be effective in AIDS therapeutics
T1010	Speculation 1209 1222	indicate that
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1209 1278	indicate that alpha-lipoic acid may be effective in AIDS therapeutics
