T1000	Negation 698 700	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 698 760	no competition between TPO and EPO for binding to EPO receptor
T1002	Negation 649 652	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 649 686	not the erythropoietin (EPO) receptor
T1004	Speculation 1036 1043	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1036 1092	suggest that TPO has a distinct action on erythropoiesis
T1006	Speculation 777 784	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 777 876	suggest that TPO has a direct effect on hemoglobinization via a specific receptor on UT-7/GMT cells
