T1000	Speculation 435 440	seems
E1000	Speculation:T1000 Scope:T1001
T1001	Span 410 523	Activation of NF-kappa B seems to play an important role in the regulation of many proinflammatory cytokine genes
T1002	Negation 588 592	lack
E1001	Negation:T1002 Scope:T1003
T1003	Span 588 643	lack respective binding sites in their promoter regions
T1004	Speculation 907 910	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 907 1006	may be important to substitute for metabolized transcription factor proteins after their activation
T1006	Speculation 716 724	possible
E1003	Speculation:T1006 Scope:T1007
T1007	Span 716 735	possible importance
T1008	Speculation 1540 1545	seems
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1448 1597	the long-term regulation of transcription factor gene expression in non-proliferating cells seems to be of minor importance after influenza infection
T1010	Negation 1262 1264	no
E1005	Negation:T1010 Scope:T1011
T1011	Span 1262 1298	no significant changes were detected
