T1000	Speculation 1335 1345	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1335 1386	suggesting a rapid mode of action of this inhibitor
T1002	Speculation 231 245	indicated that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 231 443	indicated that protein tyrosine phosphatase (PTPase) inhibitors can down-modulate the tumor necrosis factor (TNF)-mediated activation of the nuclear transcription factor NF-kappa B in ML-1a, a monocytic cell line
T1004	Speculation 1902 1905	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1902 2015	may provide a novel target of drug development for treatment of inflammation, atherogenesis, and tumor metastasis
T1006	Speculation 1738 1744	either
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1738 1767	either directly or indirectly
