T1000	Negation 1156 1162	unable
E1000	Negation:T1000 Scope:T1001
T1001	Span 1127 1221	VDR DNA-binding mutants were unable to either bind to this element in vitro or repress in vivo
T1002	Speculation 510 520	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 510 626	suggesting that it is a direct transcriptional repressive effect on IL-2 expression by the vitamin D3 receptor (VDR)
T1004	Negation 1392 1395	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1392 1433	not sufficient to mediate IL-2 repression
T1006	Negation 1293 1302	could not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1299 1326	not repress IL-2 expression
T1008	Speculation 1636 1649	indicate that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1636 1777	indicate that the VDR-retinoid X receptor heterodimer blocks NFATp/AP-1 complex formation and then stably associates with the NF-AT-1 element
T1010	Speculation 1342 1355	indicate that
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1342 1433	indicate that DNA binding by VDR is necessary but not sufficient to mediate IL-2 repression
T1012	Speculation 1879 1882	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1879 1986	may provide a mechanistic explanation of how vitamin derivatives can act as potent immunosuppressive agents
