T1000	Speculation 1355 1362	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1355 1544	suggest that UV-induced signal transduction is mediated via cell surface receptors that normally respond to biological stimulation, whereas H2O2 is able to partially bypass this requirement
T1002	Speculation 206 214	believed
E1001	Speculation:T1002 Scope:T1003
T1003	Span 115 250	Several mammalian responses to UV irradiation, including the activation of NF-kappa B, are believed to involve tyrosine phosphorylation
