T1000	Speculation 567 574	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 567 692	appears to be mediated via protein-protein interactions and not by direct binding of EBNA-2 type A (of EBV type 1) to the DNA
T1002	Negation 627 630	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 627 692	not by direct binding of EBNA-2 type A (of EBV type 1) to the DNA
T1004	Negation 1308 1312	None
E1002	Negation:T1004 Scope:T1005
T1005	Span 1308 1346	None of the DNA fragments investigated
T1006	Speculation 918 925	whether
E1003	Speculation:T1006 Scope:T1007
T1007	Span 918 1002	whether EBNA-2 also trans-activates the LMP promoter by protein-protein interactions
T1008	Negation 1426 1428	No
E1004	Negation:T1008 Scope:T1009
T1009	Span 1426 1513	No significant differences between EBNA-2-positive and EBNA-2-negative nuclear extracts
T1010	Speculation 1347 1356	indicated
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1347 1424	indicated interaction of EBNA-2 with the DNA via protein-protein interactions
T1012	Speculation 1933 1938	might
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1933 2080	might indeed contain specific complexes bound to the LMP promoter which are, however, too labile to be detected in a standard gel retardation assay
