T1000	Speculation 426 428	or
E1000	Speculation:T1000 Scope:T1001
T1001	Span 426 513	or protein level might underlie the age-associated impairments of AP-1 in human T cells
T1002	Speculation 361 368	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 361 513	whether aberrancies in the regulation of c-fos/c-jun at the mRNA or protein level might underlie the age-associated impairments of AP-1 in human T cells
T1004	Negation 739 742	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 739 748	not c-Jun
T1006	Speculation 443 448	might
E1003	Speculation:T1006 Scope:T1007
T1007	Span 443 513	might underlie the age-associated impairments of AP-1 in human T cells
T1008	Speculation 2051 2054	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2051 2132	may contribute to the age-related impairments of AP-1 activation in human T cells
T1010	Speculation 1938 1945	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1938 2132	suggest that underlying aberrancies in the induction of c-fos/c-jun as well as their nuclear regulatory proteins may contribute to the age-related impairments of AP-1 activation in human T cells
