T1000	Speculation 981 989	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 981 1054	suggests that this glucocorticoid inhibits signals downstream or parallel
T1002	Negation 938 940	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 938 980	no effect on TPA-induced activation of PKC
T1004	Negation 1257 1260	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1257 1286	not require protein synthesis
T1006	Speculation 1043 1045	or
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1032 1069	downstream or parallel to this enzyme
T1008	Speculation 1858 1865	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1858 2018	suggest that dexamethasone down-regulates TPA-induced transcription of the c-jun gene during monocytic differentiation by inhibiting activation of the AP-1 site
T1010	Speculation 1682 1687	could
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1581 1778	Increases in CAT activity during transient expression of these constructs in TPA-treated U-937 cells could be assigned to the region (-97 to -20) of the promoter that contains the AP-1 binding site
