T1000	Speculation 265 268	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 265 297	may induce programmed cell death
T1002	Speculation 149 161	hypothesized
E1001	Speculation:T1002 Scope:T1003
T1003	Span 149 297	hypothesized that in individuals with certain genetic makeup, MTBE, benzene or their metabolites act as adducts and may induce programmed cell death
T1004	Speculation 1949 1952	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1949 2055	may indicate involvement of this signaling molecule in MTBE and benzene induction of programmed cell death
T1006	Negation 629 636	without
E1003	Negation:T1006 Scope:T1007
T1007	Span 629 677	without a history of exposure to MTBE or benzene
T1008	Speculation 1953 1961	indicate
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1953 2055	indicate involvement of this signaling molecule in MTBE and benzene induction of programmed cell death
