T1000	Speculation 981 988	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 857 1060	This protein, previously identified by its binding to the Ig kappa 3' enhancer and the Ig heavy chain mu E1 site, thus also appears to be quite important in the regulation of MHC class II gene expression
T1002	Negation 782 785	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 782 821	not to the element in the DQ alpha gene
