T1000	Negation 677 680	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 677 685	not NFAT
T1002	Negation 596 603	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 596 685	without affecting the expression of other cytokines that require calcineurin but not NFAT
T1004	Speculation 952 955	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 952 1026	may be useful as therapeutic agents that are less toxic than current drugs
T1006	Negation 901 908	without
E1003	Negation:T1006 Scope:T1007
T1007	Span 901 951	without affecting calcineurin phosphatase activity
