T1000	Speculation 988 991	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 988 1043	may act in concert with PMA/ionomycin inducible factors
T1002	Speculation 917 925	proposed
E1001	Speculation:T1002 Scope:T1003
T1003	Span 917 1043	proposed that ETS1, which is expressed constitutively in Jurkat cells, may act in concert with PMA/ionomycin inducible factors
T1004	Speculation 1545 1552	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1545 1689	suggest that constitutive ETS1, and inducible NFkappaB and AP1, cooperate as part of a higher order transcriptional complex in activated T cells
