T1000	Speculation 1040 1043	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1026 1125	Many of these may be created by alternative splicing of a primary transcript of one Oct factor gene
T1002	Speculation 739 746	appears
E1001	Speculation:T1002 Scope:T1003
T1003	Span 739 955	appears that the B cell-specific expression of Ig genes is mediated at least in part by cell type-specific Oct factors, and that there are both quantitative and qualitative differences between Oct-1 and Oct-2 factors
T1004	Speculation 1130 1133	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1130 1197	may serve a specific function in the fine tuning of gene expression
