T1000	Speculation 1450 1465	indicating that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1450 1617	indicating that the NF(P) interaction is sequence-specific and that binding specificity of the protein paralleled the sequence requirements for IL-4 expression in vivo
T1002	Negation 437 439	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 437 525	no additional DNA segments with enhancer activity were identified in the human IL-4 gene
T1004	Negation 1639 1642	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1639 1704	not share homology with the 5' upstream sequence of the IL-2 gene
