T1000	Speculation 1399 1412	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1399 1539	indicate that, as already reported for the IL2Rbeta promoter, GA-binding protein is an essential component of gammac basal promoter activity
T1002	Speculation 1027 1036	potential
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1027 1099	potential Ets binding sites conserved in the murine gammac promoter gene
T1004	Speculation 1658 1661	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1658 1725	may contribute to the tissue-specific expression of the gammac gene
T1006	Negation 1569 1572	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1569 1612	not restricted to the hematopoietic lineage
