T1000	Speculation 1152 1155	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1152 1196	may result in or may promote atherosclerosis
T1002	Speculation 1070 1075	could
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1070 1196	could lead to endothelial activation, inflammation, and thrombosis, which in turn may result in or may promote atherosclerosis
T1004	Speculation 1169 1172	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1169 1196	may promote atherosclerosis
T1006	Speculation 1166 1168	or
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1166 1196	or may promote atherosclerosis
