T1000	Negation 1302 1305	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1302 1389	not block induction of an immediate-early gene encoding the transcription factor, Egr-1
T1002	Speculation 837 839	if
E1001	Speculation:T1002 Scope:T1003
T1003	Span 837 894	if TPCK and TLCK inhibited LPS induction of TF expression
T1004	Speculation 1418 1432	indicated that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1418 1559	indicated that inhibiting nuclear translocation of c-Rel/p65 heterodimers prevented LPS induction of TF gene transcription in monocytic cells
