T1000	Negation 1120 1123	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1120 1146	not to mutated APC protein
T1002	Speculation 1023 1030	unknown
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1023 1041	unknown protein(s)
T1004	Speculation 1238 1243	might
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1238 1355	might belong to the immediate/early gene family, which controls the signal transduction cascade downstream of the TCR
T1006	Speculation 1214 1222	suggests
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1214 1355	suggests that this gene might belong to the immediate/early gene family, which controls the signal transduction cascade downstream of the TCR
T1008	Speculation 1624 1627	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1624 1689	may also play a role in the proliferative control of normal cells
T1010	Speculation 1552 1555	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1552 1619	may not only be involved in the tumorigenesis of colorectal cancers
