T1000	Speculation 1727 1734	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1727 1986	suggest that CN is involved in the coordinated induction of the GM-CSF and IL-2 genes and that the CLE0 sequence of the GM-CSF gene is a functional analogue of the NF-AT-binding site in the IL-2 promoter, which mediates signals downstream of T cell activation
T1002	Negation 997 1002	lacks
E1001	Negation:T1002 Scope:T1003
T1003	Span 997 1053	lacks the auto-inhibitory and calmodulin-binding domains
