T1000	Negation 1283 1286	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1283 1305	not of FAK or paxillin
T1002	Speculation 96 104	possible
E1001	Speculation:T1002 Scope:T1003
T1003	Span 96 147	possible signaling role for the Syk tyrosine kinase
T1004	Speculation 1500 1513	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1500 1701	indicate that the Syk tyrosine kinase may be an important component of an integrin signaling pathway in monocytic cells, leading to activation of NF-kappa B and to increased levels of cytokine messages
T1006	Negation 1420 1423	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1420 1430	not of Syk
T1008	Speculation 1538 1541	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1538 1701	may be an important component of an integrin signaling pathway in monocytic cells, leading to activation of NF-kappa B and to increased levels of cytokine messages
