T1000	Speculation 977 984	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 977 1222	suggest the presence in vaginal fluid of agent(s) derived from indigenous bacteria that can activate the HIV-1 LTR, cytokine production, and NF-kappaB in cells of macrophage lineage, with possible influence on vaginal physiology and host defense
T1002	Negation 520 527	absence
E1001	Negation:T1002 Scope:T1003
T1003	Span 520 539	absence of vanadate
T1004	Speculation 1165 1173	possible
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1165 1222	possible influence on vaginal physiology and host defense
