T1000	Speculation 1773 1779	likely
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1708 1856	This differential binding of specific NF-kappa B/Rel subunits is likely to mediate the disparate functions of these two NF-kappa B/Rel binding sites
T1002	Speculation 1544 1557	indicate that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1544 1706	indicate that the presence of p50, p52, p65, and cRel correlates with positive function whereas the presence of only p50 and p52 correlates with negative function
