T1000	Speculation 556 564	possible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 556 661	possible to artificially enhance the opening of the chromatin structure of a minimal beta-globin promoter
T1002	Speculation 542 549	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 542 661	whether it is possible to artificially enhance the opening of the chromatin structure of a minimal beta-globin promoter
T1004	Speculation 1459 1472	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1459 1623	indicate that a relatively small cis-acting element is able to enhance remodeling of promoter chromatin structure resulting in increased beta-globin gene expression
