T1000	Speculation 423 433	hypothesis
E1000	Speculation:T1000 Scope:T1001
T1001	Span 423 560	hypothesis that polymorphic nucleotides within the IL-10 and TGF-beta gene promoters would link to the expression of allergies and asthma
T1002	Speculation 343 348	could
E1001	Speculation:T1002 Scope:T1003
T1003	Span 343 401	could contribute to the development of asthma or allergies
T1004	Speculation 508 513	would
E1002	Speculation:T1004 Scope:T1005
T1005	Span 508 560	would link to the expression of allergies and asthma
