T1000	Speculation 661 671	whether or
E1000	Speculation:T1000 Scope:T1001
T1001	Span 661 708	whether or not the cells expressed the nef gene
T1002	Speculation 414 417	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 408 497	which may be affected in T cells by constitutive expression of the nef gene were examined
T1004	Negation 1009 1012	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1009 1065	not affect the surface expression of the CD3-TCR complex
T1006	Negation 951 954	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 951 978	not expressing the nef gene
