T1000	Speculation 1137 1140	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1132 1218	this may be related to scavenging of endogenously produced NO by the PDTC iron complex
T1002	Negation 980 983	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 980 1062	not inhibit tumor necrosis factor-alpha-induced NF kappaB activation in astrocytes
T1004	Speculation 1519 1526	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1519 1599	suggest that nNOS in astrocytes regulates NF kappaB activity and iNOS expression
T1006	Negation 1421 1428	lacking
E1003	Negation:T1006 Scope:T1007
T1007	Span 1421 1433	lacking nNOS
T1008	Speculation 1605 1613	indicate
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1605 1721	indicate a novel regulatory role for nNOS in tonically suppressing central nervous system, NF kappaB-regulated genes
