T1000	Speculation 1219 1224	could
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1219 1344	could be due to differences in cell surface (UT-7 cells are 20% smaller than the parental UT-7 cells) or in receptor turnover
T1002	Negation 844 850	unable
E1001	Negation:T1002 Scope:T1003
T1003	Span 844 901	unable to proliferate continuously in the presence of Epo
T1004	Negation 1709 1712	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1709 1726	not in UT-7 cells
T1006	Negation 1437 1440	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1437 1453	not alpha-globin
T1008	Negation 2342 2345	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 2283 2398	The levels of GATA-1, Epo-R and globin mRNA expressed were not affected by a 24-hour incubation of either cell line
T1010	Speculation 2102 2117	indicating that
E1005	Speculation:T1010 Scope:T1011
T1011	Span 2102 2281	indicating that the increase in globin mRNA observed in UT-7 Epo is due to both an increase of gene expression per cell and an increase in numbers of cells containing gamma-globin
T1012	Speculation 2416 2418	or
E1006	Speculation:T1012 Scope:T1013
T1013	Span 2404 2439	Epo, GM-CSF or interleukin-3 (IL-3)
T1014	Negation 2382 2388	either
E1007	Negation:T1014 Scope:T1015
T1015	Span 2382 2439	either cell line with Epo, GM-CSF or interleukin-3 (IL-3)
