T1000	Speculation 1020 1033	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1020 1215	indicate that CD2 receptor activation and phytohemagglutinin plus phorbol 12-myristate 13-acetate stimulation augment T cell IL3 gene expression through the same cis- and trans-activating signals
T1002	Speculation 907 915	putative
E1001	Speculation:T1002 Scope:T1003
T1003	Span 907 943	putative AP-2 and Sp1 binding motifs
T1004	Speculation 1231 1237	should
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1231 1338	should contribute to a better understanding of the regulation of IL3 gene expression in human T lymphocytes
