T1000	Speculation 946 953	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 946 1020	whether they constitutively express Fc epsilon RI- gamma chain transcripts
T1002	Speculation 359 367	possibly
E1001	Speculation:T1002 Scope:T1003
T1003	Span 359 379	possibly other cells
T1004	Speculation 1264 1270	appear
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1258 1311	which appear to be different in basophils and T cells
