T1000	Speculation 618 632	indicated that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 618 753	indicated that both cytokines were essential for the induction and were required to generate a synergistic increase in virus expression
T1002	Negation 365 368	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 365 393	not induce HIV-1 replication
T1004	Negation 1193 1196	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1135 1275	the induction of either endogenous TNF-alpha or IL-10 was not involved in the cooperativity, nor was an up-regulation of TNF-alpha receptors
T1006	Speculation 958 968	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 958 1041	suggesting that IL-10 and TNF-alpha play different roles in the activation of virus
T1008	Speculation 1120 1134	indicated that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1120 1275	indicated that the induction of either endogenous TNF-alpha or IL-10 was not involved in the cooperativity, nor was an up-regulation of TNF-alpha receptors
T1010	Negation 1228 1231	nor
E1005	Negation:T1010 Scope:T1011
T1011	Span 1228 1275	nor was an up-regulation of TNF-alpha receptors
T1012	Speculation 1666 1679	indicate that
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1666 1866	indicate that IL-10, in addition to down-regulating the cellular immune response to HIV-1, may also play a role in TNF-alpha-mediated activation of HIV-1 replication in the monocyte/macrophage lineage
T1014	Speculation 1570 1580	suggesting
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1570 1650	suggesting the IL-10 effect occurs at least in part at the transcriptional level
T1016	Speculation 1757 1760	may
E1008	Speculation:T1016 Scope:T1017
T1017	Span 1757 1866	may also play a role in TNF-alpha-mediated activation of HIV-1 replication in the monocyte/macrophage lineage
