T1000	Negation 1168 1171	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1165 1204	is not primarily mediated by NF-kappa B
T1002	Negation 864 867	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 864 954	not correlate with NF-kappa B binding activities displayed by different T and B cell lines
T1004	Negation 1435 1438	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1435 1483	not functional on a truncated TNF-alpha promoter
T1006	Negation 1391 1394	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1391 1416	not a T (HUT78) cell line
T1008	Speculation 1485 1500	indicating that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1485 1614	indicating that promoter context and cell type specificity influence the PMA inducible function of these NF-kappa B binding sites
