T1000	Speculation 962 967	would
E1000	Speculation:T1000 Scope:T1001
T1001	Span 962 1062	would result from NF-kappa B-dependent transcriptional stimulation of the I kappa B alpha/MAD-3 gene
T1002	Speculation 830 839	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 830 1062	suggested that the rapid increase in steady-state I kappa B alpha/MAD-3 mRNA levels we observed within 30 min of monocyte adherence would result from NF-kappa B-dependent transcriptional stimulation of the I kappa B alpha/MAD-3 gene
T1004	Negation 1418 1421	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1418 1464	not a consequence of mRNA stabilization events
T1006	Speculation 1088 1102	indicated that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1088 1337	indicated that, instead, while several immediate-early cytokine genes, such as the interleukin 1 beta (IL-1 beta) gene, were transcriptionally activated during monocyte adhesion, the rate of I kappa B alpha/MAD-3 gene transcription remained constant
T1008	Speculation 1742 1749	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1742 1834	suggest that two interactive mechanisms regulate monocytic I kappa B alpha/MAD-3 mRNA levels
T1010	Negation 1712 1715	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1712 1715	not
T1012	Speculation 1839 1846	propose
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1839 2032	propose that adherent monocytes regulate nuclear processing (or decay) of I kappa B alpha/MAD-3 mRNA, thereby increasing mRNA levels without stimulating I kappa B alpha/MAD-3 gene transcription
T1014	Negation 1972 1979	without
E1007	Negation:T1014 Scope:T1015
T1015	Span 1972 2032	without stimulating I kappa B alpha/MAD-3 gene transcription
T1016	Speculation 2199 2206	suggest
E1008	Speculation:T1016 Scope:T1017
T1017	Span 2199 2328	suggest that low cytoplasmic levels of I kappa B alpha/MAD-3 mRNA are maintained by a translation-dependent degradation mechanism
T1018	Negation 2134 2141	without
E1009	Negation:T1018 Scope:T1019
T1019	Span 2134 2194	without stimulating I kappa B alpha/MAD-3 gene transcription
