T1000	Speculation 481 490	not known
E1000	Speculation:T1000 Scope:T1001
T1001	Span 481 609	not known whether this mechanism alone is sufficient to explain the block to HIV replication in human T cells when Tat is absent
T1002	Negation 603 609	absent
E1001	Negation:T1002 Scope:T1003
T1003	Span 603 609	absent
T1004	Speculation 617 625	possible
E1002	Speculation:T1004 Scope:T1005
T1005	Span 617 692	possible that Tat is also needed for other functions during HIV replication
T1006	Speculation 491 498	whether
E1003	Speculation:T1006 Scope:T1007
T1007	Span 491 609	whether this mechanism alone is sufficient to explain the block to HIV replication in human T cells when Tat is absent
T1008	Negation 1834 1836	no
E1004	Negation:T1008 Scope:T1009
T1009	Span 1834 1919	no evidence of wild-type reversion even after prolonged infection with the Tat- virus
T1010	Negation 1651 1654	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1644 1761	Tat is not otherwise absolutely required for synthesis of full-length HIV transcripts and assembly of virus particles
T1012	Speculation 1834 1845	no evidence
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1834 1919	no evidence of wild-type reversion even after prolonged infection with the Tat- virus
