T1000	Speculation 1141 1151	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1141 1208	suggesting that only VCAM-1 induction was controlled by NF-kappa B.
T1002	Negation 847 850	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 847 1045	not ICAM-1 surface protein (also in human umbilical arterial endothelial cells) and mRNA expression (by 70% at 100 mumol/L PDTC) in HUVECs as assessed by flow cytometry and polymerase chain reaction
T1004	Speculation 1733 1747	indicated that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1733 1850	indicated that U937 adhesion was VCAM-1 dependent and suppression by antioxidants was due to reduced VCAM-1 induction
T1006	Speculation 1299 1302	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1299 1329	may act as a radical scavenger
