T1000	Speculation 1538 1545	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1459 1603	The cAMP-response element CRE, TGACGTCA, present in the 21 base-pair sequence, appears to be essential for specific protein-TRE-DNA interactions
T1002	Negation 534 538	none
E1001	Negation:T1002 Scope:T1003
T1003	Span 534 582	none of which are identical with the Tax-protein
T1004	Speculation 1671 1679	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1671 1810	suggests that the cAMP response element binding protein, CREB, is involved in the protein-TRE-DNA complex and in mediating the Tax response
