T1000	Negation 1400 1403	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1400 1428	not AP1 transcription factor
T1002	Speculation 1052 1061	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1052 1235	suggested that one GATA-1 motif, one GT motif, and two NF-E2/AP1 motifs together formed the functional core of HS-40 in the erythroid-specific activation of the zeta 2 globin promoter
T1004	Speculation 1677 1685	appeared
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1576 1764	All sequence motifs within the functional core of HS-40, as mapped by transient expression analysis, appeared to bind a nuclear factor(s) in living K562 cells but not in nonerythroid cells
T1006	Negation 1739 1742	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1739 1764	not in nonerythroid cells
T1008	Speculation 2061 2068	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2061 2338	suggest that transcriptional activation of human embryonic zeta 2 globin gene and the fetal/adult alpha globin genes is mediated by erythroid cell-specific and developmental stage-specific nuclear factor-DNA complexes which form at the enhancer (HS-40) and the globin promoters
