T1000	Speculation 765 775	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 765 846	suggesting that IFN-alpha may be involved in the regulation of T-cell mitogenesis
T1002	Speculation 280 299	increasing evidence
E1001	Speculation:T1002 Scope:T1003
T1003	Span 280 354	increasing evidence that IFN-alpha has an important role in T-cell biology
T1004	Negation 1055 1058	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1055 1064	not STAT5
T1006	Speculation 791 794	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 791 846	may be involved in the regulation of T-cell mitogenesis
T1008	Speculation 1379 1386	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1379 1470	suggest that IFN-alpha, IL-2, IL-12, and IL-15 have overlapping activities on human T cells
