T1000	Speculation 1284 1292	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1284 1409	suggests a therapeutic approach against AIDS by application of two drugs, one against a cellular and the other a viral target
T1002	Speculation 818 826	proposed
E1001	Speculation:T1002 Scope:T1003
T1003	Span 818 1054	proposed that the mechanism of antiviral action of S9a was on the host cell, by blocking TNF-alpha transcription via a Tat-induced tar-independent loop, which decreases downstream NF-kappaB activation of HIV-1 long terminal repeat (LTR)
T1004	Speculation 1417 1420	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1417 1551	may provide an approach to the problem of frequent emergence of resistant variants to combinations of drugs that target only HIV genes
