T1000	Speculation 1297 1300	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1297 1425	may reside in retention of inactive nuclear factor-kappaB in the cytosol thereby abrogating interleukin-1beta gene transcription
T1002	Speculation 492 502	indicating
E1001	Speculation:T1002 Scope:T1003
T1003	Span 492 584	indicating a function for cytosolic phospholipase A2 in signal transduction and inflammation
