T1000	Speculation 1572 1575	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1572 1655	may constitute a minimal region responsible for CTL-specific expression of perforin
T1002	Speculation 1503 1510	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1503 1655	suggest that a combination of the three proximal cis-acting elements may constitute a minimal region responsible for CTL-specific expression of perforin
