T1000	Negation 1265 1272	neither
E1000	Negation:T1000 Scope:T1001
T1001	Span 1265 1335	neither eTh1 nor eTh2 cells produced significant IL-2 upon stimulation
T1002	Negation 95 98	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 95 111	not in Th1 cells
T1004	Negation 1597 1604	failure
E1002	Negation:T1004 Scope:T1005
T1005	Span 1597 1761	failure of eTh1 cells to produce IL-4 in response to an antigen is due, at least partially, to a failure to induce high-level transcription of the IL-4 gene by NFAT
T1006	Negation 1278 1281	nor
E1003	Negation:T1006 Scope:T1007
T1007	Span 1278 1335	nor eTh2 cells produced significant IL-2 upon stimulation
T1008	Speculation 1505 1512	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1505 1660	suggest that activated NFAT is involved in the effector function of eTh2 cells and that the failure of eTh1 cells to produce IL-4 in response to an antigen
T1010	Negation 1694 1701	failure
E1005	Negation:T1010 Scope:T1011
T1011	Span 1694 1761	failure to induce high-level transcription of the IL-4 gene by NFAT
T1012	Speculation 1782 1787	could
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1782 1855	could be therefore a critical element in the polarization to eTh1 or eTh2
