T1000	Speculation 1113 1119	should
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1113 1275	should shed light on the transcriptional mechanisms of this fork head gene subfamily and their role in T helper cell differentiation and regulation of cell growth
T1002	Negation 492 495	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 492 589	not contain the characteristic DNA-binding domain found in members of the forkhead protein family
