T1000	Speculation 340 347	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 328 423	This effect appears to be mediated through the induction of nuclear factor kappa B (NF-kappa B)
T1002	Negation 309 312	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 309 326	not a T cell line
T1004	Speculation 1235 1238	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1235 1339	may be clinically significant in understanding the variability of the natural history of HIV-1 infection
T1006	Negation 1082 1085	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1082 1141	not able to induce HIV-1 production in a cloned T cell line
