T1000	Negation 310 316	unable
E1000	Negation:T1000 Scope:T1001
T1001	Span 310 383	unable to stimulate a multimerized octamer enhancer element in HeLa cells
T1002	Speculation 223 228	could
E1001	Speculation:T1002 Scope:T1003
T1003	Span 223 288	could efficiently activate a promoter containing an octamer motif
T1004	Speculation 736 742	either
E1002	Speculation:T1004 Scope:T1005
T1005	Span 736 867	either a B-cell-specific cofactor or a specific modification of a cofactor or the Oct2 protein in Oct2-mediated enhancer activation
T1006	Speculation 707 716	indicates
E1003	Speculation:T1006 Scope:T1007
T1007	Span 707 830	indicates the involvement of either a B-cell-specific cofactor or a specific modification of a cofactor or the Oct2 protein
T1008	Negation 1079 1085	unable
E1004	Negation:T1008 Scope:T1009
T1009	Span 1079 1121	unable to stimulate from a remote position
T1010	Speculation 889 902	indicate that
E1005	Speculation:T1010 Scope:T1011
T1011	Span 889 974	indicate that the carboxy-terminal domain of Oct2 is critical for enhancer activation
