T1000	Speculation 1019 1030	potentially
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1019 1045	potentially phosphorylated
T1002	Negation 657 660	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 657 734	not in an RA-resistant subclone, HL60R, that harbors a mutated RAR alpha gene
T1004	Speculation 1314 1327	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1314 1439	indicate that E3 is a hematopoietic-specific gene that is an immediate target for the activated RAR alpha during myelopoiesis
T1006	Speculation 1109 1117	putative
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1109 1125	putative protein
