T1000	Speculation 889 896	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 837 927	this factor, termed IL-6 kappa B binding factor II, appears to contain the c-Rel homodimer
T1002	Negation 819 822	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 819 835	not p50 epitopes
T1004	Speculation 932 946	preferentially
E1002	Speculation:T1004 Scope:T1005
T1005	Span 932 1001	preferentially recognizes several IL-6 kappa B-related kappa B motifs
