T1000	Negation 1858 1860	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 1858 1942	no significant difference in the turnover of pre- and post-inductive I kappa B alpha
T1002	Speculation 1055 1060	seems
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1055 1145	seems to be driven by the same degradation machinery as the slower turnover in non-B cells
T1004	Speculation 1963 1970	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1963 2117	suggest that resynthesis of I kappa B alpha and removal of the stimulus are obligatory steps for the inactivation of nuclear NF kappa B. 
