T1000	Negation 644 647	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 644 698	not involved in the HIV-mediated NF-kappa B activation
T1002	Speculation 245 252	unknown
E1001	Speculation:T1002 Scope:T1003
T1003	Span 106 252	The molecular mechanisms regulating human immunodeficiency virus (HIV) persistence in a major cell reservoir such as the macrophage remain unknown
T1004	Negation 1291 1294	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1291 1593	not phorbol myristate acetate- or lipopolysaccharide-mediated activation of NF-kappa B. That PKC-zeta is specific in regulating NF-kappa B is concluded from the inability of PKC-zeta(mut) to interfere with the basal or phorbol myristate acetate-inducible CREB- or AP1-dependent transcriptional activity
T1006	Speculation 580 594	indicated that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 580 698	indicated that classical protein kinase C (PKC) isoenzymes were not involved in the HIV-mediated NF-kappa B activation
T1008	Speculation 1753 1760	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1753 1962	suggest that atypical PKC isoenzymes, including PKC-zeta, participate in the signal transduction pathways by which HIV infection results in the activation of NF-kappa B in human monocytic cells and macrophages
