T1000	Negation 666 668	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 666 707	no effect on transcription factor binding
T1002	Negation 128 135	absence
E1001	Negation:T1002 Scope:T1003
T1003	Span 128 182	absence of altered sensitivity to anti-CD3 stimulation
T1004	Negation 1459 1462	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1459 1534	not due to stabilization of the interaction of the cells with its substrate
T1006	Negation 974 977	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 974 1052	not require costimulation for cytokine secretion in response to anti-CD3 alone
