T1000	Negation 1271 1276	Virus
E1000	Negation:T1000 Scope:T1001
T1001	Span 1271 1439	Virus production occurred with slightly delayed kinetics for viruses containing combined mutations in the AP-1(III), AP3-L, and DBF sites and in the AP3-L and DBF-sites
T1002	Negation 1093 1096	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1093 1161	not affect HIV-1 replication compared to that of the wild-type virus
T1004	Negation 1605 1607	No
E1002	Negation:T1004 Scope:T1005
T1005	Span 1605 1733	No RNA-packaging defect could be measured for any of the mutant viruses as determined by quantification of their HIV genomic RNA
