T1000	Negation 555 558	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 555 583	not CD2, CD5, LFA-1, or CD7)
T1002	Speculation 434 439	seems
E1001	Speculation:T1002 Scope:T1003
T1003	Span 403 496	ligation of this receptor also seems to activate a calcium-independent, CD28-specific pathway
T1004	Negation 932 935	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 888 988	CD28-dependent elevation of c-jun mRNA does not appear to be mediated at the level of mRNA stability
T1006	Negation 768 771	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 768 873	not depend on activation of a phorbol ester-responsive protein kinase C or elevation of cytosolic calcium
T1008	Negation 1060 1067	absence
E1004	Negation:T1008 Scope:T1009
T1009	Span 1060 1220	absence of members of the fos family, can prevent inappropriate activation of T cells caused by ligation of CD28 in the absence of a specific antigenic stimulus
T1010	Speculation 936 942	appear
E1005	Speculation:T1010 Scope:T1011
T1011	Span 888 988	CD28-dependent elevation of c-jun mRNA does not appear to be mediated at the level of mRNA stability
T1012	Speculation 1005 1014	suggested
E1006	Speculation:T1012 Scope:T1013
T1013	Span 990 1096	A mechanism is suggested whereby expression of c-jun and junB, in the absence of members of the fos family
T1014	Negation 1180 1187	absence
E1007	Negation:T1014 Scope:T1015
T1015	Span 1180 1220	absence of a specific antigenic stimulus
