T1000	Speculation 1382 1389	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1382 1598	suggest that the regulation of IL-2 gene expression is a complex process and multiple cis-acting regulatory sites interact to exert different effects in T cells representative of alternative stages of differentiation
T1002	Speculation 663 670	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 663 946	suggest that the NFAT (-276 to -261), the distal octamer (-256 to -248) and the proximal octamer (-75 to -66) sites not only act as enhancers of IL-2 gene transcription in the presence of cellular stimulation, but also have a silencing effect on IL-2 gene expression in resting cells
