T1000	Speculation 1223 1238	indicating that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1223 1376	indicating that the 515 base pair IL-5 gene segment upstream of the coding region was sufficient to respond to activating signals in human helper T cells
T1002	Speculation 967 977	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 967 1075	suggesting that mite-specific helper T cells were involved in the eosinophilic inflammation of atopic asthma
T1004	Speculation 1456 1466	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1456 1541	suggesting that human T cell IL-5 synthesis is regulated at the transcriptional level
T1006	Negation 1404 1407	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1378 1454	The same gene segment was not transcribed in IL-5-nonproducing T cell clones
T1008	Speculation 1652 1655	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1652 1702	may be essential for human IL-5 gene transcription
T1010	Speculation 1607 1616	suggested
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1607 1702	suggested that a unique transcription factor may be essential for human IL-5 gene transcription
T1012	Speculation 1892 1895	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1892 2006	may facilitate the development of novel treatments for allergic diseases associated with eosinophilic inflammation
T1014	Speculation 1759 1764	seems
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1716 1839	Enhanced IL-5 production by helper T cells seems to cause the eosinophilic inflammation of both atopic and nonatopic asthma
