T1000	Negation 1322 1325	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1307 1391	the cells were not treated with cytokines before the nuclear proteins were extracted
T1002	Negation 792 795	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 792 831	not with the ISRE oligonucleotide probe
T1004	Speculation 1468 1474	likely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1468 1566	likely that the constitutive activation of STAT proteins is a part of the events of leukemogenesis
