T1000	Speculation 1551 1558	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1551 1663	suggest a ROI-dependent NF-kappaB mediated transcription of inflammatory cytokines in bronchial epithelial cells
T1002	Speculation 429 436	suppose
E1001	Speculation:T1002 Scope:T1003
T1003	Span 429 543	suppose an interaction between epithelial cells and macrophages regarding to the release of inflammatory mediators
