T1000	Negation 399 401	No
E1000	Negation:T1000 Scope:T1001
T1001	Span 399 499	No virus replication and no transcription of the Ad2 early genes was observed in either of the cells
T1002	Negation 315 322	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 315 341	without being internalized
T1004	Negation 873 876	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 859 885	IL-1 beta was not detected
T1006	Negation 424 426	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 424 499	no transcription of the Ad2 early genes was observed in either of the cells
T1008	Speculation 896 909	indicate that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 896 1036	indicate that cellular genes might be activated by Ad2 virus infection in nonpermissive cells where no viral gene products could be detected
T1010	Negation 996 998	no
E1005	Negation:T1010 Scope:T1011
T1011	Span 996 1036	no viral gene products could be detected
T1012	Speculation 925 930	might
E1006	Speculation:T1012 Scope:T1013
T1013	Span 910 1036	cellular genes might be activated by Ad2 virus infection in nonpermissive cells where no viral gene products could be detected
