T1000	Negation 1411 1417	absent
E1000	Negation:T1000 Scope:T1001
T1001	Span 1373 1417	Pu box-dependent transactivation were absent
T1002	Speculation 301 306	seems
E1001	Speculation:T1002 Scope:T1003
T1003	Span 296 378	PU.1 seems to be required for early development of multiple hematopoietic lineages
T1004	Speculation 1870 1877	unclear
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1870 1963	unclear whether the lack of PU.1 expression and activity in human multiple myeloma cell lines
T1006	Negation 1890 1894	lack
E1003	Negation:T1006 Scope:T1007
T1007	Span 1890 2106	lack of PU.1 expression and activity in human multiple myeloma cell lines represents a malignancy-associated defect in these cells or exemplifies a normal developmental regulation in terminally differentiated B cells
T1008	Speculation 2021 2023	or
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1964 2106	represents a malignancy-associated defect in these cells or exemplifies a normal developmental regulation in terminally differentiated B cells
T1010	Speculation 1878 1885	whether
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1878 2106	whether the lack of PU.1 expression and activity in human multiple myeloma cell lines represents a malignancy-associated defect in these cells or exemplifies a normal developmental regulation in terminally differentiated B cells
