T1000	Negation 534 537	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 534 584	not sensitive to H2O2-induced NF-kappaB activation
T1002	Negation 382 385	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 326 434	H2O2-induced NF-kappaB activation in Wurzburg cells was not influenced by the presence of extracellular EGTA
T1004	Speculation 906 919	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 906 1012	indicate that a sustained elevated [Ca2+]i is a significant factor in oxidant-induced NF-kappaB activation
T1006	Speculation 766 774	appeared
E1003	Speculation:T1006 Scope:T1007
T1007	Span 700 882	NF-kappaB regulatory effect of alpha-lipoate and N-acetylcysteine appeared to be, at least in part, due to their ability to stabilize elevation of [Ca2+]i following oxidant challenge
