T1000	Speculation 1345 1348	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1345 1413	may contribute to delayed progression of the HIV-1 infection in vivo
T1002	Speculation 215 229	indicates that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 215 386	indicates that the rate of progression of the HIV-1 disease is significantly reduced in thalassaemia major patients upon treatment with high doses of desferrioxamine (DFX)
