T1000	Negation 692 695	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 692 712	not able to bind DNA
T1002	Speculation 424 431	unknown
E1001	Speculation:T1002 Scope:T1003
T1003	Span 383 431	the biological function of Spi-B remains unknown
T1004	Speculation 806 811	might
E1002	Speculation:T1004 Scope:T1005
T1005	Span 806 882	might affect Spi-B function by recruiting factors involved in Spi-B activity
