T1000	Speculation 1542 1551	proposing
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1542 1797	proposing that the N-terminal domain confers calcium-signaling dependence on NFATx1 transactivation activity by regulating its intracellular localization through a protein module that associates with calcineurin and is a target of its phosphatase activity
T1002	Speculation 761 771	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 761 847	suggesting the presence of intrinsic transcriptional activation motifs in both regions
