T1000	Negation 1259 1262	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1259 1361	not involved in the regulation of dPRL promoter/reporter gene constructs carrying 3 kb 5'-flanking DNA
T1002	Speculation 875 884	potential
E1001	Speculation:T1002 Scope:T1003
T1003	Span 875 911	potential transcriptional regulators
T1004	Negation 1656 1659	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1656 1742	not contain elements restricting expression to only those lymphocytes that produce PRL
T1006	Negation 1412 1415	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1412 1474	not confer direct transcriptional control on the dPRL promoter
T1008	Negation 2280 2287	absence
E1004	Negation:T1008 Scope:T1009
T1009	Span 2280 2303	absence of progesterone
T1010	Negation 2060 2063	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 2060 2147	not allow transcription in undifferentiated non-PRL-secreting endometrial stromal cells
T1012	Speculation 2305 2315	suggesting
E1006	Speculation:T1012 Scope:T1013
T1013	Span 2305 2428	suggesting that a signal transduced through the cAMP signaling pathway is a primary inducer of decidual PRL gene expression
