T1000	Speculation 1481 1488	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1481 1667	suggest that tyrosine phosphorylation of I kappa B alpha during hypoxia is an important proximal step which precedes its dissociation and degradation from NF-kappa B. 
T1002	Negation 1341 1344	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1341 1465	not detect changes in the tyrosine phosphorylation status of I kappa B alpha following treatment with either of these agents
