T1000	Negation 761 763	No
E1000	Negation:T1000 Scope:T1001
T1001	Span 761 845	No evidence for inflammatory cytokine production was obtained under these conditions
T1002	Negation 501 511	Incubation
E1001	Negation:T1002 Scope:T1003
T1003	Span 501 548	Incubation of human whole blood with PGG-Glucan
T1004	Speculation 1461 1474	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1461 1680	indicate that PGG-Glucan enhances neutrophil anti-microbial functions and that interaction between this beta-glucan and human neutrophils is mediated by the glycosphingolipid lactosylceramide present at the cell surface
T1006	Speculation 1380 1389	suggested
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1380 1445	suggested that the PGG-Glucan binding moiety was lactosylceramide
