T1000	Negation 711 714	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 702 764	that was not impaired in its ability to activate transcription
T1002	Speculation 480 487	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 480 652	thought that ZEBRA's capacity to disrupt EBV latency resided primarily in its ability to activate transcription of genes that encode products required for lytic replication
T1004	Speculation 1528 1534	likely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1439 1728	The additional function that is required for initiation of the lytic viral life cycle is likely to require phosphorylation of serine 186 of the ZEBRA protein, which may influence either DNA recognition or transcriptional activation of lytic viral promoters in a chromatinized viral episome
T1006	Negation 1081 1084	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1081 1127	not disrupt latency in EBV-infected cell lines
T1008	Speculation 1604 1607	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1604 1728	may influence either DNA recognition or transcriptional activation of lytic viral promoters in a chromatinized viral episome
