T1000	Negation 1009 1012	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1009 1067	not the well-studied costimulatory molecules B7-1 and B7-2
T1002	Speculation 409 419	hypothesis
E1001	Speculation:T1002 Scope:T1003
T1003	Span 409 539	hypothesis that CD40 expressed on lung fibroblasts is an activation structure and mechanism for interaction with hemopoietic cells
T1004	Speculation 1102 1112	hypothesis
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1102 1305	hypothesis that cognate interactions between tissue fibroblasts and infiltrating T lymphocytes, via the CD40/CD40L pathway, augment inflammation and may promote fibrogenesis by activating both cell types
T1006	Speculation 1090 1097	support
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1090 1305	support the hypothesis that cognate interactions between tissue fibroblasts and infiltrating T lymphocytes, via the CD40/CD40L pathway, augment inflammation and may promote fibrogenesis by activating both cell types
T1008	Speculation 1251 1254	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1251 1305	may promote fibrogenesis by activating both cell types
