T1000	Speculation 393 400	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 393 650	whether the interaction of SS RBC with cultured endothelial cells induced cellular oxidant stress that would culminate in expression of cell adhesion molecules (CAMs) involved in the adhesion and diapedesis of monocytes and the adherence of SS reticulocytes
T1002	Speculation 277 284	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 189 377	The abnormal adherence of sickle red blood cells (SS RBC) to endothelial cells has been thought to contribute to vascular occlusion, a major cause of morbidity in sickle cell disease (SCD)
T1004	Negation 1104 1108	none
E1002	Negation:T1004 Scope:T1005
T1005	Span 1104 1127	none of these phenomena
T1006	Speculation 496 501	would
E1003	Speculation:T1006 Scope:T1007
T1007	Span 496 650	would culminate in expression of cell adhesion molecules (CAMs) involved in the adhesion and diapedesis of monocytes and the adherence of SS reticulocytes
T1008	Speculation 2206 2221	indicating that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2206 2294	indicating that injury/activation of endothelium can contribute to vaso-occlusion in SCD
T1010	Speculation 1975 1982	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1975 2294	suggest that the adherence/contact of SS RBC to endothelial cells in large vessel can generate enhanced oxidant stress leading to increased adhesion and diapedesis of monocytes, as well as heightened adherence of SS reticulocytes, indicating that injury/activation of endothelium can contribute to vaso-occlusion in SCD
