T1000	Speculation 1007 1020	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1007 1263	indicate that the adhesion of RA synovial cells to matrices such as hyaluronic acid through CD44 could up-regulate VCAM-1 expression and VCAM-1-mediated adhesion to T cells, which might in turn cause activation of T cells and synovial cells in RA synovitis
T1002	Speculation 264 271	unknown
E1001	Speculation:T1002 Scope:T1003
T1003	Span 162 271	the cellular functions and its role in inflammation, for example, rheumatoid synovitis, are currently unknown
T1004	Speculation 1278 1285	propose
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1278 1419	propose that such cross-talking among distinct adhesion molecules may be involved in the pathogenesis of inflammation, including RA synovitis
T1006	Speculation 1187 1192	might
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1187 1263	might in turn cause activation of T cells and synovial cells in RA synovitis
T1008	Speculation 1344 1347	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1344 1419	may be involved in the pathogenesis of inflammation, including RA synovitis
