T1000	Speculation 1673 1686	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1673 1784	indicate that Calphostin C prevents the transcription of the IL-1beta gene thereby inhibiting protein synthesis
T1002	Speculation 487 494	unclear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 393 494	the metabolic steps at which PKC acts upon to mediate the FN-induced IL-1beta response remain unclear
T1004	Speculation 1982 1989	unknown
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1982 2000	unknown mechanisms
