T1000	Speculation 377 380	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 377 440	may potentially alter immune responsiveness to Ag. In this work
T1002	Negation 595 599	lack
E1001	Negation:T1002 Scope:T1003
T1003	Span 595 628	lack of activation of jak kinases
T1004	Negation 768 772	lack
E1002	Negation:T1004 Scope:T1005
T1005	Span 768 850	lack of expression of the beta- chain (accessory factor) of the IFN-gamma receptor
T1006	Speculation 381 392	potentially
E1003	Speculation:T1006 Scope:T1007
T1007	Span 381 440	potentially alter immune responsiveness to Ag. In this work
T1008	Speculation 1428 1431	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1428 1497	may affect their ability to participate in an ongoing immune response
