T1000	Negation 632 639	absence
E1000	Negation:T1000 Scope:T1001
T1001	Span 632 683	absence of apparent genomic alteration of the locus
T1002	Negation 501 508	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 501 529	without tal-1 rearrangements
T1004	Negation 1149 1155	absent
E1002	Negation:T1004 Scope:T1005
T1005	Span 1149 1163	absent in Hela
T1006	Speculation 705 719	indicated that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 705 892	indicated that the tal-15' GC-rich region behaves like a CpG island, hypomethylated in normal cells, and methylated de novo on transcriptionally inactive alleles in established cell lines
T1008	Speculation 1225 1230	might
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1213 1305	this region might be implicated in the cis-activation of tal-1 promoter 1b in this cell line
T1010	Speculation 1197 1207	suggesting
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1197 1305	suggesting that this region might be implicated in the cis-activation of tal-1 promoter 1b in this cell line
T1012	Speculation 1472 1479	suggest
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1472 1574	suggest that distinct regulatory elements are associated with the use of the different tal-1 promoters
