T1000	Speculation 1046 1059	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1046 1162	indicate that tissue specificity of gene expression is not accompanied by drastic changes in gene nuclear topography
T1002	Negation 1101 1104	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1101 1314	not accompanied by drastic changes in gene nuclear topography, rather suggesting that gene organization within the nucleus may be primarily dependent on structural constraints imposed on the respective chromosomes
T1004	Speculation 1224 1227	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1224 1314	may be primarily dependent on structural constraints imposed on the respective chromosomes
T1006	Speculation 1171 1181	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1171 1314	suggesting that gene organization within the nucleus may be primarily dependent on structural constraints imposed on the respective chromosomes
