T1000	Speculation 884 894	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 884 960	suggesting that precursor levels of NF kappa B remain unaltered during aging
T1002	Negation 562 571	could not
E1001	Negation:T1002 Scope:T1003
T1003	Span 511 630	The age-related decline in induction of NF kappa B could not be attributed to alteration in the composition of subunits
T1004	Speculation 1092 1095	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1092 1236	may be attributable to altered regulation of the inhibitor, I kappa B, and may play an important role in immune dysregulation accompanying aging
T1006	Speculation 976 983	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 976 1161	suggest that an age-associated decline in the induction of NF kappa B in activated T cells from elderly individuals may be attributable to altered regulation of the inhibitor, I kappa B
T1008	Speculation 1167 1170	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1167 1236	may play an important role in immune dysregulation accompanying aging
