T1000	Speculation 1124 1131	propose
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1124 1257	propose that the well-known immunological consequences of GSH depletion ultimately may be results of the accompanying GSSG deficiency
T1002	Speculation 671 677	likely
E1001	Speculation:T1002 Scope:T1003
T1003	Span 671 701	likely targets for GSSG action
T1004	Speculation 1419 1430	hypothesize
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1419 1492	hypothesize that AIDS may be the consequence of a GSSG deficiency as well
T1006	Speculation 1207 1210	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1207 1257	may be results of the accompanying GSSG deficiency
T1008	Speculation 1441 1444	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1441 1492	may be the consequence of a GSSG deficiency as well
