T1000	Speculation 1171 1178	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1171 1424	suggest that next to lymphocyte infiltration, active regulatory events in the thyrocyte are responsible for the inverse relation between functional parameters (TSH-R, thyroid peroxidase, thyroglobulin, and c-fos) and immunological markers (MHC I and II)
T1002	Negation 685 688	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 685 694	not c-myc
