T1000	Negation 929 931	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 929 1021	no effect on phorbol ester-induced up-regulation of HB-EGF mRNA and kappa B binding activity
T1002	Speculation 687 695	appeared
E1001	Speculation:T1002 Scope:T1003
T1003	Span 664 749	These functions of PAF appeared to be mediated through the cell surface PAF receptors
T1004	Speculation 1333 1340	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1333 1385	suggest a potential role of PAF in HB-EGF expression
T1006	Negation 1130 1132	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1130 1150	no inhibitory effect
T1008	Speculation 1429 1432	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1429 1481	may occur through increased kappa B binding activity
T1010	Speculation 1343 1352	potential
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1343 1385	potential role of PAF in HB-EGF expression
