T1000	Negation 499 502	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 499 535	not in monocytic or epithelial cells
T1002	Speculation 363 368	might
E1001	Speculation:T1002 Scope:T1003
T1003	Span 363 417	might include 5-lipoxygenase (5-LOX) and NADPH oxidase
T1004	Negation 911 914	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 887 945	NF-kappaB induction was not influenced by 5-LOX inhibitors
T1006	Negation 861 864	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 861 945	not generate any ROIs and NF-kappaB induction was not influenced by 5-LOX inhibitors
T1008	Negation 1301 1304	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1291 1370	which are not required for NF-kappaB activation by IL-1beta in epithelial cells
