T1000	Negation 892 895	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 892 908	not either alone
T1002	Speculation 331 337	likely
E1001	Speculation:T1002 Scope:T1003
T1003	Span 311 454	This observation is likely to relate to the findings that TAL1 and LMO are highly synergistic in T-cell tumorigenesis in double-transgenic mice
T1004	Negation 1473 1476	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1473 1491	not binding to DNA
T1006	Negation 967 970	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 967 1005	not expressing endogeneous TAL1 or LMO
