T1000	Negation 607 610	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 577 642	Targeting of the IRF-1 GAS is not confined to activation via CD40
T1002	Speculation 302 313	not clearly
E1001	Speculation:T1002 Scope:T1003
T1003	Span 230 324	the molecular basis for the interplay between these distinct stimuli is not clearly delineated
T1004	Speculation 1169 1175	notion
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1169 1260	notion that modulation of IRF-1 levels may be a critical control point in B cell activation
T1006	Negation 990 993	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 990 1044	not lead to the activation of novel Rel/STAT complexes
T1008	Speculation 1208 1211	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1208 1260	may be a critical control point in B cell activation
