T1000	Speculation 972 979	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 954 1099	Enhancer activity appears to be mediated by the binding of a complex of proteins from the jun and fos families to tandem AP-1 consensus sequences
T1002	Speculation 852 855	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 852 952	may have a role in the increase in globin gene transcription that characterizes erythroid maturation
