T1000	Speculation 879 885	likely
E1000	Speculation:T1000 Scope:T1001
T1001	Span 879 902	likely other components
T1002	Speculation 187 190	can
E1001	Speculation:T1002 Scope:T1003
T1003	Span 187 300	can lead to homotypic cell adhesion, IL-6 production, and, in combination with cytokines, to Ig isotype switching
T1004	Speculation 1112 1119	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1112 1229	suggest that the CD40 pathway can influence the expression of B cell-associated genes with NF-kappa B consensus sites
