T1000	Speculation 263 266	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 263 294	may mimic mitogenic stimulation
T1002	Negation 188 191	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 188 223	not induce the biosynthesis of IL-2
T1004	Negation 537 540	nor
E1002	Negation:T1004 Scope:T1005
T1005	Span 537 580	nor on PCL gamma 1 tyrosine phosphorylation
T1006	Negation 452 454	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 452 580	no effect (in comparison to anti-CD3 antibodies) on protein tyrosine phosphorylation nor on PCL gamma 1 tyrosine phosphorylation
T1008	Negation 799 801	no
E1004	Negation:T1008 Scope:T1009
T1009	Span 799 832	no IL-2 mRNA in ALD-treated cells
T1010	Negation 702 706	lack
E1005	Negation:T1010 Scope:T1011
T1011	Span 702 776	lack of effect of herbimycin, a tyrosine-protein kinase-specific inhibitor
T1012	Speculation 1136 1143	suggest
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1136 1226	suggest that ALD cause transient but significant changes in T cell transmembrane signaling
T1014	Negation 1301 1304	not
E1007	Negation:T1014 Scope:T1015
T1015	Span 1237 1319	some events induced by stimulation with anti-CD3 antibodies are not induced by ALD
T1016	Negation 1458 1461	not
E1008	Negation:T1016 Scope:T1017
T1017	Span 1458 1507	not capable of causing complete T cell activation
