T1000	Negation 1563 1566	nor
E1000	Negation:T1000 Scope:T1001
T1001	Span 1563 1642	nor activated the tumor necrosis factor-alpha promoter in cotransfection assays
T1002	Negation 1458 1465	neither
E1001	Negation:T1002 Scope:T1003
T1003	Span 1458 1642	neither bound to the kappa3 element ( an NFAT-binding site ) in the tumor necrosis factor-alpha promoter nor activated the tumor necrosis factor-alpha promoter in cotransfection assays
T1004	Speculation 1718 1721	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1718 1779	may regulate inducible expression of different cytokine genes
T1006	Speculation 1655 1662	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1655 1779	suggest that different members or isoforms of NFAT gene family may regulate inducible expression of different cytokine genes
