T1000	Negation 1061 1072	rather than
E1000	Negation:T1000 Scope:T1001
T1001	Span 1061 1077	rather than NFAT
T1002	Negation 918 921	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 918 996	not vascular cell adhesion molecule-1 (VCAM-1) expression in endothelial cells
T1004	Speculation 1611 1616	could
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1611 1654	could function as an antiinflammatory agent
T1006	Speculation 1578 1586	suggests
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1578 1654	suggests mechanisms by which CsA could function as an antiinflammatory agent
