T1000	Speculation 936 946	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 936 1024	suggesting that STAT6 activated by IL-4 substitutes for the function of STAT5 in T cells
T1002	Negation 765 768	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 765 783	not activate STAT5
T1004	Speculation 1984 1992	possible
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1984 2038	possible role of Ras in Stat5-mediated gene expression
T1006	Speculation 1971 1981	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1971 2038	suggesting a possible role of Ras in Stat5-mediated gene expression
