T1000	Speculation 1195 1205	hypothesis
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1195 1324	hypothesis that EPO actively influences the programming of gene expression required for erythroid progenitor cell differentiation
T1002	Speculation 995 1010	indicating that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 995 1079	indicating that the EPO signal for erythroid differentiation is suppressed by GM-CSF
