T1000	Speculation 1298 1305	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1298 1419	suggest that NF-kappa B may play a central part in the activation of infiltrating T cells in chronic rheumatoid arthritis
T1002	Speculation 323 330	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 323 421	whether distinctive patterns of NF-kappa B activation are seen in different forms of joint disease
T1004	Speculation 1322 1325	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1322 1419	may play a central part in the activation of infiltrating T cells in chronic rheumatoid arthritis
