T1000	Speculation 1420 1427	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1420 1579	suggest that PU.1 plays a major role in macrophage gene regulation and development by directing the expression of a receptor for a key macrophage growth factor
T1002	Speculation 919 926	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 919 979	whether PU.1 binds and activates the M-CSF receptor promoter
