T1000	Speculation 585 592	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 585 670	whether SP-A activated NF-kappa B in the THP-1 cell line, a human monocytic cell line
T1002	Speculation 457 469	hypothesized
E1001	Speculation:T1002 Scope:T1003
T1003	Span 457 670	hypothesized that SP-A exerts its action, at least in part, via activation of NF-kappa B. We used gel shift assays to determine whether SP-A activated NF-kappa B in the THP-1 cell line, a human monocytic cell line
T1004	Speculation 1091 1098	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1091 1293	suggest a mechanism by which SP-A plays a role in the pathogenesis of some lung conditions and point to potential therapeutic measures that could be used to prevent SP-A induced inflammation in the lung
T1006	Speculation 893 895	or
E1003	Speculation:T1006 Scope:T1007
T1007	Span 859 957	by known inhibitors of NF-kappa B or by simultaneous treatment of the cells with surfactant lipids
T1008	Speculation 1231 1236	could
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1226 1293	that could be used to prevent SP-A induced inflammation in the lung
T1010	Speculation 1195 1204	potential
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1195 1293	potential therapeutic measures that could be used to prevent SP-A induced inflammation in the lung
