T1000	Speculation 209 212	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 209 274	may exist progenitor cells common to those two lineages may exist
T1002	Speculation 96 109	indicate that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 96 274	indicate that erythroid and megakaryocytic differentiation pathways are closely related to each other, and there may exist progenitor cells common to those two lineages may exist
T1004	Speculation 709 724	indicating that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 709 808	indicating that most of the blasts in M7 and TMD cases have erythroid and megakaryocytic phenotypes
T1006	Speculation 265 268	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 265 274	may exist
T1008	Speculation 858 861	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 858 933	may correspond to progenitors of both erythroid and megakaryocytic lineages
T1010	Speculation 824 831	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 824 933	suggest that blasts in M7 and TMD may correspond to progenitors of both erythroid and megakaryocytic lineages
