T1000	Speculation 1163 1174	potentially
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1163 1241	potentially novel proteins (around 35 kDa) can bind to this important sequence
T1002	Speculation 1126 1140	indicated that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1126 1205	indicated that NF-kappaB, c-Jun, and potentially novel proteins (around 35 kDa)
T1004	Speculation 1399 1406	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1399 1511	suggest that the cooperation of different transcription factors is essential for IL-9 gene expression in T cells
