T1000	Negation 1828 1831	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1828 1897	not replicate efficiently in U937 cells transduced with the IFNA gene
T1002	Negation 1179 1182	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1179 1244	not responsive to tumor necrosis factor alpha-mediated activation
T1004	Speculation 1913 1920	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1913 2101	suggest that targeting IFN synthesis to HIV-1-infected cells is an attainable goal and that autocrine IFN synthesis results in a long-lasting and permanent suppression of HIV-1 replication
