T1000	Speculation 505 512	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 505 599	suggest that a high WT1 expression in hematopoietic cells is incompatible with differentiation
T1002	Negation 45 48	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 45 142	not a prerequisite for erythroid or megakaryocytic differentiation of the leukemic cell line K562
T1004	Negation 1282 1285	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1282 1363	not a prerequisite for erythroid or megakaryocytic differentiation of these cells
T1006	Negation 977 980	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 977 1016	not affect the differentiation response
