T1000	Negation 150 153	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 150 225	not replicate in naive CD4 T cells stimulated by cross-linking CD3 and CD28
T1002	Negation 9 12	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 9 68	not replicate in naive CD4 T cells stimulated with CD3/CD28
T1004	Negation 708 711	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 708 751	not restore LAI expression in naive T cells
T1006	Negation 634 637	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 634 680	not suppress LAI replication in memory T cells
T1008	Negation 876 879	nor
E1004	Negation:T1008 Scope:T1009
T1009	Span 876 1007	nor is it due to inhibition of activation of the important HIV transcription factors, nuclear factor-kappaB and activator protein-1
T1010	Negation 819 822	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 819 1007	not due to differential expression of viral coreceptors, nor is it due to inhibition of activation of the important HIV transcription factors, nuclear factor-kappaB and activator protein-1
