T1000	Speculation 257 266	suggested
E1000	Speculation:T1000 Scope:T1001
T1001	Span 257 350	suggested, no study has reported whether EBV infection is directly linked to IL-12 expression
T1002	Negation 268 270	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 268 350	no study has reported whether EBV infection is directly linked to IL-12 expression
T1004	Speculation 957 964	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 957 1073	suggest that transformation of primary B cells with EBV induces IL-12 expression potentially through LMP1 expression
T1006	Speculation 290 297	whether
E1003	Speculation:T1006 Scope:T1007
T1007	Span 290 350	whether EBV infection is directly linked to IL-12 expression
T1008	Speculation 1038 1049	potentially
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1038 1073	potentially through LMP1 expression
