T1000	Negation 934 941	neither
E1000	Negation:T1000 Scope:T1001
T1001	Span 934 965	neither aspirin nor salicylate)
T1002	Negation 654 657	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 654 675	not sodium salicylate
T1004	Speculation 1360 1363	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1360 1553	may be, at least in part, due to the ability of HTB and triflusal to block the activation of the transcription factor nuclear factor-kappaB to a higher extent than aspirin and sodium salicylate
T1006	Negation 950 953	nor
E1003	Negation:T1006 Scope:T1007
T1007	Span 950 965	nor salicylate)
T1008	Speculation 1783 1786	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1783 1990	may exert beneficial effects in processes in which de novo COX-2 expression is involved and, in a broader sense, in pathological situations in which genes under nuclear factor-kappaB control are up-regulated
