T1000	Negation 1274 1281	without
E1000	Negation:T1000 Scope:T1001
T1001	Span 1274 1329	without apparent differences between Th1 and Th2 clones
T1002	Negation 1090 1093	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1090 1111	not in the Th2 clones
T1004	Speculation 1607 1614	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1607 1852	suggest that high-level IL-4 production in atopic Th2 cells is associated with selective reduction of suppressive NFAT1 activity at the IL-4 P0 element and that some patients with this multifactorial disease may have a putative systemic disorder
T1006	Negation 1571 1574	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1571 1590	not in control PBMC
T1008	Speculation 1826 1834	putative
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1826 1866	putative systemic disorder at this level
T1010	Speculation 1815 1818	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1815 1866	may have a putative systemic disorder at this level
