T1000	Negation 1084 1087	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1084 1134	not affect TNF-alpha-mediated NF-kappaB activation
T1002	Negation 970 973	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 970 1017	not in cells stimulated with PMA plus ionomycin
T1004	Speculation 1177 1185	possible
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1177 1360	possible relationship between the activation of the electron-transport system at the plasma membrane by ascorbate or its free radical and redox-dependent gene transcription in T-cells
