T1000	Negation 1355 1358	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1355 1371	not 10-60 mM NAC
T1002	Negation 832 838	failed
E1001	Negation:T1002 Scope:T1003
T1003	Span 832 911	failed to inhibit the endonuclease activity contained in the whole cell lysates
T1004	Speculation 1455 1462	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1455 1574	suggest that the activation of NF-kappa B plays an important role in the apoptotic process of human hematopoietic cells
