T1000	Speculation 239 244	might
E1000	Speculation:T1000 Scope:T1001
T1001	Span 239 320	might expect that a given enhancer has evolved to work best with its own promoter
T1002	Speculation 74 79	could
E1001	Speculation:T1002 Scope:T1003
T1003	Span 74 132	could new regulatory pathways evolve by enhancer shuffling
T1004	Negation 384 387	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 384 409	not found evidence for it
T1006	Speculation 245 251	expect
E1003	Speculation:T1006 Scope:T1007
T1007	Span 245 320	expect that a given enhancer has evolved to work best with its own promoter
T1008	Negation 665 667	no
E1004	Negation:T1008 Scope:T1009
T1009	Span 665 729	no strong preference for any given enhancer/promoter combination
T1010	Speculation 345 348	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 328 374	this expectation may be realized in some cases
T1012	Speculation 918 925	propose
E1006	Speculation:T1012 Scope:T1013
T1013	Span 918 1032	propose that a generally permissive enhancer/promoter interaction is of evolutionary benefit for higher eukaryotes
T1014	Negation 746 749	not
E1007	Negation:T1014 Scope:T1015
T1015	Span 746 913	not see particularly strong transcription when the immunoglobulin kappa enhancer (or the immunoglobulin heavy chain enhancer) is used to activate a kappa gene promoter
T1016	Speculation 1063 1068	could
E1008	Speculation:T1016 Scope:T1017
T1017	Span 1063 1141	could be easily brought under a new type of inducibility/cell type specificity
