T1000	Negation 1048 1051	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1048 1142	not result in the phosphorylation and/or degradation of IkB alpha in Jurkat T or in U937 cells
T1002	Speculation 281 288	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 281 411	whether this synergy is present in other cell types and the mechanism(s) by which these two pathways lead to NF-kappa B activation
T1004	Speculation 1623 1636	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1623 1890	indicate that Ca(2+)-dependent pathways, including the phosphatase calcineurin, participate in the regulation of NF-kappa B in a cell specific fashion and synergize with PKC-dependent and -independent pathways at the level of IkB alpha phosphorylation and degradation
T1006	Negation 1333 1336	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1333 1434	not the phosphorylation and degradation of IkB alpha induced by TNF-alpha, a PKC-independent stimulus
