T1000	Negation 1046 1049	nor
E1000	Negation:T1000 Scope:T1001
T1001	Span 1046 1085	nor the production of IgA, IgG, and IgM
T1002	Negation 1017 1024	neither
E1001	Negation:T1002 Scope:T1003
T1003	Span 1017 1085	neither B-cell proliferation nor the production of IgA, IgG, and IgM
T1004	Speculation 1332 1339	whether
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1332 1405	whether the RA effect was mediated by RA receptors alpha, beta, and gamma
T1006	Negation 1279 1282	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1232 1313	production of interferon-gamma (IFN-gamma) was not enhanced in the presence of RA
