T1000	Speculation 962 969	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 962 1041	whether the abnormal NF-AT binding activity was related to an impaired function
T1002	Speculation 383 390	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 383 503	whether the defect in the patient's T lymphocytes involved a trans-acting factor common to the affected lymphokine genes
T1004	Speculation 1650 1653	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1650 1713	may underlie the multiple lymphokine deficiency in this patient
T1006	Speculation 1597 1610	indicate that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1597 1713	indicate that an abnormality of/or influencing NF-AT may underlie the multiple lymphokine deficiency in this patient
