T1000	Negation 1795 1802	without
E1000	Negation:T1000 Scope:T1001
T1001	Span 1795 1881	without significantly changing the relative proportions of polyunsaturated fatty acids
T1002	Speculation 262 269	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 262 426	whether this fatty acid can modulate endothelial activation, ie, the concerted expression of gene products involved in leukocyte recruitment and early atherogenesis
T1004	Speculation 1986 1989	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1986 2216	may contribute to the prevention of atherogenesis through selective displacement of saturated fatty acids in cell membrane phospholipids and a consequent modulation of gene expression for molecules involved in monocyte recruitment
