T1000	Negation 1221 1223	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 1221 1242	no significant effect
T1002	Negation 663 666	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 663 681	not basal adhesion
T1004	Negation 1328 1330	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1328 1392	no suppression of phosphorylation of PKC substrates was observed
T1006	Negation 1272 1275	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1244 1321	Protein kinase C (PKC) does not appear to play a role in the alpha-tcp effect
T1008	Negation 1476 1479	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1476 1522	not sufficient for E-selectin expression in EC
T1010	Speculation 1276 1282	appear
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1244 1321	Protein kinase C (PKC) does not appear to play a role in the alpha-tcp effect
T1012	Speculation 1690 1702	hypothesized
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1690 1831	hypothesized that alpha-tcp acts as an anti-atherosclerotic molecule by inhibiting generation of oxidized LDL--a putative triggering molecule
T1014	Negation 1562 1568	failed
E1007	Negation:T1014 Scope:T1015
T1015	Span 1562 1676	failed to show an alpha-tcp-induced decrease in activation of this transcription factor after cytokine stimulation
T1016	Speculation 1803 1811	putative
E1008	Speculation:T1016 Scope:T1017
T1017	Span 1803 1862	putative triggering molecule in the atherosclerotic process
