T1000	Speculation 1889 1902	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1889 2042	indicate that CCK-8 exerts a trophic effect in Jurkat T cells through stimulation of CCK(B) receptors by modulation of expression of AP-1-regulated genes
T1002	Negation 1423 1426	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1423 1515	not observed a contribution of phosphatase inhibitors on a CCK-8-induced luciferase activity
