T1000	Speculation 1243 1246	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1237 1354	which may be mediated by the inhibition of transcription of certain pro-inflammatory mediators and adhesion molecules
T1002	Speculation 1140 1147	propose
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1140 1354	propose that inhibition of NF-kappa B activation produces significant anti inflammatory activity which may be mediated by the inhibition of transcription of certain pro-inflammatory mediators and adhesion molecules
