T1000	Speculation 1436 1438	or
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1420 1561	independent of, or in concert with, the LTR promoter to rapidly increase latent proviral transcription in response to cell activation signals
T1002	Speculation 1288 1295	propose
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1288 1454	propose that the inducible transcription factor binding sites in the 5'-UTR comprise a downstream enhancer domain that can function independent of, or in concert with
