T1000	Negation 802 809	without
E1000	Negation:T1000 Scope:T1001
T1001	Span 802 984	without a nonspecific serine/threonine protein kinase inhibitor staurosporine (Stauro), a specific pan-PKC inhibitor bisindolylmaleimide (Bis), or an inhibitor of PTK genistein (Gen)
T1002	Speculation 552 564	hypothesized
E1001	Speculation:T1002 Scope:T1003
T1003	Span 552 691	hypothesized that inhibition of either PKC or PTK would decrease LPS-induced NF-kappaB DNA binding and TNF-alpha release in human monocytes
T1004	Speculation 1681 1688	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1681 1799	suggest that LPS-induced NF-kappaB activation and TNF-alpha release in human monocytes are independent of PKC activity
T1006	Negation 1353 1355	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1353 1420	no effect on LPS-induced NF-kappaB DNA binding or TNF-alpha release
T1008	Speculation 1962 1971	potential
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1962 2013	potential therapeutic target in inflammatory states
T1010	Speculation 1951 1956	could
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1951 2013	could be a potential therapeutic target in inflammatory states
