T1000	Speculation 428 431	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 428 466	may function as a transcription factor
T1002	Speculation 409 419	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 409 466	suggesting that it may function as a transcription factor
T1004	Speculation 1142 1145	can
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1142 1203	can function as a sequence-specific transcriptional repressor
T1006	Speculation 1110 1123	indicate that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1110 1203	indicate that the BCL-6 protein can function as a sequence-specific transcriptional repressor
