T1000	Speculation 667 676	suggested
E1000	Speculation:T1000 Scope:T1001
T1001	Span 667 740	suggested that the ubiquitin-proteasome system is involved in the process
T1002	Speculation 644 653	not known
E1001	Speculation:T1002 Scope:T1003
T1003	Span 606 653	The mechanism of generation of p50 is not known
T1004	Speculation 874 881	obscure
E1002	Speculation:T1004 Scope:T1005
T1005	Span 751 881	the specific enzymes involved and the mechanism of limited proteolysis, in which half of the molecule is spared, have been obscure
