T1000	Speculation 523 526	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 523 648	may be due to increased transcriptional initiation, increased transcriptional elongation, or a combination of these processes
T1002	Speculation 422 427	seems
E1001	Speculation:T1002 Scope:T1003
T1003	Span 416 521	which seems to be an important component in the progression of acquired immune deficiency syndrome (AIDS)
T1004	Speculation 855 863	believed
E1002	Speculation:T1004 Scope:T1005
T1005	Span 835 928	This interaction is believed to be an important component of the mechanism of transactivation
T1006	Speculation 613 615	or
E1003	Speculation:T1006 Scope:T1007
T1007	Span 613 648	or a combination of these processes
