T1000	Speculation 1375 1382	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1375 1451	suggest a role for Jagged1 in B-cell activation, differentiation or function
T1002	Negation 520 523	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 520 523	not
T1004	Speculation 1487 1496	potential
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1487 1585	potential for an interplay between the Notch and NF-kappaB signaling pathways in the immune system
