T1000	Negation 385 388	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 385 502	not necessary for steroid-regulated apoptosis and that GR-mediated transrepression may be the more critical mechanism
T1002	Speculation 118 132	indicated that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 118 287	indicated that transcriptional transactivation functions encoded in the glucocorticoid receptor (GR) N-terminal domain are required for glucocorticoid-mediated apoptosis
T1004	Speculation 468 471	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 468 502	may be the more critical mechanism
T1006	Speculation 345 354	suggested
E1003	Speculation:T1006 Scope:T1007
T1007	Span 345 430	suggested that the N-terminal domain is not necessary for steroid-regulated apoptosis
T1008	Speculation 1939 1949	conclusion
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1939 2043	conclusion that transcriptional transactivation is a necessary signaling component of S49 cell apoptosis
T1010	Speculation 1829 1832	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1829 1895	may be a marker of early apoptotic events in steroid-treated cells
