T1000	Speculation 995 1000	could
E1000	Speculation:T1000 Scope:T1001
T1001	Span 995 1089	could use the X box region to direct the expression of a transiently transfected reporter gene
T1002	Negation 953 960	neither
E1001	Negation:T1002 Scope:T1003
T1003	Span 953 1089	neither of the class II mutant cell lines could use the X box region to direct the expression of a transiently transfected reporter gene
T1004	Speculation 1448 1455	whether
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1448 1573	whether these different X1 box activities represented distinct DNA binding proteins or multimeric forms of the same factor(s)
T1006	Speculation 1091 1106	indicating that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1091 1178	indicating that the X box-dependent transcriptional pathway is defective in these cells
T1008	Negation 2069 2071	no
E1004	Negation:T1008 Scope:T1009
T1009	Span 2069 2114	no detectable levels of the band 1pk activity
T1010	Speculation 1532 1534	or
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1502 1573	distinct DNA binding proteins or multimeric forms of the same factor(s)
