T1000	Negation 957 960	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 957 999	not inhibit c-myc and bcl-2 mRNA induction
T1002	Negation 694 697	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 694 779	not block significantly the induction of either IL-2 or IL-2R alpha- and gamma-chains
T1004	Negation 1312 1315	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1312 1362	not affect NF-kappa B activation by PMA in T cells
