T1000	Negation 763 766	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 763 874	not affect in vitro binding of Ets-1, PU.1, or the muE3-binding protein TFE3, alone or in pairwise combinations
T1002	Speculation 447 457	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 447 533	suggesting that ETS proteins bind to these sites from these same side of the DNA helix
T1004	Speculation 1021 1028	propose
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1021 1151	propose that the requirement for precise spacing of the muA and muB elements is due in part to a directed DNA bend induced by PU.1
T1006	Negation 953 956	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 953 970	not TFE3 or Ets-1
