T1000	Negation 1169 1172	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1169 1194	not Jnk or other proteins
T1002	Negation 945 947	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 945 1023	no effects on N-terminal c-Jun kinase or on events upstream of the MAP kinases
T1004	Speculation 1199 1206	propose
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1199 1459	propose that HePTP plays a negative role in antigen receptor signaling by specifically regulating MAP kinases in the cytosol and at early time points of T cell activation before the activation-induced expression of nuclear dual-specific MAP kinase phosphatases
