T1000	Speculation 926 934	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 926 1023	suggests that the pAT 133 gene encodes a transcription factor with a specific biological function
T1002	Speculation 606 613	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 597 655	which is thought to bind DNA in a sequence-specific manner
T1004	Speculation 1615 1623	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1615 1714	suggests distinct biological roles in the control of cell proliferation for the respective proteins
T1006	Negation 1550 1553	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1515 1578	mRNA representing pAT 591/EGR2 was not expressed in these cells
