T1000	Negation 851 854	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 851 887	not affect Rho-induced AP-1 activity
T1002	Negation 464 466	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 464 556	no effect on NFAT, Oct-1, and NF-kappaB enhancer element activities under similar conditions
T1004	Speculation 1272 1279	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1272 1344	suggest that Rho potentiates AP-1 transcription during T-cell activation
