T1000	Speculation 815 822	thought
E1000	Speculation:T1000 Scope:T1001
T1001	Span 779 902	NFAT-1 activity had previously been thought to be confined to activated T-lymphocytes upon release of intracellular calcium
T1002	Speculation 321 331	considered
E1001	Speculation:T1002 Scope:T1003
T1003	Span 312 387	which is considered to be an important regulator in early T-cell activation
T1004	Speculation 1837 1844	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1837 1898	suggest a role for NFAT-1 in dermal activation of the HIV-LTR
