T1000	Negation 942 953	rather than
E1000	Negation:T1000 Scope:T1001
T1001	Span 942 1076	rather than the p50-p56 heterodimer of NF-kappa B that is the predominant NF-kappa B species in most T lymphocytic and monocytic cells
T1002	Speculation 425 428	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 425 462	may differ between certain cell types
T1004	Speculation 1334 1341	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1334 1439	suggest that different proximal mechanisms may lead to restricted HIV-1 replication in various cell types
T1006	Speculation 890 898	possibly
E1003	Speculation:T1006 Scope:T1007
T1007	Span 890 940	possibly p50 homodimers or closely related species
T1008	Speculation 1377 1380	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1377 1439	may lead to restricted HIV-1 replication in various cell types
