T1000	Negation 402 405	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 402 416	not thymocytes
T1002	Speculation 240 247	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 206 288	The viral encoded protein tax, is thought to play an important role in oncogenesis
T1004	Speculation 1334 1337	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1334 1430	may facilitate tumor growth in both HTLV-1 infected human T cells and the transgenic mouse model
T1006	Negation 646 649	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 646 692	not in thymocytes from Thy-tax transgenic mice
