T1000	Negation 903 905	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 903 967	no apparent change was observed in the levels of beta-actin mRNA
T1002	Speculation 420 423	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 420 452	may participate in this response
T1004	Speculation 1758 1761	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1758 1913	may function as an important signaling molecule capable of initiating proinflammatory events in monocytes that come into contact with activated endothelium
T1006	Negation 1577 1580	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1577 1620	not affect SV40 promoter specific protein-1
