T1000	Speculation 942 948	likely
E1000	Speculation:T1000 Scope:T1001
T1001	Span 942 1062	likely that the binding of the purified factors involves cooperation between octamer and heptamer sites in this promoter
T1002	Speculation 936 941	seems
E1001	Speculation:T1002 Scope:T1003
T1003	Span 936 1062	seems likely that the binding of the purified factors involves cooperation between octamer and heptamer sites in this promoter
T1004	Speculation 1711 1719	possibly
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1711 1795	possibly at the protein-protein level) may be critical to B-cell-specific expression
T1006	Speculation 1630 1637	propose
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1630 1748	propose that NTF and OTF2 interactions (both with their cognate DNA elements and possibly at the protein-protein level
T1008	Speculation 1750 1753	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1750 1882	may be critical to B-cell-specific expression and that these interactions provide additional pathways for regulating gene expression
