T1000	Speculation 1136 1143	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1136 1314	suggest the possibility that Stat3gamma may be transcriptionally inactive and may compete with Stat3alpha for Stat3 binding sites in these terminally differentiated myeloid cells
T1002	Negation 995 1000	lacks
E1001	Negation:T1002 Scope:T1003
T1003	Span 995 1044	lacks the carboxyl-terminal portion of Stat3alpha
T1004	Speculation 1176 1179	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1176 1314	may be transcriptionally inactive and may compete with Stat3alpha for Stat3 binding sites in these terminally differentiated myeloid cells
T1006	Speculation 1148 1159	possibility
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1148 1314	possibility that Stat3gamma may be transcriptionally inactive and may compete with Stat3alpha for Stat3 binding sites in these terminally differentiated myeloid cells
T1008	Speculation 1214 1217	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1214 1314	may compete with Stat3alpha for Stat3 binding sites in these terminally differentiated myeloid cells
