T1000	Speculation 362 365	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 362 401	may be an inhibitor HIV-1 transcription
T1002	Speculation 343 352	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 343 401	suggested that Nef may be an inhibitor HIV-1 transcription
T1004	Speculation 416 423	whether
E1002	Speculation:T1004 Scope:T1005
T1005	Span 416 498	whether Nef affects the binding of cellular factors implicated in HIV-1 regulation
T1006	Negation 653 656	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 648 707	were not stimulated or were stimulated with T-cell mitogens
T1008	Negation 1140 1143	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1140 1160	not in control cells
T1010	Speculation 668 670	or
E1005	Speculation:T1010 Scope:T1011
T1011	Span 648 707	were not stimulated or were stimulated with T-cell mitogens
T1012	Speculation 1225 1228	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1225 1296	may play a role in regulating HIV-1 gene expression in infected T-cells
T1014	Speculation 1176 1183	suggest
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1176 1296	suggest that, by inhibiting AP-1 activation, Nef may play a role in regulating HIV-1 gene expression in infected T-cells
