T1000	Speculation 405 412	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 405 509	whether this may be partly explained by changes in expression of NF-kappaB with monocyte differentiation
T1002	Speculation 132 140	possible
E1001	Speculation:T1002 Scope:T1003
T1003	Span 132 239	possible mechanism influencing human immunodeficiency virus replication in monocytes and mature macrophages
T1004	Negation 1088 1094	failed
E1002	Negation:T1004 Scope:T1005
T1005	Span 1088 1128	failed to induce p50/p65 as seen in MDMs
T1006	Speculation 418 421	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 418 509	may be partly explained by changes in expression of NF-kappaB with monocyte differentiation
T1008	Speculation 1426 1429	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1426 1537	may also explain the different transcriptional activities of these cell populations in HIV-infected individuals
T1010	Speculation 1233 1236	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1233 1351	may partially explain the progressive increase in susceptibility of monocytes to HIV infection during in vitro culture
