T1000	Speculation 337 344	thought
E1000	Speculation:T1000 Scope:T1001
T1001	Span 318 381	the Tax protein is thought to play a major role in this process
T1002	Speculation 309 316	unclear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 234 316	the exact mechanism by which HTLV-I contributes to leukemogenesis is still unclear
T1004	Negation 1168 1172	fail
E1002	Negation:T1004 Scope:T1005
T1005	Span 1168 1287	fail to activate either ATF- or NF-kappaB-dependent promoters and different 5' truncation mutants of the E2F-1 promoter
T1006	Negation 833 837	lack
E1003	Negation:T1006 Scope:T1007
T1007	Span 833 862	lack expression of p16(INK4A)
