T1000	Speculation 976 983	thought
E1000	Speculation:T1000 Scope:T1001
T1001	Span 976 1113	thought to activate NF-kappa B by distinct intracellular pathways might all act through a common mechanism involving the synthesis of ROI
T1002	Speculation 947 955	suggests
E1001	Speculation:T1002 Scope:T1003
T1003	Span 947 1041	suggests that diverse agents thought to activate NF-kappa B by distinct intracellular pathways
T1004	Speculation 1119 1125	appear
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1115 1181	ROI appear to serve as messengers mediating directly or indirectly
T1006	Speculation 1042 1047	might
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1042 1113	might all act through a common mechanism involving the synthesis of ROI
T1008	Speculation 1168 1170	or
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1159 1269	directly or indirectly the release of the inhibitory subunit I kappa B from NF-kappa B. 
