T1000	Negation 1077 1084	neither
E1000	Negation:T1000 Scope:T1001
T1001	Span 1077 1117	neither a TATA nor a CAAT consensus site
T1002	Speculation 295 297	if
E1001	Speculation:T1002 Scope:T1003
T1003	Span 295 362	if platelet thromboxane receptors are under transcriptional control
T1004	Speculation 2166 2173	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2166 2380	suggest that the mechanism for previously described upregulation of platelet thromboxane receptors after acute myocardial infarction is increased thromboxane receptor gene transcription in platelet-progenitor cells
T1006	Negation 1092 1095	nor
E1003	Negation:T1006 Scope:T1007
T1007	Span 1092 1117	nor a CAAT consensus site
