T1000	Negation 563 566	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 563 598	not bcl-2, bcl-xs, bak, bad, or bax
T1002	Speculation 199 206	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 148 259	Human T-cell leukemia virus type 1 (HTLV-1) Tax is thought to play a pivotal role in immortalization of T cells
T1004	Speculation 1306 1313	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1306 1481	suggest that constitutive expression of Bcl-x(L) induced by Tax through the NF-kappaB pathway contributes to the inhibition of apoptosis in CTLL-2 cells after IL-2 deprivation
T1006	Speculation 920 928	putative
E1003	Speculation:T1006 Scope:T1007
T1007	Span 920 984	putative NF-kappaB binding site identified in the bcl-x promoter
