T1000	Speculation 512 522	hypothesis
E1000	Speculation:T1000 Scope:T1001
T1001	Span 512 590	hypothesis that acute ethanol affects NF-kappa B activation in human monocytes
T1002	Speculation 307 313	yet to
E1001	Speculation:T1002 Scope:T1003
T1003	Span 245 327	the intracellular mechanisms for these effects of ethanol are yet to be understood
T1004	Negation 1193 1204	rather than
E1002	Negation:T1004 Scope:T1005
T1005	Span 1193 1267	rather than activation of NF-kappa B-regulated inflammatory cytokine genes
T1006	Negation 899 901	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 899 938	no induction of the p65/p50 heterodimer
T1008	Speculation 1297 1304	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1297 1532	suggest that physiologically relevant concentrations of ethanol may affect production of inflammatory cytokines, such as tumor necrosis factor-alpha, interleukin-1 beta, and interleukin-6 by disrupting NF-kappa B signaling in monocytes
T1010	Speculation 1168 1171	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1168 1267	may result in inhibition rather than activation of NF-kappa B-regulated inflammatory cytokine genes
T1012	Speculation 1361 1364	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1361 1532	may affect production of inflammatory cytokines, such as tumor necrosis factor-alpha, interleukin-1 beta, and interleukin-6 by disrupting NF-kappa B signaling in monocytes
