T1000	Negation 1018 1020	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 1018 1069	no effect was noticed on the expression of p65 mRNA
T1002	Negation 414 421	Priming
E1001	Negation:T1002 Scope:T1003
T1003	Span 414 455	Priming of human monocytes with IFN-gamma
T1004	Negation 1898 1901	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1898 1951	not result in enhanced p50 and p65 protein expression
T1006	Negation 1106 1109	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1106 1151	not affect the expression of p105 transcripts
T1008	Speculation 2238 2241	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2238 2350	may be important for the modulatory effects of IFN-gamma on the cytokine expression in activated human monocytes
T1010	Negation 2028 2030	no
E1005	Negation:T1010 Scope:T1011
T1011	Span 2028 2350	no change was observed in the expression of NF-IL-6 or I kappa B alpha, the inhibitor of NF-kappa B. We conclude that the effects of IFN-gamma on the expression of the transcription factors AP-1 and NF-kappa B may be important for the modulatory effects of IFN-gamma on the cytokine expression in activated human monocytes
