T1000	Speculation 2206 2214	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 2206 2331	suggests a common step in the signaling pathways that trigger I kappaB alpha, I kappaB beta, and I kappaB epsilon degradation
T1002	Negation 695 698	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 695 748	not activate NF-kappaB in response to several stimuli
T1004	Negation 49 52	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 49 103	not activate NF-kappaB in response to multiple stimuli
T1006	Negation 933 940	absence
E1003	Negation:T1006 Scope:T1007
T1007	Span 933 988	absence of induced phosphorylation on serines 32 and 36
T1008	Negation 901 904	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 883 913	I kappaB alpha is not degraded
T1010	Negation 1027 1030	nor
E1005	Negation:T1010 Scope:T1011
T1011	Span 1027 1153	nor a mutation in p50 or relA, the two major subunits of NF-kappaB in this cell line, accounts for this phosphorylation defect
T1012	Negation 990 997	Neither
E1006	Negation:T1012 Scope:T1013
T1013	Span 990 1153	Neither a mutation in I kappaB alpha nor a mutation in p50 or relA, the two major subunits of NF-kappaB in this cell line, accounts for this phosphorylation defect
T1014	Negation 1797 1800	not
E1007	Negation:T1014 Scope:T1015
T1015	Span 1797 1834	not operate via the defective pathway
T1016	Negation 1576 1579	not
E1008	Negation:T1016 Scope:T1017
T1017	Span 1576 1622	not reveal any difference from wild-type 70Z/3
T1018	Negation 1952 1955	not
E1009	Negation:T1018 Scope:T1019
T1019	Span 1858 2009	two other I kappaB molecules, I kappaB beta and the recently identified I kappaB epsilon, are not degraded in the 1.3E2 cell line following stimulation
T1020	Speculation 1757 1767	suggesting
E1010	Speculation:T1020 Scope:T1021
T1021	Span 1757 1834	suggesting that this viral protein does not operate via the defective pathway
