T1000	Speculation 1227 1237	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1227 1336	suggesting a positive feedback loop between HIV-1 infection, LT-alpha1beta2 expression, and HIV-1 replication
T1002	Speculation 988 996	probably
E1001	Speculation:T1002 Scope:T1003
T1003	Span 933 1112	cosignaling via the LT-beta and TNF-alpha receptors is probably involved in the modulation of HIV-1 replication and the subsequent determination of HIV-1 viral burden in monocytes
T1004	Speculation 1447 1450	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1447 1517	may be involved in HIV-associated abnormalities of the lymphoid organs
T1006	Speculation 1417 1426	speculate
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1417 1517	speculate that LT-alpha1beta2 may be involved in HIV-associated abnormalities of the lymphoid organs
