T1000	Negation 1011 1014	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1011 1072	not by activated T cells isolated from one normal blood donor
T1002	Speculation 620 634	indicated that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 620 863	indicated that these cells were expressing high levels of vascular cell adhesion molecule 1 (VCAM-1 [CD106]), a 110-kDa member of the immunoglobulin gene superfamily, first identified on endothelial cells stimulated with inflammatory cytokines
T1004	Speculation 2141 2144	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2141 2219	may represent a pivotal event in the progression of HTLV-1-associated diseases
T1006	Speculation 2070 2077	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 2070 2219	suggest that the exclusive Tax-induced expression of VCAM-1 on T cells may represent a pivotal event in the progression of HTLV-1-associated diseases
