T1000	Speculation 491 494	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 491 524	may act by an autocrine mechanism
T1002	Speculation 470 479	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 470 524	suggested that M-CSF may act by an autocrine mechanism
T1004	Negation 1304 1307	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1304 1353	not in monocytes exposed to medium treatment only
T1006	Speculation 643 646	can
E1003	Speculation:T1006 Scope:T1007
T1007	Span 622 709	sensitivity to M-CSF can be modulated by regulation of receptor expression and function
T1008	Speculation 1367 1374	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1367 1471	suggest that M-CSF induction of M-CSF involves G proteins, PKC and NF kappa B. 
