T1000	Speculation 1631 1644	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1631 1836	indicate that NF-kappa B activation might constitute one of the mechanisms underlying the inducible expression of kappa B-dependent genes in microglia stimulated by A beta peptides and IFN gamma, or by LPS
T1002	Speculation 136 144	suggests
E1001	Speculation:T1002 Scope:T1003
T1003	Span 136 260	suggests that amyloid-beta (A beta) peptides and microglia are crucially involved in the pathogenesis of Alzheimer's disease
T1004	Speculation 1827 1829	or
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1793 1836	by A beta peptides and IFN gamma, or by LPS
T1006	Speculation 1667 1672	might
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1667 1836	might constitute one of the mechanisms underlying the inducible expression of kappa B-dependent genes in microglia stimulated by A beta peptides and IFN gamma, or by LPS
