T1000	Speculation 1355 1363	apparent
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1355 1388	apparent molecular mass of 32 kDa
T1002	Speculation 664 672	unlikely
E1001	Speculation:T1002 Scope:T1003
T1003	Span 664 785	unlikely candidate to have an exclusive role as a combinatorial differentiation switch during myelopoiesis in human cells
T1004	Speculation 2550 2559	suggested
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2550 2666	suggested a role for C/EBP-epsilon transcription factor in the regulation of a subset of myeloid-cell-specific genes
T1006	Negation 1665 1667	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1665 1678	no TATAAA box
