T1000	Negation 800 803	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 800 812	not p90(rsk)
T1002	Negation 699 702	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 699 752	not of another putative IkappaBalpha kinase, p90(rsk)
T1004	Speculation 1228 1241	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1228 1405	indicate that within the TCR/CD3 signal transduction pathway both PKC and calcineurin are required for the effective activation of the IKK complex and NF-kappaB in T lymphocytes
