T1000	Negation 547 550	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 527 612	CTLA-4 ligation did not appear to affect the CD28-mediated stabilization of IL-2 mRNA
T1002	Speculation 434 441	appears
E1001	Speculation:T1002 Scope:T1003
T1003	Span 428 516	which appears to be mediated in part through decreasing NF-AT accumulation in the nuclei
T1004	Negation 1034 1037	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1034 1079	not simply oppose CD28-mediated costimulation
T1006	Speculation 551 557	appear
E1003	Speculation:T1006 Scope:T1007
T1007	Span 527 612	CTLA-4 ligation did not appear to affect the CD28-mediated stabilization of IL-2 mRNA
T1008	Speculation 861 874	indicate that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 861 1079	indicate that CTLA-4 signaling inhibits events early in T cell activation both at IL-2 transcription and at the level of IL-2-independent events of the cell cycle, and does not simply oppose CD28-mediated costimulation
