T1000	Negation 969 972	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 969 1003	not alter the interaction with DNA
T1002	Negation 791 794	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 791 850	not require the simultaneous binding of Oct proteins to DNA
T1004	Negation 1426 1433	failure
E1002	Negation:T1004 Scope:T1005
T1005	Span 1426 1524	failure of full-length BOB.1/OBF.1 to stimulate octamer-dependent enhancer elements in non B cells
T1006	Negation 1098 1103	fails
E1003	Negation:T1006 Scope:T1007
T1007	Span 1098 1152	fails to stimulate octamer-dependent enhancer activity
