T1000	Speculation 1253 1262	suggested
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1253 1357	suggested that AP-1 and NF-kappaB are among the possible targets of GC actions on TCR-stimulated T cells
T1002	Speculation 1015 1030	indicating that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1015 1205	indicating that the approximately 500-bp human IL-5 gene segment located 5' upstream of the coding region contains activation-inducible enhancer elements responsible for the regulation by GC
T1004	Speculation 1301 1309	possible
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1301 1357	possible targets of GC actions on TCR-stimulated T cells
