T1000	Negation 1026 1029	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1026 1066	not affect the DNA binding of NF-kappa B
T1002	Speculation 184 192	possible
E1001	Speculation:T1002 Scope:T1003
T1003	Span 184 390	possible involvement of the mitogen-activated protein kinase family members extracellular-regulated kinase 1/2 (ERK1/2) and c-Jun N-terminal kinase (JNK) in mediating IL-6 gene expression in human monocytes
T1004	Speculation 1584 1587	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1584 1687	may regulate NF-kappa B-mediated gene transcription through its phosphorylation and activation of c-Jun
T1006	Speculation 1555 1562	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1555 1687	suggest that the JNK pathway may regulate NF-kappa B-mediated gene transcription through its phosphorylation and activation of c-Jun
