T1000	Negation 1168 1170	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 1168 1228	no detrimental effect on OCA-B/Oct-1-dependent transcription
T1002	Speculation 699 709	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 699 839	suggesting a joint requirement for PC4 and another, USA-derived component(s) for optimal function of Oct-1/OCA-B in the reconstituted system
T1004	Speculation 1417 1424	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1417 1472	suggest a functional redundancy in general coactivators
