T1000	Speculation 773 778	seems
E1000	Speculation:T1000 Scope:T1001
T1001	Span 762 826	the former seems to be related to the 50 kD polypeptide of NF-kB
T1002	Negation 452 455	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 452 469	not in HeLa cells
T1004	Speculation 1336 1349	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1336 1475	indicate that lymphocyte-specific factors binding to the TCEd are involved in the control of T cell specific-transcription of the Il-2 gene
