T1000	Negation 987 990	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 987 1100	not the deleted promoter lacking the three consensus binding sites for NF-kappa B located from -571 bp to -459 bp
T1002	Negation 537 540	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 537 572	not PAFR transcript 2 (tissue-type)
T1004	Speculation 1117 1124	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1117 1293	suggest a molecular mechanism of positive regulation of PAFR gene expression by PAF through NF-kappa B, possibly by a phosphorylation reaction involving protein kinase C by PAF
T1006	Negation 1012 1019	lacking
E1003	Negation:T1006 Scope:T1007
T1007	Span 1012 1100	lacking the three consensus binding sites for NF-kappa B located from -571 bp to -459 bp
T1008	Speculation 1221 1229	possibly
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1221 1293	possibly by a phosphorylation reaction involving protein kinase C by PAF
