T1000	Negation 2208 2215	without
E1000	Negation:T1000 Scope:T1001
T1001	Span 2208 2240	without TCR-mediated stimulation
T1002	Negation 2008 2010	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 2008 2049	no obvious sequence homology between them
T1004	Speculation 2078 2084	appear
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2051 2240	The viral trans-activators appear to target specific DNA binding protein such as NF-kB and Sp1 to cis-acting DNA site and promote lymphokine gene expression without TCR-mediated stimulation
