T1000	Speculation 701 714	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 701 902	indicate that the functional activity of ligands built from the binding site of G28-5 is highly dependent upon the size and physical properties of the molecule both in solution and on the cell surfaces
T1002	Negation 396 399	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 396 429	not crosslink CD40-Ig in solution
