T1000	Negation 503 507	lack
E1000	Negation:T1000 Scope:T1001
T1001	Span 503 595	lack of expression of the transcriptional regulatory elements required for T-cell activation
T1002	Speculation 385 393	not been
E1001	Speculation:T1002 Scope:T1003
T1003	Span 385 412	not been clearly elucidated
T1004	Speculation 489 492	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 489 595	may be due to lack of expression of the transcriptional regulatory elements required for T-cell activation
T1006	Speculation 422 434	hypothesized
E1003	Speculation:T1006 Scope:T1007
T1007	Span 422 595	hypothesized that such defects in fetal/neonatal T-cell activation may be due to lack of expression of the transcriptional regulatory elements required for T-cell activation
T1008	Negation 1606 1615	could not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1540 1645	qualitative differences in the capacity to regulate these factors could not be shown in fetal blood cells
