T1000	Negation 1411 1414	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1411 1477	not have low-level constitutive expression of STAT binding factors
T1002	Speculation 913 920	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 913 996	whether the patterns observed correlated with functional differences in these cells
T1004	Negation 1812 1815	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1812 1888	not a precise congruence between PBMC activated in vivo and in vitro by IL-2
