T1000	Speculation 983 990	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 983 1164	suggest that IFN-alpha5 and IFN-beta are produced at low levels in normal tissues and play an important role in the regulation of cell function and in the maintenance of homeostasis
T1002	Speculation 712 722	indicating
E1001	Speculation:T1002 Scope:T1003
T1003	Span 712 807	indicating the presence of endogenous IFN activity equivalent to approximately 0.3 to 0.5 IU/mL
