T1000	Negation 1067 1070	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1067 1124	not to reduced amounts of the other transcription factors
T1002	Speculation 197 200	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 197 265	may be through the modulation of transcription factor binding to DNA
T1004	Speculation 1278 1281	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1278 1330	may be an important molecular site of steroid action
T1006	Speculation 1131 1139	suggests
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1131 1271	suggests that in these cells GR within the nucleus interacts with cytokine-stimulated transcription factors by the process of cross coupling
