T1000	Speculation 917 931	indicated that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 917 983	indicated that regulation predominantly occurred at the mRNA level
T1002	Negation 682 688	unable
E1001	Negation:T1002 Scope:T1003
T1003	Span 682 736	unable to induce sialoadhesin expression by themselves
T1004	Negation 1423 1426	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1423 1456	not by mineralocorticoid receptor
