T1000	Negation 737 743	failed
E1000	Negation:T1000 Scope:T1001
T1001	Span 737 818	failed to protect them from killing mediated by lymphokine-activated killer cells
T1002	Speculation 243 246	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 243 300	may be a critical component in the development of disease
T1004	Speculation 1270 1278	putative
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1270 1329	putative function of BHRF1 in EBV-infected epithelial cells
T1006	Negation 1193 1196	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1193 1266	not interfere with the activation of NF-kappaB-like transcription factors
T1008	Negation 1482 1489	neither
E1004	Negation:T1008 Scope:T1009
T1009	Span 1482 1582	neither BHRF1 nor Bcl-2 in a B-cell line, BJAB, protected the cells from anti-Fas-mediated apoptosis
T1010	Speculation 1330 1333	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1330 1452	may be to protect virus-infected cells from TNF- and/or anti-Fas- induced cell death in order to maximize virus production
T1012	Negation 1496 1499	nor
E1006	Negation:T1012 Scope:T1013
T1013	Span 1496 1582	nor Bcl-2 in a B-cell line, BJAB, protected the cells from anti-Fas-mediated apoptosis
