T1000	Speculation 772 781	suggested
E1000	Speculation:T1000 Scope:T1001
T1001	Span 772 855	suggested that Tat exerts its effect on IL-2 primarily at the transcriptional level
T1002	Speculation 146 149	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 146 200	may play an important role in the pathogenesis of AIDS
T1004	Speculation 1206 1211	might
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1206 1254	might facilitate virus spread from or to T cells
T1006	Negation 941 944	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 941 974	not sufficient for the Tat effect
T1008	Speculation 1272 1277	might
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1272 1435	might contribute to the hypergammaglobulinemia or, together with other cytokines found to be dysregulated, the T-helper cell dysfunctions observed in AIDS patients
