T1000	Speculation 110 118	putative
E1000	Speculation:T1000 Scope:T1001
T1001	Span 110 130	putative NFAT-1 site
T1002	Negation 66 69	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 66 89	not dependent on NFAT-1
T1004	Negation 454 457	nor
E1002	Negation:T1004 Scope:T1005
T1005	Span 454 504	nor is it a cis-acting negative regulatory element
T1006	Negation 339 342	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 309 335	The putative NFAT-1 region
T1008	Speculation 313 321	putative
E1004	Speculation:T1008 Scope:T1009
T1009	Span 313 452	putative NFAT-1 region is not required for the response to anti-CD3 or to mitogens in T-cell, B-cell, or monocyte/macrophage leukemia lines
