T1000	Negation 1155 1158	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1155 1217	not the case when cells were pre-cultured with IL-10 on Teflon
T1002	Negation 931 934	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 931 1019	not the case when PBMC were pre-cultured in plastic multidishes in the presence of IL-10
T1004	Speculation 1709 1711	or
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1670 1741	by red cells in the whole blood assays or by cultures of PBMC on Teflon
T1006	Speculation 1553 1566	indicate that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1553 1741	indicate that the IL-10-induced up-regulation of cytokine production depends on the prevention of monocyte adherence by red cells in the whole blood assays or by cultures of PBMC on Teflon
T1008	Negation 1784 1786	no
E1004	Negation:T1008 Scope:T1009
T1009	Span 1784 1858	no effect on the IL-10-induced modulation of some monocyte surface markers
