T1000	Negation 1485 1488	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1485 1524	not induce any of these three cytokines
T1002	Negation 563 566	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 563 639	not the expression of tumor necrosis factor alpha (TNF-alpha) and IL-6 mRNAs
T1004	Speculation 1938 1945	implies
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1938 1972	implies that development of anti-E
T1006	Speculation 1526 1541	indicating that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1526 1754	indicating that ehrlichial binding is required for IL-1beta mRNA expression and that binding of the immune complex to the Fc gamma receptor is required for TNF-alpha and IL-6 mRNA expression and enhanced IL-1beta mRNA expression
T1008	Speculation 2078 2081	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2078 2170	may play an important role in the pathophysiology of ehrlichiosis and immune responses to it
