T1000	Negation 1654 1657	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1654 1694	not produce a significant level of virus
T1002	Negation 1251 1258	absence
E1001	Negation:T1002 Scope:T1003
T1003	Span 1251 1325	absence of nuclear NF-kappaB activity in these freshly isolated thymocytes
T1004	Speculation 1775 1782	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1775 1977	suggest that in vivo, despite an efficient entry of the virus in all the CD4(+) subpopulations, a high viral load may be generated exclusively within the mature CD4(+) CD8(-) CD3(+) subset of thymocytes
T1006	Speculation 1696 1706	presumably
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1696 1752	presumably because they are unresponsive to TNF and IL-7
T1008	Speculation 2051 2056	might
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2051 2167	might also be present in the intermediate thymocyte compartment, leading to efficient HIV replication in these cells
T1010	Speculation 1889 1892	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1871 1977	a high viral load may be generated exclusively within the mature CD4(+) CD8(-) CD3(+) subset of thymocytes
