T1000	Speculation 932 934	or
E1000	Speculation:T1000 Scope:T1001
T1001	Span 925 942	factor or factors
T1002	Speculation 870 878	possibly
E1001	Speculation:T1002 Scope:T1003
T1003	Span 870 942	possibly through binding to an NF-kappa B-like nuclear factor or factors
T1004	Speculation 1484 1491	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1484 1626	suggest that the HTLV-I enhancer contains multiple functional elements, including binding sites for at least CREB- and NF-kappa B-like factors
T1006	Negation 1262 1271	could not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1262 1294	could not be activated by p40tax
T1008	Speculation 1802 1805	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1754 1841	TPA-dependent activation of the HTLV-I enhancer may be mediated through the C26 element
