T1000	Speculation 398 403	might
E1000	Speculation:T1000 Scope:T1001
T1001	Span 398 431	might regulate calcium signalling
T1002	Speculation 346 355	potential
E1001	Speculation:T1002 Scope:T1003
T1003	Span 346 431	potential cellular homologues of cyclosporin A that might regulate calcium signalling
T1004	Speculation 901 908	appears
E1002	Speculation:T1004 Scope:T1005
T1005	Span 896 975	CAML appears to be a new participant in the calcium-signal transduction pathway
T1006	Negation 1038 1045	absence
E1003	Negation:T1006 Scope:T1007
T1007	Span 1038 1060	absence of cyclosporin
