T1000	Negation 943 946	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 943 958	not IkappaBbeta
T1002	Negation 677 684	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 677 748	without reduction of its nuclear translocation and DNA binding activity
T1004	Negation 1144 1151	neither
E1002	Negation:T1004 Scope:T1005
T1005	Span 1144 1243	neither involved in IkappaB kinase complex activation nor modulated by the addition of homocysteine
T1006	Negation 1044 1051	absence
E1003	Negation:T1006 Scope:T1007
T1007	Span 1044 1102	absence of its transcriptional activity in RAW 264.7 cells
T1008	Speculation 1265 1273	suggests
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1265 1479	suggests that DZA may be a potent drug for the treatment of diseases in which NF-kappaB plays a central pathogenic role, as well as a useful tool for studying the regulation and physiological functions of NF-kappaB
T1010	Negation 1198 1201	nor
E1005	Negation:T1010 Scope:T1011
T1011	Span 1198 1243	nor modulated by the addition of homocysteine
T1012	Speculation 1283 1286	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1283 1479	may be a potent drug for the treatment of diseases in which NF-kappaB plays a central pathogenic role, as well as a useful tool for studying the regulation and physiological functions of NF-kappaB
