T1000	Speculation 478 484	either
E1000	Speculation:T1000 Scope:T1001
T1001	Span 478 505	either a TATA or a CAAT box
T1002	Negation 472 477	lacks
E1001	Negation:T1002 Scope:T1003
T1003	Span 472 501	lacks either a TATA or a CAAT
T1004	Speculation 1479 1492	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1479 1596	indicate that B29 gene expression is controlled by the complex interplay of positive and negative regulatory elements
T1006	Speculation 1137 1144	appears
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1016 1201	A newly identified motif called the B29 conserved sequence (BCS), found upstream of both human and murine B29 promoters, appears to stimulate B29 transcription through a novel mechanism
