T1000	Speculation 1177 1179	or
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1170 1225	by NAC or by a decoy oligodeoxynucleotide for NF-kappaB
T1002	Speculation 259 266	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 259 335	whether this factor is involved in regulating IgE synthesis by human B cells
T1004	Speculation 1630 1633	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1594 1857	coordination of NF-kappaB and STAT6 may be required for induction of germline Cepsilon transcription by IL-4, and that CD40-mediated NF-kappaB activation may be important in regulating both enhancement of germline Cepsilon transcription and class switching to IgE
T1006	Speculation 1581 1588	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1581 1702	suggest that coordination of NF-kappaB and STAT6 may be required for induction of germline Cepsilon transcription by IL-4
T1008	Speculation 1748 1751	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1748 1857	may be important in regulating both enhancement of germline Cepsilon transcription and class switching to IgE
