T1000	Negation 646 649	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 646 931	not unexpected that this versatile cellular homeostatic switch would be affected by a variety of viral pathogens, which have evolved mechanisms to utilize various aspects of Rel/NF-kappa B activity to facilitate their replication, cell survival and possibly evasion of immune responses
T1002	Negation 443 446	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 443 457	not surprising
T1004	Speculation 895 903	possibly
E1002	Speculation:T1004 Scope:T1005
T1005	Span 895 931	possibly evasion of immune responses
T1006	Speculation 709 714	would
E1003	Speculation:T1006 Scope:T1007
T1007	Span 666 931	this versatile cellular homeostatic switch would be affected by a variety of viral pathogens, which have evolved mechanisms to utilize various aspects of Rel/NF-kappa B activity to facilitate their replication, cell survival and possibly evasion of immune responses
