T1000	Negation 349 352	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 349 386	not express AP-1 DNA binding activity
T1002	Negation 272 275	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 224 291	the reason(s) for these functional changes have not been determined
T1004	Negation 623 626	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 623 709	not a decrease in expression of the FOS and JUN proteins that make up the AP-1 complex
T1006	Negation 553 556	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 553 590	not express AP-1 DNA binding activity
T1008	Speculation 1376 1379	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1376 1490	may explain, in part, some of the functional differences observed for alveolar macrophages compared with monocytes
T1010	Speculation 1222 1229	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1222 1357	suggest that the process of differentiation of monocytes into alveolar macrophages is associated with a loss of REF-1 and AP-1 activity
