T1000	Negation 780 783	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 776 803	are not killed by LAK cells
T1002	Negation 238 245	lacking
E1001	Negation:T1002 Scope:T1003
T1003	Span 238 290	lacking capability to form metastatic tumors in vivo
T1004	Speculation 773 775	or
E1002	Speculation:T1004 Scope:T1005
T1005	Span 769 803	are or are not killed by LAK cells
T1006	Speculation 672 675	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 672 803	may provide a tool to improve current protocols of immunotherapy and insights to how tumor cells are or are not killed by LAK cells
