T1000	Negation 1156 1159	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1129 1218	the level of c-jun mRNA is not altered by PHA activation in the absence or presence of EC
T1002	Speculation 250 253	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 250 354	may have important roles in vivo in the pathogenesis of allograft rejection and delayed hypersensitivity
T1004	Negation 1699 1702	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1699 1716	not c-Fos protein
T1006	Negation 1321 1324	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1321 1342	not induce c-fos mRNA
T1008	Speculation 2088 2095	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2088 2274	suggest that changes in the composition of transcription factor AP-1 is a key molecular mechanism for increasing IL-2 transcription and may underlie the phenomenon of costimulation by EC
T1010	Negation 1977 1980	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1912 1994	Levels of other nuclear factors involved in IL-2 regulation were not altered by EC
T1012	Speculation 2224 2227	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 2224 2274	may underlie the phenomenon of costimulation by EC
