T1000	Speculation 746 749	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 736 829	NF-kappaB may be required for human CD34(+) bone marrow cell clonogenic function and survival
T1002	Negation 390 393	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 330 408	a role for NF-kappaB in human CD34(+) bone marrow cells has not been described
T1004	Speculation 1088 1094	should
E1002	Speculation:T1004 Scope:T1005
T1005	Span 986 1121	proposed strategies involving inhibition of NF-kappaB activation as an adjunct to cancer chemotherapy should be approached with caution
T1006	Speculation 973 980	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 973 1121	suggest that proposed strategies involving inhibition of NF-kappaB activation as an adjunct to cancer chemotherapy should be approached with caution
