T1000	Negation 616 619	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 530 635	induction of NF-AT, which has the same signaling requirements as c-Rel induction, was not inhibited by PF
T1002	Speculation 89 97	possible
E1001	Speculation:T1002 Scope:T1003
T1003	Span 89 213	possible clinical use of the methyl xanthine derivative, pentoxifylline (PF), for the treatment of T cell-dependent diseases
T1004	Negation 1010 1013	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 990 1038	c-Rel induction was not blocked by PF in B cells
T1006	Negation 782 785	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 744 794	IL-2R(alpha) chain mRNA induction was not affected
T1008	Speculation 1134 1137	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1134 1197	may prove advantageous in manipulating T cell responses in vivo
