T1000	Speculation 533 538	seems
E1000	Speculation:T1000 Scope:T1001
T1001	Span 504 594	the ubiquitous protein Oct-1 seems to control general octamer site-dependent transcription
T1002	Speculation 436 443	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 376 496	the octamer-binding protein Oct-2A and variants thereof are thought to contribute to the B-cell specific gene expression
T1004	Negation 1728 1731	nor
E1002	Negation:T1004 Scope:T1005
T1005	Span 1728 1802	nor was it repressed upon contransfection with an Oct-2A expression vector
T1006	Negation 1710 1717	neither
E1003	Negation:T1006 Scope:T1007
T1007	Span 1663 1802	a transfected lymphocyte-specific promoter was neither activated nor was it repressed upon contransfection with an Oct-2A expression vector
T1008	Speculation 1817 1826	speculate
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1817 1934	speculate that N-Oct-3 and other N-Oct factors have a specific role in gene expression in cells of the nervous system
