T1000	Negation 1024 1031	lacking
E1000	Negation:T1000 Scope:T1001
T1001	Span 1024 1090	lacking obvious sequence similarity to known transcription factors
T1002	Negation 663 666	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 646 749	transcripts were not detected at significant levels in plasmacytoma, T-cell, and nonlymphoid cell lines
T1004	Speculation 1442 1449	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1442 1528	suggest that EBF represents a novel regulator of B lymphocyte-specific gene expression
T1006	Speculation 1166 1180	indicated that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1166 1231	indicated that the protein interacts with its site as a homodimer
