T1000	Negation 463 466	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 463 482	not sensitive to VD
T1002	Negation 315 318	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 315 354	not sensitive to differentiating agents
T1004	Speculation 1399 1409	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1399 1484	suggesting that the genetic program underlying monocytic differentiation is activated
T1006	Speculation 896 909	indicate that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 896 1032	indicate that ATRA as well as VD efficiently increases the nuclear abundance of VD receptor (VDR) and promotes monocytic differentiation
T1008	Speculation 1615 1628	indicate that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1615 1705	indicate that the M2 leukemic cell context is only permissive of monocytic differentiation
T1010	Speculation 1585 1592	unknown
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1486 1592	The molecular mechanism by which ATRA increases the nuclear abundance of a functional VDR is still unknown
