T1000	Speculation 1765 1778	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1765 1985	indicate that NF-kappaB activation, required for a high level of HIV replication in thymocytes, is regulated in a specific manner in the thymic microenvironment which provides the necessary cytokines: TNF, IL-1, and IL-7
T1002	Negation 796 801	fails
E1001	Negation:T1002 Scope:T1003
T1003	Span 796 814	fails to replicate
