T1000	Speculation 875 883	proposed
E1000	Speculation:T1000 Scope:T1001
T1001	Span 875 1043	proposed that reactivation of latent HIV-1 harbored in chronically infected T lymphocytes, monocytes, or macrophages plays an important role in the pathogenesis of AIDS
T1002	Speculation 536 539	can
E1001	Speculation:T1002 Scope:T1003
T1003	Span 467 663	activation of the T cell lines leading to enhanced HIV-1 replication can be induced by antigens, mitogens, and cytokines (tumor necrosis factor alpha [TNF-alpha], interleukin 1, and interleukin-2)
T1004	Negation 1063 1065	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1063 1155	no drugs or therapy available that can provide protection against HIV-1 latency reactivation
