T1000	Speculation 1107 1115	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1107 1270	suggests a model in which functionally indistinguishable kappa B complexes can be activated via two separate pathways of signal transduction distinguishable by CsA
T1002	Speculation 199 206	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 176 399	Cyclosporin A (CsA) is thought to exert its immunosuppressive effects by inhibiting the expression of a distinct set of lymphokine genes which are induced upon T-cell activation, among them the gene coding for interleukin-2
