T1000	Speculation 910 916	appear
E1000	Speculation:T1000 Scope:T1001
T1001	Span 905 976	that appear to be required for optimal enhancer function and activation
T1002	Speculation 153 156	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 153 299	may include a spectrum of retroviruses with varying potential to infect their host, undergo long periods of latent infection, and induce pathology
T1004	Speculation 1042 1045	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1042 1202	may be subtle differences in the regulation of HIV-1 and HIV-2 expression that may be relevant to the possible longer latency and reduced pathogenicity of HIV-2
T1006	Speculation 1019 1030	speculation
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1019 1202	speculation that there may be subtle differences in the regulation of HIV-1 and HIV-2 expression that may be relevant to the possible longer latency and reduced pathogenicity of HIV-2
T1008	Speculation 1144 1152	possible
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1144 1202	possible longer latency and reduced pathogenicity of HIV-2
T1010	Speculation 1121 1124	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1121 1202	may be relevant to the possible longer latency and reduced pathogenicity of HIV-2
