T1000	Speculation 832 835	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 832 976	may have implications for pathophysiological conditions that involve the upregulation of these molecules (e.g. inflammation and atherosclerosis)
T1002	Speculation 641 654	indicate that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 641 825	indicate that specific tyrosine phosphorylation following PTK activation is involved in the mobilization of the transcription factor, nuclear factor kappa B, and VCAM-1 mRNA expression
