T1000	Speculation 1022 1028	likely
E1000	Speculation:T1000 Scope:T1001
T1001	Span 964 1066	the majority of the Kruppel-related zinc finger genes are likely to be expressed in most human tissues
T1002	Speculation 951 958	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 951 1066	suggest that the majority of the Kruppel-related zinc finger genes are likely to be expressed in most human tissues
T1004	Speculation 1173 1182	potential
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1173 1238	potential regulators of monocyte differentiation or proliferation
T1006	Speculation 1142 1157	indicating that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1142 1238	indicating that they represent potential regulators of monocyte differentiation or proliferation
