T1000	Speculation 1035 1042	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1035 1097	whether there was an up-regulation of nuclear NF-kappaB levels
T1002	Speculation 747 749	if
E1001	Speculation:T1002 Scope:T1003
T1003	Span 747 822	if HCMV binding also resulted in the translation and secretion of cytokines
T1004	Speculation 1615 1624	potential
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1615 1758	potential mechanism whereby HCMV infection of monocytes can result in profound pathogenesis, especially in chronic inflammatory-type conditions
T1006	Speculation 1504 1514	hypothesis
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1504 1758	hypothesis that HCMV initiates a signal transduction pathway that leads to monocyte activation and pinpoints a potential mechanism whereby HCMV infection of monocytes can result in profound pathogenesis, especially in chronic inflammatory-type conditions
T1008	Speculation 1671 1674	can
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1671 1758	can result in profound pathogenesis, especially in chronic inflammatory-type conditions
