T1000	Negation 862 866	lack
E1000	Negation:T1000 Scope:T1001
T1001	Span 862 880	lack of EBNA2 mRNA
T1002	Negation 708 711	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 708 722	not EBNA2 mRNA
T1004	Negation 980 983	nor
E1002	Negation:T1004 Scope:T1005
T1005	Span 980 1036	nor LMP2B mRNA was detected in any of the tumours tested
T1006	Negation 967 974	neither
E1003	Negation:T1006 Scope:T1007
T1007	Span 967 1036	neither LMP1 nor LMP2B mRNA was detected in any of the tumours tested
T1008	Speculation 1239 1249	suggesting
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1239 1316	suggesting that the tumour cells carried EBV genomes in a tightly latent form
T1010	Negation 1201 1204	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1124 1229	BZLF1 mRNA and the product, an immediate-early gene for EBV replication, was not expressed in any of them
