T1000	Speculation 789 795	likely
E1000	Speculation:T1000 Scope:T1001
T1001	Span 782 896	Tap is likely to be an important cellular mediator of Tip function in T cell transformation by herpesvirus saimiri
T1002	Speculation 507 513	likely
E1001	Speculation:T1002 Scope:T1003
T1003	Span 491 637	Aggregation was likely caused by the up-regulated surface expression of adhesion molecules including integrin alpha, L-selectin, ICAM-3, and H-CAM
