T1000	Speculation 1425 1438	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1425 1548	indicate that cepharanthine is a highly potent inhibitor of HIV-1 replication in a chronically infected monocytic cell line
T1002	Negation 1156 1159	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1156 1174	not in ACH-2 cells
T1004	Speculation 1733 1739	should
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1719 1820	cepharanthine should be further pursued for its chemotherapeutic potential in HIV-1-infected patients
