T1000	Speculation 975 985	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 975 1096	suggesting that the activity of upstream PRL response elements may require an interaction with promoter-proximal elements
T1002	Negation 937 943	failed
E1001	Negation:T1002 Scope:T1003
T1003	Span 937 973	failed to respond to PRL stimulation
T1004	Speculation 1574 1581	appears
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1520 1634	the PRL-induced biphasic expression of the IRF-1 gene appears to be controlled by separate PRL-responsive elements
T1006	Speculation 1038 1041	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1038 1096	may require an interaction with promoter-proximal elements
