T1000	Speculation 412 421	potential
E1000	Speculation:T1000 Scope:T1001
T1001	Span 412 465	potential therapeutic drugs for inflammatory diseases
T1002	Speculation 399 408	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 368 465	NF-kappaB inhibitors have been suggested as potential therapeutic drugs for inflammatory diseases
T1004	Speculation 1483 1497	indicated that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1483 1637	indicated that PDTC promoted a transient and rapid shuttling of NFATp and NFATc, leading to their accelerated export from the nucleus of activated T cells
T1006	Speculation 993 1007	indicated that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 993 1259	indicated that pyrrolidine DTC (PDTC) prevented NF-kappaB, and NFAT DNA-binding activity in T cells stimulated with either phorbol myristate acetate plus ionophore or antibodies against the CD3-T-cell receptor complex and simultaneously activated the binding of AP-1
T1008	Speculation 1696 1701	could
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1696 1886	could be responsible for the rapid shuttling of the NFAT, therefore transiently converting the sustained transactivation of this transcription factor that occurs during lymphocyte activation
T1010	Speculation 1642 1649	propose
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1642 1752	propose that the activation of an NFAT kinase by PDTC could be responsible for the rapid shuttling of the NFAT
T1012	Speculation 2050 2059	potential
E1006	Speculation:T1012 Scope:T1013
T1013	Span 2050 2093	potential use of DTCs as immunosuppressants
