T1000	Speculation 889 892	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 889 1097	may be due to the fact that T cells treated with IL-2 contained those located in S + G2/M phases of the cell cycle, whereas the vast majority of T cells treated with IFN-alpha/beta were located in G0/G1 phase
T1002	Negation 776 783	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 776 804	without active proliferation
