T1000	Speculation 237 240	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 237 298	may be related to alterations in signal transduction pathways
T1002	Speculation 148 155	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 148 298	suggest that the poor induction of a T-cell response to human renal cell carcinoma (RCC) may be related to alterations in signal transduction pathways
T1004	Negation 1250 1253	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1250 1335	not detect any RelA in nuclear extracts either before or after stimulation of T cells
T1006	Negation 1171 1174	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1171 1218	not induced in the nucleus following activation
T1008	Speculation 1403 1406	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1403 1467	may impair their capacity to respond normally to various stimuli
