T1000	Speculation 1133 1135	or
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1128 1208	RelB or p65 in transactivation of a reporter plasmid dependent on a kappa B site
T1002	Speculation 614 616	or
E1001	Speculation:T1002 Scope:T1003
T1003	Span 594 632	six full cell cycle or ankyrin repeats
T1004	Speculation 1219 1224	imply
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1219 1299	imply the existence of a complex family of NF-kappa B-like transcription factors
