T1000	Speculation 2301 2304	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 2301 2362	may be required to effect some functions of the viral protein
T1002	Speculation 565 577	not possible
E1001	Speculation:T1002 Scope:T1003
T1003	Span 565 843	not possible to ascertain whether Bcl-2 upregulation was a specific consequence of LMP1 expression or an artifact of the selection procedure whereby rare Bcl-2+ cells already present in the starting population might best be able to tolerate the potentially toxic effects of LMP1
T1004	Speculation 361 370	suggested
E1002	Speculation:T1004 Scope:T1005
T1005	Span 198 454	An ability of the Epstein-Barr virus latent membrane protein LMP1 to enhance the survival of infected B cells through upregulation of the bcl-2 oncogene was first suggested by experiments involving gene transfection and the selection of stable LMP1+ clones
T1006	Speculation 664 666	or
E1003	Speculation:T1006 Scope:T1007
T1007	Span 664 843	or an artifact of the selection procedure whereby rare Bcl-2+ cells already present in the starting population might best be able to tolerate the potentially toxic effects of LMP1
T1008	Speculation 591 598	whether
E1004	Speculation:T1008 Scope:T1009
T1009	Span 591 843	whether Bcl-2 upregulation was a specific consequence of LMP1 expression or an artifact of the selection procedure whereby rare Bcl-2+ cells already present in the starting population might best be able to tolerate the potentially toxic effects of LMP1
T1010	Speculation 810 821	potentially
E1005	Speculation:T1010 Scope:T1011
T1011	Span 810 843	potentially toxic effects of LMP1
T1012	Speculation 775 780	might
E1006	Speculation:T1012 Scope:T1013
T1013	Span 775 843	might best be able to tolerate the potentially toxic effects of LMP1
T1014	Negation 1992 1997	never
E1007	Negation:T1014 Scope:T1015
T1015	Span 1992 2019	never any effect upon Bcl-2
T1016	Negation 1043 1050	absence
E1008	Negation:T1016 Scope:T1017
T1017	Span 1043 1073	absence of selective pressures
T1018	Speculation 2214 2217	may
E1009	Speculation:T1018 Scope:T1019
T1019	Span 2214 2362	may be an essential component of LMP1 signal transduction, other cell-specific factors may be required to effect some functions of the viral protein
T1020	Speculation 2183 2190	suggest
E1010	Speculation:T1020 Scope:T1021
T1021	Span 2183 2271	suggest that whilst NF-kappa B may be an essential component of LMP1 signal transduction
