T1000	Speculation 667 675	possible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 667 749	possible role in the clinical manifestations of advanced infection with this virus
T1002	Speculation 373 382	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 297 428	Pharmacological modification of cytokine dysregulation, therefore, has been suggested as a therapeutic modality for HIV-1 infection
T1004	Speculation 1064 1067	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1064 1130	may prove useful in the treatment of patients with HIV-1 infection
T1006	Speculation 988 995	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 988 1130	suggest that use of this agent in combination with antiretroviral compounds may prove useful in the treatment of patients with HIV-1 infection
