T1000	Negation 1163 1166	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1090 1236	Two of these regions, BR3 and BR4 located at positions -102 to -73, have not previously been described as regulators of IL-5 expression in T cells
T1002	Speculation 1015 1029	indicates that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1015 1088	indicates that the BRs are involved in control of hIL-5 promoter activity
T1004	Speculation 1597 1604	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1597 1772	suggest that Oct1, YY1, and octamer-like factors binding to the -90/-79 sequence within the proximal IL-5 promoter are involved in suppression of IL-5 transcription in T cells
