T1000	Negation 1030 1033	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1030 1052	not the immediate ones
T1002	Negation 930 933	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 930 976	not p65 mRNA whose expression was constitutive
T1004	Speculation 1448 1461	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1448 1650	indicate that the regulation of NF-kappa B activation during T cell activation by TcR/CD3 signals is biphasic: TcR/CD3 triggers its immediate translocation, which is transient if no TNF-alpha is present
T1006	Negation 1627 1629	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1627 1650	no TNF-alpha is present
