T1000	Speculation 382 389	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 382 532	whether and how glucocorticoids affect the function of the inflammatory infiltrate or why the disease persists subclinically despite chronic treatment
T1002	Speculation 372 381	not known
E1001	Speculation:T1002 Scope:T1003
T1003	Span 372 464	not known whether and how glucocorticoids affect the function of the inflammatory infiltrate
T1004	Speculation 1820 1823	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1820 1880	may provide an explanation for the chronicity of the disease
T1006	Speculation 1296 1305	suggested
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1296 1455	suggested that steroid doses currently used in clinical medicine are suboptimal in repressing NFkappaB-mediated cytokine production in the inflammatory lesions
T1008	Speculation 1886 1889	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1886 1959	may identify a novel therapeutic target in this inflammatory vasculopathy
