T1000	Speculation 1217 1229	hypothesised
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1217 1298	hypothesised that NF-kappa B antagonists may offer important therapeutic benefits
T1002	Speculation 800 809	potential
E1001	Speculation:T1002 Scope:T1003
T1003	Span 800 890	potential pathways for cytokine-induced periodontal tissue damage, mediated by NF-kappa B1
T1004	Speculation 1258 1261	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1258 1298	may offer important therapeutic benefits
