T1000	Negation 868 875	absence
E1000	Negation:T1000 Scope:T1001
T1001	Span 868 918	absence of a cloned MIBP1 gene for further studies
T1002	Speculation 786 792	likely
E1001	Speculation:T1002 Scope:T1003
T1003	Span 786 809	likely as a heterodimer
T1004	Speculation 1094 1104	raises the
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1094 1181	raises the possibility that RFX1 may play a dual role in regulating HBV gene expression
T1006	Speculation 923 934	hypothesize
E1003	Speculation:T1006 Scope:T1007
T1007	Span 923 1037	hypothesize that RFX1 acts with MIBP1 to negatively regulate the core promoter activity through the NRE gamma site
T1008	Speculation 1127 1130	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1127 1181	may play a dual role in regulating HBV gene expression
