T1000	Speculation 1208 1215	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1208 1345	suggest that inhibition of NFkappaB activation may provide a molecular approach to increase apoptosis sensitivity in anticancer treatment
T1002	Speculation 296 299	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 296 337	may rescue cells from apoptosis induction
T1004	Speculation 1255 1258	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1255 1345	may provide a molecular approach to increase apoptosis sensitivity in anticancer treatment
