T1000	Speculation 2038 2045	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 2038 2137	suggest that CaM-K II may exert negative influences on cytokine gene transcription in human T cells
T1002	Speculation 714 721	unknown
E1001	Speculation:T1002 Scope:T1003
T1003	Span 685 721	the role of CaM-K II remains unknown
T1004	Speculation 2060 2063	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2060 2137	may exert negative influences on cytokine gene transcription in human T cells
