T1000	Speculation 848 862	indicated that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 848 981	indicated that DOX induced an increased stability of PBGD and GATA-1 mRNAs, whereas ACLA did not affect the half-lives of these mRNAs
T1002	Negation 941 944	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 941 981	not affect the half-lives of these mRNAs
T1004	Negation 1337 1340	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1337 1361	not in DOX-treated cells
T1006	Speculation 1109 1117	suggests
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1109 1259	suggests that transcriptional activation in ACLA-treated cells and mRNA stabilization in DOX-treated cells were dependent on de novo protein synthesis
T1008	Speculation 1435 1443	appeared
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1363 1501	These two anthracyclines, although closely related in their structures, appeared to act as differentiation inducers by distinct mechanisms
