T1000	Speculation 1230 1237	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1230 1343	suggest that selenium supplementation may be used to modulate the expression of NF-kappa B target genes and HIV-1
T1002	Negation 1203 1206	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1153 1217	the activity of the transcription factor AP-1 was not suppressed
T1004	Speculation 1268 1271	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1268 1343	may be used to modulate the expression of NF-kappa B target genes and HIV-1
