T1000	Speculation 680 687	unclear
E1000	Speculation:T1000 Scope:T1001
T1001	Span 566 687	The exact role of these different proteins in directing the tissue-specific expression of immunoglobulin genes is unclear
T1002	Speculation 487 495	possibly
E1001	Speculation:T1002 Scope:T1003
T1003	Span 487 500	possibly more
T1004	Negation 1267 1274	without
E1002	Negation:T1004 Scope:T1005
T1005	Span 1267 1446	without OTF-2, is sufficient for transcription of immunoglobulin genes and that OTF-2 alone is not responsible for the B-cell-specific regulation of immunoglobulin gene expression
T1006	Speculation 1122 1130	appeared
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1116 1231	OFT-1 appeared to have approximately the same transactivation ability as OTF-2 when normalized for binding activity
T1008	Speculation 1247 1254	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1247 1280	suggest that OTF-1, without OTF-2
T1010	Negation 1362 1365	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1362 1446	not responsible for the B-cell-specific regulation of immunoglobulin gene expression
