T1000	Negation 782 791	no longer
E1000	Negation:T1000 Scope:T1001
T1001	Span 782 807	no longer have a silencer
T1002	Negation 64 67	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 64 106	not in memory resting T helper lymphocytes
T1004	Speculation 1387 1393	likely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1387 1505	likely that the presence of a silencer contributes to the more stringent activation requirements of naive CD4+ T cells
T1006	Speculation 834 839	seems
E1003	Speculation:T1006 Scope:T1007
T1007	Span 809 1039	Their IL-2 transcription seems to be controlled solely by the transition from inactive to active functional state of a positive transcription factor binding to these promoter elements as well as its cytoplasmic or nuclear location
