T1000	Negation 723 726	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 723 747	not in nonlymphoid cells
T1002	Speculation 138 145	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 138 323	whether enhancer elements in addition to the highly conserved octamer (OCTA)-nucleotide motif are important for lymphoid-specific expression of the immunoglobulin heavy-chain (IgH) gene
T1004	Negation 1213 1215	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1213 1233	no enhancer activity
T1006	Negation 1065 1070	lacks
E1003	Negation:T1006 Scope:T1007
T1007	Span 1065 1096	lacks the binding site for OCTA
T1008	Speculation 1380 1387	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1380 1576	suggest that the microB element is a new crucial element important for lymphoid-specific expression of the IgH gene but that interaction with another enhancer element is essential for its activity
