T1000	Speculation 1803 1810	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1803 1896	suggest that its activity may be controlled by a complex interplay of cis-regulatory elements
T1002	Negation 1292 1295	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1276 1305	this PU box was not conserved
T1004	Speculation 1829 1832	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1829 1896	may be controlled by a complex interplay of cis-regulatory elements
