T1000	Speculation 1662 1675	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1662 1914	indicate that STAT1 plays a pivotal role in the differentiation/maturation process of monocytes as an early transcription factor initially activated by adherence and then able to modulate the expression of functional genes, such as ICAM-1 and FcgammaRI
T1002	Negation 367 370	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 367 387	not been yet defined
