T1000	Negation 677 684	without
E1000	Negation:T1000 Scope:T1001
T1001	Span 677 703	without anti-CD18 antibody
T1002	Speculation 257 264	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 257 369	whether dexamethasone directly suppresses adhesion by inhibiting activation of nuclear factor kappa B (NFkappaB)
T1004	Speculation 2009 2012	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2009 2081	may be due in part to the suppression of NFkappaB entry into the nucleus
