T1000	Negation 529 534	never
E1000	Negation:T1000 Scope:T1001
T1001	Span 519 559	which has never been reported previously
T1002	Speculation 362 368	likely
E1001	Speculation:T1002 Scope:T1003
T1003	Span 362 488	likely corresponds to the well documented typical junB mRNA, stimulated in response to numerous growth factors, including IL-6
T1004	Negation 1320 1323	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1320 1349	not the second junB mRNA peak
T1006	Negation 1188 1194	failed
E1003	Negation:T1006 Scope:T1007
T1007	Span 1188 1228	failed to affect the early-induced burst
T1008	Speculation 1556 1569	indicate that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1556 1687	indicate that, in 7TD1 cells, IL-6 controls junB transcription in a biphasic fashion by means of two separate transduction pathways
T1010	Negation 1489 1492	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1489 1532	not affect the expression of the first peak
