T1000	Speculation 605 612	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 605 713	whether different cellular factors were involved in E3 regulation in lymphocytes as compared with HeLa cells
T1002	Negation 321 324	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 240 338	the cellular factors that regulate adenoviral gene expression in lymphocytes has not been reported
T1004	Negation 1702 1713	rather than
E1002	Negation:T1004 Scope:T1005
T1005	Span 1702 1791	rather than their position in the E3 promoter was critical for regulating gene expression
T1006	Negation 911 914	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 911 928	not HeLa extracts
T1008	Speculation 1650 1664	indicated that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1650 1747	indicated that the primary sequence of these motifs rather than their position in the E3 promoter
