T1000	Speculation 1540 1548	possible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1540 1633	possible role of 5-hydroxyeicosatetraenoic acid as a regulator of arachidonic acid liberation
T1002	Negation 936 938	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 936 982	no effect on any of the membrane phospholipids
T1004	Speculation 1758 1765	perhaps
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1758 1805	perhaps acting at the level of phospholipase A2
