T1000	Speculation 868 876	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 868 1012	suggests that genital tract infection with G. vaginalis increases the risk of HIV transmission by increasing HIV expression in the genital tract
T1002	Speculation 760 770	indicating
E1001	Speculation:T1002 Scope:T1003
T1003	Span 760 817	indicating an effect by G. vaginalis on HIV transcription
T1004	Speculation 1019 1022	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1019 1105	may explain, at least in part, the increased rate of HIV transmission in women with BV
