T1000	Speculation 991 998	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 991 1136	suggest that PPARgamma activation may play a role in monocyte differentiation and function analogous to its well-characterized role in adipocytes
T1002	Speculation 666 669	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 666 795	may play a role in the induction of differentiation of macrophages to foam cells that are associated with atherosclerotic lesions
T1004	Speculation 1025 1028	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1025 1136	may play a role in monocyte differentiation and function analogous to its well-characterized role in adipocytes
