T1000	Speculation 667 677	presumably
E1000	Speculation:T1000 Scope:T1001
T1001	Span 667 725	presumably through RBP-Jkappa response elements within DNA
T1002	Negation 497 504	lacking
E1001	Negation:T1002 Scope:T1003
T1003	Span 497 557	lacking a major portion of the extracellular domain (DeltaE)
T1004	Negation 1413 1416	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1413 1472	not essential for oncogenesis or transcriptional activation
T1006	Negation 1206 1209	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1025 1266	a second, stronger RBP-Jkappa-binding site, which lies within the intracellular domain close to the transmembrane region and significantly augments association with RBP-Jkappa, was not needed for oncogenesis or for transcriptional activation
T1008	Speculation 1368 1378	suggesting
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1368 1472	suggesting that intranuclear localization is not essential for oncogenesis or transcriptional activation
