T1000	Speculation 394 397	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 394 454	may differentially regulate expression of endothelial ICAM-1
T1002	Speculation 327 339	hypothesized
E1001	Speculation:T1002 Scope:T1003
T1003	Span 327 454	hypothesized that combinations of hypoxia and inflammatory stimuli may differentially regulate expression of endothelial ICAM-1
T1004	Negation 642 645	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 642 659	not induce ICAM-1
T1006	Negation 523 530	absence
E1003	Negation:T1006 Scope:T1007
T1007	Span 523 564	absence of added lipopolysaccharide (LPS)
