T1000	Negation 1132 1139	absence
E1000	Negation:T1000 Scope:T1001
T1001	Span 1132 1158	absence of transactivators
T1002	Speculation 748 751	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 748 830	may employ a gene activation pathway with some common and some distinct components
T1004	Speculation 1227 1235	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1227 1391	suggests that the element that responds to CMV transactivation in human CD4+ lymphocytes is either a diffuse one or located downstream of the HIV-2 enhancer element
T1006	Speculation 1093 1099	appear
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1053 1158	A significant proportion of transcripts appear to terminate prematurely in the absence of transactivators
T1008	Speculation 1319 1325	either
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1319 1391	either a diffuse one or located downstream of the HIV-2 enhancer element
