T1000	Speculation 1014 1024	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1014 1160	suggesting that protein-protein interactions might functionally coordinate the actions of the upstream and downstream positive regulatory elements
T1002	Speculation 85 94	potential
E1001	Speculation:T1002 Scope:T1003
T1003	Span 85 180	potential role of physical interactions between Elf-1, HMG-I(Y), and NF-kappa B family proteins
T1004	Speculation 1059 1064	might
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1059 1160	might functionally coordinate the actions of the upstream and downstream positive regulatory elements
