T1000	Speculation 1483 1496	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1483 1680	indicate that TNFalpha induces a delayed ROS-dependent signalling pathway that is required for NF-kappaB transcriptional activation and is separable from that required for its nuclear translocation
T1002	Negation 1301 1303	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 1301 1337	no effect on inducible Rel A binding
