T1000	Speculation 847 854	propose
E1000	Speculation:T1000 Scope:T1001
T1001	Span 847 975	propose the common pathway as the simplest way of accounting for the common requirements and properties of the signaling pathway
T1002	Negation 726 729	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 726 737	not Jurkat)
T1004	Speculation 1641 1648	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1641 1828	suggest that intracellular redox status controls NF-kappa B activation by regulating tyrosine phosphorylation event(s) within the common step of the NF-kappa B signal transduction pathway
T1006	Negation 1165 1168	n't
E1003	Negation:T1006 Scope:T1007
T1007	Span 1165 1189	n't activate NF-kappa B)
