T1000	Speculation 680 689	suggested
E1000	Speculation:T1000 Scope:T1001
T1001	Span 680 743	suggested a less important role in the rapid production of IL-8
T1002	Negation 552 555	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 552 584	not NF-IL-6 DNA binding activity
T1004	Speculation 1426 1433	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1426 1599	suggest that NF-kappaB activation is required for C5a-induced IL-8 gene expression and that this response is mediated primarily through a pertussis toxin-insensitive pathway
