T1000	Speculation 888 893	could
E1000	Speculation:T1000 Scope:T1001
T1001	Span 855 965	Lack of full activation of NF-AT could be correlated to a dramatically reduced capacity to induce calcium flux
T1002	Negation 587 594	Whereas
E1001	Negation:T1002 Scope:T1003
T1003	Span 587 758	Whereas different anti-CD4 mAb or HIV-1 gp120 could all trigger activation of the protein tyrosine kinases p56lck and p59fyn and phosphorylation of the Shc adaptor protein
T1004	Speculation 970 975	could
E1002	Speculation:T1004 Scope:T1005
T1005	Span 970 1016	could be complemented with a calcium ionophore
