T1000	Speculation 1389 1392	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1389 1487	may have important ramifications in T cell development by upregulating NF-kappa B1 gene expression
T1002	Speculation 1299 1312	indicate that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1299 1487	indicate that transcriptional synergy mediated by activation of both Egr-1 and NF-kappa B may have important ramifications in T cell development by upregulating NF-kappa B1 gene expression
