T1000	Speculation 649 656	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 649 785	whether the acquisition of antitumor function during ex vivo activation is associated with modifications in signal transduction capacity
T1002	Negation 611 613	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 611 634	no therapeutic activity
T1004	Speculation 1725 1738	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1725 1923	indicate that the recovery of proteins mediating signal transduction through the T cell receptor/CD3 complex in LN T cells activated ex vivo was associated with the acquisition of antitumor function
