T1000	Negation 814 816	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 814 855	no induction of NF-KB factor was detected
T1002	Negation 543 546	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 543 588	not retinoic acid treatment of the U937 cells
T1004	Speculation 909 919	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 909 975	suggesting that this factor was not required for viral replication
T1006	Negation 941 944	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 941 975	not required for viral replication
T1008	Speculation 1038 1043	could
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1038 1123	could mimic some differentiation/activation stimuli allowing nuclear NF-KB expression
T1010	Speculation 991 1004	indicate that
E1005	Speculation:T1010 Scope:T1011
T1011	Span 991 1123	indicate that in monocytic cell lineage, HIV-1 could mimic some differentiation/activation stimuli allowing nuclear NF-KB expression
