T1000	Negation 743 748	lacks
E1000	Negation:T1000 Scope:T1001
T1001	Span 743 801	lacks the 190 C-terminal amino acids of p70I kappa B gamma
T1002	Negation 558 563	lacks
E1001	Negation:T1002 Scope:T1003
T1003	Span 558 609	lacks 59 amino acids C-terminal to ankyrin repeat 7
T1004	Speculation 1463 1471	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1463 1600	suggests that alternative RNA splicing may be used to generate I kappa B gamma isoforms that respond differently to intracellular signals
T1006	Negation 1314 1321	absence
E1003	Negation:T1006 Scope:T1007
T1007	Span 1314 1462	absence in I kappa B gamma-1 and I kappa B gamma-2 of a protein kinase A site whose phosphorylation modulates p70I kappa B gamma inhibitory activity
T1008	Speculation 1502 1505	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1477 1600	alternative RNA splicing may be used to generate I kappa B gamma isoforms that respond differently to intracellular signals
