T1000	Speculation 575 589	indicated that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 575 703	indicated that the apoptosis induced by bufalin in U937 cells was significantly inhibited by overexpression of the Bcl-2 protein
T1002	Negation 563 566	The
E1001	Negation:T1002 Scope:T1003
T1003	Span 563 703	The results indicated that the apoptosis induced by bufalin in U937 cells was significantly inhibited by overexpression of the Bcl-2 protein
T1004	Speculation 1130 1143	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1130 1203	indicate that Bcl-2 acts downstream of MAPK kinase-1 but upstream of MAPK
T1006	Negation 705 707	No
E1003	Negation:T1006 Scope:T1007
T1007	Span 705 852	No significant difference was detected in the activation of MAPK kinase-1 that is induced by bufalin in wild-type or Bcl-2-overexpressed U937 cells
T1008	Speculation 1344 1347	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1344 1414	may be down-regulated through the inhibition of MAPK activity by Bcl-2
T1010	Speculation 1208 1215	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1208 1414	suggest that, in the signaling pathway of the apoptotic process induced by bufalin, the transcriptional activity of activator protein-1 may be down-regulated through the inhibition of MAPK activity by Bcl-2
