T1000	Speculation 1309 1324	indicating that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1309 1411	indicating that ML-9's induction of expression of differentiation-associated phenotypes was reversible
T1002	Negation 461 464	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 461 529	not of myeloblastic leukemic ML-1 cell or erythroleukemia K562 cells
T1004	Negation 1913 1916	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1913 1969	not affect the expression of these oncogenes appreciably
T1006	Negation 1578 1580	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1578 1619	no effect on the morphology of U937 cells
T1008	Speculation 2429 2436	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2429 2520	suggest that ML-9 should be useful for studying the mechanisms of monocytic differentiation
T1010	Negation 2298 2301	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 2298 2338	not induce differentiation of U937 cells
T1012	Speculation 2447 2453	should
E1006	Speculation:T1012 Scope:T1013
T1013	Span 2447 2520	should be useful for studying the mechanisms of monocytic differentiation
