T1000	Negation 890 893	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 890 941	not the result of a global TCR/CD3-signaling defect
T1002	Negation 160 163	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 160 223	not produce IL-2 when challenged with Ag-pulsed accessory cells
T1004	Speculation 1193 1200	appears
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1159 1326	defective IL-2 gene transcription appears to be due, at least in part, to a selective block in the expression of the AP-1 Fos and Jun family members in anergic T cells
