T1000	Negation 1131 1134	nor
E1000	Negation:T1000 Scope:T1001
T1001	Span 1131 1250	nor the translocation of nuclear factor NF-kappa B to the nucleus in macrophages activated by 15 min of LPS stimulation
T1002	Negation 1046 1053	neither
E1001	Negation:T1002 Scope:T1003
T1003	Span 1046 1250	neither the lipopolysaccharide (LPS)-induced increases in the expression of TNF mRNA nor the translocation of nuclear factor NF-kappa B to the nucleus in macrophages activated by 15 min of LPS stimulation
T1004	Speculation 1252 1267	indicating that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1252 1360	indicating that CNI-1493 does not interfere with early NF-kappa B-mediated transcriptional regulation of TNF
T1006	Negation 1282 1285	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1282 1360	not interfere with early NF-kappa B-mediated transcriptional regulation of TNF
T1008	Speculation 1895 1901	should
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1895 1993	should provide insight into the regulation of macrophage activation and mechanisms of inflammation
