T1000	Speculation 364 371	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 364 438	whether fibrinogen triggers activation of NF-kappa B transcription factors
T1002	Speculation 188 197	not fully
E1001	Speculation:T1002 Scope:T1003
T1003	Span 169 208	the mechanisms are not fully understood
T1004	Speculation 1587 1590	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1587 1762	may contribute to mononuclear phagocyte activation by signaling through CD11b/CD18, resulting in selective activation of transcriptional regulatory factors, including NF-kappa
T1006	Negation 895 898	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 895 958	not SP1 or cAMP response element-binding protein (CREB) factors
