T1000	Negation 445 448	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 445 491	not by its inactive analog methylthiogliotoxin
T1002	Speculation 119 130	potentially
E1001	Speculation:T1002 Scope:T1003
T1003	Span 119 146	potentially tissue-damaging
T1004	Negation 1423 1425	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1423 1446	no pro-apoptotic effect
T1006	Speculation 1150 1153	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1150 1266	may underlie the ability of TNF-alpha to delay apoptosis at later times (12-24 h) and limit its early killing effect
T1008	Speculation 1474 1477	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1474 1581	may regulate the production of protein(s) which protect neutrophils from the cytotoxic effects of TNF-alpha
T1010	Speculation 1448 1458	suggesting
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1448 1581	suggesting that NF-kappaB may regulate the production of protein(s) which protect neutrophils from the cytotoxic effects of TNF-alpha
T1012	Speculation 1708 1721	indicate that
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1708 1844	indicate that the transcription factor NF-kappaB plays a crucial role in regulating the physiological cell death pathway in granulocytes
