T1000	Speculation 613 616	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 613 695	may be dependent on different routes on nuclear signalling employed by the factors
T1002	Speculation 521 528	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 521 695	suggest that differences in functional responses elicited in monocytes by all three factors may be dependent on different routes on nuclear signalling employed by the factors
