T1000	Speculation 330 336	appear
E1000	Speculation:T1000 Scope:T1001
T1001	Span 314 375	GM-CSF does not appear to be essential for normal hemopoiesis
T1002	Negation 326 329	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 314 375	GM-CSF does not appear to be essential for normal hemopoiesis
T1004	Speculation 817 826	potential
E1002	Speculation:T1004 Scope:T1005
T1005	Span 817 868	potential tool to inhibit GM-CSF gene transcription
T1006	Speculation 594 601	appears
E1003	Speculation:T1006 Scope:T1007
T1007	Span 510 714	An NF-kappaB/Rel binding site within the GM-CSF promoter, termed the kappaB element appears to be important for controlling expression in reporter gene assays in response to a number of stimuli in T cells
T1008	Speculation 1895 1898	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1895 1992	may have potential therapeutic application in cases of undesirable overexpression of this protein
T1010	Negation 1598 1601	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1598 1652	not affect interleukin 3 mRNA levels in the same cells
T1012	Speculation 1904 1913	potential
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1904 1992	potential therapeutic application in cases of undesirable overexpression of this protein
