T1000	Speculation 512 520	putative
E1000	Speculation:T1000 Scope:T1001
T1001	Span 512 538	putative AML1-binding site
T1002	Speculation 461 470	potential
E1001	Speculation:T1002 Scope:T1003
T1003	Span 461 489	potential AML1-binding sites
T1004	Speculation 1374 1381	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1374 1466	suggest that AML1 is an important factor for regulating a critical B cell-specific gene, blk
