T1000	Speculation 399 409	hypothesis
E1000	Speculation:T1000 Scope:T1001
T1001	Span 399 494	hypothesis that the nuclear factor of activated T cells (NF-AT) may influence HIV-1 replication
T1002	Speculation 356 359	can
E1001	Speculation:T1002 Scope:T1003
T1003	Span 356 393	can be critical for HIV-1 replication
T1004	Speculation 463 466	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 463 494	may influence HIV-1 replication
