T1000	Speculation 1001 1004	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1001 1099	may be important in disease progression induced by opportunistic infections directly or indirectly
T1002	Speculation 934 937	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 934 996	may have fundamental implications in AIDS pathogenesis in vivo
T1004	Speculation 1086 1088	or
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1077 1121	directly or indirectly involving macrophages
