T1000	Speculation 721 727	likely
E1000	Speculation:T1000 Scope:T1001
T1001	Span 721 783	likely to represent the GATA-1 foci seen by immunofluorescence
T1002	Negation 527 530	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 527 634	not represent sites of active transcription or binding of GATA-1 to consensus sites in the beta-globin loci
T1004	Speculation 1281 1289	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1281 1395	suggests a protein-protein interaction with other components of the nuclear bodies via the GATA zinc finger domain
T1006	Negation 879 881	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 879 1033	no co-localization with nuclear antigens involved in RNA processing or other ubiquitous (Spl, c-Jun and TBP) or haemopoietic (NF-E2) transcription factors
