T1000	Speculation 312 315	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 312 425	may inhibit activation of the transcription factor nuclear factor-kappaB (NF-kappaB) through an unknown mechanism
T1002	Speculation 292 300	suggests
E1001	Speculation:T1002 Scope:T1003
T1003	Span 292 425	suggests that IL-10 may inhibit activation of the transcription factor nuclear factor-kappaB (NF-kappaB) through an unknown mechanism
T1004	Speculation 596 608	hypothesized
E1002	Speculation:T1004 Scope:T1005
T1005	Span 596 733	hypothesized that IL-10 prevents human monocyte NF-kappaB activation and resultant TNF-alpha production by stabilization of IkappaB-alpha
T1006	Speculation 408 415	unknown
E1003	Speculation:T1006 Scope:T1007
T1007	Span 408 425	unknown mechanism
T1008	Speculation 1703 1710	appears
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1697 1833	IL-10 appears to prevent activation of NF-kappaB by preserving IkappaB-alpha protein levels, leading to a reduction in TNF-alpha release
T1010	Negation 1030 1037	without
E1005	Negation:T1010 Scope:T1011
T1011	Span 1030 1060	without human IL-10 (10 ng/mL)
