T1000	Negation 696 698	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 696 783	no corresponding up-regulation of these cell surface molecules was seen in CD8+ T cells
T1002	Negation 541 547	failed
E1001	Negation:T1002 Scope:T1003
T1003	Span 541 558	failed to respond
T1004	Negation 1355 1357	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1355 1417	no induction of AP-1 was seen in A6H costimulated CD8+ T cells
T1006	Negation 1220 1222	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1220 1340	no increase in NF-kappa B and octamer-binding (Oct) proteins was seen compared to T cells stimulated with anti-CD3 alone
T1008	Speculation 1666 1669	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1666 1714	may exist in CD4+ and CD8+ T cell subpopulations
T1010	Speculation 1433 1441	suggests
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1433 1553	suggests that both proximal steps in CD8+ T-cell activation as well as the later phases are unresponsive to A6H ligation
