T1000	Negation 1108 1110	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 1108 1128	no inhibitory effect
T1002	Negation 976 985	Pertussis
E1001	Negation:T1002 Scope:T1003
T1003	Span 976 1128	Pertussis toxin treatment markedly decreased kappaB binding activities induced by both C5a and C3a, whereas cholera toxin displayed no inhibitory effect
T1004	Speculation 1250 1259	potential
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1250 1397	potential role of the anaphylatoxins C5a and C3a in regulating leukocytes gene expression through G protein-coupled transcription factor activation
T1006	Speculation 1242 1247	imply
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1242 1397	imply a potential role of the anaphylatoxins C5a and C3a in regulating leukocytes gene expression through G protein-coupled transcription factor activation
