T1000	Speculation 1084 1090	appear
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1078 1291	which appear to differ with respect to DNA binding activity and partition selectively between nuclear matrix and nonmatrix compartments, consistent with the role of the nuclear matrix in regulating gene expression
T1002	Negation 668 671	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 668 687	not with ATF4/CREB2
