T1000	Negation 719 726	without
E1000	Negation:T1000 Scope:T1001
T1001	Span 719 807	without the antioxidants pyrrolidine dithiocarbamate (PDTC) or N-acetyl-L-cysteine (NAC)
T1002	Speculation 358 368	hypothesis
E1001	Speculation:T1002 Scope:T1003
T1003	Span 358 636	hypothesis that low shear-induced activation of NF-kappaB is responsible for enhanced expression of vascular cell adhesion molecule (VCAM-1) resulting in augmented endothelial cell-monocyte (EC-Mn) adhesion and that this activation is dependent on intracellular oxidant activity
T1004	Speculation 1343 1346	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1277 1374	pathways mediating low shear- and cytokine-induced EC-Mn adhesion may be differentially regulated
T1006	Speculation 1189 1196	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1189 1374	suggest that NF-kappaB plays a key role in low shear-induced VCAM-1 expression and that pathways mediating low shear- and cytokine-induced EC-Mn adhesion may be differentially regulated
