T1000	Speculation 1125 1134	potential
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1125 1210	potential role of distal promoter sequences in regulating collagenase-1 transcription
T1002	Speculation 965 979	indicated that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 965 1077	indicated that functional Jun and Fos proteins were present in nuclear extracts of PMA-differentiated U937 cells
T1004	Speculation 1464 1471	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1464 1587	suggest that distinct regulatory elements, acting somewhat independently of each other, control expression of collagenase-1
T1006	Speculation 1279 1288	suggested
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1279 1449	suggested a role for CCAAT/enhancer-binding protein-beta (C/EBP-beta) binding site between -2010 and -1954 in regulating transcription of collagenase-1 in monocytic cells
T1008	Speculation 1611 1619	suggests
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1611 1816	suggests that the rapid PMA-mediated induction of collagenase-1 transcription is controlled by a mechanism distinct from that regulating the sustained expression of this proteinase in activated macrophages
