T1000	Speculation 789 792	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 789 908	may be due to different effects of anti-inflammatory agents on adhesion molecule and Hsp expression in EC, respectively
T1002	Speculation 219 222	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 180 298	the earliest stages of atherosclerosis may be mediated by an autoimmune reaction against heat shock protein 60 (Hsp60)
T1004	Negation 1690 1693	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1690 1789	not suppress tumor necrosis factor-alpha (TNF-alpha)-induced adhesion molecule expression on HUVECs
T1006	Negation 1446 1454	With the
E1003	Negation:T1006 Scope:T1007
T1007	Span 1446 1480	With the exception of indomethacin
T1008	Negation 2172 2178	except
E1004	Negation:T1008 Scope:T1009
T1009	Span 2172 2192	except indomethacin)
T1010	Negation 2025 2028	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 2025 2032	not CyA
T1012	Speculation 2642 2645	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 2642 2928	may be due to its potential as an inducer of Hsp60 expression and its inability to down-regulate adhesion molecule expression on EC; and (3) that down-regulation of MCP-1 expression by aspirin may result in decreased recruitment of monocytes into the arterial intima beneath stressed EC
T1014	Speculation 2498 2501	may
E1007	Speculation:T1014 Scope:T1015
T1015	Span 2498 2579	may be due to the prevention of the adhesion of sensitized T cells to stressed EC
T1016	Speculation 2835 2838	may
E1008	Speculation:T1016 Scope:T1017
T1017	Span 2835 2928	may result in decreased recruitment of monocytes into the arterial intima beneath stressed EC
