T1000	Negation 1227 1230	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1227 1247	not linear templates
T1002	Negation 1049 1055	lacked
E1001	Negation:T1002 Scope:T1003
T1003	Span 1049 1065	lacked the Y box
T1004	Speculation 1326 1328	or
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1318 1363	lacking or disrupting the X consensus element
T1006	Negation 1318 1325	lacking
E1003	Negation:T1006 Scope:T1007
T1007	Span 1318 1456	lacking or disrupting the X consensus element that reflect effects of random replacement of X box sequences in transient expression assays
T1008	Speculation 1527 1535	suggests
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1527 1700	suggests that, despite its demonstrated importance in the DRA promoter, the DRA "octamer" does not utilize OTF-2 in a manner analogous to immunoglobulin promoters in B cells
T1010	Negation 1622 1625	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1622 1700	not utilize OTF-2 in a manner analogous to immunoglobulin promoters in B cells
