T1000	Negation 436 439	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 436 448	not by FK506
T1002	Negation 310 313	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 310 349	not by its structural analog, rapamycin
T1004	Speculation 1229 1232	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1181 1334	The drug concentrations required for antagonism may be explained by the relative affinity of the drugs to, and by the abundance of, the immunophilin FKBP
T1006	Speculation 508 519	raising the
E1003	Speculation:T1006 Scope:T1007
T1007	Span 508 615	raising the possibility that both act by means of a common immunophilin (immunosuppressant binding protein)
T1008	Negation 1608 1611	nor
E1004	Negation:T1008 Scope:T1009
T1009	Span 1608 1718	nor inhibition of rotamase activity of FKBP alone is sufficient to explain the biologic actions of these drugs
T1010	Negation 1587 1594	Neither
E1005	Negation:T1010 Scope:T1011
T1011	Span 1587 1718	Neither FKBP binding nor inhibition of rotamase activity of FKBP alone is sufficient to explain the biologic actions of these drugs
T1012	Speculation 1743 1750	suggest
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1743 1912	suggest that immunophilin bound to FK506 interferes with antigen receptor-induced signals, while rapamycin bound to the immunophilin interferes with IL-2-induced signals
