T1000	Speculation 587 590	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 587 676	may play key roles for the proliferation and differentiation of hematopoietic progenitors
T1002	Speculation 286 293	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 252 353	The pleiotropic effects of RA are thought to be mediated through specific nuclear RA receptors (RARs)
T1004	Speculation 1253 1260	thought
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1248 1334	were thought to be blocked at the promyelocytic stage in their myeloid differentiation
T1006	Speculation 703 710	unknown
E1003	Speculation:T1006 Scope:T1007
T1007	Span 703 790	unknown how RA and RARs are involved in regulating normal hematopoietic differentiation
T1008	Speculation 1820 1823	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1820 1925	may serve as a model for studying the the essential genes for differentiation of normal bone marrow cells
T1010	Speculation 1600 1607	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1600 1792	suggest that an overexpression of RAR alpha alone is effective to suppress myeloid cell differentiation and RAR alpha plays a crucial role in the terminal differentiation of myeloid precursors
