T1000	Speculation 600 609	suggested
E1000	Speculation:T1000 Scope:T1001
T1001	Span 600 680	suggested that significant E2A protein expression is restricted to B-lymphocytes
T1002	Negation 440 443	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 381 464	the abundance, distribution, and form of Pan proteins have not been clearly defined
T1004	Speculation 1393 1403	postulated
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1393 1504	postulated that pituitary endocrine cells and pancreatic endocrine beta-cells share identical Pan/E2A complexes
T1006	Negation 1345 1348	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1345 1370	not contain Pan molecules
