T1000	Speculation 834 841	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 834 922	suggest that this regulatory switch contributes to controlling entry into the cell cycle
T1002	Speculation 408 417	not clear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 408 488	not clear at which point in cell cycle the peripheral B lymphocytes are arrested
T1004	Speculation 1092 1102	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1092 1195	suggesting that, after infection, EBV exploits the normal program of B-lymphocyte cell cycle activation
