T1000	Negation 703 712	could not
E1000	Negation:T1000 Scope:T1001
T1001	Span 692 725	NF-kappa B could not be activated
T1002	Negation 629 632	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 629 686	not undergo signal-induced phosphorylation or degradation
T1004	Speculation 741 748	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 741 854	suggest that phosphorylation at one or both of these residues is critical for activation of NF-kappa B. 
