T1000	Speculation 932 940	appeared
E1000	Speculation:T1000 Scope:T1001
T1001	Span 919 975	two of which appeared to be important for gene induction
T1002	Speculation 640 648	appeared
E1001	Speculation:T1002 Scope:T1003
T1003	Span 622 747	The enhancer also appeared to mediate phorbol myristate acetate induction in monocytes and IL-1 responsiveness in fibroblasts
T1004	Negation 1437 1440	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1437 1484	not normally competent for IL-1 beta expression
T1006	Speculation 1047 1049	or
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1039 1059	similar or identical
T1008	Speculation 1630 1640	suggesting
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1630 1725	suggesting the existence of a proIL-1 beta promoter-proximal requirement for tissue specificity
