T1000	Negation 978 981	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 978 1029	not in primary cases of acute myelogenous leukaemia
T1002	Speculation 760 770	raises the
E1001	Speculation:T1002 Scope:T1003
T1003	Span 760 838	raises the possibility of cis-activation by the t(9;22)(q34;q11) translocation
T1004	Speculation 1125 1128	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1125 1192	may prove useful as a marker of CML for monitoring residual disease
T1006	Speculation 1099 1108	not known
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1031 1108	The role of hLH-2 in the development or progression of leukaemia is not known
