T1000	Negation 736 743	absence
E1000	Negation:T1000 Scope:T1001
T1001	Span 736 768	absence of any cellular stimulus
T1002	Speculation 321 328	unclear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 288 328	the underlying mechanism remains unclear
T1004	Negation 1107 1110	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1107 1147	not that from TNF-alpha-stimulated cells
T1006	Negation 896 899	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 770 1021	This action of the phosphatase inhibitors, which is associated with the activation of the RelA.p50 NF-kappa B heterodimer, is not affected by agents that block the induction of I kappa B alpha phosphorylation by tumor necrosis factor alpha (TNF-alpha)
T1008	Negation 1606 1609	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1606 1619	not identical
T1010	Speculation 1181 1191	suggesting
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1181 1323	suggesting the existence of fundamental differences in the phosphorylation of I kappa B alpha induced by the two different NF-kappa B inducers
T1012	Speculation 1812 1815	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1812 1883	may serve to target I kappa B alpha for proteasome-mediated degradation
T1014	Speculation 1685 1692	suggest
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1685 1883	suggest that phosphorylation of I kappa B alpha, mediated through both the TNF-alpha-inducible and the PP-2A-opposing kinases, may serve to target I kappa B alpha for proteasome-mediated degradation
