T1000	Speculation 913 919	likely
E1000	Speculation:T1000 Scope:T1001
T1001	Span 881 1034	the phosphorylation of TRAF2 is likely to play an important role in regulating signaling by virtue of its ability to influence the CD40-TRAF2 interaction
T1002	Speculation 306 313	appears
E1001	Speculation:T1002 Scope:T1003
T1003	Span 286 405	The phosphorylation appears to be related to the signaling events that are activated by TRAF2 under these circumstances
