T1000	Negation 1315 1321	unable
E1000	Negation:T1000 Scope:T1001
T1001	Span 1275 1378	two mutants, IEXC29S and IEXL320G, were unable to significantly transactivate the c-sis/PDGF-B promoter
T1002	Speculation 409 417	possible
E1001	Speculation:T1002 Scope:T1003
T1003	Span 409 492	possible mechanism of cellular transformation by human T-cell leukemia virus type 1
T1004	Negation 1580 1586	unable
E1002	Negation:T1004 Scope:T1005
T1005	Span 1558 1616	Tax mutant IEXC29S is unable to interact with NGFI-A/Egr-1
