T1000	Speculation 668 683	indicating that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 668 724	indicating that PU.1 can block erythroid differentiation
T1002	Negation 230 233	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 194 244	the precise mechanisms involved are not understood
T1004	Speculation 1651 1654	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1651 1754	may be a crucial determinant governing processes of normal differentiation and malignant transformation
T1006	Speculation 1560 1573	indicate that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1560 1754	indicate that the stoichiometry of directly interacting but opposing transcription factors may be a crucial determinant governing processes of normal differentiation and malignant transformation
