T1000	Speculation 1682 1689	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1649 1742	Negative selection in the cortex appears to be a suicidal inversion of antigen responsiveness
T1002	Negation 1744 1754	instead of
E1001	Negation:T1002 Scope:T1003
T1003	Span 1744 1781	instead of turning on IL-2 expression
T1004	Speculation 1953 1955	It
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1953 2114	It is interesting that in humans and rats, cortical thymocytes undergoing negative selection can still induce IL-2R alpha expression and even be rescued in vitro
T1006	Negation 1886 1889	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1830 1904	The genes that need to be induced for this response are not yet identified
T1008	Speculation 2290 2293	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2290 2323	may be uncommonly Bcl-2 deficient
T1010	Speculation 2274 2276	or
E1005	Speculation:T1010 Scope:T1011
T1011	Span 2204 2323	because they shut off IL-2R beta chain expression at an earlier stage or because they may be uncommonly Bcl-2 deficient
T1012	Speculation 299 302	can
E1006	Speculation:T1012 Scope:T1013
T1013	Span 299 345	can occur to some extent outside of the thymus
T1014	Speculation 196 203	appears
E1007	Speculation:T1014 Scope:T1015
T1015	Span 190 286	which appears to be correlated with programming of at least some response genes for inducibility
T1016	Negation 700 703	not
E1008	Negation:T1016 Scope:T1017
T1017	Span 700 709	not known
T1018	Speculation 397 411	indicates that
E1009	Speculation:T1018 Scope:T1019
T1019	Span 397 487	indicates that the thymus is by far the most potent site for inducing the expansion per se
T1020	Speculation 792 795	may
E1010	Speculation:T1020 Scope:T1021
T1021	Span 792 921	may not always take place at a developmental stage strictly equivalent to the rearrangement of TCR beta in the alpha beta lineage
T1022	Speculation 714 719	seems
E1011	Speculation:T1022 Scope:T1023
T1023	Span 714 921	seems that the rearrangement of the TCR gamma loci in the gamma delta lineage may not always take place at a developmental stage strictly equivalent to the rearrangement of TCR beta in the alpha beta lineage
T1024	Speculation 1202 1210	probably
E1012	Speculation:T1024 Scope:T1025
T1025	Span 1202 1258	probably caused by alterations at the level of signaling
T1026	Speculation 933 942	not clear
E1013	Speculation:T1026 Scope:T1027
T1027	Span 933 982	not clear just how early the two lineages diverge
T1028	Negation 1576 1583	neither
E1014	Negation:T1028 Scope:T1029
T1029	Span 1576 1647	neither is exactly the same phenomenon that occurs in the thymic cortex
T1030	Speculation 1264 1267	may
E1015	Speculation:T1030 Scope:T1031
T1031	Span 1264 1350	may be a manifestation of the physiological state that is a precondition for selection
