T1000	Negation 1198 1201	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1198 1213	not glutathione
T1002	Speculation 177 187	hypothesis
E1001	Speculation:T1002 Scope:T1003
T1003	Span 177 398	hypothesis that cellular activation events occurring in T lymphocytes and monocytes and mediated through translocation of the transcription factor NF-kappa B are dependent upon the constitutive redox status of these cells
T1004	Speculation 1431 1440	could not
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1431 1479	could not by itself induce NF-kappa B activation
T1006	Negation 1431 1440	could not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1437 1479	not by itself induce NF-kappa B activation
T1008	Speculation 1500 1507	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1500 1615	suggest that TNF and PMA do not lead to NF-kappa B activation through induction of changes in the cell redox status
T1010	Negation 1528 1531	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1528 1615	not lead to NF-kappa B activation through induction of changes in the cell redox status
T1012	Speculation 1802 1809	appears
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1802 1982	appears that a basal redox equilibrium tending toward oxidation is a prerequisite for full activation of transduction pathways regulating the activity of NF-kappa B-dependent genes
