T1000	Negation 654 661	neither
E1000	Negation:T1000 Scope:T1001
T1001	Span 654 780	neither to segregation of human autosome 11, on which the CD5 gene has been mapped, nor to deletion of the CD5 structural gene
T1002	Negation 623 627	lack
E1001	Negation:T1002 Scope:T1003
T1003	Span 623 645	lack of CD5 expression
T1004	Negation 738 741	nor
E1002	Negation:T1004 Scope:T1005
T1005	Span 738 780	nor to deletion of the CD5 structural gene
