T1000	Negation 1113 1115	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 1113 1214	no phosphorylation of Elk-1 fusion protein occurred using lysates from CD19 cross-linked BLIN-1 cells
T1002	Speculation 603 610	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 603 789	whether phosphorylation of Elk-1, activation of activator protein-1 (AP-1), or activation of nuclear factor-kappaB (NF-kappaB) transcription factors occurred following CD19 cross-linking
T1004	Negation 1709 1711	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1709 1752	no apparent effect on AP-1-binding activity
T1006	Negation 1425 1428	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1381 1437	constitutive NF-kappaB-binding activity was not enhanced
T1008	Speculation 1902 1905	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1902 1974	may culminate in the activation or suppression of distinct sets of genes
T1010	Speculation 1765 1772	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1765 1974	suggest that CD19-mediated signal transduction activates different transcription factors at juxtaposed stages of B cell development that may culminate in the activation or suppression of distinct sets of genes
