T1000	Negation 1127 1133	lacked
E1000	Negation:T1000 Scope:T1001
T1001	Span 1127 1181	lacked detectable CD14 cell surface or mRNA expression
T1002	Speculation 787 802	indicating that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 787 859	indicating that the induction was dependent on ongoing protein synthesis
T1004	Speculation 1406 1409	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1406 1564	may have important implications for the regulation of certain immune and inflammatory responses through their inverse effects on CD14 and CD23 gene expression
T1006	Speculation 1330 1337	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1330 1564	suggest that there exists a functional antagonism between VitD3 and RA that may have important implications for the regulation of certain immune and inflammatory responses through their inverse effects on CD14 and CD23 gene expression
