T1000	Negation 1225 1227	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 1225 1294	no inducible NOS was detected in either tolerant or nontolerant cells
T1002	Negation 997 1000	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 997 1030	not after the first A/R challenge
T1004	Negation 1567 1570	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1567 1641	not effect the hyperadhesion response induced by the initial A/R challenge
T1006	Speculation 1312 1326	indicated that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1312 1519	indicated that inhibition of GTP-cyclohydrolase I (an enzyme involved in de novo synthesis of an important cofactor for NOS activity, tetrahydrobiopterin) prevented the generation of NO in A/R-tolerant cells
T1008	Speculation 2180 2186	likely
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2180 2246	likely by reducing the intracellular oxidant stress induced by A/R
T1010	Negation 1699 1702	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1699 1725	not in A/R-tolerant HUVECs
