T1000	Negation 460 463	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 411 481	the rate-limiting step in peripheral T cells has not been demonstrated
T1002	Negation 42 45	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 42 70	not tyrosine kinase activity
T1004	Negation 742 749	without
E1002	Negation:T1004 Scope:T1005
T1005	Span 742 765	without a second signal
T1006	Negation 715 721	unable
E1003	Negation:T1006 Scope:T1007
T1007	Span 712 765	is unable to activate T cells without a second signal
T1008	Negation 1485 1488	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1485 1570	not with gross levels of tyrosine kinase activity induced late following the response
