T1000	Speculation 1381 1388	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1381 1536	suggest that a so-far-unrecognized SP-1 site in the human IL-1beta promoter may participate in the transcriptional regulation of this gene in keratinocytes
T1002	Speculation 846 848	or
E1001	Speculation:T1002 Scope:T1003
T1003	Span 820 874	transcription factor SP-1 or a closely related protein
T1004	Speculation 1457 1460	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1457 1536	may participate in the transcriptional regulation of this gene in keratinocytes
