T1000	Speculation 1382 1389	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1377 1479	that appears to be required for the T-cell-receptor-mediated trans activation of HIV-2 gene expression
T1002	Speculation 428 431	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 428 468	may be more prolonged than that of HIV-1
T1004	Speculation 1585 1588	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1585 1671	may also have implications for the design of therapeutic approaches to HIV-2 infection
T1006	Speculation 1495 1498	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1495 1580	may explain differences in the clinical spectra of diseases caused by HIV-1 and HIV-2
