T1000	Negation 942 945	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 942 999	not decrease significantly between day 7 and day 14 cells
T1002	Speculation 846 856	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 846 907	suggesting an association of SCL with erythroid proliferation
T1004	Speculation 1536 1544	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1536 1628	suggests one mechanism through which Steel factor may enhance normal erythroid proliferation
T1006	Speculation 1001 1011	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1001 1112	suggesting that posttranscriptional mechanisms are largely responsible for the decrease in SCL protein observed
T1008	Speculation 1759 1769	suggesting
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1759 1888	suggesting that posttranscriptional mechanisms may also be important in the increase in SCL protein observed in response to Steel
T1010	Speculation 1586 1589	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1586 1628	may enhance normal erythroid proliferation
T1012	Speculation 1806 1809	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1806 1888	may also be important in the increase in SCL protein observed in response to Steel
