T1000	Speculation 1004 1011	propose
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1004 1092	propose that this factor may have a role in pathophysiology of chronic myeloid leukaemia
T1002	Negation 30 34	lack
E1001	Negation:T1002 Scope:T1003
T1003	Span 30 107	lack a 47 kDa factor having affinity for a genomic sterol regulatory sequence
T1004	Speculation 1029 1032	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1029 1092	may have a role in pathophysiology of chronic myeloid leukaemia
