T1000	Speculation 767 774	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 767 918	suggest that TAFII105 is a cell type-specific subunit of TFIID that may be responsible for mediating transcription by a subset of activators in B cells
T1002	Negation 288 291	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 288 350	not found associated with TFIID isolated from other cell types
T1004	Speculation 835 838	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 835 918	may be responsible for mediating transcription by a subset of activators in B cells
