T1000	Speculation 612 617	might
E1000	Speculation:T1000 Scope:T1001
T1001	Span 569 712	expression of c-jun, jun B and jun D genes might be involved in terminal granulocyte differentiation or in regulating granulocyte functionality
T1002	Speculation 556 563	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 556 712	suggest that expression of c-jun, jun B and jun D genes might be involved in terminal granulocyte differentiation or in regulating granulocyte functionality
T1004	Speculation 670 672	or
E1002	Speculation:T1004 Scope:T1005
T1005	Span 630 712	in terminal granulocyte differentiation or in regulating granulocyte functionality
