T1000	Negation 877 880	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 858 909	CD4 molecules were not required for the suppression
T1002	Negation 627 630	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 627 715	not suppress the cell growth of IL-2-independent cell lines (Hut102, Molt-4, and Jurkat)
T1004	Negation 1172 1179	Neither
E1002	Negation:T1004 Scope:T1005
T1005	Span 1172 1284	Neither chromatin condensation nor DNA fragmentation was detected in Kit225 cells cultured with V3-BH10 and IL-2
T1006	Speculation 842 857	indicating that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 842 909	indicating that CD4 molecules were not required for the suppression
T1008	Negation 1294 1301	neither
E1004	Negation:T1008 Scope:T1009
T1009	Span 1294 1500	neither blocked radiolabeled IL-2 binding to IL-2 receptors nor affected tyrosyl phosphorylation of several cellular proteins (p120, p98, p96, p54, and p38), which is immediately induced by IL-2 stimulation
T1010	Negation 1203 1206	nor
E1005	Negation:T1010 Scope:T1011
T1011	Span 1203 1284	nor DNA fragmentation was detected in Kit225 cells cultured with V3-BH10 and IL-2
T1012	Negation 1570 1573	not
E1006	Negation:T1012 Scope:T1013
T1013	Span 1570 1587	not c-myc or junB
T1014	Negation 1354 1357	nor
E1007	Negation:T1014 Scope:T1015
T1015	Span 1354 1500	nor affected tyrosyl phosphorylation of several cellular proteins (p120, p98, p96, p54, and p38), which is immediately induced by IL-2 stimulation
T1016	Speculation 1659 1666	appears
E1008	Speculation:T1016 Scope:T1017
T1017	Span 1595 1767	the binding of V3 loop of gp120 to the cell surface molecule(s) appears to affect intracellular IL-2 signaling, which leads to the suppression of IL-2-induced T cell growth
