T1000	Speculation 1064 1079	indicating that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1064 1199	indicating that increased IP-10 mRNA induction was not due to the augmented ability of the cells to respond to the presence of IFNgamma
T1002	Negation 1115 1118	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1115 1199	not due to the augmented ability of the cells to respond to the presence of IFNgamma
T1004	Speculation 1536 1539	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1536 1589	may determine the IP-10 mRNA inducibility by IFNgamma
T1006	Speculation 1497 1507	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1497 1589	suggesting that these nuclear proteins may determine the IP-10 mRNA inducibility by IFNgamma
