T1000	Negation 1225 1228	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1188 1316	this mutated NF kappa B promoter was not transactivated during HHV-6(GS) infection or after cotransfection with pZVB70 or pZVB10
T1002	Negation 518 525	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 518 547	without antigenic stimulation
T1004	Speculation 1518 1521	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1518 1636	may consequently increase HIV replication, leading to an increase in the cytopathic effect on coinfected human T cells
T1006	Speculation 1329 1342	indicate that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1329 1448	indicate that the NF kappa B sites of the HIV promoter are essential for its transactivation during HHV-6(GS) infection
