T1000	Speculation 1118 1127	suggested
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1118 1267	suggested that PGE2-mediated activation effect on HIV-1 transcription was transduced via both NF-kappaB-dependent and -independent signaling pathways
T1002	Speculation 923 938	indicating that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 923 1055	indicating that signal transduction pathways induced by PGE2 necessitate the participation of cyclic AMP, protein kinase A, and Ca2+
T1004	Speculation 1743 1750	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1743 1960	suggest that secretion of PGE2 by macrophages in response to infection or inflammatory activators could induce signaling events resulting in activation of proviral DNA present into T cells latently infected with HIV-1
T1006	Speculation 1583 1597	indicated that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1583 1727	indicated that PGE2 modulation of HIV-1 LTR-driven reporter gene activity in studied T lymphoid cells is transduced via the EP4 receptor subtype
T1008	Speculation 1841 1846	could
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1841 1960	could induce signaling events resulting in activation of proviral DNA present into T cells latently infected with HIV-1
