T1000	Negation 385 388	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 320 399	the events leading from the activated receptor to cell lysis are not understood
T1002	Speculation 172 175	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 172 269	may account for the therapeutic effects of glucocorticoids in various diseases including leukemia
T1004	Negation 904 907	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 904 931	not target site specificity
T1006	Speculation 414 424	hypothesis
E1003	Speculation:T1006 Scope:T1007
T1007	Span 414 498	hypothesis postulates induction of so-called 'lysis genes' by the activated receptor
T1008	Speculation 1139 1144	could
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1139 1232	could be mediated by interference with other transcription factors required for cell survival
T1010	Negation 1112 1123	rather than
E1005	Negation:T1010 Scope:T1011
T1011	Span 1112 1134	rather than activation
