T1000	Negation 1473 1476	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1439 1614	These effects of PI 3-kinase were not mediated by previously identified PI 3-kinase effectors, such as protein kinase B, a positive regulator of PI 3-kinase, or the GTPase Rac
T1002	Negation 1018 1021	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 897 1079	Certain aspects of TCR responses such as the induction of transcriptional activity of AP1 and serum response factor were not affected by expression of the mutant forms of PI 3-kinase
T1004	Speculation 1634 1640	likely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1620 1694	are therefore likely to involve a novel, as yet unknown, effector molecule
