T1000	Negation 1311 1314	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1311 1349	not include the cluster of c-Myb sites
T1002	Negation 133 136	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 133 153	not of c-Myb or PU.1
T1004	Speculation 1943 1956	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1943 2121	indicate that DNA methylation, chromatin structure, and transactivation at an Sp1 site contribute to the highly restricted expression of this myelomonocytic lineage specific gene
T1006	Negation 1639 1642	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1639 1656	not the PU.1 site
