T1000	Speculation 769 778	suggested
E1000	Speculation:T1000 Scope:T1001
T1001	Span 769 901	suggested that the NF-kappaB pathway was essential for IL-2-independent growth of CTLL-2 cells while the CRE pathway was unnecessary
T1002	Speculation 227 234	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 200 282	Tax, the viral protein, is thought to be crucial in the development of the disease
T1004	Speculation 1111 1118	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1111 1274	suggest that Tax plays a crucial role in IL-2-independent T-cell transformation induced by HTLV-1, in addition to its well-known IL-2-dependent cell transformation
