T1000	Speculation 483 490	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 483 563	whether monocyte TF expression is affected by treatment with cyclosporin A (CsA)
T1002	Speculation 404 411	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 404 474	whether monocyte TF activation occurs in cardiac transplant recipients
T1004	Speculation 1921 1926	might
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1921 2048	might be useful in managing further settings of vascular pathology also known to involve TF expression and NF-kappaB activation
T1006	Speculation 1849 1852	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1849 1916	may contribute to its successful use in cardiac transplant medicine
