T1000	Negation 1293 1296	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1293 1349	not related to the inhibition of cyclooxygenase activity
T1002	Speculation 981 989	appeared
E1001	Speculation:T1002 Scope:T1003
T1003	Span 973 1021	Aspirin appeared to prevent VCAM-1 transcription
T1004	Speculation 1409 1416	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1409 1649	suggest that aspirin inhibits NF-kappa B mobilization, induction of VCAM-1 and E-selectin, and subsequent monocyte adhesion in endothelial cells stimulated by TNF, thereby providing an additional mechanism for therapeutic effects of aspirin
