T1000	Negation 849 852	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 849 894	not accompanied by measurable IL-2 production
T1002	Negation 584 591	absence
E1001	Negation:T1002 Scope:T1003
T1003	Span 584 614	absence of antigenic challenge
T1004	Negation 1173 1180	without
E1002	Negation:T1004 Scope:T1005
T1005	Span 1173 1194	without CD28 ligation
T1006	Negation 1082 1085	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1082 1091	not NF-AT
T1008	Speculation 1705 1712	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1705 1954	suggest that in activated normal T cells, CD28-derived signals can stimulate proliferation at least in part via NF-kappaB and AP-1 generation, and that this response uses both acidic sphingomyelinase and phosphatidylinositol 3-kinase-linked pathways
T1010	Negation 1525 1528	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1525 1587	not to the phosphatidylinositol 3-kinase inhibitor, wortmannin
