T1000	Speculation 311 314	not
E1000	Speculation:T1000 Scope:T1001
T1001	Span 311 330	not been elucidated
T1002	Speculation 161 169	putative
E1001	Speculation:T1002 Scope:T1003
T1003	Span 161 305	putative factors that couple the signal transduction from surface receptors to the activation of cytokine synthesis in natural killer (NK) cells
T1004	Speculation 1318 1331	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1318 1421	indicate that NK cell activation early after CD16 ligand binding involves primarily, if not exclusively
T1006	Negation 982 985	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 982 1019	not require de novo protein synthesis
T1008	Negation 1571 1574	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1571 1603	not express NFATc constitutively
T1010	Speculation 1403 1409	if not
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1403 1557	if not exclusively, NFATp, and Western blot analysis shows that this has the same electrophoretic mobility (approximately 120 kD) as that of T lymphocytes
T1012	Negation 1793 1795	no
E1006	Negation:T1012 Scope:T1013
T1013	Span 1793 2043	no detectable NFATc protein in nuclear and cytoplasmic extracts from CD16- or phorbol ester-stimulated cells at any time tested, up to 4 h. These results provide the first direct evidence that both CsA-sensitive transcription factors, NFATp and NFATc
