T1000	Speculation 552 559	thought
E1000	Speculation:T1000 Scope:T1001
T1001	Span 549 593	is thought to be subject to redox regulation
T1002	Speculation 311 320	uncertain
E1001	Speculation:T1002 Scope:T1003
T1003	Span 281 320	The initiating event is still uncertain
T1004	Speculation 684 689	could
E1002	Speculation:T1004 Scope:T1005
T1005	Span 684 722	could be a target for redox regulation
T1006	Speculation 621 628	whether
E1003	Speculation:T1006 Scope:T1007
T1007	Span 621 722	whether the activation of the IL-1RI-associated protein kinase could be a target for redox regulation
T1008	Speculation 769 774	could
E1004	Speculation:T1008 Scope:T1009
T1009	Span 769 820	could influence IL-1-mediated NF-kappa B activation
T1010	Speculation 727 734	whether
E1005	Speculation:T1010 Scope:T1011
T1011	Span 727 820	whether an altered activity of the kinase could influence IL-1-mediated NF-kappa B activation
T1012	Negation 1262 1265	not
E1006	Negation:T1012 Scope:T1013
T1013	Span 1262 1281	not show any effect
T1014	Negation 883 890	without
E1007	Negation:T1014 Scope:T1015
T1015	Span 883 973	without pretreatment with different compounds known to influence the cellular redox status
