T1000	Negation 1247 1250	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1247 1275	not induce catalase activity
T1002	Negation 922 925	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 922 950	not induce catalase activity
T1004	Speculation 1033 1044	potentially
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1033 1131	potentially serve as a marker of exposure to oxidative stress and its effects on human lymphocytes
