T1000	Negation 1007 1009	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 1007 1055	no additional effect on the DNA-binding capacity
T1002	Negation 915 922	absence
E1001	Negation:T1002 Scope:T1003
T1003	Span 915 940	absence of glucocorticoid
T1004	Speculation 1635 1641	either
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1635 1722	either due to blockage of DNA-receptor complex formation or disruption of the complexes
T1006	Negation 1107 1109	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1107 1121	no activation)
T1008	Speculation 2375 2388	indicate that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2375 2607	indicate that hGR synthesized in rabbit reticulocyte lysates displays many of the same properties, including GRE-specific DNA binding, observed for glucocorticoid receptor present in cytosolic extracts of mammalian cells and tissues
T1010	Negation 2201 2207	unable
E1005	Negation:T1010 Scope:T1011
T1011	Span 2201 2281	unable to compete for mouse mammary tumor virus-long terminal repeat DNA binding
T1012	Speculation 2669 2676	suggest
E1006	Speculation:T1012 Scope:T1013
T1013	Span 2669 2774	suggest that the antiglucocorticoid properties of RU486 do not occur at the level of specific DNA binding
T1014	Negation 2728 2731	not
E1007	Negation:T1014 Scope:T1015
T1015	Span 2728 2774	not occur at the level of specific DNA binding
