T1000	Negation 1585 1588	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1585 1625	not the kappaB-mutated, HIV-1 LTR region
T1002	Speculation 365 372	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 365 597	whether the mycobacterial cell wall component mannose-capped lipoarabinomannan (ManLAM) of Mycobacterium tuberculosis (M. tuberculosis) could activate transcription of HIV-1 in T cells with the use of an in vitro cell culture system
T1004	Speculation 1872 1877	could
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1872 1950	could thus have the potential to influence the pathogenesis of HIV-1 infection
T1006	Speculation 1796 1803	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1796 1950	suggest that M. tuberculosis can upregulate HIV-1 expression in T cells and could thus have the potential to influence the pathogenesis of HIV-1 infection
