T1000	Speculation 320 334	indicated that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 320 431	indicated that the defect in this cell line influences the activity of an isotype-specific transcription factor
T1002	Negation 276 283	absence
E1001	Negation:T1002 Scope:T1003
T1003	Span 276 301	absence of HLA-DR and -DP
T1004	Negation 811 814	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 811 849	not the DQB-W region or the DQB Y-box)
T1006	Speculation 503 517	indicated that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 503 633	indicated that the affected factor operates via cis-elements located between -141 base pairs and the transcription initiation site
T1008	Speculation 1469 1476	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1469 1655	suggest that the divergent X2-box of the class II major histocompatibility complex promoters plays an important role in influencing differential expression of the human class II isotypes
T1010	Negation 1183 1191	Moreover
E1005	Negation:T1010 Scope:T1011
T1011	Span 1183 1314	Moreover, replacement of the DQB X2-box with the DRA X2-box markedly diminished the activity of the DQB promoter in the mutant cell
