T1000	Speculation 649 655	either
E1000	Speculation:T1000 Scope:T1001
T1001	Span 649 681	either the pi or the microB site
T1002	Speculation 631 634	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 631 681	may interact with either the pi or the microB site
T1004	Speculation 1914 1921	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1914 1997	suggest that ERP might play a role in B-cell development and in IgH gene regulation
T1006	Speculation 1533 1543	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1533 1589	suggesting a carboxy-terminal negative regulatory domain
T1008	Speculation 1931 1936	might
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1931 1997	might play a role in B-cell development and in IgH gene regulation
