T1000	Speculation 1121 1127	either
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1121 1184	either independent or only partially dependent on MEK1 and MEK2
T1002	Speculation 1071 1080	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1071 1184	suggested that the activation of MAPK by Tpl-2 is either independent or only partially dependent on MEK1 and MEK2
T1004	Speculation 1709 1719	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1709 1847	suggesting that the Tpl-2-mediated NFAT activation is under the control of a combination of calcineurin-dependent and independent pathways
T1006	Speculation 1204 1213	suggested
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1204 1351	suggested that the activation of the IL-2 promoter is under the control of not only NFAT but also a second factor whose activation is MEK-dependent
