T1000	Speculation 1146 1156	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1146 1214	suggesting a link between estrogenic pathways and cell proliferation
T1002	Speculation 464 478	indicated that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 464 611	indicated that a 50% decrease in VDR levels was associated with a 2-fold increase in cell proliferation and a similar rise in c-myc mRNA expression
T1004	Speculation 1242 1256	indicated that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1242 1368	indicated that there was no significant change in 17beta-HSD IV or DNA-PK(CS) mRNA levels following treatment with 1,25(OH)2D3
T1006	Negation 1267 1269	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1267 1445	no significant change in 17beta-HSD IV or DNA-PK(CS) mRNA levels following treatment with 1,25(OH)2D3, although expression of both genes varied with changes in cell proliferation
T1008	Speculation 1552 1555	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1552 1614	may influence gene expression by ligand-independent mechanisms
T1010	Speculation 1458 1465	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1458 1614	suggest that, in addition to its established role as a hormone-dependent trans-activator, VDR may influence gene expression by ligand-independent mechanisms
