T1000	Speculation 770 775	might
E1000	Speculation:T1000 Scope:T1001
T1001	Span 770 876	might result in overexpression of the gene, amplifying Th2 cell differentiation and class switching to IgE
T1002	Speculation 284 291	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 281 379	is thought to be controlled by a major susceptibility gene and multiple minor susceptibility genes
T1004	Speculation 1684 1687	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1684 1739	may provide a clue for genetic predisposition for atopy
T1006	Speculation 1239 1246	appears
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1119 1361	A nucleotide substitution within a recently described OAP40 element located just upstream of an NF-AT site (P sequence) appears to be largely responsible for the increased promotor strength of this particular allelic form of the IL-4 promoter
