T1000	Speculation 1243 1255	hypothesized
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1201 1330	An autocrine mechanism of growth could be hypothesized only for the 2 patients whose cells expressed both the M-CSF and FMS genes
T1002	Speculation 655 664	potential
E1001	Speculation:T1002 Scope:T1003
T1003	Span 655 760	potential role of the expression of these genes in the maintenance and expansion of the neoplastic clones
T1004	Negation 1507 1510	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1419 1565	deregulation of genes encoding for certain hemopoietic growth factors or receptors does not seem to represent a major mechanism of MDS progression
T1006	Negation 1332 1334	No
E1003	Negation:T1006 Scope:T1007
T1007	Span 1332 1411	No germline changes or rearrangements were observed in any of the genes studied
T1008	Speculation 1511 1515	seem
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1419 1565	deregulation of genes encoding for certain hemopoietic growth factors or receptors does not seem to represent a major mechanism of MDS progression
