T1000	Speculation 1642 1645	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1642 1665	may vary with cell type
T1002	Speculation 500 507	unknown
E1001	Speculation:T1002 Scope:T1003
T1003	Span 373 507	The mechanisms by which beta-catenin undergoes this shift in location and participates in activation of gene transcription are unknown
T1004	Negation 92 95	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 92 140	not sufficient for activation of gene expression
T1006	Negation 777 780	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 777 785	not axin
T1008	Speculation 621 624	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 618 653	it may also be exported from nuclei
T1010	Speculation 856 859	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 853 907	it may not be efficiently sequestered in the cytoplasm
T1012	Negation 860 863	not
E1006	Negation:T1012 Scope:T1013
T1013	Span 860 907	not be efficiently sequestered in the cytoplasm
T1014	Negation 1329 1332	not
E1007	Negation:T1014 Scope:T1015
T1015	Span 1329 1377	not sufficient for activation of gene expression
T1016	Negation 1209 1212	not
E1008	Negation:T1016 Scope:T1017
T1017	Span 1209 1236	not in normal T lymphocytes
T1018	Speculation 1548 1555	suggest
E1009	Speculation:T1018 Scope:T1019
T1019	Span 1548 1665	suggest that a third component is necessary for gene activation and that this third component may vary with cell type
T1020	Negation 1472 1475	not
E1010	Negation:T1020 Scope:T1021
T1021	Span 1472 1519	not activation by the transcription factor VP16
