T1000	Speculation 224 231	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 224 306	whether NF-kappa B acts as a messenger system for germline C epsilon transcription
T1002	Speculation 212 223	not evident
E1001	Speculation:T1002 Scope:T1003
T1003	Span 212 306	not evident whether NF-kappa B acts as a messenger system for germline C epsilon transcription
T1004	Speculation 1193 1206	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1193 1322	indicate that IL-4 and ligation of CD40 induce NF-kappa B expression via at least a mechanism dependent on the PI3-kinase pathway
T1006	Speculation 963 965	or
E1003	Speculation:T1006 Scope:T1007
T1007	Span 942 983	IL-4, anti-CD40 mAb, or their combination
T1008	Speculation 1368 1371	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1368 1430	may play a role in regulating germline C epsilon transcription
T1010	Speculation 1327 1334	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1327 1430	suggest that NF-kappa B sensitive to NAC may play a role in regulating germline C epsilon transcription
