T1000	Speculation 664 678	indicated that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 664 797	indicated that deletion of upstream NF-kappa B site (-533 bases from translation start site) had no effect on thrombin responsiveness
T1002	Negation 761 763	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 761 1029	no effect on thrombin responsiveness, whereas mutation/deletion of downstream NF-kappa B site (-223 bases from the translation start site) prevented the activation of ICAM-1 promoter, indicating that the downstream NF-kappa B site is critical for thrombin inducibility
T1004	Speculation 1295 1310	indicating that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1295 1371	indicating that activation of NF-kappa B was essential for thrombin response
T1006	Speculation 945 960	indicating that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 945 1029	indicating that the downstream NF-kappa B site is critical for thrombin inducibility
T1008	Speculation 1723 1736	indicate that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1723 1958	indicate that thrombin activates endothelial ICAM-1 expression and polymorphonuclear leukocyte adhesion by NF-kappa Bp65 binding to the downstream NF-kappa B site of ICAM-1 promoter after proteolytically activated receptor-1 activation
