T1000	Speculation 994 997	can
E1000	Speculation:T1000 Scope:T1001
T1001	Span 994 1016	can be quite different
T1002	Negation 566 569	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 542 655	NF-kappa B activity was not detected in the nucleus following long-term expression of Tax in Jurkat T lymphocytes
T1004	Speculation 1214 1220	should
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1214 1328	should be useful for the delineation of signaling pathways utilized in the selective regulation of gene expression
T1006	Speculation 1082 1087	might
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1082 1181	might involve cell-type-specific suppression, as opposed to activation, of distinct signal pathways
