T1000	Negation 1242 1245	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1242 1356	not contain other NF-kappaB proteins (p52, c-Rel, Rel B), AP-1 proteins (c-Fos, C-Jun), CREB or C/EBPbeta (NF-IL6)
T1002	Speculation 685 692	appears
E1001	Speculation:T1002 Scope:T1003
T1003	Span 650 749	the region between -3134 and -3059 appears to be required for the induction of transcription by LPS
T1004	Speculation 1507 1521	indicated that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1507 1659	indicated that two NF-kappaB-binding sites, which are located between -3134 and -3059, are critical for the activation of proIL-1beta gene transcription
T1006	Speculation 1148 1157	suggested
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1148 1356	suggested that both binding complexes contained the NF-kappaB components p50 and p65, and did not contain other NF-kappaB proteins (p52, c-Rel, Rel B), AP-1 proteins (c-Fos, C-Jun), CREB or C/EBPbeta (NF-IL6)
