T1000	Negation 1286 1289	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1286 1302	not T-cell lines
T1002	Negation 104 107	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 104 118	not in T cells
T1004	Speculation 1618 1625	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1618 1819	suggest that either a different protein binds to this site in monocytes versus T cells or that the protein recognizing this enhancer element undergoes differential modification in monocytes and T cells
T1006	Negation 1409 1411	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1409 1474	no comparable enhancer element has been clearly defined for HIV-1
T1008	Speculation 2094 2097	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2094 2195	may ultimately provide insight into the different role monocytes and T cells play in HIV pathogenesis
T1010	Speculation 1631 1637	either
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1631 1819	either a different protein binds to this site in monocytes versus T cells or that the protein recognizing this enhancer element undergoes differential modification in monocytes and T cells
