T1000	Negation 862 868	absent
E1000	Negation:T1000 Scope:T1001
T1001	Span 827 868	asymmetric divisions are virtually absent
T1002	Negation 252 256	lack
E1001	Negation:T1002 Scope:T1003
T1003	Span 252 364	lack of lineage specificity and developmental stage homogeneity of progenitor/precursor cells growing in culture
T1004	Negation 1492 1495	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1492 1596	not express CD36, erythropoietin receptor (EpoR), SCL/Tal1, EKLF, NF-E2, GATA-1, or glyocophorin A (GPA)
T1006	Negation 919 921	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 919 946	no erythropoietic potential
T1008	Speculation 2299 2302	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2299 2498	may eliminate the ambiguities intrinsic to molecular studies on heterogeneous populations of hematopoietic progenitors/precursors growing in culture, particularly in the initial stages of development
T1010	Negation 1874 1877	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1874 1886	not detected
