T1000	Speculation 427 432	could
E1000	Speculation:T1000 Scope:T1001
T1001	Span 396 465	specific NFAT binding activity could also be induced in human B cells
T1002	Speculation 248 255	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 245 337	is thought to be largely responsible for the T cell-specific inducibility of IL-2 expression
T1004	Negation 530 536	failed
E1002	Negation:T1004 Scope:T1005
T1005	Span 530 632	failed to activate transcription from an NFAT-driven chloramphenicol acetyltransferase (CAT) construct
T1006	Negation 505 508	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 505 519	not functional
T1008	Negation 1018 1021	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1018 1031	not truncated
T1010	Speculation 765 780	indicating that
E1005	Speculation:T1010 Scope:T1011
T1011	Span 765 851	indicating that Jun and Fos are critical for NFAT complex formation in both cell types
T1012	Speculation 1465 1472	propose
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1465 1598	propose a model whereby a core NFAT complex consisting of Jun, Fos, and a constitutive nuclear factor is formed in both T and B cells
T1014	Negation 1337 1343	failed
E1007	Negation:T1014 Scope:T1015
T1015	Span 1337 1450	failed to form a complex and to compete with the wild type motif for NFAT complex formation in both T and B cells
T1016	Speculation 1697 1702	might
E1008	Speculation:T1016 Scope:T1017
T1017	Span 1604 1695	an additional factor and/or post-translational modification of a factor, missing in B cells
T1018	Speculation 1625 1631	and/or
E1009	Speculation:T1018 Scope:T1019
T1019	Span 1604 1742	an additional factor and/or post-translational modification of a factor, missing in B cells, might be required for transactivation by NFAT
