T1000	Negation 1713 1716	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1704 1762	which is not known to be important in B cell Ig production
T1002	Negation 1608 1611	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1526 1646	Oct-2 mRNA levels and both Oct-2 and NF-kappa B proteins in nuclear extracts were not altered by treatment with TGF-beta
T1004	Speculation 2062 2069	unclear
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1999 2069	The mechanism by which TGF-beta inhibits Ig chain synthesis is unclear
T1006	Negation 2087 2090	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 2087 2184	not involve inhibition of the binding of NF-kappa B or Oct-2 to their respective target sequences
