T1000	Speculation 1193 1199	notion
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1193 1252	notion that PEBP2 is a T-cell-specific transcription factor
T1002	Speculation 1097 1111	indicated that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1097 1252	indicated that both genes are expressed in T cells throughout their development, supporting the notion that PEBP2 is a T-cell-specific transcription factor
