T1000	Speculation 1165 1172	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1165 1285	suggest that HU induces both transcriptional and post-transcription regulation of c-jun during erythroid differentiation
T1002	Speculation 824 837	indicate that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 824 946	indicate that HU regulates c-jun mRNA expression by increasing the rate of synthesis as well as stabilizing the c-jun mRNA
