T1000	Speculation 1359 1366	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1359 1454	suggest that these two phosphatases play important roles in regulating interleukin-1 production
T1002	Speculation 660 663	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 612 793	Stimulation of interleukin-1 gene transcription may be caused by the stimulation of transcription factor activities, including those of AP-1, by these protein phosphatase inhibitors
