T1000	Negation 520 522	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 520 538	no detectable IL-2
T1002	Negation 420 427	absence
E1001	Negation:T1002 Scope:T1003
T1003	Span 420 445	absence of anti-CD28 MoAb
T1004	Speculation 1513 1523	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1513 1583	suggesting the need for further activation requirements in the neonate
T1006	Speculation 1268 1271	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1268 1382	may therefore be due to decreased NF kappa B induction, reduced IL-2 mRNA expression and deficient IL-2 production
