T1000	Negation 752 755	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 741 841	TRAMP does not appear to interact with any of the known apoptosis-inducing ligands of the TNF family
T1002	Negation 714 717	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 714 726	not by Bcl-2
T1004	Speculation 756 762	appear
E1002	Speculation:T1004 Scope:T1005
T1005	Span 741 841	TRAMP does not appear to interact with any of the known apoptosis-inducing ligands of the TNF family
