T1000	Negation 694 697	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 674 768	This inhibition was not mediated through Nef phosphorylation on Thr-15 or GTP-binding activity
T1002	Negation 513 516	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 491 559	These parameters were not modified by Nef expression in Jurkat cells
T1004	Negation 911 914	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 911 959	not mediated through NF-kappa B-binding activity
T1006	Negation 809 812	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 809 834	not alter this inhibition
T1008	Speculation 1049 1056	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1049 1191	suggest that Nef downmodulates LTR activation without significantly inhibiting the capacity of T cells to respond to immunological activations
T1010	Negation 1095 1102	without
E1005	Negation:T1010 Scope:T1011
T1011	Span 1095 1191	without significantly inhibiting the capacity of T cells to respond to immunological activations
