T1000	Negation 846 851	lacks
E1000	Negation:T1000 Scope:T1001
T1001	Span 846 885	lacks any known NF-kappaB-binding sites
T1002	Speculation 633 642	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 614 642	NF-kappaB has been suggested
T1004	Speculation 1749 1756	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1749 1903	suggest that LITAF plays an important role in the activation of the human TNF-alpha gene and proposes a new mechanism to control TNF-alpha gene expression
