T1000	Speculation 2060 2065	imply
E1000	Speculation:T1000 Scope:T1001
T1001	Span 2060 2166	imply that TK activity is not obligatory for CD14-mediated signal transduction to occur in response to LPS
T1002	Speculation 207 215	believed
E1001	Speculation:T1002 Scope:T1003
T1003	Span 179 374	lipopolysaccharide (LPS) is believed to interact with macrophage receptors, resulting in the generation of inflammatory mediators and systemic symptoms including hemodynamic instability and shock
T1004	Negation 89 92	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 89 125	not require tyrosine kinase activity
T1006	Speculation 633 645	hypothesized
E1003	Speculation:T1006 Scope:T1007
T1007	Span 633 798	hypothesized that CD14-mediated signaling is effected through a receptor-associated tyrosine kinase (TK), suggesting a multicomponent receptor model of LPS signaling
T1008	Negation 534 536	no
E1004	Negation:T1008 Scope:T1009
T1009	Span 534 557	no transmembrane domain
T1010	Speculation 1077 1079	if
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1077 1123	if this pathway were present in CHO/CD14 cells
T1012	Speculation 739 749	suggesting
E1006	Speculation:T1012 Scope:T1013
T1013	Span 739 798	suggesting a multicomponent receptor model of LPS signaling
T1014	Negation 1774 1777	not
E1007	Negation:T1014 Scope:T1015
T1015	Span 1774 1824	not observed from similarly treated CHO/CD14 cells
T1016	Negation 1490 1492	no
E1008	Negation:T1016 Scope:T1017
T1017	Span 1490 1561	no effect on translocation of NF-kappa B in CHO/CD14 or RAW 264.7 cells
T1018	Negation 2086 2089	not
E1009	Negation:T1018 Scope:T1019
T1019	Span 2086 2166	not obligatory for CD14-mediated signal transduction to occur in response to LPS
T1020	Negation 1884 1890	failed
E1010	Negation:T1020 Scope:T1021
T1021	Span 1884 1960	failed to inhibit translocation of NF-kappa B in CHO/CD14 or RAW 264.7 cells
