T1000	Speculation 1023 1026	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1023 1148	may function as an antiapoptotic factor in thymocytes while functioning as a proapoptotic factor in mature peripheral T cells
T1002	Speculation 999 1007	suggests
E1001	Speculation:T1002 Scope:T1003
T1003	Span 999 1148	suggests that NF-kappaB may function as an antiapoptotic factor in thymocytes while functioning as a proapoptotic factor in mature peripheral T cells
