T1000	Negation 482 485	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 482 485	not
T1002	Speculation 151 154	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 151 217	may impair human immunodeficiency virus replication in these cells
T1004	Negation 1308 1311	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1308 1330	not in the plus clones
T1006	Speculation 574 579	might
E1003	Speculation:T1006 Scope:T1007
T1007	Span 574 615	might account for the observed phenomenon
T1008	Speculation 1674 1677	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1674 1754	may have inhibiting effects on the replication of HIV-1 in myelo-monocytic cells
T1010	Speculation 1632 1640	possible
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1632 1754	possible that particular serine proteases may have inhibiting effects on the replication of HIV-1 in myelo-monocytic cells
