T1000	Negation 241 248	without
E1000	Negation:T1000 Scope:T1001
T1001	Span 241 289	without further requirement for TCR coengagement
T1002	Negation 100 107	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 100 122	without TCR engagement
T1004	Speculation 436 443	whether
E1002	Speculation:T1004 Scope:T1005
T1005	Span 436 474	whether this putative function of CD28
T1006	Negation 376 383	without
E1003	Negation:T1006 Scope:T1007
T1007	Span 376 405	without signal 1 (TCR signal)
T1008	Negation 762 765	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 762 839	not lead to detectable activation of the protein kinases p56(lck) and c-Raf-1
T1010	Speculation 449 457	putative
E1005	Speculation:T1010 Scope:T1011
T1011	Span 449 521	putative function of CD28 is mediated via a particular signaling pathway
T1012	Speculation 1499 1514	indicating that
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1499 1569	indicating that the signaling capacity of CD28 changes with activation
T1014	Negation 1159 1165	unable
E1007	Negation:T1014 Scope:T1015
T1015	Span 1155 1233	was unable to induce the binding of transcription factors to the IL-2 promoter
T1016	Speculation 1679 1686	suggest
E1008	Speculation:T1016 Scope:T1017
T1017	Span 1679 1771	suggest that this capacity is associated with a particular pattern of early signaling events
