T1000	Speculation 652 657	could
E1000	Speculation:T1000 Scope:T1001
T1001	Span 577 702	the inhibitory effect on TNF-alpha secretion by constitutive GH production could be abolished in the presence of anti-hGH mAb
T1002	Speculation 529 536	appears
E1001	Speculation:T1002 Scope:T1003
T1003	Span 512 569	The effect of GH appears to occur in an autocrine fashion
T1004	Negation 1285 1292	without
E1002	Negation:T1004 Scope:T1005
T1005	Span 1285 1348	without altering other pathways leading to TNF-alpha production
T1006	Negation 959 961	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 959 1057	no inhibition of TNF-alpha production was observed when cells were cultured in the presence of PMA
T1008	Speculation 1359 1368	potential
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1359 1394	potential relevance in septic shock
T1010	Speculation 1349 1352	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1349 1394	may be of potential relevance in septic shock
