T1000	Negation 1389 1392	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1379 1438	POS-1 was not found in nuclear extracts of human Th1 clones
T1002	Negation 250 253	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 250 263	not Th1 cells
T1004	Speculation 1474 1477	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1474 1551	may play a role in the differential regulation of IL-4 gene expression levels
T1006	Speculation 1455 1462	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1455 1551	suggest that PRE-I may play a role in the differential regulation of IL-4 gene expression levels
