T1000	Speculation 855 860	imply
E1000	Speculation:T1000 Scope:T1001
T1001	Span 855 998	imply that Myc promotes activation-induced apoptosis by obligatory heterodimerization with Max, and therefore, by regulating gene transcription
T1002	Speculation 195 201	likely
E1001	Speculation:T1002 Scope:T1003
T1003	Span 187 302	this is likely to represent comparable events related to tolerance induction in immature and mature T cells in vivo
