T1000	Negation 1488 1497	could not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1494 1545	not sustain the expression from the down-regulation
T1002	Speculation 800 806	likely
E1001	Speculation:T1002 Scope:T1003
T1003	Span 767 824	the cells expressing p45 is most likely to be neutrophils
T1004	Speculation 1565 1568	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1565 1642	may also participate in the regulation of neutrophil-specific gene expression
T1006	Speculation 1547 1557	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1547 1642	suggesting the E2 may also participate in the regulation of neutrophil-specific gene expression
