T1000	Speculation 1262 1275	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1262 1414	indicate that TCL1 is activated in preleukemic clonal cells as a consequence of chromosome translocation involving sequences from the TCR locus at 14q11
T1002	Negation 902 905	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 902 943	not in the lymphocytes of the other cases
T1004	Speculation 1533 1542	potential
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1533 1571	potential tool for clinical evaluation
