T1000	Speculation 1256 1259	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1256 1407	may allow for the continuous presence of a cytoplasmic reservoir of p50/RelA(p65) complexes that are readily available for inducer-mediated stimulation
T1002	Speculation 1047 1054	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1047 1202	suggest that macrophage differentiation results in the expression of active p50/RelA(p65) heterodimers with the capacity to activate target gene expression
