T1000	Speculation 2000 2008	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 2000 2096	suggests the presence of tissue-specific regulators/adapters or differential MZF-1 modifications
T1002	Speculation 120 128	putative
E1001	Speculation:T1002 Scope:T1003
T1003	Span 120 181	putative transcriptional regulator of myeloid differentiation
T1004	Speculation 2061 2063	or
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2025 2153	tissue-specific regulators/adapters or differential MZF-1 modifications that determine MZF-1 transcriptional regulatory function
