T1000	Speculation 1151 1159	possible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1151 1202	possible paracrine effect on IL-2R-alpha expression
T1002	Speculation 1084 1091	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1084 1202	suggest that RA can augment IL-2 mRNA production by T cells with a possible paracrine effect on IL-2R-alpha expression
T1004	Speculation 1265 1268	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1265 1337	may be another important cytokine modulated by RA in the immune response
T1006	Speculation 1218 1224	appear
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1204 1252	These changes appear to be mediated by RAR-alpha
