T1000	Negation 1085 1088	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1085 1108	not unique to monocytes
T1002	Negation 568 571	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 512 584	the mechanism by which IFNs mediate this inhibition has not been defined
T1004	Speculation 1344 1354	indicating
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1344 1394	indicating a requirement for de novo transcription
T1006	Negation 1194 1197	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1194 1205	not evident
T1008	Speculation 1509 1517	possibly
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1509 1570	possibly one or more members of the SOCS/ SSI/CIS gene family
T1010	Speculation 1399 1406	propose
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1399 1529	propose a model in which stimulation of monocytes by IFN activates de novo synthesis of an inhibitory factor, possibly one or more
T1012	Speculation 1522 1524	or
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1518 1632	one or more members of the SOCS/ SSI/CIS gene family, capable of suppressing activation of STAT6 by IL-4 and IL-13
