T1000	Negation 1345 1348	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1345 1448	not affect NF-kappaB DNA binding activity nor the concentrations of p50, p65 and IkappaB-alpha proteins
T1002	Negation 313 316	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 231 334	the action of dopamine on HIV-1 gene expression in cells of the immune system has not yet been examined
T1004	Speculation 1456 1464	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1456 1506	suggests a distinct NF-kappaB activation mechanism
T1006	Negation 1387 1390	nor
E1003	Negation:T1006 Scope:T1007
T1007	Span 1387 1448	nor the concentrations of p50, p65 and IkappaB-alpha proteins
