T1000	Speculation 530 537	unknown
E1000	Speculation:T1000 Scope:T1001
T1001	Span 469 537	the mechanisms by which Tax induces transformation are still unknown
T1002	Speculation 381 388	appears
E1001	Speculation:T1002 Scope:T1003
T1003	Span 376 455	that appears to play an important role in the process of T-cell immortalization
T1004	Speculation 548 554	likely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 548 665	likely that the ability of Tax to alter the expression of many cellular genes plays an important part in this process
T1006	Speculation 542 547	seems
E1003	Speculation:T1006 Scope:T1007
T1007	Span 542 665	seems likely that the ability of Tax to alter the expression of many cellular genes plays an important part in this process
T1008	Speculation 1518 1525	unclear
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1462 1525	The mechanisms by which Tax activates NF-kappa B remain unclear
T1010	Negation 676 679	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 676 700	not bind directly to DNA
T1012	Speculation 1853 1859	either
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1853 1971	either p100 or p65-I kappa B alpha targets these cytoplasmic NF-kappa B/Rel complexes to the proteasome for processing
T1014	Speculation 1693 1703	raises the
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1693 1887	raises the intriguing possibility that physical association of the HsN3 proteasome subunit with HTLV-I Tax coupled with the independent interaction of Tax with either p100 or p65-I kappa B alpha
