T1000	Negation 984 991	absence
E1000	Negation:T1000 Scope:T1001
T1001	Span 984 1055	absence of slow migrating forms of I kappa B beta following stimulation
T1002	Speculation 846 853	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 846 978	suggest that, unlike I kappa B alpha, I kappa B beta is constitutively phosphorylated and resynthesized as a hypophosphorylated form
T1004	Speculation 1056 1064	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1056 1189	suggests that the phosphorylation does not necessarily constitute the signal-induced event which targets the molecule for proteolysis
