T1000	Speculation 981 984	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 981 1057	may be important for DNA-binding affinity and/or specificity of the receptor
T1002	Speculation 950 965	indicating that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 950 1057	indicating that the PAS domain may be important for DNA-binding affinity and/or specificity of the receptor
T1004	Speculation 1070 1078	possible
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1070 1164	possible to reconstitute dioxin receptor function with proteins expressed in wheat germ lysate
T1006	Negation 1066 1069	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1066 1164	not possible to reconstitute dioxin receptor function with proteins expressed in wheat germ lysate
T1008	Negation 1641 1644	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1641 1677	not for dimerization of the receptor
T1010	Negation 1223 1226	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1223 1244	not wheat germ lysate
T1012	Speculation 1765 1771	likely
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1679 1922	Several distinct roles for hsp90 in modulating dioxin receptor function are therefore likely: correct folding of the ligand-binding domain, interference with Arnt heterodimerization, and folding of a DNA-binding conformation of the bHLH domain
T1014	Speculation 1587 1595	appeared
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1564 1677	bHLH-hsp90 interaction appeared to be important for DNA-binding activity but not for dimerization of the receptor
