T1000	Speculation 977 986	suggested
E1000	Speculation:T1000 Scope:T1001
T1001	Span 977 1108	suggested that Sp1 and two other CCGCCC binding proteins from erythroid and non-erythroid cells could bind to the Sp1 binding motif
T1002	Negation 864 871	lacking
E1001	Negation:T1002 Scope:T1003
T1003	Span 864 887	lacking a TATA sequence
T1004	Negation 1251 1254	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1251 1287	not in the highly active OCIM1 cells
T1006	Speculation 1073 1078	could
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1073 1108	could bind to the Sp1 binding motif
T1008	Speculation 1544 1551	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1544 1673	suggest that while GATA-1 can transactivate the EpoR promoter, the level of hEpoR gene expression does not depend on GATA-1 alone
T1010	Negation 1647 1650	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1647 1673	not depend on GATA-1 alone
T1012	Speculation 1803 1811	possibly
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1793 1843	including possibly other Sp1-like binding proteins
