T1000	Speculation 1570 1576	likely
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1561 1622	that are likely to regulate gene transcription in neutrophils
T1002	Speculation 622 629	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 622 763	whether these transcription factors become activated under stimulatory conditions which are known to induce gene transcription in neutrophils
T1004	Speculation 1668 1673	could
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1668 1755	could prove useful in other cell types that express high levels of endogenous proteases
