T1000	Negation 1068 1071	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1068 1104	not inhibit NF-kappaB binding to DNA
T1002	Speculation 156 161	would
E1001	Speculation:T1002 Scope:T1003
T1003	Span 112 236	the inhibitory capacity of I(kappa)B(alpha) would be mediated through the retention of Rel/NF-kappaB proteins in the cytosol
T1004	Negation 1222 1228	failed
E1002	Negation:T1004 Scope:T1005
T1005	Span 1222 1314	failed to demonstrate an association between nuclear I(kappa)B(alpha) and NF-kappaB proteins
T1006	Negation 1129 1132	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1129 1188	not due to the presence of IkappaBbeta at the nuclear level
T1008	Speculation 1434 1444	apparently
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1434 1503	apparently inactive form unable to disrupt NF-kappaB binding from DNA
T1010	Negation 1459 1465	unable
E1005	Negation:T1010 Scope:T1011
T1011	Span 1431 1453	an apparently inactive
