T1000	Negation 894 901	neither
E1000	Negation:T1000 Scope:T1001
T1001	Span 894 990	neither the viability of DC nor their mannose receptor-mediated endocytosis were modified by NAC
T1002	Negation 859 862	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 859 890	not due to nonspecific toxicity
T1004	Negation 1228 1231	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1190 1248	APC-independent T cell responses were not inhibited by NAC
T1006	Negation 922 925	nor
E1003	Negation:T1006 Scope:T1007
T1007	Span 922 990	nor their mannose receptor-mediated endocytosis were modified by NAC
T1008	Speculation 1274 1281	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1274 1392	suggest that NAC might impair the generation of primary immune responses in humans through its inhibitory action on DC
T1010	Speculation 1149 1154	could
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1143 1186	which could be attributed to a defect of DC
T1012	Speculation 1291 1296	might
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1291 1392	might impair the generation of primary immune responses in humans through its inhibitory action on DC
