T1000	Negation 687 690	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 687 755	not that of the p50/p50 KBF1 factor or of other DNA-binding proteins
T1002	Speculation 508 516	putative
E1001	Speculation:T1002 Scope:T1003
T1003	Span 508 554	putative protein kinase C phosphorylation site
T1004	Speculation 814 820	likely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 806 954	that is likely to be involved in regulation of transcriptional responses to NF-kappa B, including adhesion-dependent pathways of monocyte activation
