T1000	Negation 1123 1126	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1123 1185	not result in increased binding of trans-factors to the CD28RE
T1002	Negation 108 115	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 108 151	without enhancing IL-2 gene transactivation
T1004	Negation 1320 1325	fails
E1002	Negation:T1004 Scope:T1005
T1005	Span 1320 1411	fails to enhance IL-2 promoter-reporter or RE/AP construct expression in CD2-activated LPMC
T1006	Negation 1187 1190	nor
E1003	Negation:T1006 Scope:T1007
T1007	Span 1187 1289	nor did Western blots detect changes in I-kappaBalpha or I-kappaBbeta levels following CD28 coligation
T1008	Speculation 1662 1669	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1662 1816	suggest a biological significance for different mechanisms of IL-2 activation in initiation and maintenance of the cytokine repertoire found in the mucosa
T1010	Speculation 1441 1454	indicate that
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1441 1641	indicate that the molecular mechanisms involved in CD28 cosignaling and regulation of IL-2 secretion in LP T cells are unique to that compartment and differ from those seen in peripheral blood T cells
