T1000	Speculation 1776 1783	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1776 2014	suggest that reduced IL-2 production by neonatal T cells is specific for anti-CD3 and anti-CD3+ anti-CD28-mediated stimulation and that these activators cannot effectively activate the ROI-NF-kappa B signalling pathway in neonatal T cells
T1002	Negation 1660 1663	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1621 1672	levels similar to those of adults were not achieved
