T1000	Speculation 1965 1968	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1965 2057	may, in turn, alter the course of viral replication in cells of CNS and immune system origin
T1002	Speculation 1843 1850	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1843 2057	suggest that LTR sequence changes can significantly affect basal LTR function and transcription factor recruitment, which may, in turn, alter the course of viral replication in cells of CNS and immune system origin
