T1000	Speculation 999 1012	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 999 1095	indicate that Fc gamma R can mediate a TNF-alpha-dependent induction of HIV-1 gene transcription
T1002	Negation 824 827	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 824 851	not anti-IL-1 beta antibody
T1004	Speculation 1130 1133	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1130 1231	may contribute to the pathophysiology of HIV-1 infection by augmenting viral replication in monocytes
T1006	Speculation 1100 1107	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1100 1231	suggest that immune complexes may contribute to the pathophysiology of HIV-1 infection by augmenting viral replication in monocytes
