T1000	Speculation 558 568	hypothesis
E1000	Speculation:T1000 Scope:T1001
T1001	Span 558 657	hypothesis that cortivazol acts in dex-resistant cells by making use of the residual GR found there
T1002	Negation 444 447	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 444 523	not in a dex-resistant, glucocorticoid receptor(GR)-defective clone ICR-27 TK-3
T1004	Speculation 1341 1343	or
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1341 1383	or might serve as a marker for the process
T1006	Speculation 1246 1251	might
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1246 1339	might be one of the earliest crucial steps in the lysis of normal and dex-resistant CEM cells
T1008	Speculation 1344 1349	might
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1344 1383	might serve as a marker for the process
