T1000	Speculation 788 798	raised the
E1000	Speculation:T1000 Scope:T1001
T1001	Span 788 957	raised the possibility that the effect of CIITA on promoter occupation is mediated by an effect on the cooperative stabilization of the DNA-bound multi-protein complexes
T1002	Speculation 406 415	not known
E1001	Speculation:T1002 Scope:T1003
T1003	Span 373 415	its exact mechanism of action is not known
T1004	Speculation 1112 1120	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1112 1277	suggests other mechanisms for CIITA-induced promoter occupancy, such as an effect on chromatin structure leading to increased accessibility of MHC class II promoters
T1006	Negation 1009 1012	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1009 1105	not affect the stability of the higher-order protein complex formed on DNA by RFX, X2BP and NF-Y
T1008	Negation 1487 1490	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1487 1564	not required for normal occupation of MHC class II promoters in B lymphocytes
