T1000	Negation 1065 1068	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1065 1082	not that of c-jun
T1002	Negation 813 816	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 813 949	not induce any change in the binding activity of NF-kappa B, a transcription factor whose activity is also regulated by protein kinase C
T1004	Speculation 1369 1379	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1369 1464	suggesting that de novo protein synthesis is crucial for the induction of AP-1-binding activity
