T1000	Speculation 1353 1363	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1353 1485	suggesting that glycation and reactive oxygen species, generated through the glycation reaction, serve as mediators of the phenomena
T1002	Speculation 1236 1242	seemed
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1210 1262	These effects of D-ribose seemed almost irreversible
T1004	Speculation 1506 1513	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1506 1710	suggest that protein glycation in pancreatic beta cells, which occurs in vivo under chronic hyperglycemia, suppresses insulin gene transcription and thus can explain part of the beta cell glucose toxicity
