T1000	Speculation 628 635	propose
E1000	Speculation:T1000 Scope:T1001
T1001	Span 628 950	propose that BEAD-1 functions as a boundary that separates the TCR alpha/delta locus into distinct regulatory domains controlled by Edelta and the TCR alpha enhancer, and that it prevents Edelta from opening the chromatin of the TCR alpha joining gene segments for VDJ recombination at an early stage of T cell development
