T1000	Negation 894 897	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 894 928	not present in unactivated T cells
T1002	Negation 622 625	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 622 648	not in unactivated T cells
T1004	Speculation 1589 1596	appears
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1572 1700	The CMAT protein appears to be a novel inducible protein involved in the regulation of c-myb expression during T-cell activation
T1006	Negation 1439 1442	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1439 1476	not cross-react with the CMAT protein
