T1000	Speculation 1322 1330	appeared
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1290 1364	only that located at the 3' end appeared to be utilized in the 2.3-kb cDNA
T1002	Speculation 253 260	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 253 368	whether these cells expressed the hGATA-3 T cell transcription factor and the recombination-activating gene (RAG)-1
T1004	Speculation 1700 1710	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1700 1815	suggesting that hGATA-3 may be involved in the regulation of the unrearranged TcR delta gene expression in NK cells
T1006	Negation 1576 1579	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1576 1616	not in freshly derived cell populations)
T1008	Negation 1826 1828	no
E1004	Negation:T1008 Scope:T1009
T1009	Span 1826 1918	no transcription of the RAG-1 gene could be detected in all NK cell lines or clones analyzed
T1010	Speculation 1724 1727	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1724 1815	may be involved in the regulation of the unrearranged TcR delta gene expression in NK cells
