T1000	Speculation 1297 1307	hypothesis
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1297 1377	hypothesis that gold ions could block NF-kappaB-DNA binding by a redox mechanism
T1002	Negation 1047 1049	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 1047 1056	no effect
T1004	Speculation 1451 1462	potentially
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1451 1522	potentially useful drug for the treatment of patients infected with HIV
T1006	Speculation 1398 1411	indicate that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1398 1469	indicate that the monovalent gold compound AuTG is a potentially useful
