T1000	Speculation 826 833	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 826 1035	suggest that class I triggering can induce the activity of NF-kappa B/Rel nuclear activity in peripheral blood T lymphocytes, thereby modulating the expression of genes regulated by these transcription factors
T1002	Negation 609 618	no longer
E1001	Negation:T1002 Scope:T1003
T1003	Span 609 800	no longer observed at 40 h. The mAb failed to induce NF-kappa B/Rel nuclear activity in cells incubated in the presence of 3,4-dichloroisocoumarin, an inhibitor of I kappa B-alpha degradation
