T1000	Negation 894 897	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 894 936	not resting, lymphocytes expressed the VDR
T1002	Negation 92 96	lack
E1001	Negation:T1002 Scope:T1003
T1003	Span 92 143	lack of correspondence with common allelic variants
T1004	Negation 1767 1770	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1767 1807	not affect the abundance of the VDR mRNA
T1006	Speculation 836 851	indicating that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 836 905	indicating that normal human monocytes and activated, but not resting
