T1000	Negation 1366 1369	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1366 1399	not, and the constitutive B cells
T1002	Speculation 517 524	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 514 586	is thought to participate to the selection and maturation of the T cells
T1004	Speculation 1415 1422	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1415 1656	suggest that both common mechanisms, such as the one mediated by the CIITA trans-activator, and distinct tissue-specific constraints contribute to the transcriptional control of constitutive and IFN-gamma-induced MHC class II gene expression
