T1000	Speculation 1862 1872	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1862 1961	suggesting that phosphorylation of CREB alters its interaction with the upstream regulatory element
T1002	Speculation 1009 1016	implies
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1009 1110	implies that the regulation of bcl-2 expression is linked to a signal transduction pathway in B cells
T1004	Speculation 2168 2176	possible
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2168 2321	possible that the CRE site is responsible for induction of bcl-2 expression in other cell types, particularly those in which protein kinase C is involved
T1006	Speculation 1998 2005	appears
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1963 2160	The CRE site in the bcl-2 promoter appears to play a major role in the induction of bcl-2 expression during the activation of mature B cells and during the rescue of immature B cells from apoptosis
