T1000	Speculation 971 981	apparently
E1000	Speculation:T1000 Scope:T1001
T1001	Span 957 1020	This shift is apparently not caused by a recruitment phenomenon
T1002	Negation 982 985	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 957 1020	This shift is apparently not caused by a recruitment phenomenon
T1004	Speculation 1527 1542	indicating that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1527 1561	indicating that early but not late
T1006	Negation 1553 1556	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1553 1593	not late HPC are sensitive to its action
T1008	Speculation 2026 2029	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2026 2104	may lead to a shift from the erythroid to granulocytic differentiation pathway
T1010	Speculation 1916 1929	indicate that
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1916 2104	indicate that RA directly inhibits the erythroid differentiation program at the level of early adult HPC, and may lead to a shift from the erythroid to granulocytic differentiation pathway
