T1000	Speculation 1379 1386	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1379 1537	suggest that the germline promoters and V region promoters differ in their dependence on octamer for activation and respond differently to enhancer activation
T1002	Negation 1193 1195	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 1193 1259	no effect on transcriptional activation from the germline promoter
