T1000	Negation 431 438	missing
E1000	Negation:T1000 Scope:T1001
T1001	Span 431 482	missing the NF-kappaB and four Spl binding elements
T1002	Negation 80 87	absence
E1001	Negation:T1002 Scope:T1003
T1003	Span 80 125	absence of NF-kappaB and Sp1 binding elements
T1004	Negation 2210 2217	absence
E1002	Negation:T1004 Scope:T1005
T1005	Span 2210 2244	absence of NF-kappaB and Sp1 sites
T1006	Negation 1117 1120	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1077 1224	Reversions or additional mutations were not detected in the U3 and R regions of proviral DNA from CEMxl74 cells infected with the SIVmac239 mutants
