T1000	Negation 776 779	nor
E1000	Negation:T1000 Scope:T1001
T1001	Span 776 801	nor in K562 erythroblasts
T1002	Negation 710 713	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 703 801	it was not detected in lymphoid cells MOLT4 (T cell) and BALL1 (B cell), nor in K562 erythroblasts
T1004	Speculation 1799 1806	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1799 1936	suggest that AhR may play an important role in the function of monocytes and also in the eventual activation of environmental carcinogens
T1006	Speculation 1624 1638	indicated that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1624 1785	indicated that expression of AhR mRNA was significantly induced during monocytic differentiation and that the differentiated cells were responsive to xenobiotics
T1008	Speculation 1816 1819	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1816 1936	may play an important role in the function of monocytes and also in the eventual activation of environmental carcinogens
