T1000	Speculation 1421 1428	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1421 1585	suggest that surfactant's suppressive effects on inflammatory cytokine production may involve transcriptional regulation through inhibition of NF-kappa B activation
T1002	Speculation 875 882	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 875 929	whether surfactant affected transcriptional mechanisms
T1004	Speculation 1503 1506	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1503 1585	may involve transcriptional regulation through inhibition of NF-kappa B activation
