T1000	Negation 173 180	without
E1000	Negation:T1000 Scope:T1001
T1001	Span 173 247	without affecting levels of Cu,Zn SOD, catalase, or glutathione peroxidase
T1002	Negation 39 46	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 39 101	without inflammatory cytokine production by a mutant endotoxin
T1004	Negation 828 834	failed
E1002	Negation:T1004 Scope:T1005
T1005	Span 828 954	failed to induce significant production of tumor necrosis factor-alpha and macrophage inflammatory protein-1alpha by monocytes
T1006	Negation 440 447	lacking
E1003	Negation:T1006 Scope:T1007
T1007	Span 440 530	lacking myristoyl fatty acid at the 3' R-3-hydroxymyristate position of the lipid A moiety
T1008	Negation 1219 1222	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1219 1499	not necessary for the induction of Mn SOD, 2) endotoxin-mediated induction of Mn SOD and inflammatory cytokines are regulated, at least in part, through different signal transduction pathways, and 3) failure of the mutant endotoxin to induce tumor necrosis factor-alpha production
T1010	Negation 963 966	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 963 1055	not induce the phosphorylation and nuclear translocation of mitogen-activated protein kinase
T1012	Speculation 1071 1078	suggest
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1071 1260	suggest that 1) lipid A myristoyl fatty acid, although it is important for the induction of inflammatory cytokine production by human monocytes, is not necessary for the induction of Mn SOD
T1014	Negation 1419 1426	failure
E1007	Negation:T1014 Scope:T1015
T1015	Span 1419 1587	failure of the mutant endotoxin to induce tumor necrosis factor-alpha production is, at least in part, due to its inability to activate mitogen-activated protein kinase
