T1000	Negation 319 323	fail
E1000	Negation:T1000 Scope:T1001
T1001	Span 319 346	fail to complete maturation
T1002	Negation 269 276	absence
E1001	Negation:T1002 Scope:T1003
T1003	Span 269 286	absence of GATA-1
T1004	Negation 566 569	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 566 606	not the related proteins bcl-2 and mcl-1
T1006	Speculation 436 443	unknown
E1003	Speculation:T1006 Scope:T1007
T1007	Span 378 443	The mechanisms by which GATA-1 controls cell survival are unknown
T1008	Speculation 1172 1179	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1172 1298	suggest a regulatory hierarchy in which bcl-xL is a critical downstream effector of GATA-1 and erythropoietin-mediated signals
T1010	Negation 750 754	fail
E1005	Negation:T1010 Scope:T1011
T1011	Span 750 862	fail to generate viable mature definitive erythroid cells, a phenotype resembling that of GATA-1 gene disruption
