T1000	Speculation 827 829	or
E1000	Speculation:T1000 Scope:T1001
T1001	Span 788 867	consequence of myeloid differentiation or an intrinsic differentiating stimulus
T1002	Speculation 739 741	if
E1001	Speculation:T1002 Scope:T1003
T1003	Span 739 867	if this developmentally related interaction is a consequence of myeloid differentiation or an intrinsic differentiating stimulus
T1004	Speculation 1348 1354	likely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1348 1587	likely plays a key role in myeloid cell development through dual mechanisms; inhibition of a select set of c-Myb regulated targets, such as Bcl-2 and CD13/APN, coupled with the activation of as yet undefined differentiation-promoting genes
T1006	Speculation 1327 1341	indicated that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1327 1587	indicated that c-Maf likely plays a key role in myeloid cell development through dual mechanisms; inhibition of a select set of c-Myb regulated targets, such as Bcl-2 and CD13/APN, coupled with the activation of as yet undefined differentiation-promoting genes
