T1000	Negation 1223 1226	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1223 1267	not have impaired RNA transcription activity
T1002	Negation 679 681	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 679 751	no transcription deficiency has been demonstrated in either XP-B or XP-D
T1004	Speculation 1443 1446	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1443 1526	may involve an impairment of cellular function only under certain growth conditions
T1006	Speculation 1285 1293	possible
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1285 1398	possible consequences of the reduced cellular content of TFIIH for the clinical symptoms in XP-B or XP-D patients
