T1000	Speculation 595 598	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 595 708	may be inhibiting the differentiation of B cells by blocking these two crucial elements in the maturation pathway
T1002	Speculation 576 583	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 576 708	suggest that v-abl may be inhibiting the differentiation of B cells by blocking these two crucial elements in the maturation pathway
