T1000	Negation 1445 1448	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1445 1496	not sufficient for mediating cytokine up-regulation
T1002	Speculation 954 961	appears
E1001	Speculation:T1002 Scope:T1003
T1003	Span 907 992	The complex on the proximal site (NF kappa B2) appears to be composed of p50 and relB
T1004	Speculation 1716 1723	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1716 1869	suggest that the NF kappa B2 nucleoprotein complex may cooperate with DNA-bound STAT6 to achieve IL-4-dependent activation of the human IgE germline gene
T1006	Negation 1686 1688	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1686 1695	no effect
T1008	Speculation 1767 1770	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1767 1869	may cooperate with DNA-bound STAT6 to achieve IL-4-dependent activation of the human IgE germline gene
