T1000	Speculation 555 562	thought
E1000	Speculation:T1000 Scope:T1001
T1001	Span 530 614	some, but not all, genes thought to be regulated by NF-kappa B. NF-kappa B elevation
T1002	Negation 670 677	lacking
E1001	Negation:T1002 Scope:T1003
T1003	Span 670 732	lacking both I kappa B alpha and the p50 subunit of NF-kappa B
T1004	Speculation 1022 1035	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1022 1075	indicate that I kappa b beta, but not I kappa B alpha
T1006	Negation 1056 1059	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1056 1153	not I kappa B alpha, is required for the signal-dependent activation of NF-kappa B in fibroblasts
