T1000	Speculation 1646 1661	indicating that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1646 1939	indicating that the NF-GM2 polypeptide cannot be immunologically differentiated from the 50 kDa subunit of NF-kappa B. The purified NF-GM2 activated in vitro transcription from the kappa B enhancer, while it failed to stimulate transcription from the GM-CSF promoter harboring the GM2 sequence
T1002	Negation 1854 1860	failed
E1001	Negation:T1002 Scope:T1003
T1003	Span 1854 1939	failed to stimulate transcription from the GM-CSF promoter harboring the GM2 sequence
T1004	Speculation 1946 1954	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1946 2103	suggests that the activation mechanism of the GM-CSF gene through the GM2/GC-box sequence is different from that of genes carrying the kappa B enhancer alone
