T1000	Negation 1165 1168	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1165 1174	not c-rel
T1002	Negation 558 561	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 558 570	not of c-rel
T1004	Speculation 1880 1887	appears
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1864 1950	phosphorylation appears to be a general mechanism for activation of NF-kappa B in vivo
T1006	Speculation 1220 1230	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1220 1394	suggesting that TNF-alpha selectively activates only specific NF-kappa B heteromers and that modifications regulate not only I kappa B molecules but also NF-kappa B molecules
