T1000	Negation 1269 1272	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1203 1296	the mitogen-activated protein kinase (MAPK) signaling pathway was not used by these receptors
T1002	Negation 1124 1127	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1124 1185	not have any effect on FcR-mediated nuclear factor activation
T1004	Negation 1921 1924	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1921 1944	not involve Ras and Raf
T1006	Speculation 1187 1197	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1187 1296	suggesting that the mitogen-activated protein kinase (MAPK) signaling pathway was not used by these receptors
T1008	Speculation 1647 1654	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1647 1944	suggest that the signaling pathway from Fc receptors leading to expression of different genes important to leukocyte biology, initiates with tyrosine kinases and requires MAPK activation; but in contrast to other tyrosine kinase receptors, FcR-mediated MAPK activation does not involve Ras and Raf
