T1000	Negation 476 479	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 476 614	not downstream of p21ras in the induction of NF-AT and AP-1 transcriptional activity and in the expression of IL-2 in human Jurkat T cells
T1002	Negation 20 23	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 20 76	not a downstream effector of p21ras in activated T cells
T1004	Negation 699 702	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 699 745	not affected by expression of activated p21ras
