T1000	Speculation 1332 1345	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1332 1600	indicate that the inducible nuclear import of NF-kappa B, AP-1, NFAT, and STAT1 in Jurkat T cells can be regulated by NLS peptide delivered noninvasively to the cytoplasm of Jurkat T cells to target members of the importin (karyopherin)-alpha beta NLS receptor complex
T1002	Negation 629 632	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 608 652	the NLS of STAT1 has not yet been identified
