T1000	Negation 1050 1053	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1035 1125	repression did not seem to involve another factor whose activity is affected by the NSAIDs
T1002	Speculation 454 463	potential
E1001	Speculation:T1002 Scope:T1003
T1003	Span 454 557	potential role of HSF1 in the effects of NSAIDs on gene expression in a human monocytic cell line THP-1
T1004	Speculation 1054 1058	seem
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1035 1125	repression did not seem to involve another factor whose activity is affected by the NSAIDs
T1006	Negation 1189 1192	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1189 1212	not NFkappaB responsive
T1008	Speculation 1628 1635	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1628 1726	suggest that individual NSAID family members may differentially induce one or other of these forms
T1010	Negation 1398 1401	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1398 1401	not
T1012	Speculation 1703 1705	or
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1703 1726	or other of these forms
T1014	Speculation 1673 1676	may
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1673 1726	may differentially induce one or other of these forms
T1016	Speculation 1931 1938	appears
E1008	Speculation:T1016 Scope:T1017
T1017	Span 1926 1981	HSF1 appears to play a regulatory role in these effects
