T1000	Speculation 1175 1188	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1175 1279	indicate that the concentration of NF-AT must exceed a critical threshold before transcription initiates
T1002	Negation 949 951	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 949 960	no beta-gal
T1004	Speculation 1531 1541	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1531 1651	suggesting that thresholds set by the concentration of transcription factors may be a common property of inducible genes
T1006	Speculation 1296 1302	likely
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1296 1397	likely reflects the NF-AT concentration-dependent assembly of transcription complexes at the promoter
T1008	Speculation 1608 1611	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1608 1651	may be a common property of inducible genes
