T1000	Speculation 1870 1877	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1870 2063	suggest that the nuclear localization signal and transactivation domain of NF-kappa B p65 constitute a bipartite system that is critically involved in the inhibitory function of I kappa B/MAD-3
T1002	Negation 698 701	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 695 1047	is not directly regulated by I kappa B. To investigate the molecular basis for the critical regulatory interaction between NF-kappa B and I kappa B/MAD-3, a series of human NF-kappa B p65 mutants was identified that functionally segregated DNA binding, I kappa B-mediated inhibition, and I kappa B-induced nuclear exclusion of this transcription factor
T1004	Speculation 2336 2346	presumably
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2336 2439	presumably reflecting the unique C-terminal domain that is distinct from that present in NF-kappa B p65
T1006	Negation 2291 2293	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 2291 2334	no loss of DNA binding activity is observed
