T1000	Negation 524 527	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 524 557	not affect the thymic development
T1002	Negation 197 200	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 197 225	not to abnormal thymopoiesis
T1004	Speculation 1177 1183	either
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1177 1297	either regulating proteins involved in the IL-2 signaling or by functionally interfering with the cell cycle progression
T1006	Negation 809 812	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 809 866	not attributable to an abnormal expression of these genes
