T1000	Speculation 1125 1135	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1125 1200	suggesting NFAT1 may be limiting for IL-4 gene expression in this cell type
T1002	Negation 205 208	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 205 229	not others, such as IL-2
T1004	Speculation 1434 1441	appears
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1428 1555	NFAT1 appears to be the major NFAT family member responsible for the initial increased expression of IL-4 by primed CD4 T cells
T1006	Speculation 1142 1145	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1142 1200	may be limiting for IL-4 gene expression in this cell type
