T1000	Speculation 542 547	seems
E1000	Speculation:T1000 Scope:T1001
T1001	Span 524 580	no single element seems absolutely required for activity
T1002	Negation 524 526	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 524 580	no single element seems absolutely required for activity
T1004	Negation 1282 1285	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1282 1300	not in non-B cells
T1006	Negation 1066 1072	unable
E1003	Negation:T1006 Scope:T1007
T1007	Span 1041 1144	the factor is apparently unable to bind to the endogenous Ig heavy chain enhancer in non-lymphoid cells
T1008	Negation 1529 1532	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1520 1567	that are not expressed in most other cell types
T1010	Speculation 1055 1065	apparently
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1041 1144	the factor is apparently unable to bind to the endogenous Ig heavy chain enhancer in non-lymphoid cells
T1012	Speculation 1874 1884	apparently
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1874 1956	apparently unable to bind to the endogenous Ig heavy chain enhancer in non-B cells
T1014	Negation 1885 1891	unable
E1007	Negation:T1014 Scope:T1015
T1015	Span 1871 1956	is apparently unable to bind to the endogenous Ig heavy chain enhancer in non-B cells
T1016	Speculation 1958 1965	perhaps
E1008	Speculation:T1016 Scope:T1017
T1017	Span 1958 2037	perhaps due to a non-permissive chromatin structure of the Ig heavy chain locus
