T1000	Negation 920 923	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 869 958	NFAT activation by a G-protein-coupled receptor is not modulated by p95vav overexpression
T1002	Speculation 568 575	unclear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 510 575	The role of p95vav in TCR-mediated signaling processes is unclear
T1004	Speculation 1152 1159	appears
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1140 1202	this region appears to be required for its function in T cells
T1006	Speculation 960 970	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 960 1028	suggesting that the effect is specific to the TCR signaling pathways
T1008	Speculation 1421 1431	suggesting
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1421 1477	suggesting that its activity also depends on calcineurin
T1010	Negation 1270 1273	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1232 1300	the p95vav-induced NFAT activation is not mimicked by Ras activation
T1012	Speculation 1751 1757	appear
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1717 1856	overexpression of p95vav does not appear to influence TCR-induced protein tyrosine phosphorylation or increases in cytoplasmic free calcium
T1014	Negation 1747 1750	not
E1007	Negation:T1014 Scope:T1015
T1015	Span 1717 1856	overexpression of p95vav does not appear to influence TCR-induced protein tyrosine phosphorylation or increases in cytoplasmic free calcium
T1016	Speculation 1883 1890	suggest
E1008	Speculation:T1016 Scope:T1017
T1017	Span 1883 1996	suggest that p95vav plays an important role at an yet unidentified proximal position in the TCR signaling cascade
