T1000	Speculation 627 637	apparently
E1000	Speculation:T1000 Scope:T1001
T1001	Span 627 662	apparently from within the enhancer
T1002	Negation 285 288	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 285 294	not known
T1004	Speculation 1202 1205	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1202 1326	may (i) open up the chromatin structure of a gene domain and (ii) deliver enhancer binding proteins to the promoter sequence
T1006	Negation 832 835	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 832 846	not detectable
T1008	Speculation 1338 1341	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1338 1397	may stimulate the transcription of the gene at the cap site
