T1000	Negation 978 985	absence
E1000	Negation:T1000 Scope:T1001
T1001	Span 978 1008	absence of NF-kappaB signaling
T1002	Speculation 261 269	believed
E1001	Speculation:T1002 Scope:T1003
T1003	Span 229 316	Many of the effects of CD40 are believed to be achieved through altered gene expression
T1004	Speculation 1028 1035	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1028 1143	suggest that CD40-mediated cell survival proceeds through NF-kappaB-dependent up-regulation of Bcl-2 family members
