T1000	Speculation 1303 1316	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1303 1416	indicate that LTB4 may regulate the production of different cytokines by modulating the yield and/or the function
T1002	Negation 915 918	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 873 935	Stability of the c-fos and c-jun mRNA was not affected by LTB4
T1004	Speculation 1397 1403	and/or
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1387 1486	the yield and/or the function of transcription factors such as AP-1-binding proto-oncogene products
T1006	Speculation 1322 1325	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1322 1486	may regulate the production of different cytokines by modulating the yield and/or the function of transcription factors such as AP-1-binding proto-oncogene products
