T1000	Speculation 1463 1470	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1463 1604	suggest that the germinal center reaction provides unique activation signals to B cells that allow for continued, high-level BCL-6 expression
T1002	Speculation 1342 1352	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1342 1442	suggesting that BCL-6 protein levels are controlled by translational or posttranslational mechanisms
