T1000	Speculation 942 950	probably
E1000	Speculation:T1000 Scope:T1001
T1001	Span 942 1000	probably located upstream of activation of phospholipase C
T1002	Speculation 572 580	possibly
E1001	Speculation:T1002 Scope:T1003
T1003	Span 572 609	possibly syk protein tyrosine kinases
T1004	Speculation 1085 1095	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1085 1217	suggesting that SIT not only regulates NF-AT activity but also controls NF-AT unrelated pathways of T cell activation involving SHP2
T1006	Negation 1037 1040	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1011 1083	binding of SHP2 to SIT is not required for inhibition of NF-AT induction
