T1000	Negation 665 668	nor
E1000	Negation:T1000 Scope:T1001
T1001	Span 665 705	nor the activity of the lck gene product
T1002	Negation 629 632	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 629 663	not to inhibit lck gene expression
T1004	Speculation 963 976	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 963 1080	indicate that the immunosuppressant action of CsA and FK506 is exerted at the level of these trans-activating factors
