T1000	Speculation 321 324	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 299 416	Viral gene expression may be reactivated by stimulation of the cells with LPS or cytokines such as TNF-alpha in vitro
T1002	Speculation 226 229	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 226 297	may harbor HIV in a nonproductive fashion for prolonged periods of time
T1004	Negation 1635 1638	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1635 1732	not mediate the translocation of NF-kappa B p50/p65 induced by triggering of complement receptors
T1006	Negation 926 933	absence
E1003	Negation:T1006 Scope:T1007
T1007	Span 926 1014	absence of F(ab')2 fragments of monoclonal anti-CR1 or anti-CR3 Abs or with C3 fragments
T1008	Speculation 1802 1805	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1802 2033	may be activated in infected monocytes through interaction of the cells with complement-opsonized particles and that enhanced viral replication is associated with C3 receptor-mediated nuclear translocation of the NF-kappa B complex
T1010	Speculation 1769 1776	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1769 1909	suggest that HIV gene expression may be activated in infected monocytes through interaction of the cells with complement-opsonized particles
