T1000	Negation 1727 1730	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1727 1788	not induce the HIV LTR above a constitutive level of activity
T1002	Speculation 736 746	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 736 872	suggesting that HIV-infected monocytic cells produced higher levels of TNF-alpha than did normal cells after a secondary virus infection
T1004	Speculation 1836 1843	appears
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1790 1885	This level of NF-kappa B-independent activity appears to be sufficient for virus multiplication
T1006	Negation 1917 1919	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1917 2021	no effect on the kinetics of de novo HIV type 1 (HIV-1) infection and viral RNA production in U937 cells
T1008	Speculation 2164 2179	indicating that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2164 2249	indicating that in T cells HIV-1 multiplication was stimulated by TNF-alpha treatment
