T1000	Negation 1271 1273	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 1271 1313	no differences in affinity were detectable
T1002	Negation 878 880	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 878 945	no significant influence on the binding of all-trans RA or 9-cis RA
T1004	Speculation 1461 1464	can
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1461 1583	can conclude that electrostatic interactions of retinoids with the RAR alpha-LBD play a significant role in ligand binding
T1006	Negation 1408 1410	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1408 1436	no change in agonist binding
T1008	Speculation 1678 1681	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1678 1776	may contribute to their interference in the ligand-inducible transactivation function of RAR alpha
