T1000	Negation 869 876	absence
E1000	Negation:T1000 Scope:T1001
T1001	Span 869 906	absence of their DNA-binding activity
T1002	Negation 807 814	absence
E1001	Negation:T1002 Scope:T1003
T1003	Span 807 853	absence of JunB, FosB, and c-Fos transcription
T1004	Speculation 925 938	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 925 1199	indicate that, despite the rapidity of NK cell-mediated lysis, AP-1 transcription factor is activated during the early stage of NK cell cytolytic programs and that engagement of NK cell inhibitory receptors for MHC class I molecules impairs the very early activation of AP-1
