T1000	Negation 787 789	No
E1000	Negation:T1000 Scope:T1001
T1001	Span 787 851	No positive effect of the duplicated CTG-motif could be detected
T1002	Negation 585 589	Cell
E1001	Negation:T1002 Scope:T1003
T1003	Span 585 785	Cell culture experiments demonstrated that the natural variant with four Sp1 sites had a slightly higher promoter activity and viral replication rate than the isogenic control LTR with three Sp1 sites
T1004	Speculation 1195 1203	estimate
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1195 1297	estimate a 5-10% difference in virus production of the LTR variants when compared to that of wild-type
