T1000	Speculation 823 830	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 823 939	whether GATA-1 expression involves additional regulatory factors or is maintained entirely by an autoregulatory loop
T1002	Speculation 753 763	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 753 810	suggesting autoregulatory control of GATA-1 transcription
T1004	Negation 1493 1496	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1462 1554	de novo induction of GATA-1 is not required for globin gene activation following cell fusion
T1006	Speculation 888 890	or
E1003	Speculation:T1006 Scope:T1007
T1007	Span 849 939	involves additional regulatory factors or is maintained entirely by an autoregulatory loop
T1008	Speculation 1446 1461	indicating that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1446 1554	indicating that de novo induction of GATA-1 is not required for globin gene activation following cell fusion
