T1000	Speculation 884 892	putative
E1000	Speculation:T1000 Scope:T1001
T1001	Span 884 932	putative binding sites for transcription factors
T1002	Negation 979 982	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 979 992	not by C/EBPs
T1004	Speculation 1143 1146	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1143 1261	may be critical factors for modulating the differentiation-dependent transcription of this human carboxylesterase gene
T1006	Speculation 1020 1033	indicate that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1020 1261	indicate that carboxylesterase gene transcription in THP-1 cells starts at multiple initiation sites and that Sp1 and IRBP may be critical factors for modulating the differentiation-dependent transcription of this human carboxylesterase gene
