T1000	Negation 810 813	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 810 847	not with exogenous IL-2 growth factor
T1002	Speculation 422 428	likely
E1001	Speculation:T1002 Scope:T1003
T1003	Span 422 490	likely contributes to the tissue specificity of IL-2 gene expression
T1004	Speculation 1057 1063	either
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1057 1119	either lectin or antibody to the CD3 or CD28 surface molecules
