T1000	Negation 1184 1187	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1178 1207	it is not regulated correctly
T1002	Speculation 911 925	indicates that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 911 1097	indicates that recombinant NFAT1 localizes in the cytoplasm of transiently transfected T cells and translocates into the nucleus in a CsA-sensitive manner following ionomycin stimulation
T1004	Speculation 1553 1563	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1553 1663	suggesting that NFAT1 contributes to the CsA-sensitive transcription of these genes during the immune response
T1006	Negation 1271 1274	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1271 1366	not affected by stimulation of the COS cells with ionomycin and phorbol 12-myristate 13-acetate
