T1000	Speculation 1617 1620	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1617 1729	may induce the differentiation of promonocytic cells, independently of their capacity to cause DNA strand breaks
T1002	Negation 521 524	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 502 577	these effects were not observed upon pulse-treatment with 6 microM ICRF-193
T1004	Speculation 1825 1833	probably
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1815 1918	which are probably derived from the production of primary DNA breakage by some anti-topoisomerase drugs
