T1000	Negation 497 504	absence
E1000	Negation:T1000 Scope:T1001
T1001	Span 497 541	absence of in vitro treatment of these cells
T1002	Speculation 276 283	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 272 375	are thought to be critical for the transcription of genes involved in immune and inflammatory responses
T1004	Speculation 1239 1246	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1239 1428	suggest that p65 and c-Rel complexes play distinct roles in gene expression and that both forms of NF-kappa B play critical roles during late stages of the intrathymic maturation of T cells
T1006	Speculation 875 884	suggested
E1003	Speculation:T1006 Scope:T1007
T1007	Span 875 947	suggested a preferential activation of p50/c-Rel in medullary thymocytes
