T1000	Speculation 1191 1204	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1191 1329	indicate that suppression of cytokine and NO generation by Azeptin results at least partially from the inhibition of NF-kappa B activation
T1002	Speculation 1181 1187	appear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1167 1329	These results appear to indicate that suppression of cytokine and NO generation by Azeptin results at least partially from the inhibition of NF-kappa B activation
