T1000	Speculation 1057 1060	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1057 1197	may activate their respective receptors and initiate an autocrine regulatory mechanism for persistent cytokine and chemokine gene expression
T1002	Speculation 805 811	appear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 771 949	The underlying signaling pathways appear to be different from those utilized by TNF-alpha, a better characterized cytokine that induces the transcription of immediate-early genes
