T1000	Negation 600 603	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 600 626	not of NF-kB and OCT-1/OAF
T1002	Speculation 237 244	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 237 404	whether dexamethasone (Dex) and cyclosporin A (CsA) inhibit IL-2 gene transcription by interfering with the activity of nuclear proteins that bind to the IL-2 promoter
T1004	Negation 1157 1160	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1157 1188	not the AP-1 and NF-kB plasmids
T1006	Negation 1059 1062	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1059 1091	not the NF-AT and NF-kB plasmids
T1008	Speculation 1358 1365	propose
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1358 1452	propose that, while maximum inhibition may involve interaction with both transcription factors
T1010	Speculation 1204 1211	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1204 1353	suggest that in human T lymphocytes both Dex and CsA inhibited IL-2 gene transcription through interference with transcription factors AP-1 and NF-AT
T1012	Speculation 1397 1400	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1397 1487	may involve interaction with both transcription factors, AP-1 is the primary target of Dex
