T1000	Speculation 218 225	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 218 270	whether an active negative regulatory process occurs
T1002	Negation 185 188	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 92 205	The molecular mechanism underlying IL-2 transcriptional blockade in anergic T cell clones is not fully understood
T1004	Speculation 980 994	indicated that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 980 1119	indicated that the presence of both the -130 AP-1-like site (-187 to -181) and the -150 proximal AP-1 site were necessary to observe anergy
T1006	Negation 668 671	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 668 715	not impart the ability to be affected by anergy
T1008	Speculation 1188 1196	possible
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1188 1313	possible to confirm by mutation in the normal mouse IL-2 enhancer that this site is absolutely essential for anergy induction
T1010	Negation 1146 1149	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1129 1179	the -180 site is not required for trans-activation
