T1000	Negation 815 818	The
E1000	Negation:T1000 Scope:T1001
T1001	Span 815 1127	The mechanism of this effect is that Bcl-2 prevents the nuclear translocation of NFAT (nuclear factor of activated T lymphocytes, a transcription factor activated by microtubule damage) by binding and sequestering calcineurin, a calcium-dependent phosphatase that must dephosphorylate NFAT to move to the nucleus
T1002	Speculation 472 479	unclear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 426 479	the mechanism of the antiapoptotic effects is unclear
T1004	Negation 1182 1185	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1165 1197	the FasL gene is not transcribed
T1006	Negation 1129 1136	Without
E1003	Negation:T1006 Scope:T1007
T1007	Span 1129 1163	Without NFAT nuclear translocation
T1008	Speculation 1692 1695	can
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1692 1729	can occur after Bcl-2 phosphorylation
T1010	Speculation 1208 1215	appears
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1208 1339	appears that paclitaxel and other drugs that disturb microtubule function kill cells at least in part through the induction of FasL
