T1000	Speculation 347 355	probably
E1000	Speculation:T1000 Scope:T1001
T1001	Span 347 462	probably due in part to differences in dose, route of exposure, animal species used and/or specific compound tested
T1002	Negation 219 221	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 219 249	no effect on the immune system
T1004	Negation 968 971	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 968 1034	not regain normal TNF-alpha activation, even after 72 h in culture
T1006	Negation 748 751	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 729 786	This inhibition is not accompanied by a loss in viability
T1008	Negation 1140 1143	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1140 1185	not diminish binding activity of this protein
T1010	Negation 1047 1050	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1047 1085	not appear to alter NF-kappaB directly
T1012	Speculation 1051 1057	appear
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1036 1085	DMDTC does not appear to alter NF-kappaB directly
