T1000	Speculation 360 370	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 360 441	suggesting that an active v-abl protein interferes with this differentiation step
T1002	Negation 331 334	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 331 358	not their light chain genes
T1004	Speculation 1469 1476	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1469 1553	suggest that tyrosine phosphorylation is important in regulating RAG gene expression
T1006	Negation 967 974	absence
E1003	Negation:T1006 Scope:T1007
T1007	Span 967 995	absence of protein synthesis
