T1000	Speculation 412 419	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 372 504	The integral membrane glycoprotein CD36 appears to play a physiological role in binding and uptake of Ox LDL by monocyte-macrophages
T1002	Speculation 318 325	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 315 370	is thought to represent an early event in atherogenesis
T1004	Speculation 1296 1300	idea
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1296 1374	idea that human CD36 mediates signal transduction events in response to Ox LDL
T1006	Speculation 580 587	unknown
E1003	Speculation:T1006 Scope:T1007
T1007	Span 515 587	the molecular events associated with CD36-Ox LDL interaction are unknown
