T1000	Speculation 1498 1505	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1498 1724	suggest a novel mechanism by which integrin-mediated cell adhesion can modulate the magnitude of cytokine-induced signal transduction pathways, thereby amplifying cellular events leading to monocyte activation and inflammation
T1002	Speculation 407 410	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 407 478	may influence leukocyte phenotype and function at sites of inflammation
