T1000	Negation 1067 1070	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1067 1103	not the constitutive binding protein
T1002	Negation 349 356	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 349 380	without intentional stimulation
T1004	Negation 1419 1422	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1377 1458	the amount of constitutive NF-kappa B was not increased in more mature cell lines
T1006	Negation 1288 1291	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1288 1328	not in Molt 4 T cells or K562 stem cells
T1008	Speculation 1790 1797	appears
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1762 1823	The constitutive NF-kappa B appears to be functionally active
T1010	Negation 1541 1543	no
E1005	Negation:T1010 Scope:T1011
T1011	Span 1541 1606	no change in constitutive or inducible NF-kappa B can be detected
T1012	Negation 2370 2373	not
E1006	Negation:T1012 Scope:T1013
T1013	Span 2370 2414	not reduce constitutive DNA-binding activity
T1014	Negation 2162 2165	not
E1007	Negation:T1014 Scope:T1015
T1015	Span 2134 2334	Constitutive NF-kappa B was not maintained by autocrine action of cytokines TNF, interleukin 6, interleukin 10, granulocyte-macrophage colony-stimulating factor or macrophage colony-stimulating factor
T1016	Negation 2487 2490	not
E1008	Negation:T1016 Scope:T1017
T1017	Span 2487 2532	not affect constitutive NF-kappa B. (ABSTRACT
