T1000	Negation 1770 1773	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1770 1807	not blocking p50 and p55 interactions
T1002	Speculation 1405 1415	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1405 1500	suggesting that both of these basic amino acids are required for binding to the kappa B element
T1004	Speculation 1824 1831	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1824 1963	suggest that reduced cysteine thiols play an important role in the DNA binding activity of this family of Rel-related transcription factors
