T1000	Speculation 1206 1211	might
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1206 1271	might be particularly deleterious in preinjured or infected lungs
T1002	Speculation 1167 1177	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1167 1271	suggesting that mechanical ventilation might be particularly deleterious in preinjured or infected lungs
T1004	Negation 1545 1551	failed
E1002	Negation:T1004 Scope:T1005
T1005	Span 1545 1626	failed to produce IL-8 in response to a prolonged cyclic pressure-stretching load
