T1000	Negation 741 744	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 741 792	not NF-kappa B translocation or LTR transactivation
T1002	Negation 112 115	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 112 179	not human immunodeficiency virus 1 enhancer-dependent transcription
T1004	Negation 1214 1217	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1214 1293	not sufficient to induce HIV enhancer-dependent transcription in cloned T cells
T1006	Negation 943 946	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 943 946	not
T1008	Speculation 1504 1511	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1504 1679	suggest that events linked to T-cell activation, in addition to NF-kappa B translocation per se, induce functional interactions of the NF-kappa B complex with the HIV enhancer
T1010	Speculation 1366 1380	indicates that
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1366 1477	indicates that normal T lymphocytes differ from tumoral T cells in terms of requirements for HIV LTR activation
