T1000	Speculation 772 781	potential
E1000	Speculation:T1000 Scope:T1001
T1001	Span 772 867	potential role of PGE2 in C3a-mediated enhancement of LPS- and IL-1beta-induced IL-6 production
T1002	Negation 426 428	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 426 474	no effect on the expression or secretion of IL-6
T1004	Speculation 957 967	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 957 1057	suggesting that the effects of C3a on IL-6 production are independent of PGE2 formation by monocytes
T1006	Negation 912 914	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 912 955	no influence on the observed effects of C3a
T1008	Speculation 1253 1268	indicating that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1253 1347	indicating that the actions of these two molecules are mediated by a G protein-coupled pathway
