T1000	Negation 888 890	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 888 969	no evidence for involvement of GSK-3beta in Tcf-mediated transcription in T cells
T1002	Speculation 590 600	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 590 681	suggesting that the Wnt signal transduction pathway is operational in T lymphocytes as well
T1004	Negation 1143 1146	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1143 1174	not activate Tcf reporter genes
