T1000	Speculation 1300 1307	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1300 1450	suggest that inhibition of NF kappa B activation may be an important mechanism for IL-10 suppression of cytokine gene transcription in human monocytes
T1002	Negation 795 798	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 698 816	Several other transcription factors including NF-IL-6, AP-1, AP-2, GR, CREB, Oct-1, and Sp-1 are not affected by IL-10
T1004	Negation 1687 1690	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1687 1727	not suppress cytokine gene transcription
T1006	Speculation 1349 1352	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1349 1450	may be an important mechanism for IL-10 suppression of cytokine gene transcription in human monocytes
T1008	Speculation 1740 1753	indicate that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1740 1820	indicate that IL-10 and IL-4 inhibit cytokine production by different mechanisms
