T1000	Speculation 773 788	indicating that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 773 855	indicating that lambda5 is a direct genetic target for these transcription factors
T1002	Negation 447 451	lack
E1001	Negation:T1002 Scope:T1003
T1003	Span 447 464	lack both factors
T1004	Speculation 884 891	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 884 1011	suggest that EBF and E47 synergize to activate expression of a subset of genes that define an early stage of the B cell lineage
