T1000	Speculation 986 993	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 986 1054	suggest that additional factor(s) are necessary for full ER function
T1002	Negation 764 767	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 721 782	the binding activities of NF1 and Sp1 were not affected by ER
T1004	Speculation 1185 1196	hypothesize
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1185 1345	hypothesize that interference in DNA-binding activities of GATA-1 and CACCC-binding proteins is the mechanism by which the ER inhibits regulation of these genes
