T1000	Negation 836 839	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 836 980	not IL-1, IL-2, macrophage colony-stimulating factor, granulocyte/macrophage colony-stimulating factor, IL-6, or transforming growth factor beta
T1002	Negation 261 264	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 205 277	the mechanism by which IFNs mediate this inhibition has not been defined
T1004	Negation 1135 1138	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1135 1146	not evident
