T1000	Speculation 356 361	might
E1000	Speculation:T1000 Scope:T1001
T1001	Span 356 602	might be an important trigger for a sequence of gene activation culminating in cells with increased mRNA encoding profibrotic growth factors such as platelet-derived growth factor B subunit (PDGF[B]) and transforming growth factor-beta (TGF-beta)
T1002	Speculation 321 333	hypothesized
E1001	Speculation:T1002 Scope:T1003
T1003	Span 321 602	hypothesized that adherence itself might be an important trigger for a sequence of gene activation culminating in cells with increased mRNA encoding profibrotic growth factors such as platelet-derived growth factor B subunit (PDGF[B]) and transforming growth factor-beta (TGF-beta)
T1004	Negation 1383 1386	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1383 1392	not c-fos
T1006	Negation 714 716	No
E1003	Negation:T1006 Scope:T1007
T1007	Span 714 755	No increase in TGF-beta mRNA was observed
T1008	Speculation 1596 1599	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1596 1636	may depend on cytoskeletal rearrangement
T1010	Speculation 1456 1463	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1456 1539	suggest that adherence results in increases of c-fos, c-jun, EGR2, and PDGF(B) mRNA
T1012	Speculation 1752 1755	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1718 1771	differential priming of the cells may be accomplished
