T1000	Speculation 824 832	believed
E1000	Speculation:T1000 Scope:T1001
T1001	Span 811 880	oxidants are believed to promote intestinal epithelial cell apoptosis
T1002	Speculation 732 740	believed
E1001	Speculation:T1002 Scope:T1003
T1003	Span 729 800	is believed to be important in regulating cell growth and proliferation
T1004	Speculation 1040 1047	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1040 1250	suggest that nontoxic concentrations of reactive metabolites of oxygen and nitrogen play an important role in regulating the expression of genes involved in the inflammatory response and in modulating apoptosis
T1006	Speculation 933 941	believed
E1003	Speculation:T1006 Scope:T1007
T1007	Span 886 1003	the B-cell lymphoma/leukemia-2 gene product is believed to inhibit this phenomenon in an antioxidant-dependent manner
