T1000	Speculation 1085 1096	potentially
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1085 1142	potentially dysfunctional T cells in patients with cancer
T1002	Speculation 837 840	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 837 889	may interfere with the activation of c-jun and c-fos
T1004	Negation 1494 1497	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1443 1599	the NFKB family members Rel-A, Rel-B and c-Rel are not required for the transcription of IL-2 in the peripheral T lymphocytes of patients with breast cancer
T1006	Speculation 1199 1202	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1199 1278	may allow patients with significant defects in T-cell signaling to go unnoticed
T1008	Speculation 1430 1437	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1430 1599	suggest that the NFKB family members Rel-A, Rel-B and c-Rel are not required for the transcription of IL-2 in the peripheral T lymphocytes of patients with breast cancer
