T1000	Speculation 1365 1374	speculate
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1365 1546	speculate that enhanced NF-kappa B expression caused by free radical production/oxidative stress may modulate liver injury, perhaps through an effect on cytotoxic cytokine synthesis
T1002	Speculation 192 195	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 192 279	may represent a common mechanism by which liver injury is induced by diverse etiologies
T1004	Speculation 1489 1496	perhaps
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1489 1546	perhaps through an effect on cytotoxic cytokine synthesis
T1006	Speculation 1462 1465	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1462 1546	may modulate liver injury, perhaps through an effect on cytotoxic cytokine synthesis
