T1000	Speculation 1471 1485	indicates that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1471 1625	indicates that activated platelets modulate chemotactic (MCP-1) and adhesive (ICAM-1) properties of endothelial cells via an NF-kappaB-dependent mechanism
T1002	Negation 1321 1324	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1321 1344	not of the mutated form
T1004	Speculation 1679 1684	might
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1679 1741	might contribute to early inflammatory events in atherogenesis
