T1000	Speculation 1245 1248	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1245 1398	may represent the first identified natural DNA response element for the TR2 orphan receptor that may function as a repressor for the SV40 gene expression
T1002	Speculation 1222 1229	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1222 1398	suggest the TR2RE-SV40 may represent the first identified natural DNA response element for the TR2 orphan receptor that may function as a repressor for the SV40 gene expression
T1004	Speculation 1342 1345	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1342 1398	may function as a repressor for the SV40 gene expression
