T1000	Negation 776 779	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 776 811	not reflect constitutive expression
T1002	Speculation 118 126	putative
E1001	Speculation:T1002 Scope:T1003
T1003	Span 118 168	putative G0/G1 switch regulatory genes (G0S genes)
T1004	Speculation 1368 1375	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1368 1406	suggest different roles and regulation
T1006	Speculation 693 700	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 693 811	suggest that the high initial levels are caused by the isolation procedure, and do not reflect constitutive expression
T1008	Speculation 1721 1728	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1721 1796	suggest that the potential may help locate genes in uncharted DNA sequences
T1010	Speculation 1509 1517	indicate
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1509 1601	indicate where base order has been adapted for purposes other than stem-loop stability (e.g.
T1012	Speculation 1748 1751	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1748 1796	may help locate genes in uncharted DNA sequences
