T1000	Speculation 986 994	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 986 1142	suggests that the cysteine deficiency in HIV-1-infected individuals may cause an over-expression of NF-kappa B-dependent genes and enhance HIV-1 replication
T1002	Negation 705 708	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 705 750	not to be directly correlated with GSH levels
T1004	Speculation 1148 1151	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1144 1213	NAC may be considered for the treatment of HIV-1-infected individuals
T1006	Speculation 1054 1057	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1054 1142	may cause an over-expression of NF-kappa B-dependent genes and enhance HIV-1 replication
