T1000	Speculation 2121 2124	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 2121 2220	may explain the strong cyto-differentiating potential of AM580 in PML-RAR-containing leukemic cells
T1002	Negation 1099 1102	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1099 1357	not effective as ATRA in modulating the expression of these differentiation markers in the HL-60 cell line and in freshly isolated granulocytes obtained from the peripheral blood of chronic myelogenous leukemia patients during the stable phase of the disease
