T1000	Speculation 804 811	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 751 861	the requirement for CD28 in IL-2 promoter activation appears to be due to RE/AP and not the NFAT or AP-1 sites
T1002	Negation 835 838	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 835 861	not the NFAT or AP-1 sites
T1004	Negation 1002 1005	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 969 1041	activation of a NFAT reporter is not affected by the addition of CTLA4Ig
T1006	Negation 939 942	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 900 1041	transcriptional activation of RE/AP is not mediated by NFAT, because activation of a NFAT reporter is not affected by the addition of CTLA4Ig
T1008	Speculation 887 894	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 887 959	suggest that transcriptional activation of RE/AP is not mediated by NFAT
