T1000	Speculation 299 306	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 299 399	whether this inhibition was mediated via modulation of the cellular transcription factor, NF-kappa B
T1002	Negation 530 537	absence
E1001	Negation:T1002 Scope:T1003
T1003	Span 530 595	absence of ascorbate, N-acetylcysteine (NAC), or zidovudine (AZT)
T1004	Negation 795 798	nor
E1002	Negation:T1004 Scope:T1005
T1005	Span 795 891	nor AZT affected NF-kappa B activity under all three induction conditions in the ACH-2 cell line
T1006	Negation 777 784	neither
E1003	Negation:T1006 Scope:T1007
T1007	Span 777 891	neither ascorbate nor AZT affected NF-kappa B activity under all three induction conditions in the ACH-2 cell line
T1008	Negation 1114 1117	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1056 1194	the molecular mechanism of HIV inhibition by ascorbate is not mediated via NF-kappa B inhibition, unlike that seen with other antioxidants
T1010	Negation 920 922	no
E1005	Negation:T1010 Scope:T1011
T1011	Span 920 1027	no effect on NF-kappa B activation following TNF-alpha- or PMA-induced stimulation of U1 promonocytic cells
T1012	Speculation 1043 1050	suggest
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1043 1152	suggest that the molecular mechanism of HIV inhibition by ascorbate is not mediated via NF-kappa B inhibition
