T1000	Speculation 1461 1466	seems
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1364 1440	the selective appearance of this putative cell-specific transcription factor
T1002	Speculation 1397 1405	putative
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1397 1562	putative cell-specific transcription factor in B lymphoid cells seems to be attributable, at least in part, to the elevated E2A protein concentrations in these cells
