T1000	Negation 595 598	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 595 610	not NF-kappa B1
T1002	Speculation 437 445	appeared
E1001	Speculation:T1002 Scope:T1003
T1003	Span 413 555	the ICAM-1 kappa B site appeared to bind RelA and c-Rel homodimers as well as heterodimers with NF-kappa B1, but weakly NF-kappa B1 homodimers
T1004	Speculation 1307 1313	likely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1287 1398	RelA homodimers are likely to play a dominant role in TNF-alpha-induced ICAM-1 transcription in monocytic cells
