T1000	Negation 1373 1376	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1373 1392	not with PMA/A23187
T1002	Negation 526 529	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 526 553	not that of other cytokines
T1004	Negation 1887 1890	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1887 1930	not for NF-AT, AP-1 or CLE0 binding protein
T1006	Speculation 1406 1413	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1406 1540	suggest that the target of PGE2 action is a component in the signal transduction pathway leading to the activation of protein kinase C
T1008	Speculation 1776 1781	seems
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1776 1930	seems therefore that PGE2, by elevating cAMP levels, interferes with the activation pathway for NF-kappa B but not for NF-AT, AP-1 or CLE0 binding protein
