T1000	Negation 909 912	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 909 947	not from adjacent normal kidney tissue
T1002	Negation 760 763	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 760 772	not protease
T1004	Speculation 1233 1236	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1233 1291	may blunt antitumor immune responses in patients with RCCs
T1006	Speculation 1193 1200	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1193 1291	suggest that tumor-derived gangliosides may blunt antitumor immune responses in patients with RCCs
