T1000	Negation 442 445	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 442 471	not IL-12-stimulated NK cells
T1002	Speculation 264 267	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 264 335	may depend on induced differential expression of specific sets of genes
T1004	Negation 837 840	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 837 846	not IL-12
T1006	Negation 617 620	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 617 626	not IL-12
T1008	Negation 1381 1384	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1381 1538	not involve expression of members of the immediate-early activation genes family (egr-1, c-fos, and junB), AP-1 transcriptional activity, or bcl-2 expression
T1010	Negation 888 891	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 856 919	expression of c-jun and junD is not modified by either cytokine
T1012	Speculation 1628 1631	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1628 1689	may depend, at least in part, on differential gene regulation
T1014	Speculation 1545 1559	indicates that
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1545 1689	indicates that functional differences observed in IL-2- and IL-12-stimulated cells may depend, at least in part, on differential gene regulation
