T1000	Speculation 526 540	indicated that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 526 626	indicated that this upregulation was mediated through the NF-kappa B- but not the AP-1-binding motif
T1002	Negation 600 603	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 600 661	not the AP-1-binding motif, by bona fide p50/p65 heterodimers
T1004	Negation 910 913	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 910 956	not dependent on PKC isoenzymes alpha and beta
T1006	Speculation 694 708	indicated that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 694 763	indicated that NF-kappa B levels were increased in HIV-infected cells
T1008	Speculation 1034 1047	indicate that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1034 1258	indicate that during chronic HIV infection of U937 cells, continuous NF-kappa B (p50/p65) translocation results in p105 promoter upregulation with subsequent cytosolic NF-kappa B accumulation, ready for further translocation
