T1000	Negation 1037 1040	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1037 1040	not
T1002	Negation 880 883	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 870 944	an effect not mediated indirectly by the induction of IFN-gamma production
T1004	Negation 1391 1394	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1391 1439	not block IL-12-dependent up-regulation of IRF-1
T1006	Negation 1316 1318	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1316 1376	no up-regulation of IRF-1 was found in IL-4-stimulated cells
T1008	Speculation 1458 1461	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1458 1508	may be an important contributor to IL-12 signaling
T1010	Negation 1623 1630	absence
E1005	Negation:T1010 Scope:T1011
T1011	Span 1623 1659	absence of this transcription factor
T1012	Speculation 1584 1589	might
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1584 1659	might be attributable, in part, to the absence of this transcription factor
T1014	Speculation 1517 1526	speculate
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1517 1659	speculate that the defective IL-12 responses seen in IRF-1-/- mice might be attributable, in part, to the absence of this transcription factor
