T1000	Negation 516 519	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 516 600	not give direct information about the presence of the proteins during the cell cycle
T1002	Speculation 289 296	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 285 379	are thought to play important roles in the regulation of gene expression during the cell cycle
T1004	Negation 1745 1748	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1736 1784	AP-1 was not detected in the majority of samples
T1006	Negation 1285 1288	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1285 1327	not transiently in the G0 to G1 transition
T1008	Speculation 2151 2161	suggesting
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2151 2254	suggesting that subcellular compartmentalization of these proteinsmay occur under certain circumstances
T1010	Negation 2035 2037	no
E1005	Negation:T1010 Scope:T1011
T1011	Span 2035 2091	no cytoplasmic p62c-fos was detected in unstimulated PBL
