T1000	Negation 1118 1121	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1081 1204	LPS-induced NF-kappaB activation was not inhibited by a dominant negative mutant of TRAF2 that is involved in TNF signaling
T1002	Speculation 429 436	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 402 537	Activation of NF-kappaB is thought to be required for cytokine release from LPS-responsive cells, a critical step for endotoxic effects
T1004	Speculation 1404 1411	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1404 1545	suggest that a signal transduction molecule in the LPS receptor complex may belong to the IL-1 receptor/toll-like receptor (TLR) super family
T1006	Negation 1271 1274	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1206 1312	LPS-induced activation of NF-kappaB-responsive reporter gene was not inhibited by IL-1 receptor antagonist
T1008	Speculation 1476 1479	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1476 1545	may belong to the IL-1 receptor/toll-like receptor (TLR) super family
