T1000	Speculation 764 777	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 764 845	indicate that HTLV-1 Tax targets IkappaBalpha to the ubiquitin-proteasome pathway
T1002	Speculation 88 97	potential
E1001	Speculation:T1002 Scope:T1003
T1003	Span 88 147	potential mechanism for constitutive induction of NF-kappaB
T1004	Speculation 867 874	unclear
E1002	Speculation:T1004 Scope:T1005
T1005	Span 867 959	unclear how this viral protein induces a persistent rather than transient NF-kappaB response
T1006	Negation 919 930	rather than
E1003	Negation:T1006 Scope:T1007
T1007	Span 919 959	rather than transient NF-kappaB response
T1008	Speculation 1688 1697	potential
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1688 1776	potential mechanism for the constitutive activation of NF-kappaB in Tax-expressing cells
