T1000	Negation 1206 1213	without
E1000	Negation:T1000 Scope:T1001
T1001	Span 1206 1261	without affecting the activities of NFkappaB and CD28RC
T1002	Speculation 985 1000	indicating that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 985 1068	indicating that the effect of IL-7 is in part mediated at the transcriptional level
T1004	Negation 1390 1393	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1390 1417	not cyclosporin A-sensitive
