T1000	Negation 1543 1546	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1543 1546	not
T1002	Negation 792 795	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 792 798	not P3
T1004	Speculation 1551 1556	would
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1551 1643	would thus appear that components of each P-like element-binding complexes are not identical
T1006	Negation 1630 1633	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1630 1703	not identical and may coordinately contribute to transcriptional activity
T1008	Speculation 1648 1651	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1648 1703	may coordinately contribute to transcriptional activity
T1010	Speculation 1562 1568	appear
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1562 1703	appear that components of each P-like element-binding complexes are not identical and may coordinately contribute to transcriptional activity
