T1000	Speculation 1681 1689	possible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1675 1733	it is possible to modulate IFN-beta transcription in vitro
T1002	Speculation 1251 1261	indicating
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1251 1311	indicating predominantly negative regulation of the promoter
T1004	Speculation 1772 1775	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1752 1828	additional proteins may be required to fully activate IFN-beta transcription
T1006	Speculation 1738 1751	indicate that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1738 1828	indicate that additional proteins may be required to fully activate IFN-beta transcription
