T1000	Negation 857 860	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 857 885	not IL-5-nonproducing clones
T1002	Speculation 238 241	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 238 294	may be effective for the management of allergic diseases
T1004	Negation 1321 1323	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1321 1379	no significant upregulation of binding by IL-2 stimulation
T1006	Negation 1044 1047	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1044 1106	not by hybridomas derived from IL-5-nonproducing T-cell clones
T1008	Speculation 1644 1647	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1644 1695	may be useful for treating eosinophlic inflammation
T1010	Speculation 1564 1569	seems
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1475 1594	A unique transcriptional mechanism distinct from those regulating the IL-2 or IL-4 genes seems to control the IL-5 gene
