T1000	Negation 1439 1442	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1358 1451	the activity of four other transcription factors, Oct-1, TBP, Sp1 and STAT 5 was not affected
T1002	Speculation 930 933	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 829 991	This difference in efficacy, which correlates with the compounds' anti-inflammatory potency in vivo, may be explained by differences in structure and conformation
T1004	Speculation 1654 1661	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1654 1862	suggest a molecular mechanism for the anti-inflammatory effect of sesquiterpene lactones, which differs from that of other nonsteroidal anti-inflammatory drugs (NSAIDs), indomethacin and acetyl salicylic acid
T1006	Negation 1480 1483	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1480 1548	not due to a direct modification of the active NF-kappaB heterodimer
