T1000	Speculation 1435 1448	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1435 1546	indicate that iNO attenuates iNOS expression in macrophages and inhibits monocyte adhesion to endothelial cells
T1002	Speculation 256 265	not known
E1001	Speculation:T1002 Scope:T1003
T1003	Span 216 265	its role in the inflammatory process is not known
T1004	Speculation 1590 1593	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1590 1659	may be an important autoregulatory inhibitor of vascular inflammation
T1006	Speculation 1552 1559	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1552 1659	suggest that endogenously derived iNO may be an important autoregulatory inhibitor of vascular inflammation
