T1000	Negation 485 488	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 485 502	not of SMX itself
T1002	Speculation 216 223	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 182 262	subsequent protein conjugation is thought to be involved in SMX hypersensitivity
T1004	Negation 1155 1157	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1155 1164	no effect
T1006	Speculation 760 770	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 760 837	suggesting that this is an important and ubiquitous bioinactivation mechanism
T1008	Speculation 1678 1681	can
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1678 1687	can occur
T1010	Speculation 1418 1425	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1418 1558	suggest that the balance between oxidation of SMX to its toxic metabolites and their reduction is an important protective cellular mechanism
T1012	Speculation 1693 1696	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1693 1728	may result in drug hypersensitivity
