T1000	Negation 868 871	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 809 880	secretion of IL-2 and expression of the IL-2 receptor were not affected
T1002	Speculation 319 322	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 319 382	may cleave the NF-kappa B precursor to its active form in vitro
T1004	Speculation 943 951	unlikely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 943 1019	unlikely to have a significant effect on virus expression or T cell function
