T1000	Speculation 810 817	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 810 920	suggest that CD30 critically regulates the CD40-mediated differentiation of non-antigen-selected human B cells
T1002	Speculation 425 433	possibly
E1001	Speculation:T1002 Scope:T1003
T1003	Span 425 549	possibly through interference with the CD40-mediated NF-kappaB-dependent transcriptional activation of downstream C(H) genes
