T1000	Negation 554 559	fails
E1000	Negation:T1000 Scope:T1001
T1001	Span 554 722	fails to generate vitamin D-responsive element (VDRE)-reactive nuclear protein complexes or to initiate the genomic transcription of 25-hydroxyvitamin D3 24-hydroxylase
T1002	Negation 233 236	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 233 261	not constitutively expressed
T1004	Speculation 908 916	apparent
E1002	Speculation:T1004 Scope:T1005
T1005	Span 908 951	apparent lack of response to the secosterol
T1006	Negation 917 921	lack
E1003	Negation:T1006 Scope:T1007
T1007	Span 917 1055	lack of response to the secosterol can be overcome by stimulation of B lymphocytes with a combination of these cellular activation signals
T1008	Speculation 1224 1231	appears
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1154 1403	cellular activation associated with stimulation of such a progression appears to be sufficient for the up-regulation of VDR message and protein and necessary for the establishment of VDRE binding complexes and the induction of 24-hydroxylase message
T1010	Speculation 952 955	can
E1005	Speculation:T1010 Scope:T1011
T1011	Span 903 951	this apparent lack of response to the secosterol
T1012	Speculation 1552 1559	suggest
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1552 1681	suggest that reactivity to 1 alpha,25(OH)2D3 is tightly regulated in B lymphocytes, requiring specific signals for its initiation
