T1000	Speculation 330 335	could
E1000	Speculation:T1000 Scope:T1001
T1001	Span 330 377	could explain this selective activity of c-ErbB
T1002	Speculation 305 313	possible
E1001	Speculation:T1002 Scope:T1003
T1003	Span 305 377	possible mechanisms that could explain this selective activity of c-ErbB
T1004	Negation 824 830	failed
E1002	Negation:T1004 Scope:T1005
T1005	Span 824 868	failed to induce reporter gene transcription
T1006	Negation 681 687	unable
E1003	Negation:T1006 Scope:T1007
T1007	Span 681 736	unable to induce any of these effects in the same cells
