T1000	Negation 993 997	lack
E1000	Negation:T1000 Scope:T1001
T1001	Span 993 1018	lack of sequence homology
T1002	Speculation 726 728	or
E1001	Speculation:T1002 Scope:T1003
T1003	Span 720 779	Oct-1 or an immunologically related octamer-binding protein
T1004	Speculation 1114 1120	likely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1106 1186	that is likely to be important for the T-cell-specific expression of these genes
