T1000	Speculation 687 692	might
E1000	Speculation:T1000 Scope:T1001
T1001	Span 682 740	cAMP might be involved in c-fos induction via H2 receptors
T1002	Speculation 666 676	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 666 740	suggesting that cAMP might be involved in c-fos induction via H2 receptors
T1004	Negation 865 867	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 865 951	no effect was observed with bisindolylmaleimide, a specific protein kinase C inhibitor
T1006	Negation 742 753	Furthermore
E1003	Negation:T1006 Scope:T1007
T1007	Span 742 951	Furthermore, studies carried out using H7, a protein kinase A/protein kinase C inhibitor, blocked c-fos induction, whereas no effect was observed with bisindolylmaleimide, a specific protein kinase C inhibitor
T1008	Negation 1242 1248	failed
E1004	Negation:T1008 Scope:T1009
T1009	Span 1242 1306	failed to affect proliferation and differentiation of U937 cells
T1010	Negation 953 955	No
E1005	Negation:T1010 Scope:T1011
T1011	Span 953 1051	No modification of c-myc expression could be detected on treatment with histamine or its analogues
T1012	Speculation 1574 1587	indicate that
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1574 1819	indicate that histamine activates several mechanisms involved in the induction of differentiation, such as cAMP and c-fos production, but fails to promote differentiation of U937 cells, apparently due to the rapid desensitization of H2 receptors
T1014	Negation 1712 1717	fails
E1007	Negation:T1014 Scope:T1015
T1015	Span 1712 1819	fails to promote differentiation of U937 cells, apparently due to the rapid desensitization of H2 receptors
T1016	Speculation 1760 1770	apparently
E1008	Speculation:T1016 Scope:T1017
T1017	Span 1760 1819	apparently due to the rapid desensitization of H2 receptors
