T1000	Negation 897 900	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 897 934	not by the unlabeled AP1 binding site
T1002	Speculation 455 462	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 455 550	whether NF(P), a nuclear factor specific for the P sequence, is related to NF-kappa B and NF-AT
T1004	Negation 1359 1362	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1359 1403	not contain AP1 as its DNA binding component
T1006	Speculation 1185 1198	indicate that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1185 1332	indicate that the component(s) of NF-AT has the potential to reconstitute NF(P) whereas NF-kappa B alone cannot account for NF(P) in crude extracts
