T1000	Speculation 801 816	indicating that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 801 872	indicating that ras activity is required for antigen receptor signaling
T1002	Negation 534 537	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 534 588	not replace either the calcium signal or interleukin-1
T1004	Speculation 965 975	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 965 1006	suggesting a role for ras upstream of PKC
