T1000	Speculation 225 228	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 225 281	may play an important role in modulating immune function
T1002	Speculation 114 128	indicated that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 114 281	indicated that the response of transcription factor NF-kappaB to alterations in the redox homeostasis of cells may play an important role in modulating immune function
T1004	Speculation 591 596	might
E1002	Speculation:T1004 Scope:T1005
T1005	Span 591 629	might occur during cellular senescence
T1006	Speculation 542 552	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 542 629	suggesting that impaired activation of NF-kappaB might occur during cellular senescence
T1008	Speculation 1814 1821	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1814 1927	suggest that the redox regulation in NF-kappaB activation may be relevant to immune-related diseases and to aging
T1010	Speculation 1521 1535	indicates that
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1521 1586	indicates that full activation of NF-kappaB requires dual signals
T1012	Speculation 1872 1875	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1872 1927	may be relevant to immune-related diseases and to aging
