T1000	Speculation 1494 1507	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1494 1648	indicate that the signaling events initiated in PBMCs by oligomerization of CD4 at the D1/CDR2-loop can trigger HIV-1 upregulation in infected individuals
T1002	Negation 1283 1286	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1260 1398	virus reactivation was not observed following CD4 oligomerization by antibodies that bind other epitopes in D1, including the D1/CDR3-loop
