T1000	Speculation 1285 1288	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1255 1336	subsequent cellular responses may be driven by induction of similar sets of genes
T1002	Speculation 1162 1169	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1162 1336	suggest that IL-2 and IL-7 induce assembly of STAT heterodimers in a similar manner and that subsequent cellular responses may be driven by induction of similar sets of genes
