T1000	Negation 594 597	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 559 635	the induction of HIV expression is not mediated by endogenous TNF alpha/beta
T1002	Negation 516 519	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 516 554	not alter proliferation of ACH-2 cells
T1004	Speculation 879 882	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 879 1070	may be important in the activation of HIV expression from latently infected CD4+ T cells, especially in lymphoid organs where cell to cell contact is conducive to receptor-ligand interactions
