T1000	Negation 779 782	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 779 824	not stimulate the HIV enhancer in these cells
T1002	Speculation 281 288	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 281 356	whether specific members of the NF-kappa B family contribute to this effect
T1004	Speculation 901 904	can
E1002	Speculation:T1004 Scope:T1005
T1005	Span 901 985	can act in concert with the tat-I gene product to stimulate the synthesis of HIV RNA
T1006	Speculation 841 848	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 841 985	suggest that the combination of p49(100) and p65 NF-kappa B can act in concert with the tat-I gene product to stimulate the synthesis of HIV RNA
