T1000	Speculation 1842 1852	hypothesis
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1842 2023	hypothesis that LTR mutations assist SIVsmmPBj14 in responding efficiently to cellular stimulation and allow it to replicate to high titers during the acute phase of viral infection
T1002	Speculation 1264 1277	indicate that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1264 1405	indicate that these transcriptional effects are due principally to the 22-bp sequence duplication and the NF kappa B site contained within it
