T1000	Speculation 573 578	might
E1000	Speculation:T1000 Scope:T1001
T1001	Span 573 750	might extensively heterodimerize, thereby forming complexes with distinct transcriptional activity, DNA sequence specificity, and cell type- and cell stage-specific distribution
T1002	Speculation 139 143	seem
E1001	Speculation:T1002 Scope:T1003
T1003	Span 124 206	its properties seem to be most extensively exploited in cells of the immune system
T1004	Speculation 1539 1542	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1539 1689	may be beneficial in suppressing toxic/septic shock, graft-vs-host reactions, acute inflammatory reactions, acute phase response, and radiation damage
T1006	Speculation 1430 1434	seem
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1430 1478	seem to be controlled by the cells' redox status
T1008	Speculation 1780 1783	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1780 1858	may provide a pharmacological basis for interfering with these acute processes
