T1000	Speculation 835 841	likely
E1000	Speculation:T1000 Scope:T1001
T1001	Span 781 895	The ability of BRCA1 to interact with multiple E2s is likely to be a common feature among other RING and U-box E3s
T1002	Speculation 502 516	indicates that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 502 600	indicates that the E2 dictates the type of ubiquitin modification that will occur on the substrate
T1004	Speculation 1086 1089	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1086 1132	may play a role in dictating product formation
T1006	Speculation 1066 1076	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1066 1132	suggesting that E2s may play a role in dictating product formation
