T1000	Speculation 1572 1579	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1572 1629	suggest the molecular surface involved in oligomerization
T1002	Speculation 1385 1393	putative
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1385 1442	putative ligands for the endothelial cell lectin, LSECtin
T1004	Speculation 1653 1661	possible
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1653 1756	possible pathways of virus-host interaction and strategies for the optimization of recombinant vaccines
T1006	Speculation 1645 1652	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1645 1756	suggest possible pathways of virus-host interaction and strategies for the optimization of recombinant vaccines
