T1000	Speculation 1730 1738	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1730 1800	suggests a hypothesis for E-cadherin down-regulation in leukemogenesis
T1002	Speculation 519 525	likely
E1001	Speculation:T1002 Scope:T1003
T1003	Span 519 588	likely contributes to intercellular interactions during hematopoiesis
T1004	Speculation 1741 1751	hypothesis
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1741 1800	hypothesis for E-cadherin down-regulation in leukemogenesis
