T1000	Speculation 328 338	hypothesis
E1000	Speculation:T1000 Scope:T1001
T1001	Span 328 510	hypothesis, we have characterized the binding activity of LF to HCV E2 envelope protein and have endeavored to determine which region(s) of LF are important for this binding activity
T1002	Speculation 255 262	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 227 310	the preventive mechanism is thought to be the direct interaction between LF and HCV
T1004	Speculation 1017 1025	appeared
E1002	Speculation:T1004 Scope:T1005
T1005	Span 966 1025	the amino acid sequences of these carboxyl regions appeared
