T1000	Negation 1052 1059	lacking
E1000	Negation:T1000 Scope:T1001
T1001	Span 1052 1082	lacking N-linked glycosylation
T1002	Negation 955 958	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 955 1019	not have a significant effect on receptor function or expression
T1004	Speculation 1451 1464	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1451 1628	indicate that the Semliki Forest virus system can provide large amounts of functional and fully glycosylated alpha(1B)-AR protein suitable for biochemical and structural studies
T1006	Negation 1206 1209	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1206 1250	not palmitoylation or O-linked glycosylation
