T1000	Negation 871 875	lack
E1000	Negation:T1000 Scope:T1001
T1001	Span 871 885	lack of oxygen
T1002	Negation 453 457	lack
E1001	Negation:T1002 Scope:T1003
T1003	Span 453 467	lack of oxygen
T1004	Speculation 1756 1763	propose
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1756 1929	propose that this system, in combination with a matched control, can be used as a simple and inexpensive assay to identify molecules that specifically modulate EGLN activity
T1006	Speculation 1056 1061	might
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1006 1109	the progression of the aforementioned pathologies might be influenced by activation of HIF-target genes
