T1000	Negation 839 842	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 839 861	not class III epitopes
T1002	Speculation 515 523	probably
E1001	Speculation:T1002 Scope:T1003
T1003	Span 515 622	probably related to the glycosylated part of the molecule while class III epitopes are core protein related
T1004	Speculation 1232 1237	seems
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1232 1418	seems that HPC maturation and class I and II epitope deprivation are concomitant events and that CD34 class I and II epitopes are lost prior to downregulation of the CD34 molecule per se
T1006	Negation 913 915	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 913 977	no diverse class epitope expression was observed on immature HPC
