T1000	Speculation 753 758	would
E1000	Speculation:T1000 Scope:T1001
T1001	Span 753 879	would suggest that its mechanism converged with that of other alpha-keto acid enzymes from an extradiol dioxygenase progenitor
T1002	Negation 605 608	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 605 632	not use alpha-ketoglutarate
T1004	Speculation 759 766	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 759 879	suggest that its mechanism converged with that of other alpha-keto acid enzymes from an extradiol dioxygenase progenitor
