T1000	Negation 545 547	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 545 594	no effect on HSP90 activity or cell proliferation
T1002	Speculation 364 367	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 364 427	may attenuate the cell death effects of this class of inhibitor
T1004	Speculation 953 963	indicating
E1002	Speculation:T1004 Scope:T1005
T1005	Span 953 994	indicating a potential therapeutic window
T1006	Negation 887 890	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 887 951	not result in comparable growth arrest or induction of apoptosis
