T1000	Speculation 778 785	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 778 886	suggest that the inhibition of IFN-beta induction occurred at the initial step of the TLR3 signaling pathway
T1002	Negation 715 721	failed
E1001	Negation:T1002 Scope:T1003
T1003	Span 715 767	failed to inhibit TRIF-triggered IFN-beta production
T1004	Negation 980 986	unable
E1002	Negation:T1004 Scope:T1005
T1005	Span 980 1031	unable to inhibit dsRNA-induced IFN-beta production
T1006	Negation 946 952	unable
E1003	Negation:T1006 Scope:T1007
T1007	Span 908 969	deglycosylation of E(rns) rendered it unable to bind to dsRNA
T1008	Speculation 1063 1077	indicated that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1063 1156	indicated that N-glycan of CSFV E(rns) is essential for E(rns) blocking of IFN-beta induction
