T1000	Speculation 1100 1107	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1100 1201	appears that an interaction amongst these proteins may be required for release of rhZP1 from the cell
T1002	Negation 974 977	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 933 986	biological activity to induce the AR was not observed
T1004	Negation 1229 1232	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1229 1284	not satisfactory for producing active human ZP proteins
T1006	Speculation 1151 1154	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1151 1201	may be required for release of rhZP1 from the cell
