T1000	Speculation 1662 1669	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1662 1857	suggest that a switch between posttranscriptional and transcriptional gene silencing could be a mechanism leading to irrevocable shut down of gene expression within a finite number of generations
T1002	Speculation 1590 1605	indicating that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1590 1648	indicating that the methylated promoter became inactivated
T1004	Speculation 1747 1752	could
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1747 1857	could be a mechanism leading to irrevocable shut down of gene expression within a finite number of generations
