T1000	Negation 809 812	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 809 882	not produce significant neutralizing antibodies against either SIV or HIV
T1002	Negation 355 358	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 355 468	not by itself elicit neutralizing antibodies (K. Javaherian et al., Proc. Natl. Acad. Sci. USA 89:1418-1422, 1992
T1004	Negation 1132 1135	nor
E1002	Negation:T1004 Scope:T1005
T1005	Span 1132 1198	nor the neutralizing monoclonal antibodies being investigated here
T1006	Negation 1112 1119	neither
E1003	Negation:T1006 Scope:T1007
T1007	Span 1112 1198	neither soluble CD4 nor the neutralizing monoclonal antibodies being investigated here
T1008	Negation 1208 1211	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1208 1261	not elicit sera with a significant neutralizing titer
