T1000	Speculation 375 390	indicating that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 375 432	indicating that stabilization requires additional factors
T1002	Speculation 166 173	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 157 258	which is thought to depend largely on the inability of mutant p53 to induce the ubiquitin ligase MDM2
T1004	Negation 772 779	absence
E1002	Negation:T1004 Scope:T1005
T1005	Span 772 797	absence of Hsp90 activity
T1006	Speculation 706 709	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 700 763	which may be reflected in different gain-of-function properties
T1008	Speculation 1346 1349	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1346 1448	may also provide an important avenue through which to target p53 to enhance treatment of human cancers
