T1000	Negation 1645 1648	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1600 1681	the fraction of CpG transition mutations was not reduced in Dnmt1-deficient cells
T1002	Speculation 1238 1248	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1238 1359	suggesting that the expression of Dnmt3a and Dnmt3b alone in ES cells is insufficient to achieve effective gene silencing
T1004	Negation 1749 1752	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1749 1823	not cause an increase in missense mutation rates in Dnmt1-proficient cells
