T1000	Speculation 1776 1779	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1776 1808	may have impaired heart function
T1002	Speculation 1492 1502	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1492 1579	suggesting that the loss of Asxl2 disrupts the activities of both PcG and trxG proteins
T1004	Speculation 2030 2040	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2030 2119	suggesting that the PcG/trxG system may be involved in the regulation of cardiac function
T1006	Speculation 1848 1855	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1848 1963	suggest that murine Asxl2 has conserved ETP function and plays dual roles in the promotion of PcG and trxG activity
T1008	Speculation 2066 2069	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2066 2119	may be involved in the regulation of cardiac function
