T1000	Speculation 367 375	proposed
E1000	Speculation:T1000 Scope:T1001
T1001	Span 367 391	proposed for this enzyme
T1002	Speculation 322 331	potential
E1001	Speculation:T1002 Scope:T1003
T1003	Span 322 357	potential role in tumor progression
T1004	Speculation 1783 1788	would
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1783 1932	would be predicted from the similarities between the active site sequence of collagenase-3 (MMP-13) and the gelatinases A and B. Active collagenase-3
T1006	Speculation 419 427	possible
E1003	Speculation:T1006 Scope:T1007
T1007	Span 419 479	possible role of collagenase-3 in connective tissue turnover
T1008	Speculation 2104 2109	could
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2104 2190	could play a significant role in the turnover of connective tissue matrix constituents
T1010	Speculation 2069 2076	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 2069 2190	suggest that in vivo collagenase-3 could play a significant role in the turnover of connective tissue matrix constituents
