T1000	Speculation 939 949	raises the
E1000	Speculation:T1000 Scope:T1001
T1001	Span 939 1057	raises the possibility that HIF may play a role in disorders of erythropoiesis, such as idiopathic erythrocytosis (IE)
T1002	Negation 124 127	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 124 156	not impair Pro-564 hydroxylation
T1004	Negation 1451 1457	failed
E1002	Negation:T1004 Scope:T1005
T1005	Span 1451 1520	failed to reveal a discernible effect on HIF hydroxylation at Pro-564
T1006	Speculation 971 974	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 971 1057	may play a role in disorders of erythropoiesis, such as idiopathic erythrocytosis (IE)
T1008	Negation 1743 1746	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1743 1794	not diminish the association of HIF-1alpha with VHL
T1010	Negation 1612 1615	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1612 1654	not impair HIF-1alpha prolyl hydroxylation
T1012	Speculation 1808 1816	unlikely
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1808 1907	unlikely that this polymorphism accounts for the erythrocytosis in the group of IE patients studied
