T1000	Speculation 2168 2171	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 2168 2261	may reside in the respective amounts of various TSH forms which, once bound to their receptor
T1002	Negation 948 955	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 948 984	without a significant change in cAMP
T1004	Speculation 434 444	indicating
E1002	Speculation:T1004 Scope:T1005
T1005	Span 434 488	indicating a similar recognition at the receptor sites
T1006	Negation 1176 1178	To
E1003	Negation:T1006 Scope:T1007
T1007	Span 1176 1264	To assess whether glycosylation might be responsible for the variation in hormone action
T1008	Negation 1149 1152	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1149 1174	not in cell proliferation
T1010	Speculation 1208 1213	might
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1208 1397	might be responsible for the variation in hormone action, both alkaline and neutral TSH isoforms were tested for recognition of their carbohydrate chains by concanavalin A (Con A) and ricin
T1012	Speculation 1186 1193	whether
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1186 1379	whether glycosylation might be responsible for the variation in hormone action, both alkaline and neutral TSH isoforms were tested for recognition of their carbohydrate chains by concanavalin A
T1014	Negation 1529 1532	not
E1007	Negation:T1014 Scope:T1015
T1015	Span 1529 1558	not related to core branching
T1016	Negation 1399 1401	No
E1008	Negation:T1016 Scope:T1017
T1017	Span 1399 1448	No major difference was found in binding to Con A
T1018	Speculation 2096 2105	suggested
E1009	Speculation:T1018 Scope:T1019
T1019	Span 2096 2261	suggested that physiological control of TSH action at the thyroid gland may reside in the respective amounts of various TSH forms which, once bound to their receptor
T1020	Speculation 1450 1465	indicating that
E1010	Speculation:T1020 Scope:T1021
T1021	Span 1450 1558	indicating that the contribution of carbohydrates to changes in hormone pI was not related to core branching
