T1000	Speculation 738 745	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 738 872	whether these phosphorylated molecules specifically regulate the carboxyl methylation and the catalytic activity of PP2A in beta cells
T1002	Speculation 523 532	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 523 713	suggested that adenine and guanine nucleotides or glycolytic intermediates [which are critical mediators in beta cell function] also modulate phosphatase activity in the pancreatic beta cell
T1004	Speculation 1630 1637	perhaps
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1630 1694	perhaps permitting PP2A to function under physiologic conditions
T1006	Speculation 1486 1499	indicate that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1486 1694	indicate that divalent metal ions protect against the inhibition by purine nucleotides or sugar phosphates of the carboxyl methylation of PP2Ac perhaps permitting PP2A to function under physiologic conditions
