T1000	Speculation 497 507	hypothesis
E1000	Speculation:T1000 Scope:T1001
T1001	Span 497 684	hypothesis that transgenically derived siRNAs may contemporaneously both activate the PTGS mechanism and induce chromatin modifications at the transgene and the homologous endogenous gene
T1002	Negation 75 78	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 0 197	Small interfering RNAs that trigger posttranscriptional gene silencing are not required for the histone H3 Lys9 methylation necessary for transgenic tandem repeat stabilization in Neurospora crassa
T1004	Negation 809 811	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 809 892	no alterations in the pattern of histone modifications at the endogenous al-1 locus
T1006	Speculation 543 546	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 543 684	may contemporaneously both activate the PTGS mechanism and induce chromatin modifications at the transgene and the homologous endogenous gene
T1008	Speculation 894 904	suggesting
E1004	Speculation:T1008 Scope:T1009
T1009	Span 894 1014	suggesting that siRNAs produced from the transgenic locus do not trigger modifications in trans of those histones tested
T1010	Negation 955 958	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 955 1014	not trigger modifications in trans of those histones tested
T1012	Speculation 1482 1495	indicate that
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1482 1599	indicate that the defect in PTGS of the Deltadim-5 strain is due to the inability to maintain the transgene in tandem
T1014	Negation 1350 1356	unable
E1007	Negation:T1014 Scope:T1015
T1015	Span 1350 1416	unable to maintain PTGS, with transgenic copies being rapidly lost
T1016	Negation 1818 1821	not
E1008	Negation:T1016 Scope:T1017
T1017	Span 1818 1943	not communicate with an RNAi-induced initiation of transcriptional gene silencing complex to effect chromatin-based silencing
T1018	Speculation 1601 1611	suggesting
E1009	Speculation:T1018 Scope:T1019
T1019	Span 1601 1667	suggesting a role for DIM-5 in stabilizing such repeated sequences
