T1000	Speculation 1034 1041	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1034 1285	suggest that COP1 acts as a repressor of flowering by promoting the ubiquitin-mediated proteolysis of CO in darkness and that CRY-mediated signal may negatively regulate COP1, thereby stabilizing CO, activating FT transcription, and inducing flowering
T1002	Speculation 321 329	proposed
E1001	Speculation:T1002 Scope:T1003
T1003	Span 321 472	proposed that one of the mechanisms by which CRY regulates light responses is via its physical interaction with COP1, a RING motif-containing E3 ligase
T1004	Speculation 1180 1183	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1180 1285	may negatively regulate COP1, thereby stabilizing CO, activating FT transcription, and inducing flowering
