T1000	Negation 961 963	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 961 1030	no effect on the expression of genes silenced by DNA hypermethylation
T1002	Negation 908 915	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 908 950	without affecting promoter DNA methylation
T1004	Speculation 1145 1156	potentially
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1145 1196	potentially independent of promoter DNA methylation
