T1000	Speculation 602 612	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 602 686	suggesting that lysine-79 methylation is important for efficient repair of UV damage
T1002	Speculation 423 433	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 423 476	suggesting a bipartite function for this modification
T1004	Speculation 1008 1022	indicates that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1008 1256	indicates that the lysine-to-glutamic acid substitution exerts specific effects within the nucleotide excision repair and post-replication repair pathways, suggesting that this allele only disrupts a subset of the functions of lysine-79 methylation
T1006	Speculation 748 762	indicates that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 748 937	indicates that lysine-79 methylation plays overlapping roles within the nucleotide excision, post-replication and recombination repair pathways, as well as RAD9-mediated checkpoint function
T1008	Speculation 1278 1286	indicate
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1278 1461	indicate the existence of distinct and separable roles of histone H3 lysine-79 methylation in the response to UV damage, potentially serving to coordinate the various repair processes
T1010	Speculation 1164 1174	suggesting
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1164 1256	suggesting that this allele only disrupts a subset of the functions of lysine-79 methylation
T1012	Speculation 1399 1410	potentially
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1399 1461	potentially serving to coordinate the various repair processes
