T1000	Negation 388 392	lack
E1000	Negation:T1000 Scope:T1001
T1001	Span 388 413	lack of a "gold standard.
T1002	Negation 354 357	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 354 412	not completely defined due to the lack of a "gold standard
T1004	Speculation 1835 1838	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1835 1910	may provide a specific and sensitive method for use in epidemiology studies
