T1000	Speculation 840 850	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 840 932	suggesting that loss of TBP-2 expression is due to DNA methylation and histone deacetylation
T1002	Negation 674 677	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 674 701	not in IL-2-dependent cells
T1004	Speculation 1370 1379	suggested
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1370 1553	suggested that epigenetic silencing of the TBP-2 gene results in a loss of responsiveness to IL-2, contributing to uncontrolled IL-2-independent growth in HTLV-I-infected T-cell lines
T1006	Negation 1342 1349	without
E1003	Negation:T1006 Scope:T1007
T1007	Span 1342 1354	without IL-2
