T1000	Negation 1278 1280	No
E1000	Negation:T1000 Scope:T1001
T1001	Span 1278 1377	No evidence of processing was observed in chick cells for any of the subunits that were synthesized
T1002	Negation 1113 1122	Treatment
E1001	Negation:T1002 Scope:T1003
T1003	Span 1113 1276	Treatment of the cells with inhibitors of hydroxylation and glycosylation caused a shift in mobility that revealed a size heterogeneity in the Mr = 260,000 subunit
