T1000	Speculation 1403 1410	support
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1403 1510	support the hypothesis that stress-induced protein glycosylation is a component of cellular stress response
T1002	Negation 673 676	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 673 729	not correlate with cellular heat resistance in M21 cells
T1004	Speculation 1415 1425	hypothesis
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1415 1574	hypothesis that stress-induced protein glycosylation is a component of cellular stress response, either in association with HSPs or as an independent mechanism
