T1000	Speculation 1318 1321	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1318 1480	may redirect the activity of this system toward appropriate substrates to be ubiquitinated under individual conditions for the maintenance of cellular homeostasis
T1002	Speculation 550 557	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 550 652	whether the composition of F-box proteins in the SCF complexes is remodeled under different conditions
