T1000	Speculation 1368 1375	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1368 1463	appears that N-acetylation of POMC-related products is an ancestral trait of osteichthyean fish
T1002	Speculation 1162 1169	appears
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1162 1283	appears that N-acetylation is a major post-translational processing event within the melanotropic cells of C. calabaricus
