T1000	Speculation 701 711	hypothesis
E1000	Speculation:T1000 Scope:T1001
T1001	Span 701 822	hypothesis that covalent modification of the C subunit (Pph21p/Pph22p) carboxyl terminus modulates PP2A complex formation
T1002	Speculation 577 582	might
E1001	Speculation:T1002 Scope:T1003
T1003	Span 514 595	the binding of these targeting subunits to the A/C heterodimer might be regulated
T1004	Speculation 1972 1985	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1972 2111	indicate that methylation and phosphorylation may be mechanisms by which the cell dynamically regulates PP2A complex formation and function
T1006	Speculation 1337 1346	potential
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1337 1386	potential carboxyl-terminal phosphorylation sites
T1008	Speculation 2018 2021	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2018 2111	may be mechanisms by which the cell dynamically regulates PP2A complex formation and function
