T1000	Negation 810 813	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 810 885	not differ significantly (P > 0.05) among the CYP1A2-transfected cell lines
T1002	Speculation 419 427	possibly
E1001	Speculation:T1002 Scope:T1003
T1003	Span 419 494	possibly followed by O-acetylation catalyzed by N-acetyltransferase 2 (NAT2
T1004	Speculation 1964 1971	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1964 2056	suggest a modest effect of human NAT2 and its genetic polymorphism on PhIP DNA adduct levels
T1006	Negation 1351 1354	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1351 1388	not further increase hprt mutagenesis
