T1000	Negation 839 842	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 839 848	not adapt
T1002	Speculation 611 614	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 611 653	may explain their overmethylated phenotype
T1004	Speculation 864 871	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 864 987	suggest that the dominant nature of the cheD mutations is manifested as a general defect in the regulation of demethylation
T1006	Speculation 795 801	either
E1003	Speculation:T1006 Scope:T1007
T1007	Span 795 824	either the Tsr or Tar protein
T1008	Negation 1465 1468	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1446 1503	the mutations were not located in the methylated peptides
T1010	Speculation 1187 1192	seems
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1159 1309	The mutant Tsr protein thus seems to be locked into a signaling mode that suppresses tumbling and inhibits methylesterase activity in a global fashion
T1012	Speculation 1555 1558	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1511 1622	the signaling properties of the transducers may be controlled at sites distinct from the methyl-accepting sites
