T1000	Speculation 1606 1613	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1606 1756	suggest that there could be a role for therapeutic strategies to overcome the glycosylation defect in these conditions via the overexpression of LARGE
T1002	Speculation 1198 1207	not known
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1140 1207	the precise composition of the glycans present on ADG are not known
T1004	Speculation 1625 1630	could
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1625 1756	could be a role for therapeutic strategies to overcome the glycosylation defect in these conditions via the overexpression of LARGE
