T1000	Speculation 1228 1235	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1228 1349	suggest that mutations in bfl-1 or in the signaling pathways that control its ubiquitination may predispose one to cancer
T1002	Speculation 534 543	not known
E1001	Speculation:T1002 Scope:T1003
T1003	Span 469 543	the role that dysregulation of Bfl-1 turnover plays in cancer is not known
T1004	Speculation 1443 1451	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1443 1519	suggests that strategies to promote Bfl-1 ubiquitination may improve therapy
T1006	Speculation 1321 1324	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1321 1349	may predispose one to cancer
T1008	Speculation 1500 1503	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1500 1519	may improve therapy
