T1000	Speculation 985 993	possible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 985 1116	possible mechanisms how Cul3 may be required to maintain SAC activity by ubiquitination of the chromosomal passenger protein Aurora
T1002	Speculation 359 362	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 359 399	may be causally involved in tumorgenesis
T1004	Speculation 1014 1017	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1009 1116	Cul3 may be required to maintain SAC activity by ubiquitination of the chromosomal passenger protein Aurora
