T1000	Speculation 1745 1752	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1745 1807	suggest that CD437 and MM002 analogs may have a potential role
T1002	Negation 950 953	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 921 1015	CD437-mediated apoptosis was not associated with the modulation of Bcl-2, Bax, or Mcl-1 levels
T1004	Speculation 1793 1802	potential
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1793 1841	potential role in the treatment of B-CLL and ALL
T1006	Speculation 1782 1785	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1782 1841	may have a potential role in the treatment of B-CLL and ALL
