T1000	Negation 691 694	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 637 742	Phenotype and function after maturation of Mo-DC were not impaired by infection with adenovirus particles
T1002	Negation 336 346	instead of
E1001	Negation:T1002 Scope:T1003
T1003	Span 336 370	instead of loading single peptides
T1004	Speculation 1237 1240	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1237 1344	may influence Ag presentation of the tumor glycoforms of MUC1 to immune cells, affecting tumor cell killing
T1006	Negation 1098 1100	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1098 1178	no changes in mRNA levels of relevant glycosyltransferases could be demonstrated
