T1000	Speculation 1352 1361	suggested
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1239 1595	An increased degree of protonation of the gamma-chain N-terminus of hemoglobin F from pH 9.0 to 8.0 is therefore suggested as responsible for its increased tetramer strength representing an example of transmission of a signal from its positively charged N-terminal tail to the distant subunit allosteric interface where the equilibrium constant is measured
T1002	Negation 1113 1119	unable
E1001	Negation:T1002 Scope:T1003
T1003	Span 1113 1136	unable to be protonated
