T1000	Negation 1095 1098	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1095 1138	not change in the course of differentiation
T1002	Speculation 327 339	hypothesized
E1001	Speculation:T1002 Scope:T1003
T1003	Span 327 563	hypothesized that the tissue specificity of type I collagen cross-linking is, in part, due to the differential expression of lysyl hydroxylase genes (Procollagen-lysine,2-oxyglutarate,5-dioxygenase 1, 2, and 3 [PLOD1, PLOD2, and PLOD3])
T1004	Speculation 1769 1777	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1769 1981	suggests that PLOD2 expression is associated with lysine hydroxylation in the nontriple helical domains of collagen and, thus, could be partially responsible for the tissue-specific collagen cross-linking pattern
T1006	Negation 1329 1332	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1329 1337	not NSFs
