T1000	Speculation 801 808	implies
E1000	Speculation:T1000 Scope:T1001
T1001	Span 801 890	implies glycosylation-dependent steps in the endoplasmic reticulum (ER) and Golgi complex
T1002	Speculation 759 767	putative
E1001	Speculation:T1002 Scope:T1003
T1003	Span 759 800	putative targeting mechanism of CS to jSR
T1004	Negation 1698 1701	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1698 1738	not to be affected by glycosylation-that
T1006	Speculation 1172 1174	or
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1066 1222	cDNA was transiently transfected in either HeLa cells, myoblasts of rat skeletal muscle primary cultures, or regenerating soleus muscle fibers of adult rats
