T1000	Negation 375 378	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 375 462	not led to the expression of a functional H2O2-generating system at the plasma membrane
T1002	Speculation 85 93	probably
E1001	Speculation:T1002 Scope:T1003
T1003	Span 85 99	probably Duox1
T1004	Negation 1209 1211	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1209 1218	no effect
T1006	Speculation 967 973	seemed
E1003	Speculation:T1006 Scope:T1007
T1007	Span 955 1059	Human Duox2 seemed to be more active than human Duox1 but only half as active as its porcine counterpart
T1008	Speculation 1645 1652	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1645 1834	suggest that post-translational modifications during the maturation process of Duox2 could be implicated in the mechanism of H2O2 formation by favoring intramolecular superoxide dismutation
T1010	Negation 1328 1331	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1328 1353	not release O2*- but H2O2
