T1000	Negation 612 614	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 612 692	no subsequent major modulation in the content of acetylated alpha-tubulin in MTs
T1002	Negation 314 317	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 286 366	Acetylated alpha-tubulin is not solely located in the stable microtubular arrays
T1004	Negation 1485 1488	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1485 1581	not uniquely associated with particular subsets of MTs of defined lability, position or function
T1006	Speculation 961 971	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 961 1110	suggesting that they are actually constructed of detyrosinated alpha-tubulin or that detyrosination is extremely rapid at this time in the cell cycle
T1008	Speculation 1629 1632	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1629 1776	may provide a mechanism whereby the cell could discriminate between new and old MTs, during construction of the cytoskeleton through the cell cycle
T1010	Speculation 1349 1356	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1349 1581	suggest that acetylation and detyrosination of alpha-tubulin are two independently regulated post-translational modifications, that are not uniquely associated with particular subsets of MTs of defined lability, position or function
T1012	Speculation 1795 1802	suggest
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1795 1947	suggest that continuation of detyrosination, allows the cell, at cell division, to partition into daughter cells two equivalent sets of cytoskeletal MTs
