T1000	Negation 909 918	no longer
E1000	Negation:T1000 Scope:T1001
T1001	Span 890 1126	this difference is no longer significant for either factor IX or X. Analysis of the 1H NMR chemical shift differences between the hydroxylated and nonhydroxylated factor X modules show that hydroxylation has no effect on the domain fold
T1002	Speculation 418 427	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 418 481	suggested that the hydroxyl group is essential for Ca2+ binding
T1004	Negation 1195 1197	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1195 1257	no effect on the Ca2+/Mg2+ specificity of the ion binding site
T1006	Negation 1098 1100	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1098 1126	no effect on the domain fold
T1008	Negation 1365 1368	nor
E1004	Negation:T1008 Scope:T1009
T1009	Span 1365 1415	nor is it essential for high-affinity Ca2+ binding
T1010	Negation 1298 1301	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1298 1415	not a direct ligand for the calcium ion in these EGF-like modules, nor is it essential for high-affinity Ca2+ binding
