T1000	Negation 340 343	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 340 362	not carboxypeptidase A
T1002	Negation 275 278	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 236 294	the biosynthetic pathway for hmGSH has not been identified
T1004	Speculation 583 586	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 583 625	may be involved in hmGSH synthesis in vivo
T1006	Speculation 537 546	suggested
E1003	Speculation:T1006 Scope:T1007
T1007	Span 537 625	suggested that a carboxypeptidase-like enzyme may be involved in hmGSH synthesis in vivo
