T1000	Negation 1017 1020	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1017 1095	not correlate with the presence of consensus E2 binding sites in the promoters
T1002	Speculation 956 971	indicating that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 956 1000	indicating that E2 bound to active promoters
T1004	Speculation 1324 1331	propose
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1324 1483	propose that this may be a way for the virus to ensure that the viral genome is retained in transcriptionally active regions of the nucleus to escape silencing
T1006	Negation 1294 1297	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1294 1319	not change their activity
T1008	Speculation 1342 1345	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1342 1483	may be a way for the virus to ensure that the viral genome is retained in transcriptionally active regions of the nucleus to escape silencing
