T1000	Negation 667 670	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 667 701	not with the rate of cell division
T1002	Negation 289 292	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 289 312	not block transcription
T1004	Negation 1553 1556	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1553 1584	not inhibit their remethylation
T1006	Negation 1457 1460	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1457 1584	not restricted to the S phase of the cell cycle and that transcription through CpG islands does not inhibit their remethylation
T1008	Speculation 1421 1428	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1421 1504	suggest that de novo methylation is not restricted to the S phase of the cell cycle
