T1000	Speculation 576 583	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 576 667	whether the gene silencing was associated with a specific change of the chromatin structure
T1002	Speculation 285 293	possibly
E1001	Speculation:T1002 Scope:T1003
T1003	Span 285 326	possibly interfering with gene expression
T1004	Speculation 1407 1414	propose
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1407 1504	propose that silencing of the oxidatively damaged DNA may occur in a chromatin-mediated mechanism
T1006	Speculation 1273 1283	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1273 1377	suggesting a causal connection between the changes of histone acetylation and persistent gene repression
T1008	Speculation 1461 1464	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1461 1504	may occur in a chromatin-mediated mechanism
