T1000	Speculation 1024 1031	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1024 1196	suggest that RAD18 promotes 53BP1-directed DSB repair by enhancing retention of 53BP1, possibly through an interaction between RAD18 and 53BP1 and the modification of 53BP1
T1002	Negation 781 784	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 694 846	A monoubiquitination-resistant 53BP1 mutant harboring a substitution at lysine 1268 is not retained efficiently at the chromatin in the vicinity of DSBs
T1004	Speculation 1111 1119	possibly
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1111 1196	possibly through an interaction between RAD18 and 53BP1 and the modification of 53BP1
