T1000	Speculation 1015 1025	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1015 1089	suggesting a role for this enzyme in preventing aggregation of this domain
T1002	Speculation 683 688	would
E1001	Speculation:T1002 Scope:T1003
T1003	Span 683 706	would occur in the cell
T1004	Speculation 1219 1229	indicating
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1219 1310	indicating a role for this protein in coordinating the assembly of heterotrimeric molecules
