T1000	Negation 248 250	No
E1000	Negation:T1000 Scope:T1001
T1001	Span 248 361	No essential changes in the electrophoretic pattern of the histones have been revealed during the stages examined
T1002	Negation 88 96	Histones
E1001	Negation:T1002 Scope:T1003
T1003	Span 88 246	Histones and histone acetylation have been investigated during three stages of Drosophila hydei embryogenesis--early gastrula, late gastrula and organogenesis
T1004	Speculation 700 707	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 700 838	suggest that the correlation between histone acetylation and gene activity during Drosophila embryogenesis concerns histone H3 acetylation
