T1000	Negation 1004 1007	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 982 1068	XAF1 transcripts were not observed or present at low levels in liver cancer cell lines
T1002	Speculation 203 211	putative
E1001	Speculation:T1002 Scope:T1003
T1003	Span 203 299	putative tumor suppressor gene X-linked inhibitor of apoptosis protein-associated factor 1 (XAF1
T1004	Negation 1646 1648	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1646 1742	no significant association was found between methylation status and the risk of tumor recurrence
T1006	Speculation 1017 1019	or
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1017 1068	or present at low levels in liver cancer cell lines
T1008	Speculation 1882 1885	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1882 1946	may serve as a potential biomarker for tumor recurrence after LT
T1010	Negation 1801 1804	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1801 1813	not the sole
