T1000	Speculation 1771 1774	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1771 1831	may underlie these tumors and their more favorable prognosis
T1002	Speculation 1723 1738	indicating that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1723 1831	indicating that distinct molecular pathogenesis may underlie these tumors and their more favorable prognosis
T1004	Speculation 2008 2011	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2008 2077	may contribute to the biological subclassification of medulloblastoma
