T1000	Negation 965 968	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 965 979	not abolished)
T1002	Negation 341 348	lacking
E1001	Negation:T1002 Scope:T1003
T1003	Span 341 357	lacking, however
T1004	Speculation 1507 1510	can
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1443 1559	the phorbol ester-induced phosphorylation of the LH/CG receptor can be correlated with uncoupling, other experiments
T1006	Negation 1274 1277	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1274 1302	not with a calcium ionophore
T1008	Speculation 1560 1573	indicate that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1560 1728	indicate that hCG-induced uncoupling of the LH/CG receptor can occur under conditions where the cAMP-mediated receptor phosphorylation is greatly reduced (or abolished)
