T1000	Negation 760 763	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 760 894	not only mediates selective degradation but also promotes aggregation of ubiquitinated proteins that can be harmful in some cell types
T1002	Speculation 418 427	not known
E1001	Speculation:T1002 Scope:T1003
T1003	Span 349 427	the exact mechanism underlying selection of autophagic substrates is not known
T1004	Speculation 1354 1361	propose
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1354 1524	propose that NBR1 together with p62 promotes autophagic degradation of ubiquitinated targets and simultaneously regulates their aggregation when autophagy becomes limited
T1006	Negation 1196 1199	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1196 1237	not strictly require p62 for this process
