T1000	Negation 860 867	without
E1000	Negation:T1000 Scope:T1001
T1001	Span 860 871	without HCC
T1002	Speculation 596 603	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 596 708	whether the MTHFR polymorphism is related to hepatocellular carcinoma (HCC) in patients with alcoholic cirrhosis
T1004	Negation 1226 1233	without
E1002	Negation:T1004 Scope:T1005
T1005	Span 1226 1272	without macroscopic evidence of HCC (P = 0.02)
T1006	Negation 987 994	without
E1003	Negation:T1006 Scope:T1007
T1007	Span 987 998	without HCC
T1008	Negation 1333 1340	without
E1004	Negation:T1008 Scope:T1009
T1009	Span 1333 1406	without HCC developed either on viral cirrhosis or on non-cirrhotic liver
T1010	Negation 1294 1297	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1274 1406	This difference was not observed between patients with and without HCC developed either on viral cirrhosis or on non-cirrhotic liver
T1012	Speculation 1757 1764	suggest
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1757 1869	suggest that the MTHFR CC genotype increases the risk to develop HCC in patients who consume a high alcohol diet
T1014	Negation 1568 1579	rather than
E1007	Negation:T1014 Scope:T1015
T1015	Span 1568 1648	rather than on viral cirrhosis (P = 0.002) or on non-cirrhotic livers (P = 0.02)
