T1000	Speculation 1360 1366	should
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1360 1490	should facilitate investigations into the role of N-acetylglucosamine residues in the functioning of transcription factor proteins
T1002	Speculation 1095 1098	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1095 1189	may aid the purification of other transcription factors that bear N-acetylglucosamine residues
