T1000	Speculation 779 789	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 779 846	suggesting a role for the phosphatase calcineurin in Foxp3 function
T1002	Speculation 528 535	unclear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 528 535	unclear
T1004	Speculation 1179 1182	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1179 1241	may regulate transcription through direct chromatin remodeling
T1006	Speculation 1159 1172	indicate that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1159 1241	indicate that Foxp3 may regulate transcription through direct chromatin remodeling
