T1000	Speculation 255 264	potential
E1000	Speculation:T1000 Scope:T1001
T1001	Span 255 295	potential Asn-linked glycosylation sites
T1002	Speculation 147 154	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 77 206	Post-translational modification of the scrapie prion protein (PrP) is thought to account for the unusual features of this protein
T1004	Speculation 1704 1712	probably
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1704 1822	probably possesses Asn-linked, complex oligosaccharides with terminal sialic acids, penultimate galactoses, and fucose
T1006	Speculation 1668 1673	These
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1668 1682	These findings
