T1000	Speculation 1563 1570	propose
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1563 1638	propose that it is this mutation that is responsible for the SM/J phenotype
T1002	Speculation 1264 1271	propose
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1264 1422	propose that the reduced activity is caused by the enzyme's altered affinity for its substrate, rather than a change in substrate specificity or turnover rate
