T1000	Speculation 598 606	possible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 598 674	possible role for the cortical cytoskeleton in directing early embryogenesis
T1002	Speculation 412 419	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 412 594	suggest that the fat body is a source of the actin in the oocyte and that the transport and acquisition of actin by the ovary are similar to the mechanism of vitellogenin acquisition
