T1000	Negation 460 463	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 430 531	The FANCD2-FOXO3a complex was not detected in cells deficient for the FA core complex component FANCA
T1002	Negation 168 171	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 66 184	The molecular pathway by which Fanconi anemia (FA) proteins function in oxidative stress response has not been defined
T1004	Negation 740 747	neither
E1002	Negation:T1004 Scope:T1005
T1005	Span 740 797	neither could induce the association of FANCD2 and FOXO3a
T1006	Negation 633 639	failed
E1003	Negation:T1006 Scope:T1007
T1007	Span 633 654	failed to bind FOXO3a
T1008	Negation 991 994	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 991 1013	not mutant FA-D2 cells
T1010	Speculation 748 753	could
E1005	Speculation:T1010 Scope:T1011
T1011	Span 748 797	could induce the association of FANCD2 and FOXO3a
T1012	Speculation 1122 1130	probably
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1122 1174	probably contributes to cellular antioxidant defense
