T1000	Speculation 580 588	possible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 580 633	possible asymmetry between the two monomeric subunits
T1002	Speculation 569 579	indicating
E1001	Speculation:T1002 Scope:T1003
T1003	Span 569 633	indicating possible asymmetry between the two monomeric subunits
T1004	Speculation 878 886	possible
E1002	Speculation:T1004 Scope:T1005
T1005	Span 878 955	possible dynamic flexibility of the prehelix loop in its unbound conformation
T1006	Speculation 867 877	indicating
E1003	Speculation:T1006 Scope:T1007
T1007	Span 867 894	indicating possible dynamic
T1008	Speculation 1572 1580	possibly
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1572 1643	possibly play an important role in type I receptor specificity of BMP-6
T1010	Negation 1342 1349	absence
E1005	Negation:T1010 Scope:T1011
T1011	Span 1342 1376	absence of the carbohydrate moiety
