T1000	Speculation 1369 1379	suggestion
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1369 1587	suggestion (B. A. Johnson, N. E. Freitag, and D. W. Aswad, (1985) J. Biol. Chem. 260, 10913-10916) that deamidation occurs preferentially at Asn-60 and/or Asn-97, each of which resides in a distinct Ca2+-binding domain
T1002	Speculation 453 455	or
E1001	Speculation:T1002 Scope:T1003
T1003	Span 453 480	or after 8-9 days at pH 7.4
