T1000	Negation 435 438	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 435 483	not at other transcriptionally repressed regions
T1002	Speculation 91 100	potential
E1001	Speculation:T1002 Scope:T1003
T1003	Span 91 142	potential mechanism for position-effect variegation
T1004	Negation 836 839	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 836 899	not at recombinationally inactive loci that are heterochromatic
T1006	Negation 561 564	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 561 582	not the ribosomal DNA
T1008	Speculation 1107 1114	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1107 1223	suggest that Sir proteins preferentially bind chromatin with hypomethylated H3-K79 and then block H3-K79 methylation
T1010	Speculation 915 922	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 915 1091	suggest that H3-K79 methylation is an evolutionarily conserved marker of active chromatin regions, and that silencing proteins block the ability of Dot1 to methylate histone H3
T1012	Speculation 1369 1377	suggests
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1369 1417	suggests a model for position-effect variegation
