T1000	Negation 552 555	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 552 672	not, hypothalamus-derived GT1 cells by hybridization of DNA microarrays, semiquantitative RT-PCR, and biochemical assays
T1002	Speculation 188 201	indicate that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 188 334	indicate that some glycoconjugates are efficient effectors of the cellular prion protein (PrP(C)) conversion into its pathogenic (PrP(Sc)) isoform
T1004	Speculation 1412 1420	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1412 1497	suggests a link between the genetic control of 4-O-sulfation and PrP(Sc) accumulation
T1006	Speculation 1009 1017	possible
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1009 1077	possible role for a hyposulfated chondroitin in PrP(Sc) accumulation
