T1000	Speculation 1383 1390	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1383 1558	suggest that hSWI/SNF complexes, through their ability to interact with activator and repressor proteins, control expression of genes involved in cell growth and proliferation
T1002	Speculation 807 820	indicate that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 807 905	indicate that PRMT5 and mSin3A interact with the same hSWI/SNF subunits as those targeted by c-Myc
