T1000	Negation 887 890	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 887 911	not bind methylated H3K4
T1002	Negation 10 13	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 10 121	not yeast CHD1 binds directly and selectively to histone H3 methylated at lysine 4 via its tandem chromodomains
T1004	Speculation 926 939	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 926 1157	indicate that yeast and human CHD1 have diverged in their ability to discriminate covalently modified histones and link histone modification-recognition and non-covalent chromatin remodeling activities within a single human protein
