T1000	Speculation 1295 1308	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1295 1560	indicate that direct transcriptional activation of PML by IRF3 results in the p53-dependent growth inhibition of normal and cancer cells in vitro and in vivo, which is suggestive of a novel regulatory network between the innate immune response and tumor suppression
T1002	Negation 1178 1183	fails
E1001	Negation:T1002 Scope:T1003
T1003	Span 1178 1244	fails to increase p53 acetylation and its transcriptional activity
T1004	Speculation 1463 1473	suggestive
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1463 1560	suggestive of a novel regulatory network between the innate immune response and tumor suppression
