T1000	Negation 691 697	absent
E1000	Negation:T1000 Scope:T1001
T1001	Span 691 716	absent in skeletal muscle
T1002	Negation 281 285	fail
E1001	Negation:T1002 Scope:T1003
T1003	Span 281 330	fail to express endogenously cleaved dystroglycan
T1004	Speculation 909 915	likely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 909 1068	likely to be the CT carbohydrate antigen, which is present on alpha dystroglycan in muscles overexpressing the CT GalNAc transferase [Dev. Biol. 242 (2002) 58]
T1006	Speculation 770 776	should
E1003	Speculation:T1006 Scope:T1007
T1007	Span 770 882	should inhibit later glycosylation events that would occur on the structure or structures this antibody binds to
T1008	Negation 1690 1693	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1690 1701	not present
T1010	Negation 1413 1415	no
E1005	Negation:T1010 Scope:T1011
T1011	Span 1413 1446	no evidence of muscular dystrophy
