T1000	Speculation 1756 1763	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1756 1989	suggest that NRG1 type IV expression levels associated with SNP8NRG243177 [T/T] can selectively modify signaling of NRG1 released from somato-dendritic compartments, in contrast to the type III NRG1 that is also associated with axons
T1002	Speculation 1583 1596	indicate that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1583 1740	indicate that, whereas all isoforms are expressed on somato-dendritic membranes, only the type III-cysteine-rich domain isoform is detectable in distal axons
