T1000	Speculation 577 585	possible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 577 641	possible physiologic role of peptidyl-prolyl cis-trans-isomerase
T1002	Speculation 285 288	not
E1001	Speculation:T1002 Scope:T1003
T1003	Span 285 347	not yet securely identified with any specific physiologic role
T1004	Speculation 1468 1483	indicating that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1468 1546	indicating that procollagen folding is slowed by CsA also in human fibroblasts
