T1000	Speculation 457 463	expect
E1000	Speculation:T1000 Scope:T1001
T1001	Span 457 485	expect of a scaffold protein
T1002	Speculation 451 456	would
E1001	Speculation:T1002 Scope:T1003
T1003	Span 451 485	would expect of a scaffold protein
T1004	Speculation 740 750	hypothesis
E1002	Speculation:T1004 Scope:T1005
T1005	Span 740 913	hypothesis that RKIP inhibits NF-kappaB activity via the auto-regulatory feedback loop by rapidly inducing the expression and synthesis of inhibitors of NF-kappaB activation
T1006	Speculation 730 737	support
E1003	Speculation:T1006 Scope:T1007
T1007	Span 730 913	support a hypothesis that RKIP inhibits NF-kappaB activity via the auto-regulatory feedback loop by rapidly inducing the expression and synthesis of inhibitors of NF-kappaB activation
