T1000	Negation 1642 1644	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 1642 1663	no significant effect
T1002	Negation 1105 1108	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1105 1124	not after 0.8 mg/kg
T1004	Speculation 2060 2068	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2060 2168	suggests a preferential activation of inhibitory autoregulatory dopamine receptors by low doses of this drug
T1006	Speculation 1874 1882	indicate
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1874 1915	indicate postsynaptic receptor activation
T1008	Speculation 2469 2476	perhaps
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2469 2542	perhaps less direct influence of noradrenaline neurones on motor activity
T1010	Speculation 2432 2439	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 2432 2488	suggest a somewhat less striking and perhaps less direct
T1012	Speculation 3020 3023	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 3020 3089	may be more affected by activation of postsynaptic dopamine receptors
