T1000	Speculation 1200 1208	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1200 1334	suggests that UBA1 and UBA2 domains of IsoT interact with the third and fourth ubiquitins in both polyubiquitin isoforms, respectively
T1002	Speculation 827 834	unknown
E1001	Speculation:T1002 Scope:T1003
T1003	Span 827 834	unknown
T1004	Speculation 1347 1354	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1347 1510	suggest that recognition of the polyubiquitin isoforms by IsoT involves considerable conformational mobility in the polyubiquitin ligand, in the enzyme, or in both
