T1000	Negation 1231 1234	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1231 1295	not the MGMT promoter occurred in intestinal metaplastic mucosae
T1002	Negation 1118 1121	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1118 1186	not coincide with MGMT promoter hypermethylation except in 1 patient
T1004	Speculation 1607 1610	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1607 1661	may be an early event in carcinogenesis in the stomach
T1006	Speculation 1448 1455	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1448 1555	suggest that at least two types of promoter methylation participate in the development of gastric carcinoma
