T1000	Negation 752 759	absence
E1000	Negation:T1000 Scope:T1001
T1001	Span 752 759	absence
T1002	Negation 575 578	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 575 614	not inhibit ongoing histone methylation
T1004	Speculation 1499 1506	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1499 1639	suggest that the processes of histone H4 methylation and dynamic acetylation are partially coupled in terminally differentiated erythrocytes
T1006	Speculation 1368 1378	hypothesis
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1368 1639	hypothesis that histones participating in ongoing methylation are associated with transcriptionally active/competent chromatin and suggest that the processes of histone H4 methylation and dynamic acetylation are partially coupled in terminally differentiated erythrocytes
