T1000	Negation 1273 1276	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1273 1324	not by carboxypeptidase Y or chymotrypsin treatment
T1002	Negation 1103 1105	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 1103 1158	no methylated protein was found in the soluble fraction
T1004	Speculation 1707 1715	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1707 1874	suggests that the methylation/demethylation of eEF1A at the C-terminal carboxyl group may represent a novel mode of regulation of the activity of this protein in yeast
T1006	Speculation 1329 1336	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1329 1430	suggest that the methyl ester is present on the alpha-carboxyl group of its C-terminal lysine residue
T1008	Speculation 1793 1796	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1793 1874	may represent a novel mode of regulation of the activity of this protein in yeast
