T1000	Speculation 482 490	possible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 482 503	possible target genes
T1002	Negation 252 255	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 252 277	not been well established
T1004	Speculation 1516 1523	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1516 1687	suggest that pancreatic carcinomas with MSI-H represent a distinctive oncogenic pathway because they exhibit peculiar clinical, pathological, and molecular characteristics
T1006	Negation 1317 1320	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1317 1379	not in any of the 3 hereditary MSI-H tumors or 13 MSI-L tumors
T1008	Speculation 1706 1713	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1706 1850	suggest the principal involvement of epigenetic or genetic inactivation of the hMLH1 gene in the pathogenesis of pancreatic carcinoma with MSI-H
