T1000	Speculation 603 606	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 603 692	may contribute to the structural integrity of many other tissues including skin and brain
T1002	Speculation 425 436	potentially
E1001	Speculation:T1002 Scope:T1003
T1003	Span 425 486	potentially containing new members of the link protein family
T1004	Negation 1314 1317	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1314 1396	not bind directly to each other in solution yet formed ternary complexes with HA24
T1006	Speculation 1034 1039	could
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1034 1094	could compete effectively for their binding to polymeric HA)
T1008	Speculation 1673 1676	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1673 1759	may reflect differences in the conformation of HA stabilized on binding these proteins
