T1000	Speculation 969 979	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 969 1019	suggesting that it is an integral membrane protein
T1002	Negation 945 948	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 945 1019	not solubilize Pc550gp, suggesting that it is an integral membrane protein
T1004	Negation 1299 1302	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1299 1397	not affect the translocation of Pc550gp from the parasite compartments to the erythrocyte membrane
T1006	Speculation 1132 1142	indicating
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1132 1237	indicating its transmembrane nature and that it presents extracellular domains susceptible to proteolysis
T1008	Speculation 1399 1414	indicating that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1399 1522	indicating that the secretion of Pc550gp does not follow the classical transport pathway described in most eukaryotic cells
T1010	Negation 1445 1448	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1445 1522	not follow the classical transport pathway described in most eukaryotic cells
