T1000	Speculation 1610 1613	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1561 1717	These small molecule epigenetic modifying agents may be used to sensitize poorly differentiated, PR-B negative endometrial cancers to progestational therapy
T1002	Speculation 125 127	if
E1001	Speculation:T1002 Scope:T1003
T1003	Span 125 260	if epigenetic interference can restore progesterone receptor-B (PR-B) expression in PR-B negative endometrial adenocarcinoma cell lines
