T1000	Negation 825 827	No
E1000	Negation:T1000 Scope:T1001
T1001	Span 825 926	No disorder has been directly linked to decreased expression of LH2 and LH3, two other isoforms of LH
T1002	Negation 109 112	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 109 199	not result from mutations in either the coding or proximal promoter region of the LH2 gene
T1004	Negation 1503 1506	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1503 1572	not show mutations that could explain the decreased expression of LH2
T1006	Negation 1206 1209	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1206 1228	not affect LH activity
T1008	Speculation 1588 1595	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1588 1720	suggest that the deficiency of LH2 in these fibroblasts may be caused by changes in other factors required for the expression of LH2
T1010	Speculation 1527 1532	could
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1527 1572	could explain the decreased expression of LH2
T1012	Speculation 1644 1647	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1601 1720	the deficiency of LH2 in these fibroblasts may be caused by changes in other factors required for the expression of LH2
