T1000	Speculation 800 809	suggested
E1000	Speculation:T1000 Scope:T1001
T1001	Span 800 809	suggested
T1002	Speculation 352 362	presumably
E1001	Speculation:T1002 Scope:T1003
T1003	Span 352 388	presumably due to the action of CheB
T1004	Speculation 1071 1080	supported
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1052 1100	This hypothesis is supported by two observations
T1006	Speculation 921 931	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 921 1050	suggesting that CheY-P acts in a feedback mechanism to facilitate adaptation to positive stimuli during chemotaxis in B. subtilis
