T1000	Speculation 779 793	hypothetically
E1000	Speculation:T1000 Scope:T1001
T1001	Span 779 805	hypothetically more mature
T1002	Negation 886 889	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 886 936	not express hemoglobin until the temperature shift
T1004	Negation 1332 1335	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1332 1366	not a consequence of transcription
T1006	Negation 951 954	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 951 958	not all
T1008	Negation 1595 1598	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1595 1619	not obligatorily related
T1010	Speculation 1256 1263	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1256 1366	suggest that changes in chromosomal structure precede transcription and are not a consequence of transcription
T1012	Speculation 1517 1523	likely
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1517 1619	likely that many of these properties can be independently established and are not obligatorily related
T1014	Speculation 1411 1414	can
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1411 1509	can be established with some, but not all, of the structural properties of active globin chromatin
