T1000	Speculation 535 543	possible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 535 604	possible role of histone modifications in the control of HCMV latency
T1002	Negation 301 308	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 301 338	without undergoing a productive cycle
T1004	Negation 920 927	neither
E1002	Negation:T1004 Scope:T1005
T1005	Span 920 958	neither acetylated nor dimethylated H3
T1006	Negation 828 831	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 828 847	not dimethylated H3
T1008	Speculation 1199 1206	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1199 1382	suggest that K9 methylation of H3 is involved in HCMV gene repression, while association of the above genes with acetylated histones is likely to be necessary for active transcription
T1010	Negation 939 942	nor
E1005	Negation:T1010 Scope:T1011
T1011	Span 939 958	nor dimethylated H3
T1012	Speculation 1387 1390	can
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1384 1521	It can be postulated that the same histone modifications are used to mark active and repressed genes in both cellular and viral chromatin
T1014	Speculation 1335 1341	likely
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1335 1382	likely to be necessary for active transcription
