T1000	Negation 595 598	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 595 637	not solely dependent on H2B ubiquitylation
T1002	Negation 450 456	unable
E1001	Negation:T1002 Scope:T1003
T1003	Span 450 491	unable to be ubiquitylated on H2B (K123R)
T1004	Negation 961 968	lacking
E1002	Negation:T1004 Scope:T1005
T1005	Span 961 994	lacking the ubiquitin ligase Bre1
T1006	Speculation 554 569	indicating that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 554 637	indicating that H3 methylation status is not solely dependent on H2B ubiquitylation
T1008	Speculation 1029 1039	suggesting
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1029 1143	suggesting that there is an additional Bre1 substrate that in combination with H2B K123 facilitates H3 methylation
