T1000	Speculation 910 919	suggested
E1000	Speculation:T1000 Scope:T1001
T1001	Span 910 1065	suggested that unsialylated Gal beta 1-3GalNAc sugar chains on the cell surface and/or CD44 are involved in the metastatic process of B16BL6 melanoma cells
T1002	Negation 520 523	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 520 546	not Concanavalin A (Con A)
T1004	Speculation 1367 1372	might
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1367 1441	might have other metastasis related functions that remain to be elucidated
T1006	Negation 1233 1236	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1086 1360	the known functions of CD44, such as adhesion to hyaluronate, fibronectin, collagen, and endothelial cells, as well as homotypic aggregation, were not affected by benzyl-alpha-GalNAc regardless of the enhancement of metastatic ability induced by this glycosylation inhibitor
