T1000	Speculation 586 588	or
E1000	Speculation:T1000 Scope:T1001
T1001	Span 576 687	truncated or "core" fragments of RAG1 and RAG2, which lack approximately one third of the amino acids from each
T1002	Negation 630 634	lack
E1001	Negation:T1002 Scope:T1003
T1003	Span 630 687	lack approximately one third of the amino acids from each
T1004	Speculation 751 764	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 751 834	indicate that residues outside the cores are essential to normal immune development
