T1000	Negation 706 713	without
E1000	Negation:T1000 Scope:T1001
T1001	Span 706 746	without cell division or DNA replication
T1002	Speculation 167 175	possible
E1001	Speculation:T1002 Scope:T1003
T1003	Span 167 243	possible derivation of patient-specific stem cells for regenerative medicine
T1004	Negation 1105 1108	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1105 1150	not active demethylated promoters in ES cells
