T1000	Speculation 609 617	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 609 744	suggests that tyrosine-kinase receptors (RTK) may not be polyubiquitinated but monoubiquitinated at multiple sites (multiubiquitinated)
T1002	Negation 659 662	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 659 744	not be polyubiquitinated but monoubiquitinated at multiple sites (multiubiquitinated)
T1004	Negation 805 808	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 755 816	the type of ubiquitination of the IGF-IR is still not defined
T1006	Speculation 655 658	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 623 744	tyrosine-kinase receptors (RTK) may not be polyubiquitinated but monoubiquitinated at multiple sites (multiubiquitinated)
T1008	Negation 1466 1469	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1466 1478	not degraded
T1010	Speculation 1331 1334	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1331 1380	may participate in sorting internalized receptors
T1012	Speculation 1539 1552	indicate that
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1539 1763	indicate that Grb10 and Nedd4 play a critical role in mediating IGF-IR down-regulation by promoting ligand-dependent multiubiquitination of the IGF-IR, which is required for receptor internalization and regulates mitogenesis
T1014	Speculation 1483 1489	likely
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1483 1523	likely directed into recycling endosomes
