T1000	Speculation 1065 1073	appeared
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1027 1180	the amount of endogenous TIR1 protein appeared to be rate-limiting for a proper auxin response measured by the co-transfected DR5::GUS reporter construct
T1002	Negation 726 733	lacking
E1001	Negation:T1002 Scope:T1003
T1003	Span 726 733	lacking
T1004	Negation 1465 1467	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1465 1497	no effect on Aux/IAA degradation
T1006	Negation 1316 1323	absence
E1003	Negation:T1006 Scope:T1007
T1007	Span 1316 1342	absence of auxin treatment
