T1000	Speculation 750 755	might
E1000	Speculation:T1000 Scope:T1001
T1001	Span 750 833	might correspond to the O-glycosylated forms bearing a phosphate or a sulfate group
T1002	Negation 717 720	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 696 833	Two other forms were not completely characterized but might correspond to the O-glycosylated forms bearing a phosphate or a sulfate group
T1004	Negation 857 860	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 857 977	not affect the capacity of the helospectins to recognize and to activate the human and the rat VPAC1 and VPAC2 receptors
