T1000	Speculation 1051 1060	potential
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1051 1087	potential glycosylation site at N570
T1002	Speculation 334 343	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 334 407	suggested carboxylase is a glycoprotein with N-linked glycosylation sites
T1004	Negation 1501 1504	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1475 1555	N-linked glycosylation is not required for the enzymatic function of carboxylase
T1006	Negation 1340 1343	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1340 1457	not affect either the carboxylation or epoxidation activity when the small FLEEL pentapeptide was used as a substrate
T1008	Negation 1754 1757	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1754 1853	not essential for carboxylase enzymatic activity but is important for protein folding and stability
T1010	Speculation 1459 1469	suggesting
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1459 1555	suggesting that N-linked glycosylation is not required for the enzymatic function of carboxylase
T1012	Speculation 1715 1722	suggest
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1715 1802	suggest that N-linked glycosylation is not essential for carboxylase enzymatic activity
