T1000	Speculation 1536 1539	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1536 1733	may reflect response to a selective pressure related to a decline in vitamin C in the diet during omnivorous dietary adaptation, either independently or through the common ancestor of these species
T1002	Speculation 1461 1468	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1461 1733	suggest that the absence of hydroxylation of Pro-9 in Pan, Pongo, and Homo may reflect response to a selective pressure related to a decline in vitamin C in the diet during omnivorous dietary adaptation, either independently or through the common ancestor of these species
