T1000	Negation 878 881	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 857 1014	USP1 autocleavage is not stimulated by DNA damage, and expressing a noncleavable mutant in the USP1 knockout strain partially rescues crosslinker sensitivity
T1002	Speculation 324 331	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 254 386	USP1, a protease that removes monoubiquitin from FANCD2 and PCNA, was thought to reverse the DNA damage response of these substrates
T1004	Negation 1135 1138	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1135 1169	not dependent on USP1 autocleavage
