T1000	Speculation 1048 1062	indicated that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1048 1117	indicated that its FSH residues offset the effects of deglycosylation
T1002	Speculation 454 459	would
E1001	Speculation:T1002 Scope:T1003
T1003	Span 454 500	would create a bifunctional antagonist (dgCFC)
T1004	Speculation 1186 1194	unlikely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1130 1219	this approach to preparing a bifunctional antagonist is unlikely to lead to a useful drug
T1006	Speculation 1119 1129	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1119 1219	suggesting this approach to preparing a bifunctional antagonist is unlikely to lead to a useful drug
T1008	Speculation 1306 1310	idea
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1306 1416	idea that oligosaccharides modulate glycoprotein hormone efficacy through an influence on hormone conformation
