T1000	Speculation 325 331	appear
E1000	Speculation:T1000 Scope:T1001
T1001	Span 292 442	This ordering, however, does not appear to be deterministic to the extent that chromatin and nonchromatin structures maintain a strict 3-D arrangement
T1002	Negation 321 324	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 321 442	not appear to be deterministic to the extent that chromatin and nonchromatin structures maintain a strict 3-D arrangement
T1004	Speculation 493 500	appears
E1002	Speculation:T1004 Scope:T1005
T1005	Span 452 573	spatial ordering within the cell nucleus appears to conform to stochastic rather than deterministic spatial relationships
T1006	Negation 526 537	rather than
E1003	Negation:T1006 Scope:T1007
T1007	Span 526 573	rather than deterministic spatial relationships
T1008	Negation 1267 1270	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1267 1334	not coincident are nonrandom and potentially biologically important
T1010	Negation 1186 1189	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1093 1198	the predicted one-to-one relationship between transcription factor and chromatin sequence is not observed
T1012	Speculation 1228 1235	whether
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1228 1281	whether spatial relationships that are not coincident
