T1000	Speculation 1847 1850	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1847 1962	may prevent hypoxic adaptation during CsA-induced nephrotoxicity and contribute to the adverse effects of this drug
T1002	Negation 1523 1526	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1506 1667	CsA effects were not observed when the proline residue corresponding to Pro-564 in the HIF-1alpha sequence was replaced by a hydroxyproline or an alanine residue
