T1000	Negation 882 885	nor
E1000	Negation:T1000 Scope:T1001
T1001	Span 882 954	nor was there evidence that secreted SP-A was endocytosed by COS-1 cells
T1002	Negation 847 850	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 847 881	not detectable on the cell surface
T1004	Speculation 1303 1313	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1303 1358	suggesting a role of glycosylation in secretion of SP-A
T1006	Negation 1120 1122	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1120 1180	no immunoreactive SP-A was detectable in cytosolic fractions
T1008	Speculation 1458 1461	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1458 1519	may cause destabilization of the collagen-like domain of SP-A
T1010	Negation 1537 1540	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1537 1590	not prevent secretion of SP-A into the culture medium
