T1000	Speculation 289 297	appeared
E1000	Speculation:T1000 Scope:T1001
T1001	Span 281 383	Mannose appeared to specifically inhibit thrombin binding to mouse embryo (ME) and hamster fibroblasts
T1002	Speculation 216 218	if
E1001	Speculation:T1002 Scope:T1003
T1003	Span 216 279	if glycosylation plays a role in thrombin-receptor interactions
T1004	Negation 804 810	unable
E1002	Negation:T1004 Scope:T1005
T1005	Span 804 827	unable to bind thrombin
T1006	Negation 728 731	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 728 740	not affected
T1008	Speculation 866 869	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 866 910	may be directly involved in thrombin binding
T1010	Speculation 742 757	indicating that
E1005	Speculation:T1010 Scope:T1011
T1011	Span 742 827	indicating that the receptor was present in the membrane, but unable to bind thrombin
