T1000	Speculation 1534 1541	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1534 1739	suggest that the activation of PKC induces the ubiquitylation of these C-terminal lysine residues in GLT1 and that this modification mediates the interaction of the transporter with the endocytic machinery
T1002	Speculation 942 957	indicating that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 942 1052	indicating that the addition of ubiquitin moieties to the transporter in the membrane precedes its endocytosis
