T1000	Speculation 1234 1237	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1200 1382	this remarkable cellular property may be explained by the asymmetric inheritance of peripheral centrosomal proteins when centrioles separate and migrate to opposite poles of the cell
T1002	Speculation 1187 1194	propose
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1187 1382	propose that this remarkable cellular property may be explained by the asymmetric inheritance of peripheral centrosomal proteins when centrioles separate and migrate to opposite poles of the cell
T1004	Speculation 1511 1518	thought
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1511 1518	thought
