T1000	Speculation 541 550	potential
E1000	Speculation:T1000 Scope:T1001
T1001	Span 541 593	potential mechanism for the dopaminergic dysfunction
T1002	Speculation 118 121	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 93 210	Parkinson's disease (PD) may be caused by a complex interaction of environmental insults and genetic susceptibilities
T1004	Negation 1183 1186	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1160 1249	These pathologies were not observed in brain regions of normal mice treated with paraquat
T1006	Negation 998 1001	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 998 1017	not in the striatum
T1008	Speculation 1339 1344	might
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1339 1427	might cooperatively involve the mechanisms underlying proteasome impairment in PD brains
T1010	Speculation 1277 1287	raises the
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1277 1427	raises the possibility that environmental and genetic factors might cooperatively involve the mechanisms underlying proteasome impairment in PD brains
