T1000	Negation 1171 1174	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1171 1210	not obligatory for prolyl hydroxylation
T1002	Speculation 993 995	or
E1001	Speculation:T1002 Scope:T1003
T1003	Span 984 1015	mutation or deletion of Leu-574
T1004	Speculation 1373 1386	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1373 1504	indicate that Leu-574 is essential for recruiting PHD2/HPH2, thereby providing a molecular basis for modulating HIF-1alpha activity
