T1000	Speculation 907 922	indicating that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 907 956	indicating that the two proteins weakly associate
T1002	Speculation 757 765	apparent
E1001	Speculation:T1002 Scope:T1003
T1003	Span 757 791	apparent molecular mass of 280 kDa
T1004	Speculation 1787 1794	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1787 1856	suggest that TCP is uniquely involved in TMA-dependent methanogenesis
