T1000	Negation 1172 1179	without
E1000	Negation:T1000 Scope:T1001
T1001	Span 1172 1266	without collagen-binding activity did not show any inhibitory effect on prolyl 4-hydroxylation
T1002	Speculation 508 514	and/or
E1001	Speculation:T1002 Scope:T1003
T1003	Span 508 556	and/or modification in the endoplasmic reticulum
T1004	Speculation 1316 1323	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1316 1401	suggest that HSP47 retards the enzymatic reaction competing for the substrate peptide
T1006	Negation 1210 1213	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1210 1266	not show any inhibitory effect on prolyl 4-hydroxylation
