T1000	Negation 1089 1096	without
E1000	Negation:T1000 Scope:T1001
T1001	Span 1089 1126	without preventing Smad2/3 activation
T1002	Negation 652 658	failed
E1001	Negation:T1002 Scope:T1003
T1003	Span 652 769	failed to block TGF-beta-induced responses in either primary cultures of PPAR-gamma-null murine embryonic fibroblasts
T1004	Speculation 1649 1662	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1649 1858	indicate that PPAR-gamma blocked Smad-mediated transcriptional responses by preventing p300 recruitment and histone H4 hyperacetylation, resulting in the inhibition of TGF-beta-induced collagen gene expression
T1006	Negation 1451 1454	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1451 1521	not a mutant form of p300 lacking functional histone acetyltransferase
T1008	Speculation 1906 1909	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1906 2052	may represent a novel therapeutic approach to target p300-dependent TGF-beta profibrotic responses such as stimulation of collagen gene expression
