T1000	Speculation 1250 1257	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1250 1399	suggest that FIH-dependent ARD hydroxylation is a common occurrence, potentially providing an oxygen-sensitive signal to a diverse range of processes
T1002	Negation 1215 1218	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1177 1236	this type of protein hydroxylation is not restricted to HIF
T1004	Speculation 1319 1330	potentially
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1319 1399	potentially providing an oxygen-sensitive signal to a diverse range of processes
