T1000	Negation 433 436	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 433 469	not destroy its substrate completely
T1002	Negation 42 53	rather than
E1001	Negation:T1002 Scope:T1003
T1003	Span 42 72	rather than polyubiquitination
T1004	Speculation 1142 1149	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1142 1250	suggest that a proteolytic signal can be composed of a cluster of single ubiquitins, not necessarily a chain
T1006	Negation 551 554	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 551 589	not generation of polyubiquitin chains
