T1000	Negation 1264 1267	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1264 1285	not been hydroxylated
T1002	Negation 1135 1137	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 1135 1285	no HP, which means that the helical lysines at residues 930 of alpha 1(I) and 933 of alpha 2(I) of the collagen triple-helix had not been hydroxylated
T1004	Speculation 2194 2197	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2194 2311	may allow the detection of chondrodysplasias due to genetic defects in lysyl hydroxylase isoforms active in cartilage
T1006	Speculation 1888 1895	appears
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1812 1974	The residual fraction of HP found in the urine of EDS VI patients therefore appears to be contributed in significant part by the degradation products of cartilage
