T1000	Speculation 1405 1410	might
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1405 1475	might act as blueprints for the maintenance of non-CpG DNA methylation
T1002	Negation 695 698	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 635 722	hereditary maintenance of non-CpG methylation patterns have not been analyzed in detail
T1004	Negation 1615 1618	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1615 1666	not in mutants defective for either Dnmt3a or Dnmt2
