T1000	Negation 818 821	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 818 825	not EGF
T1002	Speculation 252 261	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 252 433	suggested that the metabolism of glucose to glucosamine through the enzyme L-glutamine: D-fructose-6-phosphate amidotransferase (GFAT) plays a critical role in the glucose signaling
T1004	Speculation 1189 1195	notion
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1189 1288	notion that glucose stimulation of TGF-alpha expression requires GFAT, but EGF stimulation does not
T1006	Negation 1285 1288	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1285 1288	not
