T1000	Speculation 801 809	probable
E1000	Speculation:T1000 Scope:T1001
T1001	Span 801 827	probable autoimmune origin
T1002	Speculation 360 362	if
E1001	Speculation:T1002 Scope:T1003
T1003	Span 360 420	if abnormal glycosylation is limited to acute-phase proteins
T1004	Negation 1756 1758	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1756 1818	no differences were noted between patient samples and controls
T1006	Speculation 861 870	suspected
E1003	Speculation:T1006 Scope:T1007
T1007	Span 861 1082	suspected autoimmune origin: schizophrenia and Alzheimer's disease (AZ); and conditions not related to autoimmunity: pregnancy (PG) and elevation of the carcinoembryonic antigen (CEA), in comparison to normal donors (NHS)
T1008	Speculation 2267 2281	indicated that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2267 2419	indicated that there has been a selective increase in Con A-reactive fragments in both acute-phase and non-acute-phase proteins in autoimmune conditions
T1010	Negation 2118 2120	no
E1005	Negation:T1010 Scope:T1011
T1011	Span 2118 2143	no differences were noted
T1012	Speculation 2501 2504	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 2501 2609	may be a valuable diagnostic approach to define the pathophysiology of inflammatory and autoimmune disorders
