T1000	Speculation 546 551	infer
E1000	Speculation:T1000 Scope:T1001
T1001	Span 546 638	infer causal and combinatorial relationships among histone modifications and gene expression
T1002	Speculation 286 289	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 286 329	may combine to form complex "histone codes.
T1004	Speculation 1260 1271	potentially
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1260 1327	potentially applicable to other ChIP-chip or ChIP-seq data analyses
T1006	Speculation 1138 1141	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1138 1217	may predict new epigenetic interactions important in epigenetic gene regulation
