T1000	Negation 836 839	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 836 1027	not use a single general base or acid residue for substrate deprotonation and product reprotonation, respectively, and that a diffusional step, such as substrate binding, may be rate-limiting
T1002	Speculation 737 742	might
E1001	Speculation:T1002 Scope:T1003
T1003	Span 737 774	might play an autoregulatory function
T1004	Speculation 1007 1010	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1007 1027	may be rate-limiting
T1006	Speculation 813 821	suggests
E1003	Speculation:T1006 Scope:T1007
T1007	Span 813 949	suggests that PAT does not use a single general base or acid residue for substrate deprotonation and product reprotonation, respectively
T1008	Speculation 1140 1143	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1140 1153	may be better
T1010	Speculation 1118 1128	suggesting
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1118 1153	suggesting that there may be better
T1012	Speculation 1297 1305	suggests
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1297 1363	suggests that PAT is evolutionarily related to the eukaryotic HATs
