T1000	Negation 655 658	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 648 679	MI was not detected in any case
T1002	Speculation 459 472	evaluated for
E1001	Speculation:T1002 Scope:T1003
T1003	Span 411 560	DNA from paraffin-embedded tissue of 6 APAs was evaluated for microsatellite instability (MI), MLH-1 promoter hypermethylation, and CTNNB-1 mutations
T1004	Speculation 985 992	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 985 1074	suggest that APA and complex endometrial hyperplasia may share some molecular alterations
T1006	Negation 923 927	none
E1003	Negation:T1006 Scope:T1007
T1007	Span 923 957	none of them had CTNNB-1 mutations
T1008	Speculation 1038 1041	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1038 1074	may share some molecular alterations
