T1000	Negation 856 858	No
E1000	Negation:T1000 Scope:T1001
T1001	Span 856 912	No additional detergent was required during purification
T1002	Speculation 436 444	putative
E1001	Speculation:T1002 Scope:T1003
T1003	Span 436 502	putative enzyme responsible for the posttranslational modification
T1004	Negation 977 979	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 977 1019	no prolyl-4- or lysyl-hydroxylase activity
