T1000	Speculation 1600 1607	advance
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1600 1775	advance our understanding of the functional region(s) of Ebola virus NP, which in turn should improve our knowledge of the Ebola virus life cycle and its extreme pathogenicity
T1002	Negation 1160 1166	unable
E1001	Negation:T1002 Scope:T1003
T1003	Span 1160 1221	unable to identify the types of glycosylation and sialylation
T1004	Speculation 1687 1693	should
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1687 1775	should improve our knowledge of the Ebola virus life cycle and its extreme pathogenicity
