T1000	Speculation 872 879	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 872 1033	suggest that intracellular localization of TDP-43 and proteasomal function may be involved in inclusion formation and neurodegeneration in TDP-43 proteinopathies
T1002	Negation 756 762	lacked
E1001	Negation:T1002 Scope:T1003
T1003	Span 756 856	lacked the exon skipping activity of cystic fibrosis transmembrane conductance regulator (CFTR) exon
T1004	Speculation 947 950	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 947 1033	may be involved in inclusion formation and neurodegeneration in TDP-43 proteinopathies
