T1000	Negation 812 815	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 812 888	not its catalytic core was required for binding to and the stability of rpS2
T1002	Negation 642 645	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 642 742	not the amino-terminus of rpS2 that includes the RG repeat region was essential for binding to PRMT3
T1004	Speculation 1267 1270	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1267 1457	may control the level of rpS2 protein in cells by inhibiting ubiquitin-mediated proteolysis of rpS2, while rpS2 may regulate the enzymatic activity of PRMT3 as a likely non-catalytic subunit
T1006	Speculation 1209 1216	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1209 1457	suggest that in addition to its catalytic function, PRMT3 may control the level of rpS2 protein in cells by inhibiting ubiquitin-mediated proteolysis of rpS2, while rpS2 may regulate the enzymatic activity of PRMT3 as a likely non-catalytic subunit
T1008	Speculation 1429 1435	likely
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1429 1457	likely non-catalytic subunit
T1010	Speculation 1379 1382	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1379 1457	may regulate the enzymatic activity of PRMT3 as a likely non-catalytic subunit
