T1000	Speculation 814 820	appear
E1000	Speculation:T1000 Scope:T1001
T1001	Span 756 1048	Histone variants such as histone H3.3, H2AX, and macroH2A appear to play key roles in the various stages of spermiogenesis, in addition to the specifically modulated acetylation of histone H4 (acH4), ubiquitination of histones H2A and H2B (uH2A, uH2B), and phosphorylation of histone H3 (H3p)
T1002	Speculation 661 664	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 661 754	may shed light upon the mechanisms involved and the control of chromatin structure in general
