T1000	Negation 2109 2116	without
E1000	Negation:T1000 Scope:T1001
T1001	Span 2109 2153	without reducing its antagonistic properties
T1002	Negation 1984 1987	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1984 2153	not favorable in eliminating the initial pressor activity or prolonging the duration of action of [Sar1, Ile8]angiotensin II without reducing its antagonistic properties
T1004	Negation 2284 2287	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 2284 2376	not afford protection against proteolytic enzymes; and (d) perfusion studies in cat adrenals
T1006	Negation 2170 2174	none
E1003	Negation:T1006 Scope:T1007
T1007	Span 2170 2228	none of the analogs showed any enhanced duration of action
T1008	Speculation 1894 1909	indicating that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1894 2153	indicating that steric hindrance imposed due to N-methylation in positions 4, 5, or 8 was not favorable in eliminating the initial pressor activity or prolonging the duration of action of [Sar1, Ile8]angiotensin II without reducing its antagonistic properties
T1010	Speculation 1510 1517	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1510 2153	suggest that (a) analogs I and VI are potent antagonists of the pressor response of angiotensin II in normal rat, VI being the most potent antagonist thus far synthesized; (b) replacement of position 4 (Tyr) with MeTyr or position 5 and/or 8 (Ile) with Melle in [1-sarcosine,8-isoleucine]angiotensin II reduced the antagonist activity of this peptide (rabbit aortic strips and rats), indicating that steric hindrance imposed due to N-methylation in positions 4, 5, or 8 was not favorable in eliminating the initial pressor activity or prolonging the duration of action of [Sar1, Ile8]angiotensin II without reducing its antagonistic properties
T1012	Speculation 2230 2240	suggesting
E1006	Speculation:T1012 Scope:T1013
T1013	Span 2230 2376	suggesting that N-methylation in positions 5 or 8 did not afford protection against proteolytic enzymes; and (d) perfusion studies in cat adrenals
T1014	Speculation 1975 1977	or
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1959 2153	positions 4, 5, or 8 was not favorable in eliminating the initial pressor activity or prolonging the duration of action of [Sar1, Ile8]angiotensin II without reducing its antagonistic properties
T1016	Negation 2447 2455	With the
E1008	Negation:T1016 Scope:T1017
T1017	Span 2447 2474	With the exception of [Sar1
T1018	Speculation 2377 2391	indicated that
E1009	Speculation:T1018 Scope:T1019
T1019	Span 2377 2445	indicated that all of these analogs are only very weak secretagogues
