T1000	Negation 847 854	without
E1000	Negation:T1000 Scope:T1001
T1001	Span 847 868	without glycosylation
T1002	Speculation 405 414	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 405 448	suggested to serve as a cold-duration clock
T1004	Speculation 1156 1163	appears
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1140 1237	The sugar chain appears to reinforce the binding of peptidyl inhibitory needle, which may in turn
T1006	Speculation 1080 1090	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1080 1138	suggesting a timer mechanism in which this ion is involved
T1008	Speculation 1226 1229	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1226 1380	may in turn stabilize the initial conformation of the N-terminal domain, explaining the requirement for glycosylation and for the peptide to set the clock
