T1000	Speculation 1186 1194	putative
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1186 1203	putative upstream
T1002	Speculation 585 596	hypothesize
E1001	Speculation:T1002 Scope:T1003
T1003	Span 585 784	hypothesize that Tg forms homodimers through noncovalent interactions involving two predicted alpha-helices in each ChEL domain that are homologous to the dimerization helices of acetylcholinesterase
