T1000	Speculation 1113 1118	might
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1113 1185	might serve as a new parameter for the prognosis of colorectal carcinoma
T1002	Speculation 138 140	if
E1001	Speculation:T1002 Scope:T1003
T1003	Span 138 244	if p16 methylation in the serum can serve as a candidate marker for the malignancy of colorectal carcinoma
T1004	Speculation 1315 1320	could
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1288 1357	early colorectal carcinoma could be detected using the RTQ-MSP method
T1006	Speculation 1272 1282	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1272 1357	suggesting that early colorectal carcinoma could be detected using the RTQ-MSP method
