T1000	Speculation 1458 1465	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1458 1533	suggest a model for how this enzyme might be involved in cancer development
T1002	Speculation 4 12	putative
E1001	Speculation:T1002 Scope:T1003
T1003	Span 4 27	putative oncogene GASC1
T1004	Speculation 1539 1546	propose
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1539 1585	propose it as a target for anti-cancer therapy
T1006	Speculation 1494 1499	might
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1482 1533	this enzyme might be involved in cancer development
