T1000	Negation 733 736	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 733 806	not clearly suggest superiority of these combinations over rhGM-CSF alone
T1002	Negation 296 303	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 296 335	without and after standard chemotherapy
T1004	Speculation 817 820	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 817 879	may be partly due to the time scheduling of the growth factors
T1006	Speculation 745 752	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 745 806	suggest superiority of these combinations over rhGM-CSF alone
T1008	Speculation 1170 1173	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1170 1291	may allow a very high yield of peripheral stem cells suitable for bone marrow reconstitution after high-dose chemotherapy
T1010	Negation 904 907	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 904 938	not inferior to i.v.  Side effects
T1012	Speculation 1415 1418	not
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1415 1523	not yet clear in which way rhIL-3 combined with chemotherapy will effect tumor response and patient survival
