T1000	Negation 1351 1362	rather than
E1000	Negation:T1000 Scope:T1001
T1001	Span 1351 1474	rather than Rps2 methylation, is important for the function of Rmt3 in the regulation of small ribosomal subunit production
T1002	Negation 1232 1235	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1232 1296	not rescue the 40 S ribosomal subunit deficit of RMT3-null cells
T1004	Speculation 1311 1318	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1311 1379	suggest that the Rmt3-Rps2 interaction, rather than Rps2 methylation
