T1000	Negation 781 783	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 781 1047	no hydroxylation of the epidermal growth factor (EGF) domain of clotting Factor X. In addition to reduced fertility in females, BAH null mice display several developmental defects including syndactyly, facial dysmorphology, and a mild defect in hard palate formation
T1002	Negation 658 662	lack
E1001	Negation:T1002 Scope:T1003
T1003	Span 658 767	lack measurable BAH protein in several tissues, lack aspartyl beta-hydroxylase activity in liver preparations
T1004	Speculation 1579 1582	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1579 1689	may represent another post-translational modification of EGF domains that can modulate Notch pathway signaling
T1006	Speculation 1535 1545	suggestion
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1535 1689	suggestion that aspartyl beta-hydroxylation may represent another post-translational modification of EGF domains that can modulate Notch pathway signaling
T1008	Speculation 2140 2147	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2140 2241	suggest that, in contrast to expectations, loss of BAH catalytic activity may promote tumor formation
T1010	Speculation 1816 1824	proposed
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1816 1824	proposed
T1012	Speculation 2214 2217	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 2214 2241	may promote tumor formation
