T1000	Negation 1171 1173	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 1171 1215	no effect on vincristine-mediated cell death
T1002	Speculation 340 349	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 325 463	HDIs have been suggested to enhance the anticancer efficacy of other therapeutic regimens, such as ionizing radiation (IR) or chemotherapy
T1004	Speculation 1410 1413	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1410 1561	may be useful for the treatment of medulloblastoma as monotherapy and particularly when given in combination with IR, appropriate cytostatics, or TRAIL
