T1000	Speculation 913 921	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 913 1115	suggests that both poleta and poliota diffuse through the cell but that they are transiently immobilized for approximately 150 ms, with a larger proportion of poleta than poliota immobilized at any time
T1002	Negation 691 694	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 691 742	not required for the localization of poleta in foci
T1004	Negation 1258 1261	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1258 1269	not poliota
