T1000	Negation 1492 1495	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1483 1547	TRADD is not incorporated into TNFR2-mediated TNFalpha signaling
T1002	Speculation 1345 1352	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1345 1475	suggest that the decrease in TRADD resulting from enhanced ubiquitin-dependent degradation is involved in obstructive renal injury
T1004	Speculation 1632 1635	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1632 1663	may function, at least in part,
