T1000	Speculation 1027 1036	suggested
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1027 1147	suggested that the sequence abnormality had interfered with the propagation of the triple helix across the mutant region
T1002	Negation 963 966	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 963 1012	not in the carboxyl-terminal CB6 and CB7 peptides
T1004	Negation 1332 1335	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1332 1454	not show any evidence of the defect it is likely that the baby had a new mutation of one allele of the pro-alpha 1(I) gene
T1006	Negation 1175 1178	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1149 1241	The abnormal collagen was not incorporated into the more insoluble fraction of bone collagen
T1008	Speculation 1374 1380	likely
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1374 1454	likely that the baby had a new mutation of one allele of the pro-alpha 1(I) gene
T1010	Speculation 1252 1260	appeared
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1243 1367	The baby appeared to be heterozygous for the sequence abnormality and as the parents did not show any evidence of the defect
