T1000	Speculation 1116 1123	propose
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1116 1217	propose that loss of lipid asymmetry in the cis Golgi perturbs retrograde protein transport to the ER
T1002	Speculation 980 987	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 980 1111	suggest that the anterograde protein transport defect is a secondary consequence of a defect in a COPI-dependent retrograde pathway
