T1000	Negation 693 696	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 693 736	not blocked by inhibition of the proteasome
T1002	Speculation 339 346	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 339 535	thought that the polyubiquitin chains attached to IRAK1 are linked via Lys48 of ubiquitin, leading to its destruction by the proteasome and explaining the rapid IL-1-induced disappearance of IRAK1
T1004	Negation 1006 1012	unable
E1002	Negation:T1004 Scope:T1005
T1005	Span 1006 1102	unable to restore IL-1-stimulated NF-kappaB-dependent gene transcription to NEMO-deficient cells
T1006	Negation 881 884	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 881 944	not with the NEMO[D311N] mutant that cannot bind K63-pUb chains
T1008	Speculation 1113 1120	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1113 1318	suggest a model in which the recruitment of the NEMO-IKK complex to K63-pUb-IRAK1 and the recruitment of the TAK1 complex to TRAF6 facilitate the TAK1-catalyzed activation of IKK by the TRAF6-IRAK1 complex
