T1000	Speculation 1695 1705	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1695 1806	suggesting that alterations of APP processing might occur both in the neuronal compartment and peripheral cells
T1002	Speculation 1144 1152	probable
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1144 1155	probable AD
T1004	Speculation 1741 1746	might
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1741 1806	might occur both in the neuronal compartment and peripheral cells
