T1000	Speculation 668 674	appear
E1000	Speculation:T1000 Scope:T1001
T1001	Span 668 909	appear to reside in open chromatin environments, at least as inferred from relatively high levels of acetylation of core histones H3 and H4 when compared with adjacent intergenic DNA and from enhanced trimethylation of histone H3 at lysine 4
T1002	Negation 632 639	absence
E1001	Negation:T1002 Scope:T1003
T1003	Span 632 645	absence of GH
T1004	Negation 1002 1009	absence
E1002	Negation:T1004 Scope:T1005
T1005	Span 1002 1020	absence of hormone
T1006	Speculation 944 947	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 944 979	may reflect maturation of the liver
