T1000	Speculation 266 273	perhaps
E1000	Speculation:T1000 Scope:T1001
T1001	Span 266 403	perhaps on the basis of inherited variation (polymorphism) in genes which influence the activation or inactivation of dietary carcinogens
T1002	Speculation 182 193	possibility
E1001	Speculation:T1002 Scope:T1003
T1003	Span 182 403	possibility is that the effect of environmental factors varies between individuals, perhaps on the basis of inherited variation (polymorphism) in genes which influence the activation or inactivation of dietary carcinogens
T1004	Speculation 872 877	might
E1002	Speculation:T1004 Scope:T1005
T1005	Span 872 1148	might include enhanced activation of polycyclic aromatic hydrocarbons and N-nitroso compounds by variant genotypes of CYP1A1 and CYP2E1, respectively, and modulation by meat of the protective effect of the E4 allele of apolipoprotein E on risk for cancer of the proximal colon
T1006	Speculation 365 367	or
E1003	Speculation:T1006 Scope:T1007
T1007	Span 365 403	or inactivation of dietary carcinogens
