T1000	Speculation 1187 1195	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1187 1371	suggests that Rad6 is recruited to promoters independently of the Paf1 complex but then requires this complex for entrance into the coding region of genes in a Pol II-associated manner
T1002	Speculation 587 594	appears
E1001	Speculation:T1002 Scope:T1003
T1003	Span 570 836	This association appears to be necessary for the transcriptional activities of Rad6, as deletion of various Paf1 complex members or Bre1 abolishes H2B ubiquitylation (ubH2B) and reduces the recruitment of Rad6 to the promoters and transcribed regions of active genes
T1004	Speculation 2085 2093	indicate
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2085 2177	indicate a role for Rad6 and H2B ubiquitylation during the elongation cycle of transcription
T1006	Speculation 1827 1836	suspected
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1827 1869	suspected transcription elongation factors
T1008	Speculation 2226 2229	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2211 2242	H3 methylation may be regulated
T1010	Speculation 2182 2189	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 2182 2242	suggest a mechanism by which H3 methylation may be regulated
