T1000	Speculation 973 984	suggestions
E1000	Speculation:T1000 Scope:T1001
T1001	Span 973 1067	suggestions that it is required for normal mitosis and cell cycle progression, K20 methylation
T1002	Speculation 862 872	hypothesis
E1001	Speculation:T1002 Scope:T1003
T1003	Span 862 963	hypothesis that K20 methylation antagonizes H4 acetylation and represses transcription epigenetically
T1004	Speculation 1253 1259	appear
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1253 1397	appear to be secondary to histone hyperacetylation or other effects of butyrate since depletion of PR-Set7 did not affect cell cycle progression
T1006	Negation 1364 1367	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1364 1397	not affect cell cycle progression
