T1000	Speculation 565 575	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 565 722	suggesting that the first 201 amino acids of the CysG protein had an enzymic activity associated with the conversion of dihydrosirohydrochlorin into sirohaem
T1002	Negation 514 517	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 514 555	not able to complement E. coli cysG cells
T1004	Negation 1067 1069	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1067 1102	no such coenzyme-dependent activity
T1006	Speculation 798 806	putative
E1003	Speculation:T1006 Scope:T1007
T1007	Span 798 841	putative pyridine dinucleotide binding site
T1008	Speculation 1339 1347	suggests
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1339 1504	suggests that the CysG protein is a multifunctional protein involved in SAM-dependent methylation, pyridine dinucleotide dependent dehydrogenation and ferrochelation
T1010	Speculation 1233 1242	suggested
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1233 1300	suggested that the CysG protein was also involved in ferrochelation
