T1000	Speculation 1669 1676	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1669 1864	suggest that 5AZA used in combination with HDI may be an interesting chemotherapeutic regimen to investigate in patients with acute myeloid leukemia that is resistant to conventional chemotherapy
T1002	Speculation 664 670	should
E1001	Speculation:T1002 Scope:T1003
T1003	Span 664 744	should produce an enhancement of their antineoplastic activity on leukemic cells
T1004	Speculation 1716 1719	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1716 1864	may be an interesting chemotherapeutic regimen to investigate in patients with acute myeloid leukemia that is resistant to conventional chemotherapy
