T1000	Speculation 1032 1036	idea
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1032 1184	idea that TULA enhances the apoptotic effect of AIF by facilitating the interactions of AIF with its apoptotic co-factors, which remain to be identified
T1002	Speculation 438 451	indicate that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 438 566	indicate that TULA facilitates T-cell apoptosis independent of either T-cell receptor/CD3-mediated signaling or caspase activity
