T1000	Negation 492 495	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 492 500	not Cx32
T1002	Negation 422 425	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 422 500	not Cx43 and WB-F344 rat liver epithelial cells that express Cx43 but not Cx32
T1004	Speculation 562 576	indicated that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 562 728	indicated that two MspI/HpaII restriction sites in the Cx32 promoter (positions -147 and -847) were methylated in WB-F344 cells, but not in MH1C1 cells or hepatocytes
T1006	Negation 695 698	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 695 728	not in MH1C1 cells or hepatocytes
T1008	Speculation 968 982	indicated that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 968 1100	indicated that the Cx32 promoter was 7-fold more active in MH1C1 cells and the Cx43 promoter was 5-fold more active in WB-F344 cells
T1010	Negation 845 848	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 845 880	not in WB-F344 cells or hepatocytes
T1012	Speculation 1278 1281	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1259 1374	Similar mechanisms may be involved in the reduced expression of these genes frequently observed in neoplastic cells
T1014	Speculation 1116 1123	suggest
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1116 1257	suggest that transcription of Cx32 and Cx43 in hepatic cells is controlled by promoter methylation and by cell-specific transcription factors
