T1000	Speculation 350 364	indicates that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 350 549	indicates that Ras activation happens dynamically within defined plasma membrane microdomains and at other specific intracellular compartments, thus ensuring the generation of distinct signal outputs
T1002	Speculation 251 258	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 251 321	thought to occur uniformly on the inner leaflet of the plasma membrane
T1004	Speculation 1563 1569	should
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1563 1645	should provide new insights into the nature and dynamics of protein ubiquitination
T1006	Speculation 1480 1483	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1480 1512	may be subject to ubiquitination
