T1000	Negation 1387 1390	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1387 1435	not changed after 48 h. After 24 h of incubation
T1002	Negation 885 888	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 885 919	not form using a degassed solution
T1004	Speculation 1895 1900	would
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1895 2021	would play an important role in accelerating the hydroxylation in the apoferritin cavity compared to the bulk solution outside
