T1000	Negation 1013 1024	rather than
E1000	Negation:T1000 Scope:T1001
T1001	Span 1013 1060	rather than by enhancing promoter accessibility
T1002	Negation 311 314	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 311 366	not been ascribed to any particular regulatory function
T1004	Speculation 878 885	propose
E1002	Speculation:T1004 Scope:T1005
T1005	Span 878 1060	propose that global acetylation by the MSL complex increases the expression of X-linked genes by facilitating transcription elongation rather than by enhancing promoter accessibility
