T1000	Negation 801 807	failed
E1000	Negation:T1000 Scope:T1001
T1001	Span 801 862	failed to demonstrate dimerization of the nascent proreceptor
T1002	Negation 88 95	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 88 111	without dimer formation
T1004	Negation 1095 1098	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1023 1164	similar to that observed in vivo, insulin proreceptor dimerization does not appear to be a co-translational or early post-translational event
T1006	Negation 992 999	without
E1003	Negation:T1006 Scope:T1007
T1007	Span 992 1015	without dimer formation
T1008	Speculation 1099 1105	appear
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1099 1164	appear to be a co-translational or early post-translational event
