T1000	Speculation 639 646	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 608 755	the function of these antigens appears to be dependent on the presence of multiple O-linked alpha-N-acetylgalactosamine (alpha-GalNAc) determinants
T1002	Speculation 544 547	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 544 597	may be good targets for anticryptosporidial therapies
T1004	Speculation 1999 2006	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1999 2101	suggest that a surrogate system using T. gondii for the study of Cryptosporidium biology may be useful
T1006	Speculation 908 913	would
E1003	Speculation:T1006 Scope:T1007
T1007	Span 908 996	would greatly facilitate the molecular and functional characterization of these antigens
T1008	Speculation 2088 2091	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2088 2101	may be useful
