T1000	Speculation 1320 1323	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1320 1407	may participate in transcriptional regulation through ESET-mediated histone methylation
T1002	Speculation 1268 1277	raise the
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1268 1407	raise the possibility that transcription factor ERG may participate in transcriptional regulation through ESET-mediated histone methylation
