T1000	Speculation 1065 1068	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1065 1139	may preserve G:T processing in vivo by preventing CBP-mediated acetylation
T1002	Negation 1024 1027	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1024 1059	not markedly alter DNA interactions
T1004	Speculation 1161 1169	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1161 1246	suggests that the acetyl-acceptor lysines are not directly involved in contacting DNA
T1006	Negation 1207 1210	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1207 1337	not directly involved in contacting DNA, but may constitute a conformationally sensitive interface that modulates DNA interactions
T1008	Speculation 1451 1458	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1451 1602	suggest that the interplay of these modifications in vivo may be critically important in the maintenance of CpG dinucleotides and epigenetic regulation
T1010	Speculation 1252 1255	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1252 1337	may constitute a conformationally sensitive interface that modulates DNA interactions
T1012	Speculation 1509 1512	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1509 1602	may be critically important in the maintenance of CpG dinucleotides and epigenetic regulation
