T1000	Negation 1401 1404	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1401 1450	not essential for growth in this life cycle stage
T1002	Negation 1008 1011	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1008 1059	not require trypanosome cofactors for this activity
T1004	Speculation 1704 1710	likely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1693 1843	TbPRMT5 is likely to be involved in novel methylation-regulated functions in trypanosomes, some of which may include RNA processing and/or translation
T1006	Speculation 1375 1389	indicates that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1375 1450	indicates that TbPRMT5 is not essential for growth in this life cycle stage
T1008	Speculation 1798 1801	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1798 1843	may include RNA processing and/or translation
