T1000	Speculation 1465 1472	propose
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1465 1605	propose that plants use chromatin methylation as a defense against DNA viruses, which geminiviruses counter by inhibiting global methylation
T1002	Speculation 708 720	hypothesized
E1001	Speculation:T1002 Scope:T1003
T1003	Span 708 788	hypothesized that the viral genome is targeted by small-RNA-directed methylation
T1004	Speculation 1719 1726	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1719 1792	suggest that there are redundant pathways leading to cytosine methylation
