T1000	Speculation 993 1000	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 988 1026	YB-1 appears to play in tumourigenesis
T1002	Speculation 338 346	putative
E1001	Speculation:T1002 Scope:T1003
T1003	Span 338 410	putative E3 ubiquitin ligase due to the presence of a RING finger domain
T1004	Speculation 1059 1062	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1059 1145	may be a relevant target for therapeutic drugs aimed at modifying the activity of YB-1
T1006	Speculation 1040 1047	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1040 1145	suggest that RBBP6 may be a relevant target for therapeutic drugs aimed at modifying the activity of YB-1
