T1000	Negation 908 911	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 908 1020	not absolutely necessary for cell surface expression or responsiveness to icilin, menthol, and cool temperatures
T1002	Negation 353 355	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 353 502	no obvious effects on channel function in intracellular calcium imaging assays upon application of agonists, icilin or menthol, and cold temperatures
T1004	Speculation 820 828	putative
E1002	Speculation:T1004 Scope:T1005
T1005	Span 820 840	putative pore region
T1006	Speculation 699 708	potential
E1003	Speculation:T1006 Scope:T1007
T1007	Span 699 767	potential N-linked glycosylation sites in TRPM8 (Asn-821 and Asn-934
T1008	Speculation 1068 1082	indicated that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1068 1112	indicated that they are complex carbohydrate
