T1000	Speculation 493 502	suggested
E1000	Speculation:T1000 Scope:T1001
T1001	Span 493 559	suggested that Cue1p may, in addition, stimulate Ubc7p E2 activity
T1002	Speculation 375 382	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 353 449	The role of Cue1p was thought to involve passive concentration of Ubc7p at the surface of the ER
T1004	Speculation 1428 1436	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1428 1525	suggests a previously unappreciated mode for regulation of E2s by Cue1p-like interacting partners
T1006	Speculation 514 517	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 514 559	may, in addition, stimulate Ubc7p E2 activity
