T1000	Speculation 803 814	potentially
E1000	Speculation:T1000 Scope:T1001
T1001	Span 803 836	potentially be DNA repair related
T1002	Speculation 799 802	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 799 836	may potentially be DNA repair related
T1004	Speculation 865 868	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 838 864	Another possible mechanism
T1006	Speculation 846 854	possible
E1003	Speculation:T1006 Scope:T1007
T1007	Span 846 941	possible mechanism may be linked to changes in the expression of DNA methyltransferases (DNMTs)
