T1000	Speculation 810 815	could
E1000	Speculation:T1000 Scope:T1001
T1001	Span 810 890	could result in the phenotype displayed by patients with familial erythrocytosis
T1002	Speculation 712 720	implying
E1001	Speculation:T1002 Scope:T1003
T1003	Span 712 890	implying that partial inhibition or selective inhibition with regard to HIFalpha isoforms of PHD2 could result in the phenotype displayed by patients with familial erythrocytosis
