T1000	Speculation 1298 1303	seems
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1298 1434	seems possible that this increased prolyl hydroxylase activity is only a temporary phenomenon occurring shortly after the transformation
T1002	Speculation 854 864	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 854 936	suggesting a more efficient regulation of the last enzyme than of the three others
T1004	Speculation 1440 1443	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1440 1487	may be followed by a decrease in activity later
T1006	Speculation 1304 1312	possible
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1304 1434	possible that this increased prolyl hydroxylase activity is only a temporary phenomenon occurring shortly after the transformation
T1008	Speculation 1756 1763	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1756 1905	suggest that one critical factor affecting modification is the rate of collagen synthesis, which affects the ratio of enzyme to substrate in the cell
