T1000	Negation 1258 1263	lacks
E1000	Negation:T1000 Scope:T1001
T1001	Span 1258 1274	lacks this motif
T1002	Negation 1238 1241	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1238 1274	not to TTYH1, which lacks this motif
T1004	Speculation 1654 1669	indicating that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1654 1831	indicating that Nedd4-2 differentially interacts with and regulates TTYH1-3, will be important for understanding mechanisms controlling Tweety proteins in physiology and disease
T1006	Speculation 1078 1091	indicate that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1078 1250	indicate that Nedd4-2 binds to two family members, TTYH2 and TTYH3, which contain consensus PY ((L/P)PXY) binding sites for HECT type E3 ubiquitin ligases, but not to TTYH1
