T1000	Speculation 1027 1034	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1015 1107	this enzyme appears to bind the peptides in a conformation resembling that of conformation A
T1002	Speculation 433 440	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 433 522	whether the protein kinases differentiate between substrates on the basis of conformation
T1004	Speculation 1286 1289	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1286 1395	may, therefore, represent a way of making peptide substrates and inhibitors selective for a particular kinase
