T1000	Speculation 1075 1083	indicate
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1075 1138	indicate alterations in the dolichol or dolichol phosphate pool
T1002	Speculation 1071 1074	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1071 1138	may indicate alterations in the dolichol or dolichol phosphate pool
T1004	Speculation 1406 1413	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1406 1625	suggest an imbalance in the multilevel regulation of the biosynthesis of cholesterol and non-sterol isoprenoids in MKD, representing an additional causative factor responsible for the pre- and postnatal pathology of MKD
T1006	Speculation 1323 1333	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1323 1392	suggesting an impairment of non-sterol isoprenoid biosynthesis in MKD
