T1000	Negation 1630 1633	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1561 1698	the interaction of these amino acids with beta lactam antibiotics is not carried out to the same extent for all the cephalosporins tested
T1002	Negation 1236 1238	No
E1001	Negation:T1002 Scope:T1003
T1003	Span 1236 1353	No relation was found between the displacement of the marker and the chemical nature of the substituents at R1 and R2
