T1000	Negation 936 938	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 936 949	no difference
T1002	Negation 669 672	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 669 738	not influenced by the presence of sialic acid on the galactose moiety
T1004	Speculation 1238 1245	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1238 1340	suggest diminished sialic content of the O-linked oligosaccharides of IgA1 in HSP compared to controls
