T1000	Speculation 1796 1803	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1796 1948	suggest a role for the methylation of lysyl residues, located in selected domains, in the thermal stabilization of beta-glycosidase from S. solfataricus
T1002	Speculation 849 858	indicated
E1001	Speculation:T1002 Scope:T1003
T1003	Span 849 928	indicated similar secondary structure contents for the two forms of the protein
