T1000	Speculation 3322 3332	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 3322 3435	suggesting that a hypoxic up-regulation of PHD acts via feedback mechanism to attenuate hypoxia induced responses
T1002	Speculation 3288 3296	possibly
E1001	Speculation:T1002 Scope:T1003
T1003	Span 3288 3435	possibly via elevated HIF-1alpha, suggesting that a hypoxic up-regulation of PHD acts via feedback mechanism to attenuate hypoxia induced responses
T1004	Speculation 3441 3444	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 3437 3496	PHD may also be regulated by posttranscriptional mechanisms
