T1000	Negation 534 538	lack
E1000	Negation:T1000 Scope:T1001
T1001	Span 534 607	lack of an obvious defect in Kar2p-mediated pathways in scj1 null mutants
T1002	Speculation 398 406	probable
E1001	Speculation:T1002 Scope:T1003
T1003	Span 398 425	probable cofactor for Kar2p
T1004	Speculation 1351 1358	propose
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1351 1466	propose that the major role for Scj1p is to cooperate with Kar2p to mediate maturation of proteins in the RER lumen
