T1000	Speculation 834 841	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 834 1005	suggest that the beta-subunit is synthesized as a 52-kDa glycoprotein with seven N-linked precursor high-mannose oligosaccharides that mature into complex oligosaccharides
T1002	Speculation 507 516	potential
E1001	Speculation:T1002 Scope:T1003
T1003	Span 507 545	potential N-linked glycosylation sites
T1004	Negation 1281 1283	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1281 1307	no change in the Km for K+
