T1000	Speculation 1006 1014	probably
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1006 1076	probably also important for the bioactivity and potency of the hormone
T1002	Speculation 394 401	appears
E1001	Speculation:T1002 Scope:T1003
T1003	Span 394 566	appears that the charge of the gonadotrophin conferred by the acid radicals attached to the terminal groups on the oligosaccharide structures strongly influences biopotency
