T1000	Negation 1019 1030	rather than
E1000	Negation:T1000 Scope:T1001
T1001	Span 1019 1085	rather than the PP-II helix, was in equilibrium with the beta-turn
T1002	Speculation 502 511	indicated
E1001	Speculation:T1002 Scope:T1003
T1003	Span 502 872	indicated an equilibrium mixture of the polyproline-II (PP-II) helix, the beta-turn, and the random coil conformations in aqueous and trifluoroethanol solutions of the "collagen-related" peptides: t-Boc-Pro-Pro-Gly-Pro-OH, t-Boc-Pro-Pro-Gly-Pro-NHCH3, t-Pro-Pro-Gly-Pro-Pro-OH, t-Boc-Pro-Pro-Ala-Pro-OH, and t-Boc-Pro-Pro-Gln-Pro-OCH3, where t-Boc is tert-butoxycarbonyl
T1004	Negation 1503 1505	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1503 1559	no effect on the hydroxylation of the standard substrate
T1006	Speculation 989 998	indicated
E1003	Speculation:T1006 Scope:T1007
T1007	Span 989 1046	indicated the beta-structure, rather than the PP-II helix
T1008	Speculation 1855 1860	would
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1855 1996	would aid effective interaction at the substrate binding subsites, while the beta-turn would be essential at the catalytic site of the enzyme
T1010	Speculation 1640 1647	propose
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1640 1833	propose that in collagen and related peptides, a supersecondary structure consisting of the PP-II helix followed by the beta-turn is the minimal structural requirement for proline hydroxylation
T1012	Speculation 2057 2060	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 2057 2104	may be interchangeable with the PP-II structure
T1014	Speculation 1942 1947	would
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1942 1996	would be essential at the catalytic site of the enzyme
