T1000	Speculation 475 489	indicated that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 475 545	indicated that no more than 78% of the available N-sites were occupied
T1002	Speculation 289 298	potential
E1001	Speculation:T1002 Scope:T1003
T1003	Span 289 320	potential N-glycosylation sites
T1004	Speculation 770 776	should
E1002	Speculation:T1004 Scope:T1005
T1005	Span 732 862	endo H-resistant and, accordingly, it should be derived from the precursor oligosaccharide Man5-GlcNAc2 synthesized by this mutant
T1006	Speculation 616 631	indicating that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 616 707	indicating that the lipid-linked precursor had completed its synthesis to Glc3-Man9-GlcNAc2
T1008	Speculation 1401 1406	seems
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1313 1621	The preferential transfer of truncated oligosaccharides to the first glycosylation site seems to be a consequence of (1) the low percentage of truncated lipid linked oligosaccharides that receives the glucotriose unit, and (2) the effect of the glucotriose unit on the selection of N-sites to be glycosylated
T1010	Speculation 1132 1146	indicated that
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1132 1215	indicated that 38% of the oligosaccharides attached to the second site were regular
