T1000	Negation 1469 1472	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1469 1544	not to be efficiently recognised and degraded once they have escaped the ER
T1002	Negation 341 345	fail
E1001	Negation:T1002 Scope:T1003
T1003	Span 341 510	fail to fold correctly are subject to ER associated degradation (ERAD), which involves their extraction from the membrane and subsequent proteasome-dependent destruction
T1004	Speculation 1679 1682	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1679 1739	may provide a way to reduce degradation of unstable proteins
T1006	Speculation 1615 1626	potentially
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1615 1658	potentially to cytoplasmic quality controls
