T1000	Speculation 286 294	possible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 286 352	possible sites for hydroxylation of proline by proline hydroxylase
T1002	Negation 190 193	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 171 256	Hydroxyproline was not detected in the heavy and light chains portions of H kininogen
T1004	Speculation 519 532	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 519 672	indicate that only kinin moity in H kininogen from human and monkey plasmas has been partially hydroxylated post-translationally by proline-4-hydroxylase
