T1000	Speculation 502 509	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 466 525	Multimer composition of adiponectin appears to be regulated
T1002	Speculation 427 433	appear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 407 464	these HMW multimers appear to be the more bioactive forms
T1004	Speculation 1960 1967	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1960 2072	suggest that adiponectin multimer composition is affected by changes in PTM in response to physiological factors
T1006	Speculation 586 597	hypothesize
E1003	Speculation:T1006 Scope:T1007
T1007	Span 586 719	hypothesize that regulation of adiponectin multimerization and secretion occurs via changes in posttranslational modifications (PTMs)
