T1000	Negation 385 388	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 385 396	not in TGCT
T1002	Negation 70 73	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 0 109	The loss of NKX3.1 expression in testicular--and prostate--cancers is not caused by promoter hypermethylation
T1004	Speculation 471 483	hypothesized
E1002	Speculation:T1004 Scope:T1005
T1005	Span 459 516	the gene is hypothesized to be epigenetically inactivated
T1006	Negation 413 416	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 413 453	not been reported in the NKX3.1 sequence
T1008	Negation 1157 1161	lack
E1004	Negation:T1008 Scope:T1009
T1009	Span 1157 1241	lack of NKX3.1 expression, which is seen in most TGCTs and prostate cancer specimens
T1010	Negation 956 959	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 880 995	RESULTS AND CONCLUSIONS: Down-regulation of NKX3.1 expression was generally not caused by promoter hypermethylation
T1012	Speculation 1141 1144	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1141 1182	may explain the lack of NKX3.1 expression
T1014	Speculation 1111 1113	or
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1101 1139	structure or modifications of histones
