T1000	Speculation 337 344	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 337 438	whether the topology of ubiquitin linkages influences the dynamics of inclusions is not well explored
T1002	Speculation 313 320	unclear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 263 320	the mechanism underlying their biogenesis remains unclear
T1004	Speculation 1184 1197	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1184 1387	indicate that K63-linked ubiquitin chains may represent a common denominator underlying inclusions biogenesis, as well as a general cellular strategy for defining cargo destined for the autophagic system
T1006	Negation 874 881	absence
E1003	Negation:T1006 Scope:T1007
T1007	Span 874 906	absence of proteasome impairment
T1008	Speculation 1525 1528	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1525 1604	may offer innovative approaches in the treatment of neurodegenerative disorders
T1010	Speculation 1226 1229	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1226 1387	may represent a common denominator underlying inclusions biogenesis, as well as a general cellular strategy for defining cargo destined for the autophagic system
