T1000	Speculation 1599 1602	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1599 1712	may arise as products of separate mRNAs, rather than from proteolytic processing of a large polypeptide precursor
T1002	Speculation 1523 1530	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1523 1712	suggest that in vertebrate corneas, the multiple KSPG core protein isoforms may arise as products of separate mRNAs, rather than from proteolytic processing of a large polypeptide precursor
