T1000	Negation 1261 1264	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1261 1295	not its association with chromatin
T1002	Negation 923 926	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 923 952	not sufficient to recruit HP1
T1004	Speculation 1322 1335	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1322 1542	indicate that H3-K9 methylation alone can suppress transcription but is insufficient for HP1 recruitment in the context of chromatin exemplifying the importance of chromatin-associated factors in reading the histone code
