T1000	Speculation 600 603	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 600 633	may affect cellular SUMO dynamics
T1002	Speculation 581 591	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 581 633	suggesting that it may affect cellular SUMO dynamics
T1004	Speculation 863 870	appears
E1002	Speculation:T1004 Scope:T1005
T1005	Span 858 946	Slx8 appears to bear the core ligase function, with Hex3 strongly enhancing its activity
