T1000	Speculation 1412 1420	indicate
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1412 1498	indicate the renal secretion of differently glycosylated multiple forms of human renin
T1002	Negation 1348 1352	lack
E1001	Negation:T1002 Scope:T1003
T1003	Span 1348 1393	lack of binding of rat renin to these lectins
T1004	Speculation 1542 1549	appears
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1542 1582	appears to differ from that of rat renin
