T1000	Negation 769 773	lack
E1000	Negation:T1000 Scope:T1001
T1001	Span 769 851	lack of simple and sensitive analytical procedures for detecting this modification
T1002	Speculation 242 249	unclear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 242 249	unclear
T1004	Negation 1676 1679	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1676 1770	not essentially change in organs from young (10 days old) or old animals (30 and 450 days old)
