T1000	Negation 860 863	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 860 1093	not demonstrate a corresponding mass shift when cells were cultured with isotope-labeled methionine, a precursor for the synthesis of S-adenosyl-l-methionine (SAM), which is the most commonly used methyl donor for protein methylation
T1002	Speculation 544 551	unknown
E1001	Speculation:T1002 Scope:T1003
T1003	Span 460 551	substrates and functions of protein methylation at other amino acid residues remain unknown
T1004	Speculation 1121 1132	possibility
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1121 1301	possibility of either exogenous protein methylation during sample handling and processing for mass spectrometry or the existence of SAM-independent pathways for protein methylation
T1006	Speculation 1109 1116	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1109 1301	suggest the possibility of either exogenous protein methylation during sample handling and processing for mass spectrometry or the existence of SAM-independent pathways for protein methylation
