T1000	Speculation 1308 1315	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1308 1513	suggest a novel and critically important role for protein acetylation/deacetylation in the assembly of active transcription processes that may be as important as classical phosphorylation/dephosphorylation
T1002	Negation 646 649	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 646 690	not alter the steady state level of p21 mRNA
T1004	Speculation 1447 1450	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1447 1513	may be as important as classical phosphorylation/dephosphorylation
