T1000	Speculation 1016 1019	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1016 1144	may regulate SRbeta function by mediating poly-ubiquitylation of SRbeta without affecting the stability of SRbeta protein per se
T1002	Speculation 997 1004	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 997 1144	suggest that Pirh2 may regulate SRbeta function by mediating poly-ubiquitylation of SRbeta without affecting the stability of SRbeta protein per se
