T1000	Speculation 718 724	appear
E1000	Speculation:T1000 Scope:T1001
T1001	Span 718 829	appear to inhibit viral DNA synthesis by impeding the translocation of reverse transcriptase along template RNA
T1002	Negation 351 358	absence
E1001	Negation:T1002 Scope:T1003
T1003	Span 351 365	absence of Vif
T1004	Speculation 960 963	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 960 1069	may influence the natural history of HIV-1 infection, as well as viral sequence diversification and evolution
T1006	Speculation 909 915	likely
E1003	Speculation:T1006 Scope:T1007
T1007	Span 909 1069	likely that fluctuations in the Vif-APOBEC balance may influence the natural history of HIV-1 infection, as well as viral sequence diversification and evolution
