T1000	Speculation 546 561	indicating that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 546 683	indicating that carbohydrate side chains on E1 are not involved in the constitution of epitopes recognized by these monoclonal antibodies
T1002	Negation 597 600	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 597 683	not involved in the constitution of epitopes recognized by these monoclonal antibodies
T1004	Negation 1297 1300	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1297 1478	not directly involved in the antigenic structures of E1, it is important in maintaining proper protein folding and stable conformation for expression of immunological epitopes on E1
T1006	Negation 987 990	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 987 1042	not the double mutant (G23) or the triple mutant (G123)
T1008	Speculation 1253 1260	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1253 1352	suggest that although carbohydrate on E1 is not directly involved in the antigenic structures of E1
