T1000	Negation 485 489	lack
E1000	Negation:T1000 Scope:T1001
T1001	Span 485 519	lack of an appropriate methodology
T1002	Speculation 234 240	likely
E1001	Speculation:T1002 Scope:T1003
T1003	Span 234 281	likely has important physiological consequences
T1004	Speculation 1406 1412	likely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1406 1590	likely reflecting its involvement in fetal development through the generation of specific forms of IGF-II (e.g. mature IGF-II) that are required for their distinct biological functions
T1006	Negation 552 555	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 552 614	not been demonstrated and characterized in the rat circulation
T1008	Speculation 1657 1660	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1657 1704	may reflect underlying physiological conditions
T1010	Speculation 1622 1629	suggest
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1622 1704	suggest that serum IGF-II profiles may reflect underlying physiological conditions
