T1000	Speculation 512 523	possibility
E1000	Speculation:T1000 Scope:T1001
T1001	Span 512 584	possibility that these enzymes may have other substrates in the proteome
T1002	Speculation 101 110	indicates
E1001	Speculation:T1002 Scope:T1003
T1003	Span 101 192	indicates widespread asparaginyl hydroxylation of ankyrin repeat domain-containing proteins
T1004	Speculation 850 855	imply
E1002	Speculation:T1004 Scope:T1005
T1005	Span 850 875	imply a potentially broad
T1006	Speculation 543 546	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 543 584	may have other substrates in the proteome
T1008	Speculation 1937 1950	indicate that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1937 2076	indicate that asparaginyl hydroxylation is likely to be widespread among the approximately 300 ARD-containing species in the human proteome
T1010	Speculation 858 869	potentially
E1005	Speculation:T1010 Scope:T1011
T1011	Span 858 903	potentially broad range of substrates for FIH
T1012	Speculation 1980 1986	likely
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1980 2076	likely to be widespread among the approximately 300 ARD-containing species in the human proteome
