T1000	Speculation 1470 1477	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1470 1603	suggest the presence of two recognition sequences, one selective for N-acylaminopropyl moieties, the second for the aminobutyl moiety
T1002	Speculation 732 738	appear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 732 1185	appear to present the optimum length since the antibody binds polyamines with repeats of the aminobutyl moiety more actively than their homologues with shorter or longer carbon chains; (3) number of amino groups: the affinity of Spm8-2 for free homologous polyamines varied in the following order: pentamines > tetramines > triamines > diamines, showing the importance of the number of positive charges of the polyamines in the antibody-antigen reaction
