T1000	Speculation 521 529	possible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 521 547	possible disease mechanism
T1002	Speculation 419 426	unknown
E1001	Speculation:T1002 Scope:T1003
T1003	Span 378 426	the pathogenic mechanisms remain largely unknown
T1004	Speculation 1675 1678	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1675 1764	may result from aggregation of MYOC and induction of the UPR in trabecular meshwork cells
T1006	Speculation 1585 1590	infer
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1585 1764	infer from the Drosophila model that MYOC-associated ocular hypertension in the human eye may result from aggregation of MYOC and induction of the UPR in trabecular meshwork cells
T1008	Speculation 1830 1835	might
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1830 1905	might be accelerated by MYOC mutants to account for juvenile onset glaucoma
