T1000	Speculation 471 478	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 471 598	whether lrECM-dependent cell rounding and global histone deacetylation are indeed part of a common physical-biochemical pathway
T1002	Speculation 463 470	unclear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 463 598	unclear whether lrECM-dependent cell rounding and global histone deacetylation are indeed part of a common physical-biochemical pathway
T1004	Negation 1127 1133	lacked
E1002	Negation:T1004 Scope:T1005
T1005	Span 1127 1150	lacked these structures
T1006	Negation 795 802	absence
E1003	Negation:T1006 Scope:T1007
T1007	Span 795 822	absence of biochemical cues
T1008	Speculation 1376 1383	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1376 1447	suggest that this link is mediated by changes in the actin cytoskeleton
