T1000	Negation 1373 1378	could
E1000	Negation:T1000 Scope:T1001
T1001	Span 1373 1400	could not be phosphorylated
T1002	Negation 291 298	absence
E1001	Negation:T1002 Scope:T1003
T1003	Span 291 320	absence of caspase activation
T1004	Speculation 1512 1515	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1512 1678	may thus represent the prototypical member of a new class of compounds that cause paraptotic cell death via mechanisms involving eIF2alpha phosphorylation and the UPR
T1006	Speculation 1373 1382	could not
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1367 1400	which could not be phosphorylated
