T1000	Speculation 824 832	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 824 944	suggests that H3 Lys-4 methylation is a stable histone modification present throughout the cell cycle, including mitosis
T1002	Negation 702 705	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 664 776	Set1-mediated H3 Lys-4 methylation is not required for heterochromatin assembly at the silent mating-type region
T1004	Speculation 1156 1163	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1156 1409	suggest that methylation of H3 Lys-4 primarily acts in the maintenance of transcriptionally poised euchromatic domains, and that this modification is dispensable for heterochromatin formation in fission yeast, which instead utilizes H3 Lys-9 methylation
T1006	Speculation 1062 1072	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1062 1151	suggesting a mechanistic link between H3 Lys-4 methylation and acetylation of the H3 tail
