T1000	Negation 2984 2987	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 2939 3066	The pro alpha 1 (I) chain release process is not connected directly with hydroxylation, glycosylation or triple-helix formation
T1002	Speculation 411 416	might
E1001	Speculation:T1002 Scope:T1003
T1003	Span 411 484	might have a role in the coordination of procollagen I molecular assembly
T1004	Speculation 215 229	indicated that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 215 326	indicated that chain elongation pauses were prominent during the in vivo synthesis of type I procollagen chains
T1006	Negation 1566 1569	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1566 1569	not
T1008	Negation 946 949	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 946 980	not matched by a pro alpha 2 pause
T1010	Negation 2031 2037	failed
E1005	Negation:T1010 Scope:T1011
T1011	Span 2031 2083	failed to change the final pro alpha 1 chain pausing
T1012	Negation 1738 1740	no
E1006	Negation:T1012 Scope:T1013
T1013	Span 1738 1788	no evidence for pro alpha 2 (I) chain accumulation
T1014	Speculation 2198 2207	could not
E1007	Speculation:T1014 Scope:T1015
T1015	Span 2193 2307	that could not be accounted for simply as the result of lack of N-linked glycosylation in the C-propeptide regions
T1016	Negation 2198 2203	could
E1008	Negation:T1016 Scope:T1017
T1017	Span 2193 2307	that could not be accounted for simply as the result of lack of N-linked glycosylation in the C-propeptide regions
T1018	Speculation 2677 2680	may
E1009	Speculation:T1018 Scope:T1019
T1019	Span 2677 2764	may affect the rate of release of the completed pro alpha 1 (I) chain from the polysome
T1020	Negation 2590 2593	not
E1010	Negation:T1020 Scope:T1021
T1021	Span 2590 2605	not coordinated
