T1000	Speculation 934 941	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 934 987	suggest that PACS-1 is involved in the TfR2 recycling
T1002	Speculation 732 747	indicating that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 732 815	indicating that holo-Tf alters the interaction of TfR2 with the endocytic machinery
T1004	Negation 1193 1196	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1173 1314	TfR2 degradation is not mediated through ubiquitination on the single lysine (K31) in the cytoplasmic domain or on the amino terminal residue
T1006	Speculation 1088 1103	indicating that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1088 1171	indicating that TfR2 degradation occurs through a multivesicular body (MVB) pathway
T1008	Negation 1385 1389	lack
E1004	Negation:T1008 Scope:T1009
T1009	Span 1385 1450	lack of direct TfR2 ubiquitination involvement in its degradation
T1010	Negation 1316 1318	No
E1005	Negation:T1010 Scope:T1011
T1011	Span 1316 1370	No ubiquitination of TfR2 by HA-ubiquitin was detected
T1012	Speculation 1372 1382	indicating
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1372 1450	indicating a lack of direct TfR2 ubiquitination involvement in its degradation
