T1000	Negation 693 696	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 635 705	distribution of GLUT1 in antisense GnT-V transfectant was not affected
T1002	Speculation 289 294	could
E1001	Speculation:T1002 Scope:T1003
T1003	Span 289 391	could induce endoplasmic reticulum stress (ER stress) in 7721 cells, a human hepatocarcinoma cell line
T1004	Speculation 907 910	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 907 982	may be one possible mechanism of ER stress induced by down-regulating GnT-V
T1006	Speculation 824 837	indicate that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 824 982	indicate that the glycosylation change and decrease of transport activity of GLUT1 may be one possible mechanism of ER stress induced by down-regulating GnT-V
T1008	Speculation 994 997	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 994 1100	may contribute to the regulation of glucose uptake by modifying glycosylation of GLUT1 in some tumor cells
T1010	Speculation 918 926	possible
E1005	Speculation:T1010 Scope:T1011
T1011	Span 918 982	possible mechanism of ER stress induced by down-regulating GnT-V
