T1000	Negation 1018 1025	without
E1000	Negation:T1000 Scope:T1001
T1001	Span 1018 1030	without IL-2
T1002	Negation 850 853	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 850 893	not effective, even in the presence of IL-2
T1004	Negation 1135 1138	nor
E1002	Negation:T1004 Scope:T1005
T1005	Span 1135 1182	nor potentiated by NaBu in the presence of IL-2
T1006	Negation 1117 1124	neither
E1003	Negation:T1006 Scope:T1007
T1007	Span 1095 1182	the effect of TSA was neither inhibited nor potentiated by NaBu in the presence of IL-2
T1008	Speculation 1356 1363	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1356 1664	suggest that the NaBu-induced enhancement of anti-TNP antibody production in the presence of IL-2 is mediated through a moderate increase in the level of histone acetylation and that NaBu has both stimulating and inhibiting activities for anti-TNP antibody production, the latter of which is overcome by IL-2
T1010	Negation 1260 1267	absence
E1005	Negation:T1010 Scope:T1011
T1011	Span 1260 1275	absence of IL-2
