T1000	Speculation 1344 1352	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1344 1475	suggests that silencing of CREB and SP1 proteins could contribute to downregulation of this repair polymerase in colorectal tumours
T1002	Speculation 160 167	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 160 249	thought to be specialized in DNA damage processing are frequently misregulated in cancers
T1004	Speculation 1393 1398	could
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1393 1475	could contribute to downregulation of this repair polymerase in colorectal tumours
