T1000	Speculation 1658 1665	support
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1658 1811	support that patients with oxaliplatin-refractory ovarian carcinomas may benefit from non-Pt-based regimens which do not contain MRP1 and MRP4 substrates
T1002	Negation 1775 1778	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1775 1811	not contain MRP1 and MRP4 substrates
T1004	Speculation 1727 1730	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1727 1811	may benefit from non-Pt-based regimens which do not contain MRP1 and MRP4 substrates
