T1000	Speculation 677 684	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 677 818	whether Parkin has cross-function to target misfolded proteins in AD for proteasome-dependent clearance in SH-SY5Y and primary neuronal cells
T1002	Negation 480 483	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 392 503	the role of the ubiquitin-proteasome system (UPS) in the disposal of cellular Abeta has not been fully explored
T1004	Negation 1144 1147	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1144 1191	not account for their effects on the proteasome
