T1000	Speculation 1460 1470	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1460 1581	suggesting that CRF07_BC may be superior over B' and other HIV-1 subtypes in initiating infection in high-risk population
T1002	Speculation 1085 1094	potential
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1085 1123	potential N-linked glycosylation sites
T1004	Speculation 1485 1488	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1485 1581	may be superior over B' and other HIV-1 subtypes in initiating infection in high-risk population
