T1000	Speculation 1087 1094	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1087 1229	suggest that nucleotide misincorporation by pol alpha induces exposure of single-stranded DNA, PCNA mono-ubiquitination and activates TLS pols
T1002	Negation 263 266	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 263 360	not only by DNA damage but also by other factors that induce stalling of the DNA replication fork
