T1000	Negation 475 477	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 475 542	no ambiguity concerning the identity of H2B as a methylated protein
T1002	Negation 366 369	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 366 393	not a demethylation process
T1004	Speculation 1486 1489	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1412 1576	These changes in the patterns of core histone methylation and acetylation may be correlated with the reorganization of gene activity brought about by the heat shock
T1006	Negation 869 871	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 869 917	no histone variants in cultured Drosophila cells
