T1000	Speculation 889 896	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 889 986	suggest that Tyr208 is coordinated to the iron site of F208Y throughout the Dopa generation cycle
T1002	Speculation 490 496	likely
E1001	Speculation:T1002 Scope:T1003
T1003	Span 490 523	likely reaction site for dioxygen
T1004	Speculation 1051 1059	possible
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1051 1283	possible reaction geometries for the hydroxylation reaction catalyzed by these modified R2 diiron sites, geometries which might be relevant for the hydroxylation reaction catalyzed by other diiron sites such as methane monooxygenase
T1006	Speculation 1039 1046	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1039 1283	suggest two possible reaction geometries for the hydroxylation reaction catalyzed by these modified R2 diiron sites, geometries which might be relevant for the hydroxylation reaction catalyzed by other diiron sites such as methane monooxygenase
T1008	Speculation 1412 1420	proposed
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1285 1420	A critical role for residue Glu238 in directing the oxidative power of the reactive intermediate toward oxidation of Tyr122 is proposed
T1010	Speculation 1173 1178	might
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1173 1283	might be relevant for the hydroxylation reaction catalyzed by other diiron sites such as methane monooxygenase
