T1000	Speculation 1074 1083	speculate
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1074 1158	speculate that HAMLET and HDIs might be combined to promote tumor cell death in vivo
T1002	Speculation 936 943	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 936 1069	suggest that the synergy of HDIs and HAMLET is based on different but converging death pathways, both involving chromatin alterations
T1004	Speculation 1105 1110	might
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1089 1158	HAMLET and HDIs might be combined to promote tumor cell death in vivo
