T1000	Speculation 1650 1657	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1650 1735	appears that the elevated enzyme activity could be related to ras protein methylation
T1002	Negation 1245 1248	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1245 1278	not of its endogenous substrates)
T1004	Speculation 1775 1780	might
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1775 1825	might inhibit the growth of endometrial carcinomas
