T1000	Negation 536 539	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 536 596	not contain detectable protein disulphide-isomerase activity
T1002	Negation 90 93	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 90 139	not require protein disulphide-isomerase activity
T1004	Speculation 772 780	unlikely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 675 852	the protein disulphide-isomerase activity of the vertebrate prolyl 4-hydroxylase beta subunit is unlikely to be involved in the catalytic mechanism of the hydroxylation reaction
T1006	Speculation 662 669	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 662 852	suggest that the protein disulphide-isomerase activity of the vertebrate prolyl 4-hydroxylase beta subunit is unlikely to be involved in the catalytic mechanism of the hydroxylation reaction
