T1000	Speculation 1201 1209	putative
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1201 1223	putative cleavage site
T1002	Negation 1060 1063	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1060 1119	not on the putative signal peptidase cleavage site sequence
T1004	Negation 1516 1519	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1486 1581	the furin recognition site is not required for secretion or lysophospholipase D activity of ATX
T1006	Negation 1355 1358	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1355 1416	not modified secretion or lysophospholipase D activity of ATX
