T1000	Speculation 978 987	not known
E1000	Speculation:T1000 Scope:T1001
T1001	Span 861 987	the extent of hydroxylation among ARD proteins, and the ability of other members to compete with HIF-CAD for FIH, is not known
T1002	Speculation 616 623	unclear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 569 623	the function(s) of these ARD hydroxylations is unclear
T1004	Speculation 1745 1748	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1745 1810	may be extensive and have important effects on hypoxia signalling
T1006	Speculation 1659 1666	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1659 1810	suggest that cross-competition between ARDs and HIF-CAD, and between ARDs themselves, may be extensive and have important effects on hypoxia signalling
