T1000	Negation 1108 1111	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1108 1136	not at the zinc-finger motif
T1002	Negation 784 787	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 784 816	not by the activator resveratrol
T1004	Speculation 1152 1165	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1152 1208	indicate that Zn(2+) plays a dual role in SIRT1 activity
T1006	Speculation 1053 1062	suggested
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1053 1136	suggested that the exogenous Zn(2+) binds to SIRT1 but not at the zinc-finger motif
T1008	Speculation 1335 1338	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1335 1495	may also bind to another site different from the zinc-finger motif or the binding sites for the substrates or resveratrol and act as a potent inhibitor of SIRT1
