T1000	Speculation 1028 1041	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1028 1123	indicate that HBx-induced deacetylation is important for proteasomal degradation of HIF-1 alpha
T1002	Negation 482 485	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 482 498	not been studied
T1004	Speculation 1514 1517	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1514 1591	may play a critical role in angiogenesis and metastasis of HBV-associated HCC
T1006	Speculation 1411 1419	indicate
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1411 1591	indicate a positive cross talk between HBx and the MTA1/HDAC complex in stabilizing HIF-1 alpha, which may play a critical role in angiogenesis and metastasis of HBV-associated HCC
