T1000	Speculation 607 609	or
E1000	Speculation:T1000 Scope:T1001
T1001	Span 514 609	Whether H3K9 methylation is causative in the initiation and establishment of gene repression or
T1002	Speculation 358 367	Discovery
E1001	Speculation:T1002 Scope:T1003
T1003	Span 358 413	Discovery of the enzymes that catalyze H3K9 methylation
T1004	Speculation 679 686	unknown
E1002	Speculation:T1004 Scope:T1005
T1005	Span 679 686	unknown
