T1000	Speculation 1185 1190	might
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1185 1243	might play a role in the promotion stage of carcinogenesis
T1002	Speculation 677 689	hypothesized
E1001	Speculation:T1002 Scope:T1003
T1003	Span 677 789	hypothesized that transcriptional control of Ha-ras, Ki-ras, and myc is compromised in B6C3F1 mouse liver tumors
T1004	Speculation 1358 1365	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1358 1594	suggest that a component of the mechanism by which these oncogenes are activated in B6C3F1 mouse liver tumors involves loss of stringent control of expression, via hypomethylation of the ras oncogenes and, possibly, amplification of myc
T1006	Speculation 1308 1316	appeared
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1298 1342	this gene appeared to be amplified in tumors
T1008	Speculation 1564 1572	possibly
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1564 1594	possibly, amplification of myc
