T1000	Speculation 415 420	could
E1000	Speculation:T1000 Scope:T1001
T1001	Span 415 508	could be due to differential post-translational modifications of the protein was investigated
T1002	Speculation 282 293	Bacterially
E1001	Speculation:T1002 Scope:T1003
T1003	Span 282 303	Bacterially expressed
T1004	Negation 590 593	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 590 623	not necessary for enzyme activity
