T1000	Speculation 598 606	putative
E1000	Speculation:T1000 Scope:T1001
T1001	Span 598 657	putative p300 acetylation sites within FoxA1, five of which
T1002	Speculation 459 468	potential
E1001	Speculation:T1002 Scope:T1003
T1003	Span 459 548	potential role for acetylation in the regulation of FoxA chromatin binding and remodeling
T1004	Speculation 979 986	propose
E1002	Speculation:T1004 Scope:T1005
T1005	Span 979 1179	propose a model whereby stable chromatin binding protects the FoxA DNA-binding domain from acetylation to preserve chromatin binding and remodeling by FoxA factors in the absence of extracellular cues
T1006	Negation 1150 1157	absence
E1003	Negation:T1006 Scope:T1007
T1007	Span 1150 1179	absence of extracellular cues
