T1000	Negation 1202 1209	without
E1000	Negation:T1000 Scope:T1001
T1001	Span 1202 1244	without compromising substrate degradation
T1002	Negation 1061 1064	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1061 1118	not for degradation of either ERAD-L or ERAD-M substrates
T1004	Speculation 1246 1256	indicating
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1246 1340	indicating a separate role in ligase regulation that operates in parallel to stability control
