T1000	Speculation 573 576	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 573 625	may be regulated by the ubiquitin-proteasome pathway
T1002	Speculation 526 536	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 526 625	suggesting that UT-A1 urea transporter protein may be regulated by the ubiquitin-proteasome pathway
T1004	Speculation 1112 1118	likely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1095 1222	The mechanism is likely to be physiologically important as UT-A1 ubiquitination was identified in kidney inner medullary tissue
T1006	Negation 706 709	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 706 742	not the lysosome proteolytic pathway
