T1000	Speculation 2042 2050	possible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 2042 2159	possible roles that peptide epitope secondary structure and glycosylation state may play in MUC1 tumor immunogenicity
T1002	Speculation 1533 1538	might
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1533 1735	might explain the immunodominance of this region in vivo, as the presence of defined secondary structure within peptide epitope regions has been correlated with increased immunogenicity in other systems
T1004	Speculation 2122 2125	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2122 2159	may play in MUC1 tumor immunogenicity
