T1000	Speculation 1602 1611	suggested
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1602 1670	suggested an increased glycosylation of the 66-kD protein with aging
T1002	Speculation 947 957	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 947 1036	suggesting its anchorage via a phosphatidylinositol glycan linkage in the plasma membrane
T1004	Speculation 1992 1995	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1992 2039	may be a processed product of the 66-kD protein
