T1000	Speculation 931 934	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 931 971	may induce mitotic checkpoint activation
T1002	Speculation 882 892	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 882 971	suggesting that improper chromosome condensation may induce mitotic checkpoint activation
T1004	Speculation 1585 1588	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1585 1666	may promote the attachment of kinetochores to microtubules coming from both poles
T1006	Speculation 1471 1486	indicating that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1471 1666	indicating that the less constrained centromeric organization associated with heterochromatin protein 1 depletion may promote the attachment of kinetochores to microtubules coming from both poles
