T1000	Speculation 761 774	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 761 855	indicate that although the usual incorporation of radiomethyl into histone H-3 is not affected
T1002	Negation 843 846	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 784 920	the usual incorporation of radiomethyl into histone H-3 is not affected, active methylation of H-1 occurs in the presence of polycations
T1004	Speculation 1218 1221	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1218 1385	may be explained by assuming that, within the chromatin, polycations displace the lysine-rich histone towards the nucleosome, which results in its abberant methylation
T1006	Negation 1089 1094	never
E1003	Negation:T1006 Scope:T1007
T1007	Span 1089 1141	never methylated in vivo or in incubated cell nuclei
