T1000	Speculation 977 982	seems
E1000	Speculation:T1000 Scope:T1001
T1001	Span 871 1210	The difference found in the apparent molecular masses of their monomers (81.5 and 78.3 kDa, respectively) seems to be due to the size of their N-linked oligosaccharide chains (on average 2.4 and 1.9 kDa, respectively), since the number of sugar chains (9) and the molecular mass of the protein moiety (60.5 kDa) are identical in both forms
T1002	Speculation 723 728	could
E1001	Speculation:T1002 Scope:T1003
T1003	Span 723 761	could only be detected inside the cell
