T1000	Speculation 1215 1221	appear
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1215 1281	appear to be important in the downregulation of membrane receptors
T1002	Speculation 274 277	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 256 353	membrane proteins may be internalised, recycled or degraded via lysosomal or proteasomal pathways
T1004	Speculation 1563 1566	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1563 1613	may provide insights into their cellular functions
