T1000	Speculation 1322 1332	indicating
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1322 1360	indicating decreased thermal stability
T1002	Speculation 829 843	indicated that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 829 935	indicated that lysine residues in collagen I from bone and in collagen II from cartilage were overmodified
T1004	Speculation 1464 1474	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1464 1602	suggesting that the overmodified and thermally less stable collagen molecules are causally related to a lower mechanical strength of bones
