T1000	Speculation 1746 1753	advance
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1746 1894	advance, and the medical staff could pay scrupulous attention, resulting in no serious subjective symptoms such as abdominal pain, anorexia or fever
T1002	Negation 1822 1824	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 1822 1894	no serious subjective symptoms such as abdominal pain, anorexia or fever
T1004	Speculation 2018 2026	appeared
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2007 2088	genotyping appeared to be a promising method to avoid such serious adverse events
