T1000	Negation 1316 1319	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1301 1368	PRC1 foci were not fully transmitted to post-mitotic daughter cells
T1002	Speculation 421 428	unknown
E1001	Speculation:T1002 Scope:T1003
T1003	Span 421 504	unknown how PcG proteins maintain stable and plastic chromatin during cell division
T1004	Speculation 1540 1551	possibility
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1540 1656	possibility that PcG proteins enable their target chromatin to be remodeled in response to stimuli in the G(1) phase
T1006	Speculation 1527 1535	suggests
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1527 1656	suggests the possibility that PcG proteins enable their target chromatin to be remodeled in response to stimuli in the G(1) phase
