T1000	Speculation 306 311	could
E1000	Speculation:T1000 Scope:T1001
T1001	Span 306 440	could affect the post-translational modifications of STAT1 protein and whether these modifications regulate osteoblast differentiation
T1002	Speculation 294 301	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 294 372	whether PKR could affect the post-translational modifications of STAT1 protein
T1004	Speculation 1270 1277	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1270 1444	suggest that the aberrant accumulation of STAT1 protein induced by loss of PKR regulate osteoblast differentiation through both SLIM/STAT1-dependent and -independent pathways
T1006	Speculation 377 384	whether
E1003	Speculation:T1006 Scope:T1007
T1007	Span 377 440	whether these modifications regulate osteoblast differentiation
