T1000	Negation 929 931	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 929 1006	no toxic effect up to a dose of 600 mg/kg body weight, on oral administration
T1002	Negation 588 590	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 588 644	no change on the rate of aerial oxidation of GSH content
T1004	Negation 1018 1020	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1018 1067	no change in the level of TBA-reactive substances
