T1000	Speculation 784 790	should
E1000	Speculation:T1000 Scope:T1001
T1001	Span 784 868	should be inhibited, a reaction predominantly catalysed by lysyl hydroxylase (LH) 2b
T1002	Speculation 382 390	suggests
E1001	Speculation:T1002 Scope:T1003
T1003	Span 382 465	suggests that these cross-links contribute to the aberrant accumulation of collagen
T1004	Speculation 1745 1753	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1745 1849	suggests that LH1 preferentially hydroxylates triple helical lysine residues at the cross-link positions
T1006	Negation 1030 1032	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1030 1110	no effect on the total number of pyridinoline cross-links in the collagen matrix
T1008	Speculation 1881 1889	unlikely
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1868 2026	minoxidil is unlikely to serve as an anti-fibroticum, but confers features to the collagen matrix, which provide insight into the substrate specificity of LH1
