T1000	Speculation 199 206	unclear
E1000	Speculation:T1000 Scope:T1001
T1001	Span 178 206	its function remains unclear
T1002	Negation 63 70	lacking
E1001	Negation:T1002 Scope:T1003
T1003	Span 63 116	lacking a single methyl group in ribosomal protein L3
T1004	Speculation 1246 1253	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1246 1372	suggest that the L3-specific methyltransferase may qualify as one of the postulated 'assembly factors' of the E. coli ribosome
T1006	Negation 289 294	fails
E1003	Negation:T1006 Scope:T1007
T1007	Span 289 360	fails to methylate glutamine residue number 150 of ribosomal protein L3
T1008	Speculation 1293 1296	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1293 1372	may qualify as one of the postulated 'assembly factors' of the E. coli ribosome
