T1000	Speculation 1402 1409	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1402 1676	suggest that a reduction in heterochromatin integrity might interfere both with microtubule attachment to chromosomes and with the proper sensing of tension from correct microtubule-kinetochore connections, either of which will result in activation of the mitotic checkpoint
T1002	Speculation 1149 1154	might
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1149 1287	might be responsible for a noted loss of tension at the centromere in AdOx-treated cells and activation of the spindle assembly checkpoint
T1004	Speculation 1456 1461	might
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1456 1676	might interfere both with microtubule attachment to chromosomes and with the proper sensing of tension from correct microtubule-kinetochore connections, either of which will result in activation of the mitotic checkpoint
