T1000	Negation 1112 1115	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1078 1196	the increase of NIS expression is not mediated by modification of expression of thyroid-specific transcription factors
T1002	Negation 999 1001	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 999 1039	no significant effects on HEX expression
T1004	Negation 1283 1286	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1283 1333	not express thyroid-specific transcription factors
T1006	Speculation 1064 1077	indicate that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1064 1196	indicate that the increase of NIS expression is not mediated by modification of expression of thyroid-specific transcription factors
T1008	Speculation 1921 1931	suggesting
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1921 2018	suggesting it as a potential strategy to induce radioiodine sensitivity in different human tumors
T1010	Negation 1873 1876	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1873 1919	not to be mediated by cell-specific mechanisms
