T1000	Speculation 875 884	indicated
E1000	Speculation:T1000 Scope:T1001
T1001	Span 875 973	indicated increased CaMK II phosphorylation in nuclear and perinuclear regions of the muscle fiber
T1002	Negation 371 374	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 371 390	not inhibit CaMK II
T1004	Speculation 1525 1532	support
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1525 1678	support the hypothesis that CaMK II activation by exercise increases GLUT4 expression via increased accessibility of MEF2A to its cis-element on the gene
T1006	Negation 1466 1469	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1466 1512	not affect the increases in pCaMK II and GLUT4
T1008	Speculation 1537 1547	hypothesis
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1537 1678	hypothesis that CaMK II activation by exercise increases GLUT4 expression via increased accessibility of MEF2A to its cis-element on the gene
