T1000	Negation 986 989	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 986 1027	not express the long transcript of CIDE-B
T1002	Speculation 335 343	suggests
E1001	Speculation:T1002 Scope:T1003
T1003	Span 335 442	suggests that a mechanism exists for the tissue- and cell-specific regulation of transcription of this gene
T1004	Negation 1541 1544	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1541 1618	not normally express this transcript upon introduction of exogenous HNF4alpha
T1006	Speculation 1270 1278	appeared
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1270 1345	appeared to be important for cell-specific synthesis of the long transcript
