T1000	Negation 908 911	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 894 994	DAPK mRNA was not expressed in tumor and adjacent tissues with hypermethylation of the DAPK promoter
T1002	Speculation 279 282	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 279 335	may be one of the important mechanisms of carcinogenesis
T1004	Speculation 1260 1263	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1260 1338	may offer an effective means for earlier auxiliary diagnosis of the malignancy
T1006	Negation 1007 1009	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1007 1169	no statistical differences in the extent of differentiation and invasion, lymph node metastasis or pathologic type between the methylated and unmethylated tissues
T1008	Speculation 1521 1524	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1468 1584	The DAPK gene epigenetically affected by methylation may be associated with the carcinogenesis of cholangiocarcinoma
T1010	Speculation 1357 1365	probably
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1357 1466	probably suppressed by methylation, and it could become resistant to apoptosis and immunological surveillance
