T1000	Speculation 562 569	thought
E1000	Speculation:T1000 Scope:T1001
T1001	Span 554 968	This is thought to be a result of a combination of immunodominance of hypervariable regions of the Env protein that can easily escape neutralization, antibody reactivity to gp160 "decoy" protein in cell surface debris or monomeric gp120, conformational constraints within the Env trimer that create unfavorable antibody binding conditions and extensive glycosylation of the exposed regions of Env within the trimer
T1002	Speculation 302 308	should
E1001	Speculation:T1002 Scope:T1003
T1003	Span 302 360	should be the viral Env spike on the surface of the virion
T1004	Speculation 1235 1241	likely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1235 1283	likely require modification of Env glycosylation
