T1000	Speculation 397 400	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 397 516	may impair their efficient entry into the interior of the cylinder-shaped 20S proteasome, where its active site resides
T1002	Speculation 272 280	believed
E1001	Speculation:T1002 Scope:T1003
T1003	Span 256 396	The reaction is believed to be important for subsequent proteolysis by the proteasome since bulky N-glycan chains on misfolded glycoproteins
