T1000	Speculation 1181 1188	propose
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1181 1319	propose that PRC2 is able to copy the mark from an old parental H3 molecule to a newly synthesized H3 molecule as DNA replication proceeds
T1002	Speculation 1019 1028	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1019 1140	suggested that maintenance of transcriptional repression by PRC2 requires the binding of the PRC2 complex to H3K27me3/me2
