T1000	Speculation 1584 1588	seem
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1496 1660	important pathogens such as Brucella melitensis, P. aeruginosa and Borrelia burgdorferi seem to be exceptional as they possess only the PCS pathway for PC formation
T1002	Speculation 1358 1363	might
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1358 1419	might predict that if bacteria contain PC as a membrane lipid
