T1000	Negation 1225 1228	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1225 1279	not alter the binding of IL-1 to D10S or EL4-6.1 cells
T1002	Negation 848 851	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 848 882	not themselves affect IL-1 binding
T1004	Speculation 1511 1518	appears
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1483 1598	this N-linked glycosylation appears to be essential for optimal binding and activity of IL-1 to its type I receptor
