T1000	Speculation 848 854	should
E1000	Speculation:T1000 Scope:T1001
T1001	Span 848 963	should allow comparison of the independent contributions of these sites to substrate binding and transglycosylation
T1002	Speculation 439 444	would
E1001	Speculation:T1002 Scope:T1003
T1003	Span 439 502	would contribute to the acceptor binding for transglycosylation
T1004	Speculation 1274 1283	suggested
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1274 1381	suggested that the substituted amino acids changed the local conformation of this lysozyme at the E-F sites
