T1000	Speculation 1386 1401	indicating that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1386 1613	indicating that virolysis is mediated by anti-alpha-galactosyl natural Ab. These results demonstrate that, like other retroviruses bearing the alpha-galactosyl epitope, HIV modified to express this epitope is inactivated in NHS
T1002	Negation 522 530	with the
E1001	Negation:T1002 Scope:T1003
T1003	Span 522 579	with the exception of humans and other Old World primates
T1004	Speculation 1721 1724	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1721 1801	may have implications in the interspecies transmission of such viruses to humans
T1006	Speculation 1639 1646	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1639 1801	suggest that expression of the alpha-galactosyl epitope on the surface of viruses may have implications in the interspecies transmission of such viruses to humans
