T1000	Speculation 1234 1236	if
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1234 1299	if the interaction of Nedd4-2 and SP-C resulted in ubiquitination
T1002	Speculation 95 103	proposed
E1001	Speculation:T1002 Scope:T1003
T1003	Span 95 333	proposed a model of surfactant protein (SP)-C biosynthesis in which internalization of the proprotein from the limiting membrane of the multivesicular body to internal vesicles represents a key step in the processing and secretion of SP-C
T1004	Negation 1571 1574	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1571 1578	not K34
