T1000	Speculation 811 818	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 774 922	The 5' region of the calcitonin gene appears to be methylated to a significantly higher degree in T lineage ALL compared to B lineage ALL (P < 0.01)
T1002	Speculation 203 206	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 203 240	may lead to the development of cancer
T1004	Speculation 1675 1685	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1675 1752	suggesting that aberrant DNA methylation may play a role in tumor progression
T1006	Speculation 1300 1307	appears
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1269 1396	The DNA sequencing method thus appears to be better suited to assess alterations of DNA methylation than Southern blot analysis
T1008	Speculation 1716 1719	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1716 1752	may play a role in tumor progression
