T1000	Negation 906 909	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 906 925	not bind to the gel
T1002	Speculation 260 267	appears
E1001	Speculation:T1002 Scope:T1003
T1003	Span 229 398	A large proportion of this IFN appears to be glycosilated, as treatment with neuraminidase causes a shift of the isoelectric point (IP) from pH = 5.2-5.4 to pH = 5.8-6.2
T1004	Speculation 1282 1289	whether
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1282 1452	whether some glycosilated molecule present in the IFN preparation, or glycosilation of the IFN molecule per se, is responsible for acid-lability of the antiviral activity
T1006	Speculation 1090 1097	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1090 1257	suggest that acid-labile IFN alpha is largely glycosilated, and that the presence of glycosilated molecules contribute to render the IFN molecule unstable at acidic pH
