T1000	Negation 1028 1031	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1028 1099	not proceed at pH 7.4 or in the presence of p-chloromercuribenzoic acid
T1002	Speculation 334 343	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 334 397	suggested that NAAA is glycosylated and proteolytically cleaved
T1004	Speculation 1387 1396	potential
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1387 1418	potential N-glycosylation sites
T1006	Speculation 1185 1194	suggested
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1185 1261	suggested that this specific proteolysis is a self-catalyzed activation step
T1008	Speculation 1537 1545	appeared
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1519 1605	The glycosylation appeared to play an important role in stabilizing the enzyme protein
