T1000	Speculation 1478 1481	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1478 1509	may cause human pathophysiology
T1002	Speculation 1318 1331	indicate that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1318 1509	indicate that post-translational modification of NEMO through K63-linked polyubiquitination is a key event in IKK activation and that perturbation of this step may cause human pathophysiology
