T1000	Speculation 1290 1297	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1290 1406	suggest that the HGF/c-Met system might regulate extrinsic factor signaling that maintains the homeostasis of organs
T1002	Speculation 700 707	unclear
E1001	Speculation:T1002 Scope:T1003
T1003	Span 646 707	the precise mechanism how HGF reduces inflammation is unclear
T1004	Speculation 1324 1329	might
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1324 1406	might regulate extrinsic factor signaling that maintains the homeostasis of organs
