T1000	Negation 871 877	failed
E1000	Negation:T1000 Scope:T1001
T1001	Span 871 992	failed to induce cell cycle arrest in G1 phase and to suppress cell proliferation in comparison with wild-type E-cadherin
T1002	Speculation 593 602	potential
E1001	Speculation:T1002 Scope:T1003
T1003	Span 593 638	potential N-glycosylation sites of E-cadherin
T1004	Speculation 1055 1061	seemed
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1055 1143	seemed to be indispensable for E-cadherin-mediated suppression of cell cycle progression
T1006	Negation 1040 1043	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1040 1053	not at Asn618
T1008	Speculation 1640 1645	might
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1640 1718	might be crucial for E-cadherin-mediated suppression of cell cycle progression
T1010	Speculation 1611 1618	implied
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1611 1718	implied that N-glycosylation might be crucial for E-cadherin-mediated suppression of cell cycle progression
