T1000	Speculation 916 924	possible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 916 981	possible consequences for ProTalpha of its interaction with Keap1
T1002	Negation 47 50	n't
E1001	Negation:T1002 Scope:T1003
T1003	Span 47 105	n't lead to prothymosin alpha ubiquination and degradation
T1004	Speculation 1310 1317	appears
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1310 1486	appears that ProTalpha contribution to Nrf2-dependent transcription is accomplished via the increase of free Nrf2 rather then the increase of total intracellular amount of Nrf2
T1006	Negation 1110 1113	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1091 1197	Nrf2 ProTalpha was not subjected to Keap-dependent ubiquitination, degradation and export from the nucleus
