T1000	Speculation 1085 1099	indicated that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1085 1285	indicated that, although the reduced INSIG1 expression in cancers was associated with the methylation at the edge of the CGI in the promoter region, the methylation was likely to be a secondary change
T1002	Negation 784 787	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 769 812	the center was not methylated in any cancer
T1004	Negation 1385 1388	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1385 1418	not correlate with its expression
T1006	Speculation 1254 1260	likely
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1254 1285	likely to be a secondary change
T1008	Speculation 1714 1719	might
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1688 1776	their reduced expressions might be involved in gastric cancer development or progression
T1010	Speculation 1673 1682	suggested
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1673 1776	suggested that their reduced expressions might be involved in gastric cancer development or progression
