T1000	Speculation 1403 1413	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1403 1515	suggesting that glycerol could intercept the active oxidant from the FIH-1 active site and prevent hydroxylation
T1002	Negation 645 652	absence
E1001	Negation:T1002 Scope:T1003
T1003	Span 645 664	absence of HIFalpha
T1004	Speculation 1629 1638	indicated
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1629 1754	indicated distorted octahedral Fe(III) geometries, with subtle differences in inner-shell ligands for yellow and purple FIH-1
T1006	Speculation 1428 1433	could
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1428 1515	could intercept the active oxidant from the FIH-1 active site and prevent hydroxylation
T1008	Speculation 1876 1886	suggesting
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1876 1996	suggesting that resting FIH-1 can readily undergo uncoupled O2-activation by loss of an H2O ligand from the metal center
T1010	Speculation 1809 1818	indicated
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1809 1996	indicated a mixture of 5-coordinate and 6-coordinate enzyme forms, suggesting that resting FIH-1 can readily undergo uncoupled O2-activation by loss of an H2O ligand from the metal center
