T1000	Speculation 713 721	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 713 797	suggests a potential role of HAUSP as a downstream target of stress signals in cells
T1002	Negation 419 422	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 419 437	not understood yet
T1004	Speculation 724 733	potential
E1002	Speculation:T1004 Scope:T1005
T1005	Span 724 797	potential role of HAUSP as a downstream target of stress signals in cells
