T1000	Negation 1465 1467	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 1465 1508	no observable levels of H3K36 were detected
T1002	Speculation 311 326	indicating that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 311 362	indicating that SMYD2 methylates p53 and histone H3
T1004	Speculation 2023 2031	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2023 2128	suggests that some of the genes regulated by SMYD2 are closely associated with SMYD2-interacting proteins
