T1000	Speculation 940 948	estimate
E1000	Speculation:T1000 Scope:T1001
T1001	Span 940 1055	estimate that after 1 hr of G-protein activation at least 6% of the total pool of G gamma 2 was carboxyl-methylated
T1002	Negation 475 478	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 475 583	not G gamma 3 or G gamma 7 and that carboxyl methylation of G gamma 2 is associated with signal transduction
T1004	Speculation 1549 1552	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1549 1587	may play a role in signal transduction
T1006	Speculation 1504 1511	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1504 1587	suggest that carboxyl methylation of G gamma may play a role in signal transduction
