T1000	Negation 1000 1003	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1000 1035	not vary between B10.A and C3H mice
T1002	Speculation 617 625	probably
E1001	Speculation:T1002 Scope:T1003
T1003	Span 617 630	probably high
T1004	Speculation 1545 1558	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1545 1699	indicate that glycosylation differences may be found between highly homologous (91%) alleles of an H-2 gene, even when co-dominantly expressed by F1 cells
T1006	Negation 1188 1190	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 1188 1212	no effect on sialylation
T1008	Speculation 1585 1588	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1585 1699	may be found between highly homologous (91%) alleles of an H-2 gene, even when co-dominantly expressed by F1 cells
