T1000	Speculation 1483 1490	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1483 1727	suggest that E6-AP functions as a cellular quality control ubiquitin ligase and, therefore, can be implicated not only in the pathogenesis of Angelman syndrome but also in the biology of neurodegenerative disorders involving protein aggregation
T1002	Speculation 107 110	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 107 178	may be involved in the ubiquitination of Hsp70-bound misfolded proteins
