T1000	Negation 1612 1615	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1612 1643	not from false-positive testing
T1002	Speculation 393 400	unknown
E1001	Speculation:T1002 Scope:T1003
T1003	Span 393 409	unknown activity
T1004	Speculation 1570 1573	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1570 1643	may only result from false-negatives, but not from false-positive testing
T1006	Speculation 1340 1343	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1340 1467	may corroborate the potential misuse of rEPO or NESP based on the particular enzymatic activity of an arylsulfatase preparation
