T1000	Speculation 799 806	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 799 850	suggest that HHV-8 gB is not processed in the Golgi
T1002	Negation 824 827	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 812 913	HHV-8 gB is not processed in the Golgi and localizes to the endoplasmic reticulum or nuclear membrane
T1004	Negation 1185 1191	failed
E1002	Negation:T1004 Scope:T1005
T1005	Span 1185 1248	failed to restore the infectivity of gp110-negative EBV mutants
T1006	Speculation 1109 1119	indicating
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1109 1149	indicating formation of hetero-oligomers
T1008	Speculation 1265 1278	indicate that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1265 1459	indicate that although HHV-8 gB and EBV gp110 have similar patterns of intracellular localization and can interact, there is not sufficient functional homology to allow efficient complementation
T1010	Negation 1390 1393	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1390 1459	not sufficient functional homology to allow efficient complementation
