T1000	Negation 953 955	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 953 1016	no evidence for exceptionally high- or low-labeling chromosomes
T1002	Speculation 390 398	possible
E1001	Speculation:T1002 Scope:T1003
T1003	Span 390 416	possible acetylation sites
T1004	Speculation 1528 1537	indicates
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1528 1622	indicates more frequent use of the acetylation site at lysine 12 in H4Ac1 from metaphase cells
