T1000	Speculation 373 381	possible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 373 426	possible that they might accomplish similar functions
T1002	Speculation 367 372	seems
E1001	Speculation:T1002 Scope:T1003
T1003	Span 367 426	seems possible that they might accomplish similar functions
T1004	Negation 778 781	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 778 804	not ubiquitinated by HERC3
T1006	Speculation 392 397	might
E1003	Speculation:T1006 Scope:T1007
T1007	Span 392 426	might accomplish similar functions
