T1000	Speculation 445 450	might
E1000	Speculation:T1000 Scope:T1001
T1001	Span 442 531	it might be involved in regulating protein translation or other aspects of RNA metabolism
T1002	Speculation 426 436	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 426 531	suggesting that it might be involved in regulating protein translation or other aspects of RNA metabolism
T1004	Speculation 1140 1145	would
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1134 1212	which would be eliminated by apoptosis under normal levels of Pdcd4 expression
T1006	Speculation 1041 1048	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1041 1212	suggest a model in which low Pdcd4 expression after DNA damage favors the survival of cells, which would be eliminated by apoptosis under normal levels of Pdcd4 expression
T1008	Speculation 1313 1320	suggest
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1313 1459	suggest that low levels of Pdcd4 expression observed in certain tumor cells contribute to tumorigenesis by affecting the fate of DNA-damaged cells
