T1000	Negation 1149 1165	Myelosuppression
E1000	Negation:T1000 Scope:T1001
T1001	Span 1149 1201	Myelosuppression was dose limiting in one individual
T1002	Speculation 117 131	indicated that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 117 234	indicated that Romidepsin (Depsipeptide FK228; DP) mediates growth arrest and apoptosis in cultured lung cancer cells
T1004	Negation 1330 1332	No
E1002	Negation:T1004 Scope:T1005
T1005	Span 1330 1366	No objective responses were observed
T1006	Negation 1203 1205	No
E1003	Negation:T1006 Scope:T1007
T1007	Span 1203 1250	No significant cardiac toxicities were observed
T1008	Speculation 1758 1761	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1758 1892	may warrant further evaluation of this histone deacetylase inhibitor in combination with novel-targeted agents in lung cancer patients
T1010	Speculation 1521 1527	seemed
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1521 1635	seemed to shift global gene expression profiles in these cells toward those detected in normal bronchial epithelia
