T1000	Speculation 1253 1266	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1253 1464	indicate that increased DB dynamics characterizes the lethargus phase of molting in parallel to decreased levels of DB components and that temporal expression of RNF-5 contributes to an efficient molting process
T1002	Negation 1125 1132	failure
E1001	Negation:T1002 Scope:T1003
T1003	Span 1125 1143	failure of ecdysis
