T1000	Speculation 832 837	might
E1000	Speculation:T1000 Scope:T1001
T1001	Span 832 874	might stimulate the autologous lymphocytes
T1002	Negation 679 682	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 679 735	not resulted from some idiosyncrasy of the first patient
T1004	Negation 1222 1225	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1222 1281	not by a mock transfectant in cold target inhibition assays
