T1000	Negation 951 954	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 951 990	not related to non-covalent E2-bindings
T1002	Negation 655 658	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 655 692	not present at the E2-binding surface
T1004	Speculation 858 865	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 858 990	suggest the presence of an uncharacterized determinant for the K48 ubiquitin-linkage that is not related to non-covalent E2-bindings
