T1000	Speculation 441 450	potential
E1000	Speculation:T1000 Scope:T1001
T1001	Span 441 493	potential developmental roles of these modifications
T1002	Speculation 353 361	presumed
E1001	Speculation:T1002 Scope:T1003
T1003	Span 336 424	each of which is presumed to represent a distinct functional state at the cellular level
T1004	Speculation 1655 1663	suggests
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1655 1716	suggests a role in gene silencing in postmitotic muscle cells
