T1000	Speculation 1286 1300	indicated that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1286 1548	indicated that the E1 mutant antigens induced antibody directed at two major domains: one, located at amino acids (aa) 313 to 332, which is known to be reactive with sera from HCV patients, and a second one, located in the N-terminal domain of E1 (aa 192 to 226)
T1002	Negation 904 906	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 904 1117	no or only minor effects on the antibody titers induced, mutation of the fourth glycosylation site (N4) significantly enhanced the anti-E1 humoral response in terms of both seroconversion rates and antibody titers
