T1000	Speculation 529 537	presumed
E1000	Speculation:T1000 Scope:T1001
T1001	Span 501 625	the inhibition of fusion is presumed to be the result of the prevention of HN-mediated bridging of potential fusion partners
T1002	Negation 370 377	without
E1001	Negation:T1002 Scope:T1003
T1003	Span 370 383	without (FFWO
T1004	Negation 1130 1133	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1130 1173	not, even when added at high concentrations
T1006	Negation 914 917	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 914 928	not infectious
T1008	Speculation 1217 1220	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1217 1260	may be different in the two modes of fusion
T1010	Speculation 1180 1188	suggests
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1180 1260	suggests that the requirement for HN may be different in the two modes of fusion
T1012	Speculation 1569 1579	presumably
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1546 1622	which are utilized and presumably account for the escape from neutralization
