T1000	Negation 848 851	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 848 865	not express LMP 1
T1002	Speculation 337 345	possible
E1001	Speculation:T1002 Scope:T1003
T1003	Span 337 444	possible initiator sites for transcripts of Epstein-Barr nuclear antigens) in Burkitt's lymphoma (BL) lines
T1004	Speculation 1658 1661	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1658 1702	may contribute to silencing their expression
T1006	Speculation 1539 1545	notion
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1539 1702	notion that methylation at discrete sites within control regions of latent, growth-transformation associated EBV genes may contribute to silencing their expression
