T1000	Negation 752 755	nor
E1000	Negation:T1000 Scope:T1001
T1001	Span 752 870	nor what control mechanisms are responsible for the down-regulation of the synthesis at the end of the first trimester
T1002	Speculation 541 546	seems
E1001	Speculation:T1002 Scope:T1003
T1003	Span 526 649	hCG production seems to mark a certain step in the process of differentiation of cytotrophoblasts and choriocarcinoma cells
T1004	Speculation 1316 1326	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1316 1387	suggesting autoregulation as a regulatory principle of hCG biosynthesis
T1006	Speculation 1051 1055	seem
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1051 1081	seem to play an important role
T1008	Negation 1552 1558	unable
E1004	Negation:T1008 Scope:T1009
T1009	Span 1552 1593	unable to down-regulate its own synthesis
T1010	Speculation 1502 1507	seems
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1457 1516	a truncated form (50 kd) of LH/hCG receptors seems to exist
T1012	Speculation 1922 1935	indicate that
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1922 2138	indicate that cAMP, which increases transcription and mRNA stability, also expands the N-glycosylation capacity and thus may accomplish an over-all coordination of hCG biosynthesis including post-translational events
T1014	Speculation 1760 1763	may
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1760 1788	may prevent subunit assembly
T1016	Speculation 2043 2046	may
E1008	Speculation:T1016 Scope:T1017
T1017	Span 2043 2138	may accomplish an over-all coordination of hCG biosynthesis including post-translational events
