T1000	Negation 493 496	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 493 578	not inhibit lectin binding in a competitive adhesion assay (less than 15% inhibition)
T1002	Speculation 97 105	possible
E1001	Speculation:T1002 Scope:T1003
T1003	Span 97 212	possible interaction of galactose/glucose-specific liver lectins with nonenzymatically glycated human serum albumin
T1004	Speculation 869 872	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 869 905	may interact with endogenous lectins
