T1000	Speculation 1045 1053	possibly
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1045 1085	possibly at the junction of COL1 and NC2
T1002	Speculation 399 412	indicate that
E1001	Speculation:T1002 Scope:T1003
T1003	Span 399 606	indicate that the structures of the collagenous domain closest to the cell membrane, COL1, the adjacent noncollagenous domain, NC2, and the C-terminal domains COL3 and NC4 are subject to alternative splicing
T1004	Speculation 1206 1220	indicated that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1206 1340	indicated that the type XIII collagen alpha chains form homotrimers whose three collagenous domains are in triple helical conformation
T1006	Speculation 1130 1136	likely
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1093 1161	the two cysteine residues in NC4 are likely to form intrachain bonds
T1008	Speculation 1648 1651	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1648 1707	may have an important role in the stability of the molecule
T1010	Speculation 1598 1606	suggests
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1598 1707	suggests that the central portion of the molecule may have an important role in the stability of the molecule
T1012	Speculation 1857 1859	or
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1847 1955	the short or highly interrupted triple helical domains of the other known collagenous transmembrane proteins
T1014	Speculation 1763 1770	appears
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1763 1859	appears to be present in triple helical conformation, which is in clear contrast to the short or
