T1000	Negation 1074 1076	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 1074 1156	no induction in three additional lines derived from normal breast epithelial cells
T1002	Negation 594 597	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 594 634	not in the normal breast epithelial line
T1004	Negation 1452 1455	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1452 1535	not in DNA from normal breast epithelia or matched lymphocytes from cancer patients
