T1000	Speculation 929 938	could not
E1000	Speculation:T1000 Scope:T1001
T1001	Span 929 969	could not exit the endoplasmic reticulum
T1002	Negation 929 934	could
E1001	Negation:T1002 Scope:T1003
T1003	Span 935 969	not exit the endoplasmic reticulum
T1004	Negation 1364 1367	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 1364 1405	not restore the features of wild-type LPH
T1006	Negation 1157 1160	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1157 1405	not correct folding, of LPH-G1363S were partially restored by expression at 20 degrees C. However, a form of LPH that contains the mutations G1363S and N1361A, which eliminates the N-glycosylation site, did not restore the features of wild-type LPH
T1008	Negation 1446 1449	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1413 1485	the additional glycosyl group is not required for the LPH-G1363S defects
