T1000	Speculation 1183 1190	propose
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1183 1310	propose a model whereby binding of the LRR to proteins at the target site releases the ligase domain for site-specific function
T1002	Speculation 924 931	suggest
E1001	Speculation:T1002 Scope:T1003
T1003	Span 924 1063	suggest a mechanism for activation of the ligase requiring a substantial conformational change to release the catalytic domain for function
