T1000	Speculation 1353 1366	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1353 1475	indicate that altered activity of ceruloplasmin may present a vulnerability factor for iron induced oxidative stress in PD
T1002	Speculation 206 211	imply
E1001	Speculation:T1002 Scope:T1003
T1003	Span 206 271	imply impaired iron metabolism in this neurodegenerative disorder
T1004	Speculation 1401 1404	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1401 1475	may present a vulnerability factor for iron induced oxidative stress in PD
