T1000	Negation 422 424	No
E1000	Negation:T1000 Scope:T1001
T1001	Span 422 524	No alterations in the p16(INK4A) or p14(ARF) genes were found in any of the chronic phase (CP) samples
T1002	Negation 147 150	The
E1001	Negation:T1002 Scope:T1003
T1003	Span 147 420	The frequency and mechanism of p16(INK4A) and p14(ARF) gene alterations were studied in cell samples from 30 patients with Philadelphia (Ph) chromosome-positive chronic myeloid leukaemia (CML), both at diagnosis and at the onset of the accelerated phase (AP) of the disease
T1004	Speculation 858 871	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 858 983	indicate that p16(INK4A) and p14(ARF) are primary targets for inactivation by promoter methylation in the acceleration of CML
T1006	Negation 642 649	without
E1003	Negation:T1006 Scope:T1007
T1007	Span 642 674	without loss of the other allele
T1008	Speculation 1048 1051	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1048 1111	may be important in the conversion of CML from the CP to the AP
