T1000	Speculation 1338 1345	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1338 1576	suggest that histone H3 modification at lysine 9 directly regulates chromatin condensation by recruiting MENT to chromatin in a fashion that is spatially constrained from active genes by gene boundary elements and histone hyperacetylation
T1002	Negation 1230 1233	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1230 1333	not acetylated N-terminal domain of histone H3 specifically restored chromatin self-association by MENT
