T1000	Speculation 1225 1238	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1225 1412	indicate that DNMT1 and ICBP90 are involved in VEGF gene expression, possibly via an interaction of the SRA domain of ICBP90 with a novel domain of DNMT1 and an upregulation of p16(INK4A)
T1002	Speculation 671 678	whether
E1001	Speculation:T1002 Scope:T1003
T1003	Span 671 824	whether ICBP90 and DNMT1 are present in the same macro-molecular complexes in Jurkat cells and immortalized human vascular smooth muscle cells (HVTs-SM1)
T1004	Speculation 1427 1434	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1427 1603	suggest a new role of ICBP90 in the relationship between histone ubiquitination and DNA methylation in the context of tumoral angiogenesis and tumour suppressor genes silencing
T1006	Speculation 1294 1302	possibly
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1294 1412	possibly via an interaction of the SRA domain of ICBP90 with a novel domain of DNMT1 and an upregulation of p16(INK4A)
