T1000	Speculation 1250 1257	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1250 1487	suggest that the increased level of lysylhydroxylation in human osteopenia is related to the glycosylation of collagen I, while it seems to have little impact on the formation of the mature, non-reducible collagen crosslinks investigated
T1002	Negation 790 793	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 790 942	not show any relationship between the level of collagen glycosylation and the diameter of in vivo formed fibrils or in vitro formed fibrillar aggregates
T1004	Speculation 1526 1534	unlikely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1526 1695	unlikely that the different diameters of collagen fibrils contribute greatly to the reduced biomechanical stability reported for overhydroxylated, osteopenic bone tissue
T1006	Speculation 1381 1386	seems
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1378 1487	it seems to have little impact on the formation of the mature, non-reducible collagen crosslinks investigated
