T1000	Speculation 3878 3891	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 3878 4014	indicate that streptococci sense and, on a transcriptional level, respond to various signals and cues in the pharyngeal cell environment
T1002	Speculation 3838 3847	not known
E1001	Speculation:T1002 Scope:T1003
T1003	Span 3793 3847	the mechanisms mediating these responses are not known
T1004	Speculation 4588 4597	could not
E1002	Speculation:T1004 Scope:T1005
T1005	Span 4588 4805	could not reconstruct; and (3) providing preliminary insight and clues about the function or regulation of uncharacterized genes by associating their co-expression with physically proximate, functionally defined genes
T1006	Negation 4588 4593	could
E1003	Negation:T1006 Scope:T1007
T1007	Span 4588 4805	could not reconstruct; and (3) providing preliminary insight and clues about the function or regulation of uncharacterized genes by associating their co-expression with physically proximate, functionally defined genes
T1008	Negation 998 1001	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 998 1069	not reveal a considerable amount of information contained in array data
T1010	Negation 317 320	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 317 357	not account for experimental variability
T1012	Speculation 994 997	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 994 1069	may not reveal a considerable amount of information contained in array data
T1014	Speculation 863 873	assumption
E1007	Speculation:T1014 Scope:T1015
T1015	Span 863 938	assumption that co-expressed genes share common function or regulation [3,4
T1016	Negation 1465 1467	no
E1008	Negation:T1016 Scope:T1017
T1017	Span 1465 1514	no tools exist to interpret unknown gene clusters
T1018	Speculation 1316 1319	may
E1009	Speculation:T1018 Scope:T1019
T1019	Span 1316 1454	may lack either common function or regulation, a considerable limitation for genomes containing a large percentage of undefined genes [1,2
T1020	Speculation 1493 1500	unknown
E1010	Speculation:T1020 Scope:T1021
T1021	Span 1493 1674	unknown gene clusters or to assess their significance and completeness, a significant portion of bacterial expression profiles are not interpretable using current clustering methods
T1022	Negation 1624 1627	not
E1011	Negation:T1022 Scope:T1023
T1023	Span 1624 1674	not interpretable using current clustering methods
T1024	Speculation 2872 2878	likely
E1012	Speculation:T1024 Scope:T1025
T1025	Span 2872 2914	likely share common function or regulation
T1026	Speculation 2290 2301	potentially
E1013	Speculation:T1026 Scope:T1027
T1027	Span 2290 2309	potentially related
