T1000	Speculation 278 283	would
E1000	Speculation:T1000 Scope:T1001
T1001	Span 278 348	would illuminate the molecular events that result in host colonization
T1002	Speculation 194 196	or
E1001	Speculation:T1002 Scope:T1003
T1003	Span 194 207	or indirectly
T1004	Negation 1367 1374	without
E1002	Negation:T1004 Scope:T1005
T1005	Span 1367 1390	without its application
T1006	Speculation 951 962	potentially
E1003	Speculation:T1006 Scope:T1007
T1007	Span 951 1097	potentially share common function or regulation by coupling statistically analyzed gene expression profiles with the chromosomal position of genes
T1008	Speculation 1358 1366	possible
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1358 1390	possible without its application
T1010	Speculation 1342 1347	would
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1342 1390	would have been possible without its application
