T1000	Speculation 3852 3859	appears
E1000	Speculation:T1000 Scope:T1001
T1001	Span 3812 3916	A cascade regulation starting with FimR appears to act on the upstream promoter (Nishikawa et al., 2004)
T1002	Speculation 4125 4130	imply
E1001	Speculation:T1002 Scope:T1003
T1003	Span 4125 4178	imply the complexity of regulation of mfa1 expression
T1004	Speculation 4186 4194	possible
E1002	Speculation:T1004 Scope:T1005
T1005	Span 4186 4282	possible that two promoters of mfa1 are regulated in response to different environmental signals
T1006	Speculation 4560 4563	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 4516 4610	other surface proteins, such as gingipains, may also be involved in the bacterial colonization
T1008	Speculation 3198 3208	suggesting
E1004	Speculation:T1008 Scope:T1009
T1009	Span 3198 3314	suggesting that this promoter may make significant contributions toward mfa1 expression through the FimS/FimR system
T1010	Speculation 3228 3231	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 3228 3314	may make significant contributions toward mfa1 expression through the FimS/FimR system
T1012	Speculation 3617 3626	suggested
E1006	Speculation:T1012 Scope:T1013
T1013	Span 3617 3693	suggested that each promoter may interact with different regulatory elements
T1014	Speculation 3646 3649	may
E1007	Speculation:T1014 Scope:T1015
T1015	Span 3646 3693	may interact with different regulatory elements
T1016	Speculation 4889 4895	appear
E1008	Speculation:T1016 Scope:T1017
T1017	Span 4815 4985	Major fimbriae are required for initial attachment and the minor fimbriae appear to play an important role in microcolony formation by facilitating cell-cell interactions
T1018	Speculation 5294 5302	proposed
E1009	Speculation:T1018 Scope:T1019
T1019	Span 5294 5385	proposed that FimR can be an attractive target for inhibition of P. gingivalis colonization
T1020	Speculation 389 396	unknown
E1010	Speculation:T1020 Scope:T1021
T1021	Span 363 396	two-component systems are unknown
T1022	Speculation 127 135	putative
E1011	Speculation:T1022 Scope:T1023
T1023	Span 127 160	putative two-component regulatory
T1024	Speculation 812 824	hypothesized
E1012	Speculation:T1024 Scope:T1025
T1025	Span 812 920	hypothesized that the FimS/FimR system regulates expression of each fimbrial gene through a unique mechanism
T1026	Speculation 658 672	indicates that
E1013	Speculation:T1026 Scope:T1027
T1027	Span 658 735	indicates that the FimS/FimR system is a positive regulator for the mfa1 gene
T1028	Speculation 1234 1244	suggesting
E1014	Speculation:T1028 Scope:T1029
T1029	Span 1234 1299	suggesting a direct role of FimR in activation of mfa1 expression
T1030	Speculation 941 950	suggested
E1015	Speculation:T1030 Scope:T1031
T1031	Span 941 1142	suggested that regulation of fimA expression by FimR is through a regulation cascade involving interaction of FimR and the promoter region of the first gene in the fimA cluster (Nishikawa et al., 2004)
T1032	Speculation 1512 1515	may
E1016	Speculation:T1032 Scope:T1033
T1033	Span 1512 1575	may explain the much tighter control of fimA expression by FimR
T1034	Speculation 1412 1422	indicating
E1017	Speculation:T1034 Scope:T1035
T1035	Span 1412 1485	indicating multiple levels of control of fimA expression in P. gingivalis
T1036	Negation 2028 2030	no
E1018	Negation:T1036 Scope:T1037
T1037	Span 2028 2050	no apparent difference
T1038	Speculation 1590 1601	possibility
E1019	Speculation:T1038 Scope:T1039
T1039	Span 1590 1700	possibility cannot be excluded that other regulatory elements are also involved in expression of the mfa1 gene
T1040	Speculation 2156 2164	suggests
E1020	Speculation:T1040 Scope:T1041
T1041	Span 2156 2239	suggests that different mechanisms may be involved in P. gingivalis FimR activation
T1042	Negation 2108 2115	without
E1021	Negation:T1042 Scope:T1043
T1043	Span 2108 2142	without acetyl phosphate treatment
T1044	Negation 2438 2440	no
E1022	Negation:T1044 Scope:T1045
T1045	Span 2438 2475	no effect on its DNA-binding affinity
T1046	Speculation 2191 2194	may
E1023	Speculation:T1046 Scope:T1047
T1047	Span 2191 2239	may be involved in P. gingivalis FimR activation
T1048	Speculation 2533 2536	may
E1024	Speculation:T1048 Scope:T1049
T1049	Span 2533 2662	may also be due to the short lifetime of the phosphorylated state, which has been observed in other bacteria (Stock et al., 2000)
T1050	Negation 2500 2503	not
E1025	Negation:T1050 Scope:T1051
T1051	Span 2491 2532	FimR was not activated by phosphorylation
T1052	Speculation 2955 2962	suggest
E1026	Speculation:T1052 Scope:T1053
T1053	Span 2955 3126	suggest that transcription of the mfa1 gene originated at a distal upstream transcriptional start site and read through the promoter region suggested by Park et al. (2006)
T1054	Speculation 2746 2754	putative
E1027	Speculation:T1054 Scope:T1055
T1055	Span 2746 2766	putative start codon
T1056	Speculation 3143 3150	appears
E1028	Speculation:T1056 Scope:T1057
T1057	Span 3138 3196	FimR appears to act on the promoter region identified here
T1058	Speculation 3095 3104	suggested
E1029	Speculation:T1058 Scope:T1059
T1059	Span 3095 3126	suggested by Park et al. (2006)
