T1000	Speculation 181 184	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 181 304	may be involved in coronary heart disease and preterm births (Boggess et al., 2005; Brodala et al., 2005; Chou et al., 2005
T1002	Speculation 78 88	considered
E1001	Speculation:T1002 Scope:T1003
T1003	Span 69 151	which is considered to be a major periodontal pathogen (Socransky & Haffajee, 2005
T1004	Speculation 1221 1231	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1221 1351	suggesting the involvement of FimA in the bacterial interaction with surface receptor(s) on gingival cells (Weinberg et al., 1997)
T1006	Speculation 739 745	appear
E1003	Speculation:T1006 Scope:T1007
T1007	Span 725 808	Both fimbriae appear to be involved in bacterial pathogenicity (Amano et al., 2004)
T1008	Speculation 1846 1860	indicates that
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1846 1909	indicates that FimR does not bind directly to the fimA promoter
T1010	Negation 1871 1874	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1871 2165	not bind directly to the fimA promoter, but rather binds to the promoter region of the first gene (pg2130) in the fimA cluster, suggesting that PG2130 is the FimR target gene, which in turn regulates expression of other genes in the fimA cluster, including the fimA gene (Nishikawa et al., 2004
T1012	Negation 2673 2676	not
E1006	Negation:T1012 Scope:T1013
T1013	Span 2673 2719	not form microcolonies as the wild-type strain
T1014	Speculation 1999 2009	suggesting
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1999 2166	suggesting that PG2130 is the FimR target gene, which in turn regulates expression of other genes in the fimA cluster, including the fimA gene (Nishikawa et al., 2004)
T1016	Negation 2937 2940	not
E1008	Negation:T1016 Scope:T1017
T1017	Span 2916 2970	such differences are not found in gingipain expression
T1018	Speculation 2742 2749	appears
E1009	Speculation:T1018 Scope:T1019
T1019	Span 2726 2794	Mfa1 expression appears to fluctuate under various growth conditions
