T1000	Speculation 1570 1580	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1570 1776	suggesting that loss of one or more insect gut toxins is a critical step in the change of the Y. pestis lifestyle compared with the Y. pseudotuberculosis and thus in evolution of flea-borne transmission [8]
T1002	Speculation 1198 1202	idea
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1198 1254	idea that yersiniae are capable to interact with insects
T1004	Speculation 2993 3000	assumed
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2993 3123	assumed that these strains are associated with spiders, because spider bites where attended with Photorhabdus human infections [15
T1006	Negation 2186 2189	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 2186 2219	not at mammalian body temperature
T1008	Negation 4734 4738	lack
E1004	Negation:T1008 Scope:T1009
T1009	Span 4734 4779	lack protease, lipase and antibiotic activity
T1010	Speculation 3920 3928	probably
E1005	Speculation:T1010 Scope:T1011
T1011	Span 3920 4020	probably by providing essential nutrients that are required for efficient nematode proliferation [16
T1012	Speculation 5443 5451	probably
E1006	Speculation:T1012 Scope:T1013
T1013	Span 5434 5484	that are probably attributed to insect association
T1014	Speculation 4980 4987	assumed
E1007	Speculation:T1014 Scope:T1015
T1015	Span 4980 5052	assumed that primary variants correspond to the nematode-associated form
T1016	Speculation 5632 5640	possible
E1008	Speculation:T1016 Scope:T1017
T1017	Span 5632 5698	possible function during colonization and infection of non-mammals
T1018	Speculation 5618 5625	suggest
E1009	Speculation:T1018 Scope:T1019
T1019	Span 5618 5698	suggest their possible function during colonization and infection of non-mammals
