T1000	Speculation 1154 1159	might
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1148 1210	which might be involved in detecting insect-specific molecules
T1002	Negation 379 382	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 379 392	not to humans
T1004	Speculation 1767 1772	might
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1762 1937	that might be used to explore nutrients within the insect gut or hemolymph, thus enabling the proliferation of P. luminescens and Y. enterocolitica in their invertebrate hosts
T1006	Speculation 1352 1361	suggested
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1352 1418	suggested to play a major role in the pathogen-insect relationship
T1008	Speculation 2167 2175	putative
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2167 2221	putative broader insect host spectrum of this pathogen
T1010	Speculation 2156 2164	suggests
E1005	Speculation:T1010 Scope:T1011
T1011	Span 2156 2183	suggests a putative broader
T1012	Speculation 2431 2436	might
E1006	Speculation:T1012 Scope:T1013
T1013	Span 2418 2491	Some of them might have been selected during the association with insects
