T1000	Speculation 2251 2259	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 2251 2295	suggests an altered outer membrane structure
T1002	Speculation 1499 1507	putative
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1499 1562	putative two-component regulatory systems in the Brucella genus
T1004	Speculation 2975 2982	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2975 3085	suggest the existence of a complex regulatory network with the interplay of several transcriptional regulators
