T1000	Speculation 2472 2487	indicating that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 2472 2577	indicating that attachment and biofilm formation are mediated by extracellular appendages [12], [15]-[17]
T1002	Negation 1224 1227	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1224 1238	not surprising
T1004	Speculation 5101 5109	probably
E1002	Speculation:T1004 Scope:T1005
T1005	Span 5101 5292	probably in response to environmental cues or signals present during attachment, and involves the coordinated transduction of phosphorylation events via two-component regulatory systems (TCS)
T1006	Speculation 5008 5015	suggest
E1003	Speculation:T1006 Scope:T1007
T1007	Span 5008 5180	suggest that the transition to a surface associated lifestyle proceeds via several pathways, probably in response to environmental cues or signals present during attachment
T1008	Speculation 5322 5329	whether
E1004	Speculation:T1008 Scope:T1009
T1009	Span 5322 5616	whether the transition to later stages of biofilm formation, which coincide with distinct phenotypes compared to planktonic and initial attached bacterial cells, also involves sensing of environmental signal(s) and requires the coordinated transduction of phosphorylation events (phosphorelays)
