T1000	Speculation 6347 6355	possible
E1000	Speculation:T1000 Scope:T1001
T1001	Span 6347 6444	possible that the observed differences may be caused by variations of in vitro culture conditions
T1002	Speculation 6386 6389	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 6361 6444	the observed differences may be caused by variations of in vitro culture conditions
T1004	Speculation 7110 7116	should
E1002	Speculation:T1004 Scope:T1005
T1005	Span 7107 7312	It should be mentioned here that the SO2 phoP ko strain, which showed strong ESAT-6 expression but little ESAT-6 secretion (Figure 5), induced only very reduced ESAT-6- specific T cell responses (Figure 3)
T1006	Speculation 7575 7580	might
E1003	Speculation:T1006 Scope:T1007
T1007	Span 7575 7679	might be used to differentiate between vaccination with SO2 and infection with wild-type M. tuberculosis
T1008	Negation 5725 5727	no
E1004	Negation:T1008 Scope:T1009
T1009	Span 5725 5791	no significant differences in the ESX-1 encoding region were found
T1010	Speculation 5797 5807	assumption
E1005	Speculation:T1010 Scope:T1011
T1011	Span 5797 5910	assumption that the observed lack of ESAT-6 secretion in H37Ra may be caused by factors outside of the RD1 region
T1012	Speculation 5860 5863	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 5813 5928	the observed lack of ESAT-6 secretion in H37Ra may be caused by factors outside of the RD1 region is very plausible
T1014	Speculation 5919 5928	plausible
E1007	Speculation:T1014 Scope:T1015
T1015	Span 5793 5910	the assumption that the observed lack of ESAT-6 secretion in H37Ra may be caused by factors outside of the RD1 region
T1016	Speculation 8126 8132	likely
E1008	Speculation:T1016 Scope:T1017
T1017	Span 8080 8263	the strong attenuation of the H37Ra strain is likely based on several different genetic lesions, such as the one responsible for the absence of phthiocerol dimycocerosates (PDIM) [29]
T1018	Speculation 8275 8283	probably
E1009	Speculation:T1018 Scope:T1019
T1019	Span 8265 8429	that were probably introduced into this strain during years of continued culture following the original event of attenuation described by Steenken et al. in 1934 [6
T1020	Speculation 712 719	unknown
E1010	Speculation:T1020 Scope:T1021
T1021	Span 649 719	the genetic basis of the decreased virulence of H37Ra remained unknown
T1022	Negation 317 323	failed
E1011	Negation:T1022 Scope:T1023
T1023	Span 317 427	failed to propagate in an ordinarily susceptible host while the virulent variant H37Rv was able to proliferate
T1024	Negation 1801 1804	not
E1012	Negation:T1024 Scope:T1025
T1025	Span 1801 1861	not have a strong impact on the virulence of M. tuberculosis
T1026	Speculation 1409 1419	suggesting
E1013	Speculation:T1026 Scope:T1027
T1027	Span 1409 1501	suggesting that the phoP gene is required for intracellular growth of M. tuberculosis [14,25
T1028	Negation 2935 2938	not
E1014	Negation:T1028 Scope:T1029
T1029	Span 2935 2949	not ppe68 [21]
T1030	Speculation 2513 2519	likely
E1015	Speculation:T1030 Scope:T1031
T1031	Span 2513 2635	likely has a broad impact on gene regulation in H37Ra with effects similar to those seen for complete inactivation of phoP
T1032	Speculation 2981 2989	putative
E1016	Speculation:T1032 Scope:T1033
T1033	Span 2981 3127	putative nitrite reductase and MmpL10-FadD21 (Rv1183-85c), which were all identified by TraSH analysis as potentially implicated in virulence [16]
T1034	Speculation 2902 2906	seem
E1017	Speculation:T1034 Scope:T1035
T1035	Span 2897 2948	that seem to be regulated by phoP but not ppe68 [21
T1036	Speculation 3129 3133	seem
E1018	Speculation:T1036 Scope:T1037
T1037	Span 3129 3165	seem to be regulated by PhoP [12,21]
T1038	Speculation 3087 3098	potentially
E1019	Speculation:T1038 Scope:T1039
T1039	Span 3087 3127	potentially implicated in virulence [16]
T1040	Negation 4176 4180	lack
E1020	Negation:T1040 Scope:T1041
T1041	Span 4176 4224	lack of a fully functional PhoP in these strains
T1042	Negation 3999 4003	lack
E1021	Negation:T1042 Scope:T1043
T1043	Span 3999 4224	lack of ESAT-6-specific T cell responses observed for strains H37Ra and SO2 (Figure 3) might be caused by the insufficient expression of rv3612c-rv3616c, which results from the lack of a fully functional PhoP in these strains
T1044	Speculation 4086 4091	might
E1022	Speculation:T1044 Scope:T1045
T1045	Span 3995 4224	the lack of ESAT-6-specific T cell responses observed for strains H37Ra and SO2 (Figure 3) might be caused by the insufficient expression of rv3612c-rv3616c, which results from the lack of a fully functional PhoP in these strains
T1046	Speculation 3981 3989	probable
E1023	Speculation:T1046 Scope:T1047
T1047	Span 3981 4151	probable that the lack of ESAT-6-specific T cell responses observed for strains H37Ra and SO2 (Figure 3) might be caused by the insufficient expression of rv3612c-rv3616c
T1048	Speculation 4564 4573	not clear
E1024	Speculation:T1048 Scope:T1049
T1049	Span 4564 4623	not clear yet which factors might contribute to this effect
T1050	Speculation 4481 4486	might
E1025	Speculation:T1050 Scope:T1051
T1051	Span 4481 4556	might be regulated by environmental conditions through the PhoP/PhoR system
T1052	Speculation 4896 4901	seems
E1026	Speculation:T1052 Scope:T1053
T1053	Span 4896 5295	seems plausible that the pleiotropic regulator PhoP is involved in the regulation of rv3612c-rv3616c expression and thereby influences ESAT-6 secretion and virulence [16], but to unambiguously answer this question, virulence tests with recombinant H37Ra and/or phoP ko strains that express rv3616c-3612c under a constitutive promoter or a tetracycline inducable expression system [39] will be needed
T1054	Speculation 4592 4597	might
E1027	Speculation:T1054 Scope:T1055
T1055	Span 4592 4623	might contribute to this effect
T1056	Speculation 5534 5542	putative
E1028	Speculation:T1056 Scope:T1057
T1057	Span 5534 5597	putative progenitor species Mycobacterium prototuberculosis [40
T1058	Speculation 4902 4911	plausible
E1029	Speculation:T1058 Scope:T1059
T1059	Span 4902 5295	plausible that the pleiotropic regulator PhoP is involved in the regulation of rv3612c-rv3616c expression and thereby influences ESAT-6 secretion and virulence [16], but to unambiguously answer this question, virulence tests with recombinant H37Ra and/or phoP ko strains that express rv3616c-3612c under a constitutive promoter or a tetracycline inducable expression system [39] will be needed
T1060	Speculation 9035 9042	appears
E1030	Speculation:T1060 Scope:T1061
T1061	Span 8939 9105	The link described here between mutation of phoP and consequences on ESAT-6 secretion, however, appears to be one factor that significantly contributes to attenuation
T1062	Negation 8678 8681	not
E1031	Negation:T1062 Scope:T1063
T1063	Span 8678 8764	not know how many of these differences actually contribute to the attenuation of H37Ra
