T1000	Speculation 2866 2874	probably
E1000	Speculation:T1000 Scope:T1001
T1001	Span 2866 2884	probably conserved
T1002	Negation 1379 1382	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1379 1435	not involved in regulation of activities against insects
T1004	Speculation 710 717	assumed
E1002	Speculation:T1004 Scope:T1005
T1005	Span 710 818	assumed that there are parallels in the regulation of pathogenicity in mammals and insect pathogens [41,123]
T1006	Speculation 1199 1207	possibly
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1199 1252	possibly involved in pathogen-insect association only
T1008	Speculation 1112 1120	putative
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1112 1135	putative key regulators
T1010	Speculation 1461 1468	whether
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1461 1618	whether fundamental differences in regulatory networks reflect how each of these two bacteria specifically interacts with either the insect or the human host
T1012	Speculation 1370 1378	probably
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1370 1435	probably not involved in regulation of activities against insects
T1014	Speculation 1833 1841	possible
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1833 1961	possible competitors that are going to colonize the same insect cadaver or that are already present in the insect gut flora [17]
T1016	Speculation 1761 1766	might
E1008	Speculation:T1016 Scope:T1017
T1017	Span 1761 1960	might explain the high number of antibacterial factors directed against possible competitors that are going to colonize the same insect cadaver or that are already present in the insect gut flora [17
T1018	Speculation 2544 2552	suggests
E1009	Speculation:T1018 Scope:T1019
T1019	Span 2544 2745	suggests that Y. enterocolitica, similar to Y. pestis, has developed a strategy to infect and proliferate in insects, and use these organisms rather as transmission vectors than as pure nutrient source
T1020	Negation 1972 1974	no
E1010	Negation:T1020 Scope:T1021
T1021	Span 1972 2001	no corresponding determinants
