T1000	Negation 974 977	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 965 1003	that are not co-transcribed in operons
T1002	Negation 292 297	lacks
E1001	Negation:T1002 Scope:T1003
T1003	Span 292 320	lacks the SPI-2-encoded T3SS
T1004	Speculation 1369 1375	likely
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1369 1440	likely paralog of SseK1, an effector translocated by the SPI-2 T3SS [33
T1006	Speculation 1077 1083	likely
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1077 1143	likely that srcA (32% G+C) and an adjacent gene, STM2137 (37% G+C)
T1008	Speculation 1725 1733	possible
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1725 1793	possible that SrcA also chaperones SseK2 for low-level translocation
T1010	Negation 1634 1637	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 1634 1704	not able to detect SseK2 secretion or a physical interaction with SrcA
T1012	Speculation 2273 2280	appears
E1006	Speculation:T1012 Scope:T1013
T1013	Span 2268 2404	srcA appears to be a genetic acquisition separate from SPI-2 that functionally links some effectors to the T3SS apparatus via the ATPase
T1014	Speculation 2155 2163	implying
E1007	Speculation:T1014 Scope:T1015
T1015	Span 2155 2234	implying they have co-evolved as a single genetic entity from a common ancestor
T1016	Speculation 2783 2786	may
E1008	Speculation:T1016 Scope:T1017
T1017	Span 2783 2812	may improve host adaptability
T1018	Speculation 2542 2550	possible
E1009	Speculation:T1018 Scope:T1019
T1019	Span 2542 2581	possible implications for T3SS function
