T1000	Negation 499 501	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 499 526	no obvious recognition site
T1002	Negation 354 357	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 354 382	not fit a consensus sequence
T1004	Negation 1540 1542	no
E1002	Negation:T1004 Scope:T1005
T1005	Span 1540 1570	no consensus SsrB binding site
T1006	Speculation 1231 1234	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1197 1475	SPI-2 regulation by SsrB and SlyA may be explained in a similar mechanism where both SlyA and SsrB counteract the silencing activity of H-NS/YdgT/Hha by competing for binding to the same target sequences or by altering the structure of the DNA to promote transcription for SPI-2
T1008	Speculation 2011 2020	supported
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1997 2173	This model is supported by SlyA binding sites that are located downstream of transcriptional start sites [31],[86], which is unusual for a traditional transcriptional activator
T1010	Speculation 1679 1682	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1659 1723	different promoters may be activated by distinct SsrB mechanisms
T1012	Speculation 2517 2528	possibility
E1006	Speculation:T1012 Scope:T1013
T1013	Span 2517 2651	possibility may be reflected in the differences in expression of the five operons within SPI-2 following ssrB and slyA over-expression
T1014	Speculation 2361 2364	may
E1007	Speculation:T1014 Scope:T1015
T1015	Span 2361 2509	may be that both SlyA and SsrB counteract binding of small nucleoid-like proteins including both H-NS and YdgD/Hha in this A+T rich SPI-2 region [70
T1016	Speculation 2529 2532	may
E1008	Speculation:T1016 Scope:T1017
T1017	Span 2512 2651	This possibility may be reflected in the differences in expression of the five operons within SPI-2 following ssrB and slyA over-expression
