T1000	Speculation 2025 2032	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 2025 2232	suggest class III chaperones adopt an extended alpha helical structure, which was confirmed by the crystal structure of the CesA chaperone in enteropathogenic E. coli that binds the EspA filament protein [5]
T1002	Negation 885 888	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 885 923	not themselves subject to secretion [3
T1004	Speculation 3307 3312	seems
E1002	Speculation:T1004 Scope:T1005
T1005	Span 3307 3362	seems considerably larger than that of the SPI-1 system
T1006	Negation 3223 3225	no
E1003	Negation:T1006 Scope:T1007
T1007	Span 3223 3280	no structures are available for the SPI-2 T3SS chaperones
T1008	Speculation 3965 3972	whether
E1004	Speculation:T1008 Scope:T1009
T1009	Span 3965 4038	whether this system conforms to the emerging escort paradigm is not known
T1010	Negation 3928 3931	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 3874 4025	A chaperone-ATPase interaction for the SPI-2 T3SS has not been described previously and so whether this system conforms to the emerging escort paradigm
T1012	Speculation 4577 4584	unknown
E1006	Speculation:T1012 Scope:T1013
T1013	Span 4577 4593	unknown function
T1014	Speculation 4029 4038	not known
E1007	Speculation:T1014 Scope:T1015
T1015	Span 4029 4038	not known
