T1000	Speculation 1196 1205	not known
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1196 1205	not known
T1002	Speculation 1019 1021	As
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1019 1040	As introduced earlier
T1004	Speculation 1360 1363	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1360 1439	may be a common feature of the vicRK mutants of various Gram-positive pathogens
T1006	Speculation 1316 1326	suggesting
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1316 1439	suggesting that the growth defect phenotype may be a common feature of the vicRK mutants of various Gram-positive pathogens
T1008	Negation 2037 2040	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 2037 2062	not naturally infect mice
T1010	Speculation 1462 1469	appears
E1005	Speculation:T1010 Scope:T1011
T1011	Span 1441 1523	The DeltavicK mutant appears to possess the properties of a potential live vaccine
T1012	Speculation 1854 1857	can
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1854 1898	can be an effective live vaccine and whether
T1014	Speculation 1836 1843	whether
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1836 1886	whether DeltavicK can be an effective live vaccine
T1016	Speculation 2067 2071	hope
E1008	Speculation:T1016 Scope:T1017
T1017	Span 2067 2191	hope to perform this expensive test in future when funds are available

T1018	Speculation 1891 1898	whether
E1009	Speculation:T1018 Scope:T1019
T1019	Span 1891 2062	whether the DeltavicK mutant has any advantages over the current live S. equi vaccine require the test of the mutant in horses since S. equi does not naturally infect mice
T1020	Negation 197 200	not
E1010	Negation:T1020 Scope:T1021
T1021	Span 197 221	not essential in S. equi
T1022	Negation 71 74	not
E1011	Negation:T1022 Scope:T1023
T1023	Span 71 91	not in S. pneumoniae
T1024	Negation 541 544	not
E1012	Negation:T1024 Scope:T1025
T1025	Span 541 603	not grow as well as the wild-type strain in both THY and blood
T1026	Speculation 352 367	indicating that
E1013	Speculation:T1026 Scope:T1027
T1027	Span 352 399	indicating that VicRK is important to virulence
T1028	Speculation 666 675	plausible
E1014	Speculation:T1028 Scope:T1029
T1029	Span 666 776	plausible reason that likely contributes to the attenuation of S. equi virulence in the mouse infection models
T1030	Speculation 605 615	suggesting
E1015	Speculation:T1030 Scope:T1031
T1031	Span 605 776	suggesting that the vicK deletion causes defect in growth, a plausible reason that likely contributes to the attenuation of S. equi virulence in the mouse infection models
T1032	Negation 955 958	not
E1016	Negation:T1032 Scope:T1033
T1033	Span 946 1017	VicRK is not required for the evasion of S. equi to the innate immunity
T1034	Speculation 688 694	likely
E1017	Speculation:T1034 Scope:T1035
T1035	Span 688 776	likely contributes to the attenuation of S. equi virulence in the mouse infection models
T1036	Speculation 933 940	suggest
E1018	Speculation:T1036 Scope:T1037
T1037	Span 933 1017	suggest that VicRK is not required for the evasion of S. equi to the innate immunity
T1038	Speculation 783 793	suggestion
E1019	Speculation:T1038 Scope:T1039
T1039	Span 783 1017	suggestion is further supported by the observations that both the wild-type and DeltavicK mutant strains are resistant to phagocytosis by PMNs, which suggest that VicRK is not required for the evasion of S. equi to the innate immunity
