T1000	Negation 795 798	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 795 834	not in B. subtilis [2] and S. aureus [3
T1002	Negation 615 618	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 615 664	not to be essential in Streptococcus pyogenes [6]
T1004	Negation 2199 2204	lacks
E1002	Negation:T1004 Scope:T1005
T1005	Span 2199 2232	lacks the hyaluronic acid capsule
T1006	Negation 1246 1249	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 1153 1262	The vicRK system of Gram-positive bacterium Streptococcus equi subspecies equi (S. equi) has not been studied
