T1000	Speculation 787 797	hypothesis
E1000	Speculation:T1000 Scope:T1001
T1001	Span 787 840	hypothesis that Rv2623 regulates tuberculosis latency
T1002	Speculation 528 535	thought
E1001	Speculation:T1002 Scope:T1003
T1003	Span 528 554	thought to promote latency
T1004	Speculation 1660 1673	indicate that
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1660 1751	indicate that i) M. tuberculosis Rv2623 regulates mycobacterial growth in vitro and in vivo
T1006	Speculation 1229 1238	suggested
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1229 1276	suggested that this mycobacterial USP binds ATP
T1008	Speculation 2021 2024	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2021 2124	may function as an ATP-dependent signaling intermediate in a pathway that promotes persistent infection
T1010	Speculation 2001 2008	propose
E1005	Speculation:T1010 Scope:T1011
T1011	Span 2001 2124	propose that Rv2623 may function as an ATP-dependent signaling intermediate in a pathway that promotes persistent infection
