T1000	Speculation 1174 1179	seems
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1130 1275	emm49 GAS isolated from invasive infections seems to acquire the novel or altered virulence factors by mutations, genomic additions, or deletions
T1002	Negation 1080 1083	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1080 1117	not isolated before 1999 in Japan [8]
T1004	Speculation 1583 1590	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1583 1675	suggest that host defense factors play an important role in the onset of invasive infections
T1006	Speculation 1263 1265	or
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1233 1275	mutations, genomic additions, or deletions
T1008	Negation 2626 2633	without
E1004	Negation:T1008 Scope:T1009
T1009	Span 2626 2695	without severe invasive infection, and their gene-manipulated mutants
T1010	Negation 2238 2242	fail
E1005	Negation:T1010 Scope:T1011
T1011	Span 2238 2405	fail to elucidate direct relationship between definitive genetic changes in clinically isolated severe invasive GAS and the lack of PMN at the site of bacterial growth
T1012	Speculation 3217 3220	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 3217 3358	may participate in prediction of GAS potential for future invasive infection as well as risk assessment of patients by measuring PMN function
