T1000	Speculation 1010 1020	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1010 1068	suggesting that SsrB requires phosphorylation for activity
T1002	Speculation 735 738	not
E1001	Speculation:T1002 Scope:T1003
T1003	Span 735 754	not yet established
T1004	Speculation 1639 1647	possible
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1639 1808	possible that the environmental conditions that distinguish growth in minimal media from those in the SCV inside hosts are sensed via these two alternative sigma factors
T1006	Speculation 1178 1186	possible
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1178 1390	possible that SsrB can be phosphorylated from other sources as noted by Walthers et al. [52] or that the over-expression results in dimerization and self activation similar to what has been observed for PhoP [78]
T1008	Speculation 2179 2186	Strains
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2179 2223	Strains containing mutations in spvR and hnr
T1010	Speculation 2021 2027	likely
E1005	Speculation:T1010 Scope:T1011
T1011	Span 2021 2177	likely explanation for the large intracellular growth defects observed in the mutant smpB and hfq derivatives despite relative small transcriptional effects
