T1000	Negation 1335 1338	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1335 1384	not present in nonpathogenic but related bacteria
T1002	Negation 1066 1069	nor
E1001	Negation:T1002 Scope:T1003
T1003	Span 1066 1117	nor required for growth under laboratory conditions
T1004	Negation 2302 2305	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 2302 2405	not found extracellularly until the last one or two days immediately before death of the mouse [15]-[17
