T1000	Speculation 1865 1878	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 1865 1977	indicate that SeMac is a cysteine endopeptidase but does not inhibit opsonophagocytosis of S. equi by horse PMNs
T1002	Negation 1922 1925	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 1922 2082	not inhibit opsonophagocytosis of S. equi by horse PMNs, suggesting that SeMac has function other than evading horse acquired immunity against S. equi infection
T1004	Speculation 1979 1989	suggesting
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1979 2082	suggesting that SeMac has function other than evading horse acquired immunity against S. equi infection
