T1000	Speculation 10208 10215	suggest
E1000	Speculation:T1000 Scope:T1001
T1001	Span 10208 10558	suggest a link between the multi-component switch RetS/LadS/GacAS/RsmA which reciprocally regulates virulence and the transition between the planktonic and the surface attached mode of growth and the previously undescribed signaling network which regulates developmental steps once P. aeruginosa has committed to the surface associated lifestyle (Fig
T1002	Speculation 11121 11129	suggests
E1001	Speculation:T1002 Scope:T1003
T1003	Span 11121 11211	suggests that biofilm development is analogous to other programmed developmental processes
T1004	Speculation 11281 11288	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 11281 11518	suggest that both two-component regulatory systems and sigma factor dependent response regulators are key components of the transcriptional and regulatory machinery that coordinate gene expression during P. aeruginosa biofilm development
T1006	Speculation 8216 8224	probably
E1003	Speculation:T1006 Scope:T1007
T1007	Span 8216 8285	probably by controlling the expression of fimbrial cup genes [66],[76
T1008	Negation 8956 8959	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 8956 9004	not result in the identification of RetS or LadS
T1010	Speculation 9848 9851	may
E1005	Speculation:T1010 Scope:T1011
T1011	Span 9848 9987	may suggest that RetS only remains functional for a period of 8 hours during initial attachment after which RetS is rendered non-functional
T1012	Speculation 9852 9859	suggest
E1006	Speculation:T1012 Scope:T1013
T1013	Span 9852 9987	suggest that RetS only remains functional for a period of 8 hours during initial attachment after which RetS is rendered non-functional
T1014	Negation 479 481	no
E1007	Negation:T1014 Scope:T1015
T1015	Span 479 501	no regulatory pathways
T1016	Speculation 139 149	assumption
E1008	Speculation:T1016 Scope:T1017
T1017	Span 139 221	assumption that the formation of biofilms is a regulated progression [11],[12],[66
T1018	Speculation 1545 1560	indicating that
E1009	Speculation:T1018 Scope:T1019
T1019	Span 1545 1711	indicating that the phosphorylation status of the three novel two-component systems is essential for their function in regulating biofilm development by P. aeruginosa
T1020	Negation 871 874	not
E1010	Negation:T1020 Scope:T1021
T1021	Span 871 900	not affect initial attachment
T1022	Speculation 2361 2370	not clear
E1011	Speculation:T1022 Scope:T1023
T1023	Span 2361 2471	not clear how the three two-component systems interact to form the observed sequential phosphorylation cascade
T1024	Speculation 2179 2185	appear
E1012	Speculation:T1024 Scope:T1025
T1025	Span 2142 2347	the novel TCS systems described here appear to be linked via GacS to the multicomponent system RetS/LadS/GacAS/RsmA essential for regulating the switch between the planktonic and the sessile mode of growth
T1026	Negation 2898 2904	failed
E1013	Negation:T1026 Scope:T1027
T1027	Span 2898 2982	failed to exhibit stage-specific protein production and phosphorylation events (Figs
T1028	Speculation 2618 2619	2
E1014	Speculation:T1028 Scope:T1029
T1029	Span 2618 2620	2)
T1030	Speculation 3014 3020	likely
E1015	Speculation:T1030 Scope:T1031
T1031	Span 3014 3163	likely that the mutant biofilms in turn do not produce the necessary signal(s) to activate or phosphorylate TCS system(s) that are further downstream
T1032	Negation 3057 3060	not
E1016	Negation:T1032 Scope:T1033
T1033	Span 3057 3163	not produce the necessary signal(s) to activate or phosphorylate TCS system(s) that are further downstream
T1034	Speculation 3177 3183	likely
E1017	Speculation:T1034 Scope:T1035
T1035	Span 3177 3348	likely that inactivation of one TCS system (in)directly results in altered or arrested phosphorylation patterns and thus, lack of phosphorylation of downstream TCS systems
T1036	Negation 3299 3303	lack
E1018	Negation:T1036 Scope:T1037
T1037	Span 3299 3367	lack of phosphorylation of downstream TCS systems (as observed here)
T1038	Speculation 4174 4182	possible
E1019	Speculation:T1038 Scope:T1039
T1039	Span 4174 4305	possible that the novel regulatory proteins identified here play a role under more than one discrete culturing condition or pathway
T1040	Speculation 3940 3948	suggests
E1020	Speculation:T1040 Scope:T1041
T1041	Span 3940 4305	suggests that while biofilm formation, architecture and cell-cell signaling is modulated by environmental and nutritional conditions resulting in biofilm development proceeding via distinctly different pathways [16], [55]-[63], it is possible that the novel regulatory proteins identified here play a role under more than one discrete culturing condition or pathway
T1042	Negation 4812 4814	No
E1021	Negation:T1042 Scope:T1043
T1043	Span 4812 4825	No homologues
T1044	Negation 4524 4527	not
E1022	Negation:T1044 Scope:T1045
T1045	Span 4524 4605	not reveal any proteins that have been previously characterized in the literature
T1046	Speculation 6588 6594	either
E1023	Speculation:T1046 Scope:T1047
T1047	Span 6588 6769	either by cleaving the precursor molecules or by sequestration of sigma factors by "anti-sigma factor" proteins in response to intercellular cues, and compartmentalization [68],[73]
T1048	Speculation 6129 6139	suggestion
E1024	Speculation:T1048 Scope:T1049
T1049	Span 6129 6284	suggestion that NtrC-like activators are key components of the transcriptional machinery that coordinates gene expression during M. xanthus development [72
T1050	Speculation 7446 7450	idea
E1025	Speculation:T1050 Scope:T1051
T1051	Span 7446 7537	idea that biofilm development by P. aeruginosa is orchestrated by a regulatory cascade (Fig
T1052	Speculation 6814 6820	appear
E1026	Speculation:T1052 Scope:T1053
T1053	Span 6782 6854	biofilm developmental processes appear to be controlled by sigma factors
