T1000	Speculation 566 576	suggesting
E1000	Speculation:T1000 Scope:T1001
T1001	Span 566 677	suggesting that Y. pestis is vulnerable to the initial encounter with innate immune cells at the flea bite site
T1002	Negation 496 499	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 496 564	not produced in the low-temperature environment of the flea, however
T1004	Speculation 1428 1435	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1428 1587	suggest that transit through the flea vector induces a phenotype that enhances survival and dissemination of Y. pestis after transmission to the mammalian host
