T1000	Speculation 2076 2079	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 2076 2111	may be insignificant in whole blood
T1002	Speculation 2031 2034	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1979 2072	the inhibition of the bactericidal activity of PMNs may not be mediated by opsonophagocytosis
T1004	Speculation 2429 2436	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 2429 2503	suggest that the semac and mac genes are regulated by different mechanisms
T1006	Negation 2122 2125	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 2122 2143	not produced in vitro
T1008	Speculation 2524 2533	supported
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2505 2644	This suggestion is supported by only 29% DNA sequence identity between S. equi and M1 GAS in the upstream region of the semac and mac genes
T1010	Speculation 2510 2520	suggestion
E1005	Speculation:T1010 Scope:T1011
T1011	Span 2510 2644	suggestion is supported by only 29% DNA sequence identity between S. equi and M1 GAS in the upstream region of the semac and mac genes
T1012	Negation 2780 2783	not
E1006	Negation:T1012 Scope:T1013
T1013	Span 2780 2854	not involved in the evasion of the acquired horse immunity against S. equi
T1014	Negation 2700 2703	not
E1007	Negation:T1014 Scope:T1015
T1015	Span 2700 2755	not inhibit opsonophagocytosis of S. equi by horse PMNs
T1016	Speculation 2861 2869	suggests
E1008	Speculation:T1016 Scope:T1017
T1017	Span 2861 2907	suggests that SeMac has other unknown function
T1018	Speculation 2756 2770	indicates that
E1009	Speculation:T1018 Scope:T1019
T1019	Span 2756 2854	indicates that SeMac is not involved in the evasion of the acquired horse immunity against S. equi
T1020	Speculation 2891 2898	unknown
E1010	Speculation:T1020 Scope:T1021
T1021	Span 2891 2907	unknown function
T1022	Speculation 609 617	proposed
E1011	Speculation:T1022 Scope:T1023
T1023	Span 609 719	proposed to bind to the active site of Mac [9], and the cleavage occurs between the two Gly residues (Table 1)
T1024	Negation 124 130	unable
E1012	Negation:T1024 Scope:T1025
T1025	Span 124 208	unable to inhibit opsonophagocytosis of S. equi by horse PMNs in a whole blood assay
T1026	Negation 1144 1147	not
E1013	Negation:T1026 Scope:T1027
T1027	Span 1144 1158	not be cleaved
T1028	Speculation 919 929	suggesting
E1014	Speculation:T1028 Scope:T1029
T1029	Span 919 1037	suggesting that the amino acid sequences of the lower hinge region are important for cleavability by SeMac and GAS Mac
T1030	Speculation 1140 1143	may
E1015	Speculation:T1030 Scope:T1031
T1031	Span 1105 1158	the other five horse IgG subgroups may not be cleaved
T1032	Speculation 1067 1070	may
E1016	Speculation:T1032 Scope:T1033
T1033	Span 1067 1097	may be also cleavable by SeMac
T1034	Speculation 1719 1729	suggesting
E1017	Speculation:T1034 Scope:T1035
T1035	Span 1719 1827	suggesting that SeMac functions like GAS M1 Mac in the inhibition of opsonophagocytosis of GAS by human PMNs
T1036	Negation 1540 1546	unable
E1018	Negation:T1036 Scope:T1037
T1037	Span 1540 1601	unable to inhibit opsonophagocytosis of S. equi by horse PMNs
T1038	Speculation 1966 1973	suggest
E1019	Speculation:T1038 Scope:T1039
T1039	Span 1966 2072	suggest that the inhibition of the bactericidal activity of PMNs may not be mediated by opsonophagocytosis
T1040	Negation 2035 2038	not
E1020	Negation:T1040 Scope:T1041
T1041	Span 2035 2072	not be mediated by opsonophagocytosis
