T1000	Negation 1203 1206	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 1203 1291	not affect planktonic growth, motility, polysaccharide production, or initial attachment
T1002	Speculation 1049 1059	indicating
E1001	Speculation:T1002 Scope:T1003
T1003	Span 1049 1169	indicating a requirement for these regulatory systems for the development and maintenance of normal biofilm architecture
T1004	Speculation 1654 1660	appear
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1473 1817	a novel signal transduction network regulating committed biofilm developmental steps following attachment, in which phosphorelays and two sigma factor-dependent response regulators appear to be key components of the regulatory machinery that coordinates gene expression during P. aeruginosa biofilm development in response to environmental cues
