T1000	Negation 2204 2206	no
E1000	Negation:T1000 Scope:T1001
T1001	Span 2204 2288	no evidence of interactions between SrcA and translocon components of the SPI-2 T3SS
T1002	Speculation 535 543	suggests
E1001	Speculation:T1002 Scope:T1003
T1003	Span 535 652	suggests a docking recognition function with other components of the type III apparatus, possibly the T3SS-accociated
T1004	Speculation 496 505	not known
E1002	Speculation:T1004 Scope:T1005
T1005	Span 446 505	The exact function of this charge distribution is not known
T1006	Negation 795 798	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 795 814	not cargo stability
T1008	Speculation 624 632	possibly
E1004	Speculation:T1008 Scope:T1009
T1009	Span 624 659	possibly the T3SS-accociated ATPase
T1010	Speculation 987 997	suggesting
E1005	Speculation:T1010 Scope:T1011
T1011	Span 987 1083	suggesting a role in either targeting bound cargo to the T3SS or in the secretion process itself
T1012	Negation 965 968	not
E1006	Negation:T1012 Scope:T1013
T1013	Span 965 972	not Tir
T1014	Speculation 1303 1309	likely
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1303 1487	likely that other surface charged residues of SrcA are involved in these functions or that SrcA targets effector cargo to the secretion apparatus through a mechanism distinct from CesT
T1016	Negation 1105 1110	lacks
E1008	Negation:T1016 Scope:T1017
T1017	Span 1105 1125	lacks 17-amino acids
T1018	Speculation 2059 2062	may
E1009	Speculation:T1018 Scope:T1019
T1019	Span 2059 2193	may relate to biological function in the SPI2 T3SS and/or in vetting effector cargo amongst the >30 effectors identified in Salmonella
T1020	Speculation 1386 1388	or
E1010	Speculation:T1020 Scope:T1021
T1021	Span 1386 1487	or that SrcA targets effector cargo to the secretion apparatus through a mechanism distinct from CesT
