T1000	Negation 846 852	lacked
E1000	Negation:T1000 Scope:T1001
T1001	Span 846 931	lacked a domain at the carboxyl terminus thought to be involved in oligomer stability
T1002	Negation 777 780	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 777 795	not in its absence
T1004	Speculation 976 983	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 976 1134	suggest that type III chaperones might have an as yet undefined role in assembly of the ATPase homohexamer that gives rise to efficient effector translocation
T1006	Speculation 887 894	thought
E1003	Speculation:T1006 Scope:T1007
T1007	Span 887 963	thought to be involved in oligomer stability, at least for E. coli EscN [14]
T1008	Speculation 1009 1014	might
E1004	Speculation:T1008 Scope:T1009
T1009	Span 1009 1134	might have an as yet undefined role in assembly of the ATPase homohexamer that gives rise to efficient effector translocation
