T1000	Speculation 415 423	believed
E1000	Speculation:T1000 Scope:T1001
T1001	Span 415 545	believed to harbor latent bacilli that can reactivate to cause tuberculous diseases, sometimes decades after the initial infection
T1002	Speculation 200 208	estimate
E1001	Speculation:T1002 Scope:T1003
T1003	Span 200 331	estimate that, in the immunocompetent host, only approximately10% of M. tuberculosis infection progress to active pulmonary disease
T1004	Speculation 1322 1330	believed
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1313 1428	that are believed, based on in vitro studies, to promote latency by prompting the M. tuberculosis dormancy response
T1006	Speculation 1261 1267	likely
E1003	Speculation:T1006 Scope:T1007
T1007	Span 1261 1330	likely to be encountered within tuberculous lesions that are believed
T1008	Speculation 2528 2531	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2528 2588	may be conducive to the establishment of persistence in vivo
T1010	Speculation 2491 2501	suggesting
E1005	Speculation:T1010 Scope:T1011
T1011	Span 2491 2588	suggesting that expression of Rv2623 may be conducive to the establishment of persistence in vivo
