T1000	Speculation 3465 3468	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 3465 3495	may not be sufficiently acidic
T1002	Speculation 3415 3418	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 3415 3449	may not be low enough in magnesium
T1004	Negation 3837 3840	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 3820 4023	STM3117-3120 are not transcribed under a variety of in vitro conditions including AMM1 and 2 and the many conditions corresponding to the transcriptional profiles reported for microarrays archived in GEO
T1006	Speculation 3541 3544	may
E1003	Speculation:T1006 Scope:T1007
T1007	Span 3541 3621	may be only weakly transcribed or not at all transcribed in acidic minimal media
T1008	Speculation 5405 5415	presumably
E1004	Speculation:T1008 Scope:T1009
T1009	Span 5405 5562	presumably respond to differences in ssrB/slyA activation, perhaps establishing part of the temporal order of expression following phagocytosis of Salmonella
T1010	Speculation 4180 4189	not known
E1005	Speculation:T1010 Scope:T1011
T1011	Span 4180 4189	not known
T1012	Negation 5687 5694	without
E1006	Negation:T1012 Scope:T1013
T1013	Span 5687 5724	without a compensating mutation (hns;
T1014	Speculation 5464 5471	perhaps
E1007	Speculation:T1014 Scope:T1015
T1015	Span 5464 5562	perhaps establishing part of the temporal order of expression following phagocytosis of Salmonella
T1016	Speculation 1437 1442	could
E1008	Speculation:T1016 Scope:T1017
T1017	Span 1437 1486	could be a surrogate for systemic mouse infection
T1018	Speculation 1394 1404	hypothesis
E1009	Speculation:T1018 Scope:T1019
T1019	Span 1394 1486	hypothesis that replication in macrophages could be a surrogate for systemic mouse infection
T1020	Speculation 1787 1793	likely
E1010	Speculation:T1020 Scope:T1021
T1021	Span 1695 1875	Transcriptional profiles from intracellular bacteria at different times after infection are likely to match most closely the environments encountered by Salmonella during infection
T1022	Negation 1608 1611	not
E1011	Negation:T1022 Scope:T1023
T1023	Span 1608 1623	not always true
T1024	Negation 2031 2034	not
E1012	Negation:T1024 Scope:T1025
T1025	Span 2031 2092	not survive within cells long enough to allow RNA preparation
T1026	Negation 1935 1938	not
E1013	Negation:T1026 Scope:T1027
T1027	Span 1886 1943	isolation of RNA from intracellular bacteria was not used
T1028	Negation 3419 3422	not
E1014	Negation:T1028 Scope:T1029
T1029	Span 3419 3495	not be low enough in magnesium, phosphate, or may not be sufficiently acidic
T1030	Speculation 3128 3136	putative
E1015	Speculation:T1030 Scope:T1031
T1031	Span 3128 3177	putative, hypothetical, or conserved hypothetical
T1032	Speculation 3366 3376	suggesting
E1016	Speculation:T1032 Scope:T1033
T1033	Span 3366 3449	suggesting that the acidic minimal media we used may not be low enough in magnesium
T1034	Negation 3469 3472	not
E1017	Negation:T1034 Scope:T1035
T1035	Span 3469 3495	not be sufficiently acidic
