T1000	Negation 777 780	not
E1000	Negation:T1000 Scope:T1001
T1001	Span 777 881	not found in closely related non-pathogenic bacteria (overall comparison eliminating SPI-2 genes p<e-15)
T1002	Speculation 70 79	suggested
E1001	Speculation:T1002 Scope:T1003
T1003	Span 70 96	suggested by these studies
T1004	Speculation 1162 1165	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1162 1216	may interact and coordinate regulation within the host
