T1000	Speculation 7750 7753	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 7750 7848	may provide with novel clues for early diagnosis and therapeutics of invasive bacterial infections
T1002	Negation 5324 5327	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 5324 5404	not reach the threshold level to kill PMN by formation of pores (data not shown)
T1004	Negation 5394 5397	not
E1002	Negation:T1004 Scope:T1005
T1005	Span 5388 5404	(data not shown)
T1006	Negation 5422 5425	not
E1003	Negation:T1006 Scope:T1007
T1007	Span 5422 5643	not undergo necrosis upon incubation with culture media of severe invasive GAS (Figure 3B), leading to the novel possibility that PMN are probably killed following encounter with invasive GAS in a contact-dependent manner
T1008	Speculation 5535 5546	possibility
E1004	Speculation:T1008 Scope:T1009
T1009	Span 5535 5643	possibility that PMN are probably killed following encounter with invasive GAS in a contact-dependent manner
T1010	Negation 4228 4231	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 4228 4349	not exclude the possibility that other CsrS-regulating factors contribute to the escape of invasive GAS from host defense
T1012	Speculation 4244 4255	possibility
E1006	Speculation:T1012 Scope:T1013
T1013	Span 4244 4349	possibility that other CsrS-regulating factors contribute to the escape of invasive GAS from host defense
T1014	Negation 5093 5096	not
E1007	Negation:T1014 Scope:T1015
T1015	Span 5093 5212	not due to cytotoxity of SLO itself as judged by their flow cytometry profiles which are distinct from ours (Figure 2A)
T1016	Speculation 5018 5024	likely
E1008	Speculation:T1016 Scope:T1017
T1017	Span 5018 5212	likely due to complement activation by SLO [28] or PMN activation [29] but not due to cytotoxity of SLO itself as judged by their flow cytometry profiles which are distinct from ours (Figure 2A)
T1018	Speculation 5560 5568	probably
E1009	Speculation:T1018 Scope:T1019
T1019	Span 5552 5643	PMN are probably killed following encounter with invasive GAS in a contact-dependent manner
T1020	Speculation 5661 5664	may
E1010	Speculation:T1020 Scope:T1021
T1021	Span 5661 5826	may make a small interface containing a high concentration of SLO between bacteria and PMN, which resembles to killing mechanism of killer cells to target cells [30]
T1022	Speculation 7462 7465	may
E1011	Speculation:T1022 Scope:T1023
T1023	Span 7462 7525	may be the reason for rare outbreaks of invasive GAS infections
T1024	Speculation 7579 7584	could
E1012	Speculation:T1024 Scope:T1025
T1025	Span 7579 7603	could evade PMN function
T1026	Speculation 1124 1129	seems
E1013	Speculation:T1026 Scope:T1027
T1027	Span 1088 1148	mutation frequency of csrS and csrR seems to be the same [21
T1028	Negation 389 392	not
E1014	Negation:T1028 Scope:T1029
T1029	Span 389 430	not with emm-matched non-invasive strains
T1030	Negation 1296 1299	not
E1015	Negation:T1030 Scope:T1031
T1031	Span 1287 1306	and data not shown)
T1032	Negation 1255 1258	not
E1016	Negation:T1032 Scope:T1033
T1033	Span 1255 1306	not in the csrR gene (Figure 5B and data not shown)
T1034	Speculation 1585 1595	suggesting
E1017	Speculation:T1034 Scope:T1035
T1035	Span 1585 1716	suggesting the csrS mutation is more important in comparison with that of csrR in the clinical isolates regardless of emm genotypes
T1036	Speculation 1333 1340	whether
E1018	Speculation:T1036 Scope:T1037
T1037	Span 1333 1443	whether severe invasive isolates of other than emm49 genotype have the mutation of the csrS and the csrR genes
T1038	Speculation 2102 2105	may
E1019	Speculation:T1038 Scope:T1039
T1039	Span 2102 2169	may transmit a signal not only to CsrR but also to other regulators
T1040	Negation 1861 1864	not
E1020	Negation:T1040 Scope:T1041
T1041	Span 1861 1883	not in the csrR mutant
T1042	Speculation 2621 2628	perhaps
E1021	Speculation:T1042 Scope:T1043
T1043	Span 2621 2675	perhaps due to lack of proper non-invasive counterpart
T1044	Speculation 2268 2276	possibly
E1022	Speculation:T1044 Scope:T1045
T1045	Span 2252 2372	its mutation is possibly more important than that of csrR in terms of etiopathogenesis of human severe invasive diseases
T1046	Speculation 7318 7325	suggest
E1023	Speculation:T1046 Scope:T1047
T1047	Span 7318 7525	suggest that the level of PMN function is one of the critical factors to determine the threshold for the onset of invasive GAS infection, which may be the reason for rare outbreaks of invasive GAS infections
T1048	Negation 7255 7262	failure
E1024	Negation:T1048 Scope:T1049
T1049	Span 7255 7266	failure [37
T1050	Speculation 2723 2731	proposed
E1025	Speculation:T1050 Scope:T1051
T1051	Span 2680 2798	examples, SpeB [22] and SLS [23] have been proposed as an invasive infection-associated factor by its cytotoxic effect
T1052	Negation 2837 2840	not
E1026	Negation:T1052 Scope:T1053
T1053	Span 2809 2937	speB and sagA expression is not enhanced in any csrS-mutated severe invasive GAS isolate used in this study and others [5], [24]
T1054	Negation 3110 3113	not
E1027	Negation:T1054 Scope:T1055
T1055	Span 3110 3222	not affect PMN survival at all, excluding the possibility for the role of SLS in PMN necrosis seen in this study
T1056	Negation 3062 3065	not
E1028	Negation:T1056 Scope:T1057
T1057	Span 3056 3072	(data not shown)
T1058	Negation 3488 3491	not
E1029	Negation:T1058 Scope:T1059
T1059	Span 3488 3526	not alter the level of PI-positive PMN
T1060	Speculation 3156 3167	possibility
E1030	Speculation:T1060 Scope:T1061
T1061	Span 3156 3222	possibility for the role of SLS in PMN necrosis seen in this study
T1062	Speculation 3717 3725	possibly
E1031	Speculation:T1062 Scope:T1063
T1063	Span 3717 3759	possibly due to the difference of emm type
T1064	Negation 3565 3568	not
E1032	Negation:T1064 Scope:T1065
T1065	Span 3565 3613	not due to release of NETs from PMN (Figure S1A)
T1066	Speculation 3915 3918	may
E1033	Speculation:T1066 Scope:T1067
T1067	Span 3915 3980	may be important but redundant for induction of invasive diseases
T1068	Speculation 3896 3903	suggest
E1034	Speculation:T1068 Scope:T1069
T1069	Span 3896 3980	suggest that DNase may be important but redundant for induction of invasive diseases
T1070	Speculation 5988 5995	whether
E1035	Speculation:T1070 Scope:T1071
T1071	Span 5988 6094	whether there exist explore interaction-associated molecules on both host and bacterial membrane is needed
T1072	Speculation 5867 5870	may
E1036	Speculation:T1072 Scope:T1073
T1073	Span 5867 6084	may be critical to induce PMN necrosis as similarly mechanism has been reported [31], although it remains to be examined whether there exist explore interaction-associated molecules on both host and bacterial membrane
T1074	Speculation 6865 6869	seem
E1037	Speculation:T1074 Scope:T1075
T1075	Span 6840 6896	Several clinical reports seem to support this hypothesis
T1076	Negation 7072 7079	without
E1038	Negation:T1076 Scope:T1077
T1077	Span 7072 7094	without leukocytopenia
T1078	Speculation 6769 6772	may
E1039	Speculation:T1078 Scope:T1079
T1079	Span 6769 6838	may determine the induction and clinical outcome of invasive diseases
T1080	Speculation 6685 6692	suggest
E1040	Speculation:T1080 Scope:T1081
T1081	Span 6685 6838	suggest that the ability of incompetence for PMN functions by individual GAS strain may determine the induction and clinical outcome of invasive diseases
T1082	Negation 6516 6521	lacks
E1041	Negation:T1082 Scope:T1083
T1083	Span 6516 6596	lacks PMN infiltration in mice tissues infected with csrS-mutated GAS (Figure 7)
T1084	Negation 6187 6190	not
E1042	Negation:T1084 Scope:T1085
T1085	Span 6187 6203	not each of them
