T1000	Speculation 6930 6933	may
E1000	Speculation:T1000 Scope:T1001
T1001	Span 6930 6982	may play in biofilm-associated antibiotic resistance
T1002	Speculation 4660 4668	possibly
E1001	Speculation:T1002 Scope:T1003
T1003	Span 4660 4720	possibly control the switch to a biofilm lifestyle [34],[35]
T1004	Speculation 7735 7738	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 7735 7932	may include the quorum sensing regulated release of DNA [51] and/or DNA contained within outer membrane vesicles (OMV) that bleb and are released from the OM of living P. aeruginosa cells [56],[57]
T1006	Speculation 7506 7512	likely
E1003	Speculation:T1006 Scope:T1007
T1007	Span 7506 7554	likely released by dead bacteria or immune cells
T1008	Speculation 8063 8066	may
E1004	Speculation:T1008 Scope:T1009
T1009	Span 8063 8172	may exist, similar to the autolysin-mediated DNA release observed in Staphylococcus epidermidis biofilms [53]
T1010	Speculation 8035 8043	possible
E1005	Speculation:T1010 Scope:T1011
T1011	Span 8035 8171	possible that such a method may exist, similar to the autolysin-mediated DNA release observed in Staphylococcus epidermidis biofilms [53
T1012	Speculation 8244 8247	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 8244 8300	may contribute to biofilm-specific antibiotic resistance
T1014	Speculation 1725 1733	suggests
E1007	Speculation:T1014 Scope:T1015
T1015	Span 1725 1795	suggests that P. aeruginosa forms biofilms in the lungs of CF patients
T1016	Speculation 347 354	thought
E1008	Speculation:T1016 Scope:T1017
T1017	Span 347 464	thought to contribute to their ability to thrive in hostile host environments and result in chronic infection [3],[4]
T1018	Speculation 2234 2237	may
E1009	Speculation:T1018 Scope:T1019
T1019	Span 2234 2356	may be protected from antibiotic exposure due to the restricted penetration of antibiotics through the biofilm matrix [19]
T1020	Speculation 2108 2114	likely
E1010	Speculation:T1020 Scope:T1021
T1021	Span 2108 2213	likely that multiple mechanisms operate simultaneously in biofilms to contribute to antibiotic resistance
T1022	Speculation 2392 2395	may
E1011	Speculation:T1022 Scope:T1023
T1023	Span 2392 2495	may limit diffusion initially for certain antibiotics such as beta-lactams and aminoglycosides [14],[22
T1024	Negation 2557 2564	without
E1012	Negation:T1024 Scope:T1025
T1025	Span 2557 2570	without delay
T1026	Negation 2939 2942	not
E1013	Negation:T1026 Scope:T1027
T1027	Span 2939 3003	not play a significant role during long-term antibiotic exposure
T1028	Speculation 2626 2636	presumably
E1014	Speculation:T1028 Scope:T1029
T1029	Span 2626 2703	presumably dependent on binding of the antibiotic molecules to the EPS matrix
T1030	Speculation 4625 4631	appear
E1015	Speculation:T1030 Scope:T1031
T1031	Span 4584 4719	the hybrid sensor kinases, LadS and RetS appear to work upstream of GacA to possibly control the switch to a biofilm lifestyle [34],[35
T1032	Negation 4392 4395	not
E1016	Negation:T1032 Scope:T1033
T1033	Span 4392 4567	not limited to, the global virulence factor regulator GacA, mutation of which results in a 10-fold decrease in biofilm formation and failure to form microcolony structures [33
