T1000	Speculation 8695 8703	suggests
E1000	Speculation:T1000 Scope:T1001
T1001	Span 8695 8790	suggests the possibility that this mycobacterial USP, like MJ0577, is capable of ATP hydrolysis
T1002	Speculation 8708 8719	possibility
E1001	Speculation:T1002 Scope:T1003
T1003	Span 8708 8790	possibility that this mycobacterial USP, like MJ0577, is capable of ATP hydrolysis
T1004	Speculation 8985 8993	putative
E1002	Speculation:T1004 Scope:T1005
T1005	Span 8985 9020	putative ATP-hydrolyzing properties
T1006	Speculation 9703 9714	potentially
E1003	Speculation:T1006 Scope:T1007
T1007	Span 9703 9756	potentially, the hydrolysis of ATP by Rv2623 regulate
T1008	Speculation 7054 7060	likely
E1004	Speculation:T1008 Scope:T1009
T1009	Span 7054 7160	likely that the mycobacterial growth-regulatory faculty of Rv2623 is mediated by an ATP-dependent function
T1010	Negation 7380 7385	fails
E1005	Negation:T1010 Scope:T1011
T1011	Span 7380 7526	fails to establish a persistent infection in susceptible hosts, as well as the growth attenuation observed in mycobacteria overexpressing this USP
T1012	Speculation 7557 7560	may
E1006	Speculation:T1012 Scope:T1013
T1013	Span 7557 7630	may serve the function of promoting mycobacterial transition into latency
T1014	Speculation 7846 7849	may
E1007	Speculation:T1014 Scope:T1015
T1015	Span 7846 7985	may contribute significantly to the propagation of the tubercle bacillus in the human host and the difficulties in eradicating tuberculosis
T1016	Speculation 9806 9812	likely
E1008	Speculation:T1016 Scope:T1017
T1017	Span 9806 9893	likely illuminate the mechanisms by which the tubercle bacillus establishes persistence
T1018	Speculation 1986 1989	may
E1009	Speculation:T1018 Scope:T1019
T1019	Span 1986 2015	may have biological relevance
T1020	Speculation 1949 1956	suggest
E1010	Speculation:T1020 Scope:T1021
T1021	Span 1949 2015	suggest that the induction of rv2623 may have biological relevance
T1022	Speculation 2506 2512	likely
E1011	Speculation:T1022 Scope:T1023
T1023	Span 2506 2520	likely complex
T1024	Speculation 2465 2472	suggest
E1012	Speculation:T1024 Scope:T1025
T1025	Span 2465 2520	suggest that the regulation of Rv2623 is likely complex
T1026	Speculation 2758 2763	could
E1013	Speculation:T1026 Scope:T1027
T1027	Span 2758 2910	could result in inability of the tubercle bacillus to enter a latent state in the infected host, leading to unrestrained growth and thus, hypervirulence
T1028	Speculation 2690 2698	possible
E1014	Speculation:T1028 Scope:T1029
T1029	Span 2690 2910	possible that deficiency in certain members of the dormancy regulon could result in inability of the tubercle bacillus to enter a latent state in the infected host, leading to unrestrained growth and thus, hypervirulence
T1030	Speculation 3415 3422	unclear
E1015	Speculation:T1030 Scope:T1031
T1031	Span 3335 3422	The discrepancies regarding M. tuberculosis virulence in these DosR studies are unclear
T1032	Negation 3247 3249	no
E1016	Negation:T1032 Scope:T1033
T1033	Span 3247 3285	no effect on M. tuberculosis virulence
T1034	Speculation 3985 3998	indicate that
E1017	Speculation:T1034 Scope:T1035
T1035	Span 3985 4031	indicate that the phenotype is Rv2623-specific
T1036	Negation 3767 3772	fails
E1018	Negation:T1036 Scope:T1037
T1037	Span 3767 3816	fails to establish a chronic persistent infection
T1038	Speculation 4560 4570	suggesting
E1019	Speculation:T1038 Scope:T1039
T1039	Span 4560 4683	suggesting that these two tightly co-regulated "stress" proteins might have similar growth-regulatory roles during dormancy
T1040	Speculation 4212 4219	suggest
E1020	Speculation:T1040 Scope:T1041
T1041	Span 4212 4311	suggest that the M. tuberculosis USP Rv2623 has the ability to regulate growth in vitro and in vivo
T1042	Speculation 4725 4732	suggest
E1021	Speculation:T1042 Scope:T1043
T1043	Span 4725 4857	suggest that nucleotide-binding capacity represents a discriminating biochemical feature that facilitates USP protein classification
T1044	Speculation 4625 4630	might
E1022	Speculation:T1044 Scope:T1045
T1045	Span 4625 4683	might have similar growth-regulatory roles during dormancy
T1046	Speculation 4908 4915	implied
E1023	Speculation:T1046 Scope:T1047
T1047	Span 4859 4953	Putative functional differences between USPs are implied by their assignment to two subclasses
T1048	Negation 4976 4979	not
E1024	Negation:T1048 Scope:T1049
T1049	Span 4976 5068	not bind ATP and another whose constituents bind and hydrolyze adenine nucleotide substrates
T1050	Speculation 6038 6045	unclear
E1025	Speculation:T1050 Scope:T1051
T1051	Span 6038 6049	unclear [9]
T1052	Speculation 5877 5883	appear
E1026	Speculation:T1052 Scope:T1053
T1053	Span 5843 5972	the non-ATP-binding UspA homologs appear to play diverse roles in promoting survival under a variety of environmental insults [15
T1054	Speculation 6939 6944	could
E1027	Speculation:T1054 Scope:T1055
T1055	Span 6872 7046	the attenuated growth phenotype caused by overexpression of Rv2623 could be abrogated by mutations that interfere with the binding of this protein to its nucleotide substrate
T1056	Speculation 6745 6754	predicted
E1028	Speculation:T1056 Scope:T1057
T1057	Span 6734 6846	which were predicted to disrupt nucleotide-binding, yielded mutant proteins with attenuated ATP-binding capacity
