T1000	Speculation 413 420	thought
E1000	Speculation:T1000 Scope:T1001
T1001	Span 413 464	thought to attribute to genetic changes in bacteria
T1002	Negation 475 477	no
E1001	Negation:T1002 Scope:T1003
T1003	Span 475 616	no clear evidence has shown due to lack of an intriguingly study using serotype-matched isolates from clinical severe invasive GAS infections
T1004	Speculation 758 770	hypothesized
E1002	Speculation:T1004 Scope:T1005
T1005	Span 758 844	hypothesized us invasive GAS could evade host defense, especially neutrophil functions
T1006	Negation 726 733	without
E1003	Negation:T1006 Scope:T1007
T1007	Span 726 757	without neutrophil infiltration
T1008	Speculation 990 995	could
E1004	Speculation:T1008 Scope:T1009
T1009	Span 990 1338	could abrogate functions of human polymorphnuclear neutrophils (PMN) in at least two independent ways; due to inducing necrosis to PMN by enhanced production of a pore-forming toxin streptolysin O (SLO) and due to impairment of PMN migration via digesting interleukin-8, a PMN attracting chemokine, by increased production of a serine protease ScpC
T1010	Negation 957 960	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 957 1091	not from non-invaive infections, could abrogate functions of human polymorphnuclear neutrophils (PMN) in at least two independent ways
T1012	Speculation 1868 1875	suggest
E1006	Speculation:T1012 Scope:T1013
T1013	Span 1868 1990	suggest that the abilities of GAS to abrogate PMN functions can determine the onset and severity of invasive GAS infection
T1014	Negation 1730 1734	lack
E1007	Negation:T1014 Scope:T1015
T1015	Span 1730 1753	lack either SLO or ScpC
