T1000	Speculation 568 575	whether
E1000	Speculation:T1000 Scope:T1001
T1001	Span 568 669	whether SeMac has IgG endopeptidase activity and inhibits opsonophagocytosis of S. equi by horse PMNs
T1002	Negation 29 32	not
E1001	Negation:T1002 Scope:T1003
T1003	Span 29 136	not Inhibit Opsonophagocytosis of Streptococcus equi Subspecies equi by Horse Polymorphonuclear Leukocytes 
T1004	Speculation 1059 1062	may
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1059 1089	may be IgG1 only, of horse IgG
T1006	Speculation 889 904	indicating that
E1003	Speculation:T1006 Scope:T1007
T1007	Span 889 947	indicating that SeMac is produced in vivo during infection
T1008	Negation 1264 1267	not
E1004	Negation:T1008 Scope:T1009
T1009	Span 1264 1363	not inhibit opsonophagocytosis of S. equi by horse PMNs but opsonophagocytosis of GAS by human PMNs
