T1000	Speculation 7279 7292	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 7279 7433	indicate that DNA-rich environments, such as bacterial biofilms or the CF lung, may represent the natural setting where bacterial growth is cation limited
T1002	Speculation 7359 7362	may
E1001	Speculation:T1002 Scope:T1003
T1003	Span 7359 7433	may represent the natural setting where bacterial growth is cation limited
T1004	Speculation 1291 1300	suggested
E1002	Speculation:T1004 Scope:T1005
T1005	Span 1291 1467	suggested that Mg2+ is limiting within host cells, but it was recently shown that vacuole acidification and low pH is the crucial environmental trigger of PhoPQ activation [66]
T1006	Speculation 274 281	thought
E1003	Speculation:T1006 Scope:T1007
T1007	Span 274 409	thought to contribute significantly to its ability to survive long-term within the hostile environment of chronically-infected patients
T1008	Speculation 2651 2657	likely
E1004	Speculation:T1008 Scope:T1009
T1009	Span 2651 2793	likely blocks the self-promoted uptake of aminoglycosides, which normally bind and displace cations that crosslink adjacent LPS molecules [68]
T1010	Negation 2072 2075	not
E1005	Negation:T1010 Scope:T1011
T1011	Span 2010 2099	the contribution of the PhoPQ-regulated LPS modifications has not been clearly determined
T1012	Speculation 3382 3390	unlikely
E1006	Speculation:T1012 Scope:T1013
T1013	Span 3382 3439	unlikely that a biofilm environment may be cation limited
T1014	Speculation 3374 3381	thought
E1007	Speculation:T1014 Scope:T1015
T1015	Span 3374 3439	thought unlikely that a biofilm environment may be cation limited
T1016	Speculation 3459 3473	indicates that
E1008	Speculation:T1016 Scope:T1017
T1017	Span 3459 3629	indicates that the presence of DNA in biofilms does indeed result in a cation-limited environment, resulting in the induction of the LPS modification operon PA3552-PA3559
T1018	Speculation 3418 3421	may
E1009	Speculation:T1018 Scope:T1019
T1019	Span 3418 3439	may be cation limited
T1020	Speculation 4688 4698	hypothesis
E1010	Speculation:T1020 Scope:T1021
T1021	Span 4688 4908	hypothesis that the release of genomic DNA by lysed cells following exposure to inhibitory concentrations of extracellular DNA may result in a continual release of DNA by dying cells and a DNA gradient within the biofilm
T1022	Speculation 4600 4614	indicated that
E1011	Speculation:T1022 Scope:T1023
T1023	Span 4600 4653	indicated that DNA was present throughout the biofilm
T1024	Speculation 5650 5656	likely
E1012	Speculation:T1024 Scope:T1025
T1025	Span 5650 5755	likely that within the CF lung, localized cation limited environments exist within DNA-rich microcolonies
T1026	Speculation 4815 4818	may
E1013	Speculation:T1026 Scope:T1027
T1027	Span 4815 4908	may result in a continual release of DNA by dying cells and a DNA gradient within the biofilm
T1028	Speculation 6104 6107	may
E1014	Speculation:T1028 Scope:T1029
T1029	Span 6104 6221	may explain why many P. aeruginosa CF isolates show LPS modifications such as aminoarabinose addition to lipid A [78]
T1030	Speculation 5972 5979	appears
E1015	Speculation:T1030 Scope:T1031
T1031	Span 5972 6220	appears that there are multiple environmental signals in the CF lung that can induce the expression the PA3552-PA3559 operon, which may explain why many P. aeruginosa CF isolates show LPS modifications such as aminoarabinose addition to lipid A [78
T1032	Speculation 6358 6361	may
E1016	Speculation:T1032 Scope:T1033
T1033	Span 6358 6443	may also be a relevant in vivo signal inducing expression of the PA3552-PA3559 operon
T1034	Speculation 6331 6343	hypothesized
E1017	Speculation:T1034 Scope:T1035
T1035	Span 6331 6443	hypothesized that alginate may also be a relevant in vivo signal inducing expression of the PA3552-PA3559 operon
T1036	Negation 6539 6542	not
E1018	Negation:T1036 Scope:T1037
T1037	Span 6533 6549	(data not shown)
T1038	Negation 6495 6498	not
E1019	Negation:T1038 Scope:T1039
T1039	Span 6495 6532	not occur in the presence of alginate
T1040	Speculation 6799 6802	may
E1020	Speculation:T1040 Scope:T1041
T1041	Span 6799 6942	may, in part, be attributed to the degradation of DNA and subsequent disarming of the PhoPQ/PmrAB response and antibiotic resistance mechanisms
T1042	Speculation 6755 6763	suggests
E1021	Speculation:T1042 Scope:T1043
T1043	Span 6755 6811	suggests that the success of DNAseI therapy may, in part
