T1000	Speculation 906 919	indicate that
E1000	Speculation:T1000 Scope:T1001
T1001	Span 906 970	indicate that VicRK is important to S. equi growth and virulence
T1002	Speculation 657 667	suggesting
E1001	Speculation:T1002 Scope:T1003
T1003	Span 657 711	suggesting that the vicK deletion causes growth defect
T1004	Speculation 975 982	suggest
E1002	Speculation:T1004 Scope:T1005
T1005	Span 975 1057	suggest that DeltavicK has the potential to be developed as a live S. equi vaccine
